### ISSUE TITLE
Question About Feature Extraction Tutorial

### ISSUE THREAD

**Issue by Charliechen1** [pyannote/pyannote-audio#100]
Hi,
I have tried tutorial for feature extraction tutorial step by step. The database is the default AMI one.
But when I execute
`pyannote-speech-feature  ${EXPERIMENT_DIR} AMI.SpeakerDiarization.MixHeadset`
But I got error:
`ValueError: Could not find file "EN2001a.Mix-Headset".`
Where can I get these files and what should I do?

Thank you and look forward to your reply.

**Comment by bml1g12** [comment]
The files are freely available at http://groups.inf.ed.ac.uk/ami/download/ 

After download, make a ~/.pyannote/db.yml with the path to the corpus as per the tutorial
