### ISSUE TITLE
How diarization assign speakers in overlapped sppech? 

### ISSUE THREAD

**Issue by YuGuiwe** [pyannote/pyannote-audio#1008]
How does speaker diarization assign speakers in overlapped speech? I saw it was masked in pyannote.audio.pipelines.speaker_diarization line 294.
I also question the relation between speech segmentation, resegmentation, and speaker diarization and their purpose.

**Comment by hbredin** [comment]
I recommend you read [this](https://github.com/juanmc2005/StreamingSpeakerDiarization/blob/main/paper.pdf) paper, which is an online variant of what is currently implemented in `develop` branch.

**Comment by YuGuiwe** [comment]
Thanks for your reply! This paper I already read. But assign speaker method seems different from this. I couldn't understand why the cluster method in your diarization didn't calculate embedding in overlapping speech intervals, but it can still predict the correct prediction. Or did I miss something after you masked the overlapping speech intervals?

**Comment by hbredin** [comment]
Overlapping frames are only masked for computing the embeddings, not for the rest of the pipeline. Anyway, I plan to write a technical report describing the approach and will share it once it is ready.

**Comment by YuGuiwe** [comment]
Thank you again. I really appreciate it!
So assigning speakers in overlapping didn't rely on embedding but on other mechanisms. Where can I find the code?
