### ISSUE TITLE
Limiting number of speakers?

### ISSUE THREAD

**Issue by alpoktem** [pyannote/pyannote-audio#1009]
Most of the time diarization predicts there are more speakers than there actually are in the recording. Can we somehow specify the number of speakers and model classifies audio chunks into that number? 

I usually know how many speakers are present in my recordings. So that would help incredibly.

**Comment by hbredin** [comment]
This is not yet possible but is something I have (not that deep) in my TODO list.

**Comment by hbredin** [comment]
The pretrained pipeline in pyannote.audio 2.0 now supports this option.
See documentation [here](https://huggingface.co/pyannote/speaker-diarization).
