### ISSUE TITLE
No module named 'pyannote.audio.features'

### ISSUE THREAD

**Issue by heunggyulee** [pyannote/pyannote-audio#1011]
when i start this code in jupyter notebook.

from pyannote.audio.features import RawAudio
from IPython.display import Audio

# load audio waveform, crop excerpt, and play it
waveform = RawAudio(sample_rate=16000).crop(DEMO_FILE, EXCERPT)
Audio(data=waveform.squeeze(), rate=16000, autoplay=True)

i got "No module named error" message.

**i used pyenv and conda also.**
**when conda used**
conda create -n pyannote python=3.8
conda activate pyannote
conda install pytorch torchaudio -c pytorch
pip install https://github.com/pyannote/pyannote-audio/archive/develop.zip

**when pyenv used**
pip install pytorch torchaudio -c pytorch
pip install https://github.com/pyannote/pyannote-audio/archive/develop.zip

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/home/clab/Downloads/pyannote-audio/pyannote audio.ipynb Cell 6' in <cell line: 1>()
----> [1](vscode-notebook-cell://ssh-remote%2B10.114.75.39/home/clab/Downloads/pyannote-audio/pyannote%20audio.ipynb#ch0000004vscode-remote?line=0) from pyannote.audio.features import RawAudio
      [2](vscode-notebook-cell://ssh-remote%2B10.114.75.39/home/clab/Downloads/pyannote-audio/pyannote%20audio.ipynb#ch0000004vscode-remote?line=1) from IPython.display import Audio
      [4](vscode-notebook-cell://ssh-remote%2B10.114.75.39/home/clab/Downloads/pyannote-audio/pyannote%20audio.ipynb#ch0000004vscode-remote?line=3) # load audio waveform, crop excerpt, and play it

ModuleNotFoundError: No module named 'pyannote.audio.features'

**Comment by hbredin** [comment]
Looks like you are trying to use pyannote.audio 1.x code although you installed pyannote.audio from the 2.x branch.

**Comment by heunggyulee** [comment]
i changed ipynb file out from pyannote-audio and solved. :)

**Comment by AMITKESARI2000** [comment]
@heunggyulee can you paste the changes you made here as well.
Thanks
