### ISSUE TITLE
VAD Significant inconsistency in the results when using CPU and GPU

### ISSUE THREAD

**Issue by Sorrow321** [pyannote/pyannote-audio#1013]
**Describe the bug**
I was trying different functions from the library and found inconsistency between the results on the HuggingFace demo and in my Python code.  After hours of debug I found that the issue happens when you switch from CPU to GPU.

Here is a sample code to use voice activity detection in raw form (without binarization) which I extracted from `__init__` method of **VoiceActivityDetection** class:
```
model = get_model('pyannote/segmentation')
if model.device.type == "cpu":
    (segmentation_device,) = get_devices(needs=1)
    model.to(segmentation_device)

inference_kwargs = {}
inference_kwargs["pre_aggregation_hook"] = lambda scores: np.max(
    scores, axis=-1, keepdims=True
)

_segmentation = Inference(model, **inference_kwargs)
```

Let's comment lines 2-4 in this code and compare the results.

![image](https://user-images.githubusercontent.com/20703486/174434990-58b4c7fa-14ae-493c-9edc-5f778386b9b7.png)
![image](https://user-images.githubusercontent.com/20703486/174435027-34934ea0-3f50-45f1-8091-0600f30f36d0.png)

As you can see, there is a huge difference between the plots (6-8 seconds).

[Here you can download](https://drive.google.com/file/d/1OZHus4Uowtu-DYzuuGVzeZi9cTm9LwvR/view?usp=sharing) the sample I used for the testing.

**pyannote environment**
```
$ pip freeze | grep pyannote
pyannote.audio @ https://github.com/pyannote/pyannote-audio/archive/develop.zip
pyannote.core==4.4
pyannote.database==4.1.3
pyannote.metrics==3.2
pyannote.pipeline==2.3
```

**Comment by hbredin** [comment]
Thanks for reporting this.
Would you mind running the following and sharing the visual output on both CPU and GPU?

```python
segmentation = Inference(model, skip_aggregation=True)
segmentation("v.wav")
```

**Comment by hbredin** [comment]
Any update on this?

**Comment by Sorrow321** [comment]
I may have update some of my packages, didn't track exactly what I have changed, but now pictures look in other way. 
![image](https://user-images.githubusercontent.com/20703486/179664643-409bf7d6-8416-4d53-9c66-e1c3bb82cb97.png)
![image](https://user-images.githubusercontent.com/20703486/179664799-9157aacc-f0dc-44e4-a4ce-77992c791590.png)

**Comment by hbredin** [comment]
Could be related to #1370 if GPU was an Ampere (e.g. A100) device.
