### ISSUE TITLE
Can I download a separate audio file for each speaker?

### ISSUE THREAD

**Issue by heunggyulee** [pyannote/pyannote-audio#1014]
First of all, thank you for providing a good module.

I want to connect speaker diarization of pyannote and STT module that i made.
I uploaded speech file and ran the pretrained model and got a diarization result prefectly :)
And now, i want to download a separate audio file for each speaker to progress STT module.
Is there any way to download mp3 or wav file?!

**Comment by manish-kumar-iisc** [comment]
As far i know, you cannot download directly.
I am not award of stt module.
one way i can suggest is

1. Get diarization timestamp boundary(output of pyannote)
2. using ffmpeg command you can cut the uploaded speech file, according to diariazation timestamp.
3. there can be possiblity, in which each speaker is not continuous, so you get multiple mp3 files for each speaker,
4. either you can merge file for which speaker is same(using ffmpeg command), or you can keep separate
5.

**Comment by heunggyulee** [comment]
Thank you for replies.

If speaker1 speaks from 00:03 to 00:10 and speaker2 speaks from 00:07 to 00:15.
Two voices will be mixed from 00:07 to 00:10.

But i want to get seperated voice files.
file1 : speaker1.mp3 (00:03~00:10) without speaker2 voice.
file2 : speaker2.mp3 (00:07~00:15) without speaker1 voice.

Is it impossible in pyannote?!

**Comment by hbredin** [comment]
No. pyannote does not do speaker separation, it focuses on diarization. For source separation, see [asteroid](https://github.com/asteroid-team/asteroid).

**Comment by heunggyulee** [comment]
If i open Pipeline module. 
Can i get a speaker separation result?!

**Comment by hbredin** [comment]
No. Again: pyannote.audio does not do (nor rely on) separation.
