### ISSUE TITLE
Installing pyannote from pypi.org not working?

### ISSUE THREAD

**Issue by manish-kumar-iisc** [pyannote/pyannote-audio#1015]
I tried to use pyannote VAD, by installing pyannote from [LINK](https://pypi.org/project/pyannote.audio/1.1.2/),
It is giving below error  
```
File "utils/pyannote_vad.py", line 1, in <module>
from pyannote.audio import Pipeline
ImportError: cannot import name 'Pipeline' from 'pyannote.audio'
```
what can be the possible solution?
But When i tried to install pyannote VAD using [Link](https://github.com/pyannote/pyannote-audio/tree/develop) as mentioned in this link, it worked, but this way of installing, its docker image consume large memory 
using Python version: 3.7

**Comment by hbredin** [comment]
The API has changed between pyannote.audio 1.x (served by PyPI) and pyannote.audio 2.x (not yet released and only available on Github for now).

`from pyannote.audio import Pipeline` will only work in 2.x.
