### ISSUE TITLE
huggingface_hub cached_download fails

### ISSUE THREAD

**Issue by kaylC4** [pyannote/pyannote-audio#1018]
**Describe the bug**
I try the "Introduction to **pyannote.audio speaker diarization toolkit**" notebook on Colab PRO, as I already done yesterday but today it does not work. In particular the section **Speaker diarization with pyannote.pipeline**
NB I also try anothe method like  **inference = Inference("pyannote/embedding",window="whole",device="cuda")** and it works.

**To Reproduce**
Just go trough the notebook till the section highlighted.

**Additional context**

TypeError                                 Traceback (most recent call last)
[<ipython-input-8-22fcfc59b044>](https://localhost:8080/#) in <module>()
      1 from pyannote.audio import Pipeline
----> 2 pipeline = Pipeline.from_pretrained('pyannote/speaker-diarization')
      3 diarization = pipeline(DEMO_FILE)

5 frames
[/usr/local/lib/python3.7/dist-packages/pyannote/audio/core/pipeline.py](https://localhost:8080/#) in from_pretrained(cls, checkpoint_path, hparams_file, use_auth_token, cache_dir)
     96             pipeline_name, default_module_name="pyannote.pipeline.blocks"
     97         )
---> 98         pipeline = Klass(**config["pipeline"].get("params", {}))
     99 
    100         # freeze  parameters

[/usr/local/lib/python3.7/dist-packages/pyannote/audio/pipelines/speaker_diarization.py](https://localhost:8080/#) in __init__(self, segmentation, embedding, clustering, expects_num_speakers, segmentation_batch_size, embedding_batch_size)
    115         self._frames: SlidingWindow = self._segmentation.model.introspection.frames
    116 
--> 117         self._embedding = PretrainedSpeakerEmbedding(self.embedding, device=emb_device)
    118         self.embedding_batch_size = embedding_batch_size or len(
    119             model.specifications.classes

[/usr/local/lib/python3.7/dist-packages/pyannote/audio/pipelines/speaker_verification.py](https://localhost:8080/#) in PretrainedSpeakerEmbedding(embedding, device)
    273 
    274     if isinstance(embedding, str) and "speechbrain" in embedding:
--> 275         return SpeechBrainPretrainedSpeakerEmbedding(embedding, device=device)
    276     else:
    277         return PyannoteAudioPretrainedSpeakerEmbedding(embedding, device=device)

[/usr/local/lib/python3.7/dist-packages/pyannote/audio/pipelines/speaker_verification.py](https://localhost:8080/#) in __init__(self, embedding, device)
     96             source=self.embedding,
     97             savedir=f"{CACHE_DIR}/speechbrain",
---> 98             run_opts={"device": self.device},
     99         )
    100 

[/usr/local/lib/python3.7/dist-packages/speechbrain/pretrained/interfaces.py](https://localhost:8080/#) in from_hparams(cls, source, hparams_file, pymodule_file, overrides, savedir, use_auth_token, **kwargs)
    330             savedir = f"./pretrained_models/{clsname}-{hash(source)}"
    331         hparams_local_path = fetch(
--> 332             hparams_file, source, savedir, use_auth_token
    333         )
    334         try:

[/usr/local/lib/python3.7/dist-packages/speechbrain/pretrained/fetching.py](https://localhost:8080/#) in fetch(filename, source, savedir, overwrite, save_filename, use_auth_token)
    114         url = huggingface_hub.hf_hub_url(source, filename)
    115         try:
--> 116             fetched_file = huggingface_hub.cached_download(url, use_auth_token)
    117         except HTTPError as e:
    118             if e.response.status_code == 404:

TypeError: cached_download() takes 1 positional argument but 2 were given

**Comment by kaylC4** [comment]
Here find problem and solution:
https://github.com/speechbrain/speechbrain/issues/1459

**Comment by hbredin** [comment]
Thanks for sharing the workaround!

Closing because this is a speechbrain issue.
