### ISSUE TITLE
Speaker-diarization acceleration

### ISSUE THREAD

**Issue by faad3** [pyannote/pyannote-audio#1019]
Hello!

Is there any way to speed up the speaker-diarization?  For example, increase the batch size or the number of workers.

**Comment by hbredin** [comment]
You can indeed [increase the batch size](https://github.com/pyannote/pyannote-audio/blob/26cddd98f91a770f9c73f569f200674fda1ee705/pyannote/audio/pipelines/speaker_diarization.py#L76
)

Do not expect a huge speed up, though.
