### ISSUE TITLE
Installation Error: Couldn't find marching distribution for chocolate

### ISSUE THREAD

**Issue by bluemonk482** [pyannote/pyannote-audio#102]
> Collecting chocolate>=0.6 (from pyannote.audio)
>   Could not find a version that satisfies the requirement chocolate>=0.6 (from pyannote.audio) (from versions: )
> No matching distribution found for chocolate>=0.6 (from pyannote.audio)

The error above appears after 

> pip install --process-dependency-links pyannote.audio

As a result `pyannote` cannot be installed.

**Comment by hbredin** [comment]
You may want to try and install chocolate alone first:
http://chocolate.readthedocs.io/installation.html

**Comment by bluemonk482** [comment]
Thanks very much @hbredin ! `pip install --process-dependency-links pyannote.audio` seems to be successful. But when I try `pyannote-change-detection`or `pyannote-pipeline` I get errors.

> (pyannote) $ pyannote-change-detection
> Traceback (most recent call last):
>   File "/usr/local/bin/pyannote-change-detection", line 7, in <module>
>     from pyannote.audio.applications.change_detection import main
>   File "/usr/local/lib/python3.5/dist-packages/pyannote/audio/applications/change_detection.py", line 248
>     metric_name = f'{task}/coverage@{target_purity:.2f}purity'
>                                                              ^
> SyntaxError: invalid syntax


> (pyannote) $ pyannote-pipeline --help
> Traceback (most recent call last):
>   File "/usr/local/bin/pyannote-pipeline", line 7, in <module>
>     from pyannote.audio.applications.pipeline import main
>   File "/usr/local/lib/python3.5/dist-packages/pyannote/audio/applications/pipeline.py", line 152
>     tune_db = f'{train_dir}/tune.db'
>                                    ^
> SyntaxError: invalid syntax

**Comment by hbredin** [comment]
This is because you are using Python 3.5.
You need to carefully follow the installation instructions: 
https://github.com/pyannote/pyannote-audio#installation

It clearly says that you need to use Python 3.6.

**Comment by bluemonk482** [comment]
Thanks very much @hbredin ! You're right, apologise for not following the instructions carefully.

I have installed `pyannote` successfully by using `pip3.6 install --process-dependency-links pyannote.audio`. Can I please ask two more questions?

1), Where is `tutorials/pipeline/config.yml` hiding? I can't seem to find the file or directory. It doesn't look it is in `./miniconda2/envs/pyannote`.

2), Why is `pyannote-pipeline` still loading from `/usr/local/lib/python3.5/dist-packages/pyannote/audio/applications/pipeline.py`? Which is still giving me the same error as before. I clearly installed it using `pip3.6` or `python3.6 -m pip`. I know this is probably not a `pyannote` issue but I'd greatly appreciate if any help :)

**Comment by hbredin** [comment]
> 1), Where is tutorials/pipeline/config.yml hiding? I can't seem to find the file or directory. It doesn't look it is in ./miniconda2/envs/pyannote.

You have to obtain it directly from the Github repository.
It is not installed with the library.

> 2), Why is pyannote-pipeline still loading from /usr/local/lib/python3.5/dist-packages/pyannote/audio/applications/pipeline.py? Which is still giving me the same error as before. I clearly installed it using pip3.6 or python3.6 -m pip. I know this is probably not a pyannote issue but I'd greatly appreciate if any help :)

Indeed. This is not a pyannote.audio issue. I won’t be able to help.

Hervé.

**Comment by bluemonk482** [comment]
Thanks @hbredin ! Problems solved!

Can I ask a final question please: 

How do I obtain `~/.pyannote/db.yml`? I indeed have `pyannote.db.odessa.ami-0.7:` installed in:

>     /home/ccrmad/.local/lib/python3.6/site-packages/AMI/*
>     /home/ccrmad/.local/lib/python3.6/site-packages/pyannote.db.odessa.ami-0.7.dist-info/*

**Comment by bluemonk482** [comment]
Sorry for asking so many different questions..

**Comment by hbredin** [comment]
You have to create this file yourself:
https://github.com/pyannote/pyannote-audio/tree/master/tutorials/feature-extraction#ami-database
