### ISSUE TITLE
Failure to load pretrained diarization pipeline

### ISSUE THREAD

**Issue by rc634** [pyannote/pyannote-audio#1021]
**Describe the bug**
Failure to load the pyannote-audio pre-trained diarization pipeline

**To Reproduce**
Following https://github.com/pyannote/pyannote-audio:

![IPYTHON_EXAMPLE](https://user-images.githubusercontent.com/20278503/176189219-1630ce2d-2ea3-441b-92c1-a312b90a7142.png)

I copy the error message at the end of the Issue.

**pyannote environment**

$ pip3 freeze | grep pyannote
pyannote.audio @ https://github.com/pyannote/pyannote-audio/archive/develop.zip
pyannote.core==4.4
pyannote.database==4.1.3
pyannote.metrics==3.2.1
pyannote.pipeline==2.3

$ conda list | grep pyannote
pyannote-audio            0.0.1                    pypi_0    pypi
pyannote-core             4.4                      pypi_0    pypi
pyannote-database         4.1.3                    pypi_0    pypi
pyannote-metrics          3.2.1                    pypi_0    pypi
pyannote-pipeline         2.3                      pypi_0    pypi

Example is being run in a conda environment as suggested on the Github readme. I have tried running this and the examples from https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/applying_a_pipeline.ipynb. I have tried command line ipython and jupyter - both give the same error. 

I have ubuntu 22.04 and python 3.8.13.

Thanks, 
Robin.

**Copied error from ipython in command line**

In [1]: from pyannote.audio import Pipeline

In [2]: pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization")

File ~/anaconda3/envs/tarxya/lib/python3.8/site-packages/pyannote/audio/core/pipeline.py:98, in Pipeline.from_pretrained(cls, checkpoint_path, hparams_file, use_auth_token, cache_dir)
     94 pipeline_name = config["pipeline"]["name"]
     95 Klass = get_class_by_name(
     96     pipeline_name, default_module_name="pyannote.pipeline.blocks"
     97 )
---> 98 pipeline = Klass(**config["pipeline"].get("params", {}))
    100 # freeze  parameters
    101 if "freeze" in config:

File ~/anaconda3/envs/tarxya/lib/python3.8/site-packages/pyannote/audio/pipelines/speaker_diarization.py:117, in SpeakerDiarization.__init__(self, segmentation, embedding, clustering, expects_num_speakers, segmentation_batch_size, embedding_batch_size)
    112 self._segmentation = Inference(
    113     model, skip_aggregation=True, batch_size=self.segmentation_batch_size
    114 )
    115 self._frames: SlidingWindow = self._segmentation.model.introspection.frames
--> 117 self._embedding = PretrainedSpeakerEmbedding(self.embedding, device=emb_device)
    118 self.embedding_batch_size = embedding_batch_size or len(
    119     model.specifications.classes
    120 )
    122 self._audio = Audio(sample_rate=self._embedding.sample_rate, mono=True)

File ~/anaconda3/envs/tarxya/lib/python3.8/site-packages/pyannote/audio/pipelines/speaker_verification.py:275, in PretrainedSpeakerEmbedding(embedding, device)
    248 """Pretrained speaker embedding
    249 
    250 Parameters
   (...)
    271 >>> embeddings = get_embedding(waveforms, masks=masks)
    272 """
    274 if isinstance(embedding, str) and "speechbrain" in embedding:
--> 275     return SpeechBrainPretrainedSpeakerEmbedding(embedding, device=device)
    276 else:
    277     return PyannoteAudioPretrainedSpeakerEmbedding(embedding, device=device)

File ~/anaconda3/envs/tarxya/lib/python3.8/site-packages/pyannote/audio/pipelines/speaker_verification.py:95, in SpeechBrainPretrainedSpeakerEmbedding.__init__(self, embedding, device)
     92 self.embedding = embedding
     93 self.device = device
---> 95 self.classifier_ = EncoderClassifier.from_hparams(
     96     source=self.embedding,
     97     savedir=f"{CACHE_DIR}/speechbrain",
     98     run_opts={"device": self.device},
     99 )

File ~/anaconda3/envs/tarxya/lib/python3.8/site-packages/speechbrain/pretrained/interfaces.py:331, in Pretrained.from_hparams(cls, source, hparams_file, pymodule_file, overrides, savedir, use_auth_token, **kwargs)
    329     clsname = cls.__name__
    330     savedir = f"./pretrained_models/{clsname}-{hash(source)}"
--> 331 hparams_local_path = fetch(
    332     hparams_file, source, savedir, use_auth_token
    333 )
    334 try:
    335     pymodule_local_path = fetch(
    336         pymodule_file, source, savedir, use_auth_token
    337     )

File ~/anaconda3/envs/tarxya/lib/python3.8/site-packages/speechbrain/pretrained/fetching.py:116, in fetch(filename, source, savedir, overwrite, save_filename, use_auth_token)
    114 url = huggingface_hub.hf_hub_url(source, filename)
    115 try:
--> 116     fetched_file = huggingface_hub.cached_download(url, use_auth_token)
    117 except HTTPError as e:
    118     if e.response.status_code == 404:

TypeError: cached_download() takes 1 positional argument but 2 were given

**Comment by hbredin** [comment]
Closing as duplicate of #1018

**Comment by rc634** [comment]
I managed to fix my problem by changing speechbrain from 0.5.11 to 0.5.12 with 

$ pip3 install speechbrain==0.5.12
