### ISSUE TITLE
ArcFace embedding task is broken

### ISSUE THREAD

**Issue by olvb** [pyannote/pyannote-audio#1022]
**Describe the bug**

The `SpeakerEmbedding` / `SupervisedRepresentationLearningWithArcFace` cannot  be used anymore for training since commit 0fb42ad08cb92539a37702cb7afcc20dad8871d7. It is missing an implementation of the `collate_fn` method.

Is this known/expected? I see that this task is not tested in `pyannote-audio/tests/test_train.py`

**To Reproduce**
```python3
import pytorch_lightning as pl

from pyannote.database import get_protocol, FileFinder
from pyannote.audio.models.embedding.debug import SimpleEmbeddingModel
from pyannote.audio.tasks import SpeakerEmbedding

protocol = get_protocol(
    "Debug.SpeakerDiarization.Debug",
    preprocessors={"audio": FileFinder()}
)

emb = SpeakerEmbedding(protocol)
model = SimpleEmbeddingModel(task=emb)
trainer = pl.Trainer(max_epochs=1)
_ = trainer.fit(model)

```

**Comment by hbredin** [comment]
Thanks for reporting this.

This is indeed expected but should definitely be fixed -- but unfortunately not at the top of my priority list (as I have been using speechbrain speaker embedding instead).

Would you like to contribute a fix? Or at least a test?

**Comment by olvb** [comment]
Sure, I can give it a try! I suppose restoring the previous behavior relying on `default_collate` should be enough?

Also, do you fine tune the speechbrain ecapa embeddings or do you directly use the ones pretrained on VoxCeleb?

**Comment by hbredin** [comment]
@olvb should be fixed in `develop` branch.
