### ISSUE TITLE
music activity detection?

### ISSUE THREAD

**Issue by manish-kumar-iisc** [pyannote/pyannote-audio#1023]
Pyannote is trained for voice activity detection, instead if we want music activity detection
what changes we need to make?
Are there any resources for music activity detection?

**Comment by hbredin** [comment]
[This (soon-to-be-merged) PR](https://github.com/pyannote/pyannote-audio/pull/891) introduces a generic multi-label classification task that can be used to train such a model (as long as you do have access to annotated music vs. not music data).

cc @hadware
