### ISSUE TITLE
Useful multi-label models

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#1027]
I'd like to pretrain a couple of models to host then on hugginface along with the others. What kind of classes/train datasets would you suggest? I was thinking about `MALE`/`FEMALE` using AMI/VoxCeleb, but that's it. Any other ideas?

_Originally posted by @hadware in https://github.com/pyannote/pyannote-audio/issues/891#issuecomment-1172205394_

**Comment by hadware** [comment]
Sidenote: we may be able to pretrain a `MALE`/`FEMALE`/`CHILD`/`KEYCHILD` model using our internal data, but this depends on the severely restrictive (and rightfully so) nature of the data. This could be a really nice addition to the child language acquisition community.

**Comment by hbredin** [comment]
I can think of several others:

* `SPEECH` vs. `MUSIC` vs. `NOISE` with [`MUSAN`](https://www.openslr.org/17/)
* Stuttering event detection with [Sep-28k](https://machinelearning.apple.com/research/stuttering-event-detection)
* `Sheldon` vs. `Leonard` vs. `Penny` using [`Bazinga`](https://huggingface.co/datasets/bazinga/bazinga) (could be used for a demo: which one of The Big Bang Theory character are you?)
 
Note that the new `MultiLabelSegmentation` task requires annotations with fine (start time, end time) boundaries. However, neither VoxCeleb nor MUSAN provide this kind of annotations (as one file contains only one class). It means that `MultiLabelSegmentation` is probably not really a good choice for this kind of dataset. That is also the reason why I renamed the task to segmentation (rather than detection).

**Comment by hbredin** [comment]
Another one:

* sound event detection with [AudioSet](https://research.google.com/audioset/) (and its [strong labels](https://research.google.com/audioset/download_strong.html))

**Comment by hbredin** [comment]
Laughter detection

**Comment by manish-kumar-iisc** [comment]
@hbredin here is [dataset](https://github.com/qlemaire22/speech-music-detection), it have overlap annotation also, for quality of annotation i am not sure.

**Comment by hbredin** [comment]
[PodcastFillers](https://podcastfillers.github.io/)

<img width="487" alt="image" src="https://user-images.githubusercontent.com/1080837/179692817-4695c4e0-e112-452f-95e4-b29b11bc210d.png">

**Comment by hbredin** [comment]
[LibriStutter](https://borealisdata.ca/dataset.xhtml?persistentId=doi:10.5683/SP3/NKVOGQ&version=1.0)

**Comment by hbredin** [comment]
[VocalSound](https://github.com/YuanGongND/vocalsound)

**Comment by hbredin** [comment]
[EpicSounds](https://github.com/epic-kitchens/epic-sounds-annotations)
