### ISSUE TITLE
Pyannote VAD probability score?

### ISSUE THREAD

**Issue by manish-kumar-iisc** [pyannote/pyannote-audio#1028]
Is it possible to get VAD probability score along with timestamp?
Is onset & offset logic in pyannote VAD is applied in both forward & backward direction also?

**Comment by hbredin** [comment]
This (untested) code will give you `(t, score)` tuples:

```python
import numpy as np
from pyannote.audio import Inference
hook = lambda segmentation: np.max(segmentation, axis=2, keepdims=True)
inference = Inference("pyannote/segmentation", pre_aggregation_hook=hook)
vad = inference("audio.wav")
for frame, score in vad:
    t = frame.middle
    print(f"{t=:.3f} {score=:.3f}")
```

`onset` and `offset` logic is only applied in forward direction.

**Comment by manish-kumar-iisc** [comment]
```
relies on the former
```
Is there way to see the those parameters? i tried to get those parameters, it is in object form
```
{'onset': <pyannote.pipeline.parameter.Uniform object at 0x7f2919c419d0>, 'offset': <pyannote.pipeline.parameter.Uniform object at 0x7f2919bdc090>, 'min_duration_on': <pyannote.pipeline.parameter.Uniform object at 0x7f291832b090>, 'min_duration_off': <pyannote.pipeline.parameter.Uniform object at 0x7f291832b310>}
```

**Comment by manish-kumar-iisc** [comment]
> This (untested) code will give you `(t, score)` tuples:
> 
> ```python
> import numpy as np
> from pyannote.audio import Inference
> hook = lambda segmentation: np.max(segmentation, axis=2, keepdims=True)
> inference = Inference("pyannote/segmentation", pre_aggregation_hook=hook)
> vad = inference("audio.wav")
> for frame, score in vad:
>     t = frame.middle
>     print(f"{t=:.3f} {score=:.3f}")
> ```
> 
> `onset` and `offset` logic is only applied in forward direction.

It works well, but can you suggest how to cache the file it is downloading probably form hugging face website?

**Comment by hbredin** [comment]
Closing as I believe the original issue has been solved.

Please open a new issue/discussion for other topics.
