### ISSUE TITLE
can not import pyannote.audio.pipelines

### ISSUE THREAD

**Issue by Juliaququ** [pyannote/pyannote-audio#1029]
**Describe the bug**
can not run the demo in huggingface. can not import pyannote.audio.pipelines 

**To Reproduce**
```
from pyannote.audio.pipelines import VoiceActivityDetection
pipeline = VoiceActivityDetection(segmentation="pyannote/segmentation")
HYPER_PARAMETERS = {
  # onset/offset activation thresholds
  "onset": 0.5, "offset": 0.5,
  # remove speech regions shorter than that many seconds.
  "min_duration_on": 0.0,
  # fill non-speech regions shorter than that many seconds.
  "min_duration_off": 0.0
}
pipeline.instantiate(HYPER_PARAMETERS)
vad = pipeline("audio.wav")
# `vad` is a pyannote.core.Annotation instance containing speech regions
```
**Content of `config.yml`**

```yaml
task:
   name:  Speaker-Segmentation
```

**pyannote environment**

```bash
$ pip freeze | grep pyannote
pyannote.audio            0.0.1
pyannote.core             4.4
pyannote.database         4.1.3
pyannote.metrics          3.2.1
pyannote.pipeline         2.3
torch                     1.10.1+cu111
torch-audiomentations     0.11.0
torch-pitch-shift         1.2.2
torchaudio                0.10.1+rocm4.1
torchmetrics              0.9.2
torchvision               0.11.2+cu111
```

**Additional context**

**Comment by Juliaququ** [comment]
> 
Here is the link to huggingface
https://huggingface.co/pyannote/segmentation 
Here is the eroor info
File "test_for_transformer.py", line 1, in <module>
    from pyannote.audio.pipelines import VoiceActivityDetection
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/pyannote/audio/__init__.py", line 29, in <module>
    from .core.inference import Inference
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/pyannote/audio/core/inference.py", line 33, in <module>
    from pyannote.audio.core.io import AudioFile
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/pyannote/audio/core/io.py", line 38, in <module>
    import torchaudio
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import _extension  # noqa: F401
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/torchaudio/_extension.py", line 27, in <module>
    _init_extension()
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/torchaudio/_extension.py", line 21, in _init_extension
    torch.ops.load_library(path)
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/torch/_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "/root/anaconda3/envs/py38/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_hip.so: cannot open shared object file: No such file or directory

**Comment by manish-kumar-iisc** [comment]
It is torch version issue, 
i got the same error. 
But corrected with installing latest version of cpu-torch.
use this
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
https://pytorch.org/get-started/locally/

**Comment by Juliaququ** [comment]
> It is torch version issue, i got the same error. But corrected with installing latest version of cpu-torch. use this
> 
> ```
> pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
> ```
> 
> https://pytorch.org/get-started/locally/

Work for me! But is there any gpu versions of torch that is compatible with this issue

**Comment by manish-kumar-iisc** [comment]
Yes some of GPU version are compatible. 
try this
```
https://pytorch.org/get-started/locally/
```

**Comment by Juliaququ** [comment]
> Yes some of GPU version are compatible. try this
> 
> ```
> https://pytorch.org/get-started/locally/
> ```
Thanks a lot!

**Comment by hbredin** [comment]
This [PR](#1030) that updates the installation instructions in the main `README` fixes the issue.
