### ISSUE TITLE
How to train a speaker diarization model

### ISSUE THREAD

**Issue by AMITKESARI2000** [pyannote/pyannote-audio#1032]
Hello,
I am a little new to this so wanted to know how i can train and fine tune the speaker diarization model being used in pyannote. And what will be the hyper parameters to look for.
Thank You

**Comment by kaleaniket** [comment]
Hi Amit, Did you find anything on it?

**Comment by hbredin** [comment]
[This tutorial](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/adapting_pretrained_pipeline.ipynb) should do the trick.

**Comment by kaleaniket** [comment]
> [This tutorial](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/adapting_pretrained_pipeline.ipynb) should do the trick.

How can I use it for inference on my own audio file?
