### ISSUE TITLE
Fail from pyannote.audio import Audio

### ISSUE THREAD

**Issue by kaylC4** [pyannote/pyannote-audio#1034]
**Describe the bug**
Once you install pyannote on Colab with:
`!pip install -q https://github.com/pyannote/pyannote-audio/archive/develop.zip`
`!pip install -q speechbrain`
and then run
 `from pyannote.audio import Audio`

and you get
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[<ipython-input-10-20d020a1322e>](https://localhost:8080/#) in <module>()
----> 1 from pyannote.audio import Audio
      2 from IPython.display import Audio as IPythonAudio
      3 waveform, sr = Audio().crop(DEMO_FILE, EXCERPT)
      4 IPythonAudio(waveform.flatten(), rate=sr)

15 frames
[/usr/local/lib/python3.7/dist-packages/pyannote/audio/__init__.py](https://localhost:8080/#) in <module>()
     27 
     28 
---> 29 from .core.inference import Inference
     30 from .core.io import Audio
     31 from .core.model import Model

[/usr/local/lib/python3.7/dist-packages/pyannote/audio/core/inference.py](https://localhost:8080/#) in <module>()
     29 import torch
     30 from einops import rearrange
---> 31 from pytorch_lightning.utilities.memory import is_oom_error
     32 
     33 from pyannote.audio.core.io import AudioFile

[/usr/local/lib/python3.7/dist-packages/pytorch_lightning/__init__.py](https://localhost:8080/#) in <module>()
     28     _logger.propagate = False
     29 
---> 30 from pytorch_lightning.callbacks import Callback  # noqa: E402
     31 from pytorch_lightning.core import LightningDataModule, LightningModule  # noqa: E402
     32 from pytorch_lightning.trainer import Trainer  # noqa: E402

[/usr/local/lib/python3.7/dist-packages/pytorch_lightning/callbacks/__init__.py](https://localhost:8080/#) in <module>()
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from pytorch_lightning.callbacks.base import Callback
     15 from pytorch_lightning.callbacks.device_stats_monitor import DeviceStatsMonitor
     16 from pytorch_lightning.callbacks.early_stopping import EarlyStopping

[/usr/local/lib/python3.7/dist-packages/pytorch_lightning/callbacks/base.py](https://localhost:8080/#) in <module>()
     23 
     24 import pytorch_lightning as pl
---> 25 from pytorch_lightning.utilities.types import STEP_OUTPUT
     26 
     27 

[/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/__init__.py](https://localhost:8080/#) in <module>()
     16 import numpy
     17 
---> 18 from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
     19 from pytorch_lightning.utilities.distributed import AllGatherGrad  # noqa: F401
     20 from pytorch_lightning.utilities.enums import (  # noqa: F401

[/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/apply_func.py](https://localhost:8080/#) in <module>()
     27 
     28 from pytorch_lightning.utilities.exceptions import MisconfigurationException
---> 29 from pytorch_lightning.utilities.imports import _compare_version, _TORCHTEXT_LEGACY
     30 from pytorch_lightning.utilities.warnings import rank_zero_deprecation
     31 

[/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/imports.py](https://localhost:8080/#) in <module>()
    116 _TORCH_QUANTIZE_AVAILABLE = bool([eg for eg in torch.backends.quantized.supported_engines if eg != "none"])
    117 _TORCHTEXT_AVAILABLE = _package_available("torchtext")
--> 118 _TORCHTEXT_LEGACY: bool = _TORCHTEXT_AVAILABLE and _compare_version("torchtext", operator.lt, "0.11.0")
    119 _TORCHVISION_AVAILABLE = _package_available("torchvision")
    120 _WANDB_AVAILABLE = _package_available("wandb")

[/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/imports.py](https://localhost:8080/#) in _compare_version(package, op, version, use_base_version)
     69     """
     70     try:
---> 71         pkg = importlib.import_module(package)
     72     except (ImportError, DistributionNotFound):
     73         return False

[/usr/lib/python3.7/importlib/__init__.py](https://localhost:8080/#) in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

[/usr/local/lib/python3.7/dist-packages/torchtext/__init__.py](https://localhost:8080/#) in <module>()
      4 
      5 # the following import has to happen first in order to load the torchtext C++ library
----> 6 from torchtext import _extension  # noqa: F401
      7 
      8 _TEXT_BUCKET = "https://download.pytorch.org/models/text/"

[/usr/local/lib/python3.7/dist-packages/torchtext/_extension.py](https://localhost:8080/#) in <module>()
     62 
     63 
---> 64 _init_extension()

[/usr/local/lib/python3.7/dist-packages/torchtext/_extension.py](https://localhost:8080/#) in _init_extension()
     56         raise ImportError("torchtext C++ Extension is not found.")
     57 
---> 58     _load_lib("libtorchtext")
     59     # This import is for initializing the methods registered via PyBind11
     60     # This has to happen after the base library is loaded

[/usr/local/lib/python3.7/dist-packages/torchtext/_extension.py](https://localhost:8080/#) in _load_lib(lib)
     48     if not path.exists():
     49         return False
---> 50     torch.ops.load_library(path)
     51     return True
     52 

[/usr/local/lib/python3.7/dist-packages/torch/_ops.py](https://localhost:8080/#) in load_library(self, path)
    218             # static (global) initialization code in order to register custom
    219             # operators with the JIT.
--> 220             ctypes.CDLL(path)
    221         self.loaded_libraries.add(path)
    222 

[/usr/lib/python3.7/ctypes/__init__.py](https://localhost:8080/#) in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: /usr/local/lib/python3.7/dist-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN3c1022getCustomClassTypeImplERKSt10type_inde

**To Reproduce**
just run into **Introduction to pyannote.audio speaker diarization toolkit**  `from pyannote.audio import Audio` and you get it.

**Comment by kaylC4** [comment]
I also try to reinstall torchvision but it does not work...

**Comment by kaylC4** [comment]
Making a step by step installation
`!pip install -q https://github.com/pyannote/pyannote-audio/archive/develop.zip`
works well. 
While with:
`!pip install -q speechbrain`
The issue is:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.13.0+cu113 requires torch==1.12.0, but you have torch 1.11.0 which is incompatible.
torchtext 0.13.0 requires torch==1.12.0, but you have torch 1.11.0 which is incompatible.
So it seems a **speechbrain** issue

**Comment by try2becareful** [comment]
#Also getting error but it looks like this one

OSError                                   Traceback (most recent call last)
[<ipython-input-8-20d020a1322e>](https://localhost:8080/#) in <module>()
----> 1 from pyannote.audio import Audio
      2 from IPython.display import Audio as IPythonAudio
      3 waveform, sr = Audio().crop(DEMO_FILE, EXCERPT)
      4 IPythonAudio(waveform.flatten(), rate=sr)

15 frames
[/usr/lib/python3.7/ctypes/__init__.py](https://localhost:8080/#) in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: /usr/local/lib/python3.7/dist-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN3c1022getCustomClassTypeImplERKSt10type_index

**Comment by try2becareful** [comment]
me too
please write here solution if anyone get it

**Comment by kaylC4** [comment]
Hi everyone,

I just found this issue [issue](https://github.com/speechbrain/speechbrain/issues/1493)

and the following workaround.
Meanwhile I found the following workaround on Colab:

**BEFORE installing speechbrain:**
`!pip uninstall torch`
`!pip uninstall torchvision`
`!pip uninstall torchtext`
`!pip uninstall torchaudio`

This should avoid all incopatibility issues.
Then I do not get the exact order to reinstall because while installing **torch**, it requires **torchvision**, and viceversa but at the it works for me:
`!pip install "torch==1.11.0"`
`!pip install "torchvision == 0.12.0"`
`!pip install "torchaudio == 0.11.0"`
`!pip install "torchtext == 0.12.0"`

And in the end install speechbrain
`!pip install -q speechbrain`

I try some use cases with **pyannote.audio (speaker diarization)** and it works

**Comment by Yinsight** [comment]
It worked for me. Thank you so much!

**Comment by hbredin** [comment]
This [PR](#1030) that updates the installation instructions in the main `README` fixes the issue.
