### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by mateosere** [pyannote/pyannote-audio#1036]
Hi, when I run 

`diarization = pipeline("audio.wav")
`
I receive "`CUDA out of memory. Tried to allocate xxx GiB (GPU 0; x.xx GiB total capacity; x.xx GiB already allocated; 0 bytes free`"

The audio.wav file is a 2 min audio of 25mb. What can I do? 

Cheers

**Comment by hbredin** [comment]
You may try to decrease the [batch size](https://github.com/pyannote/pyannote-audio/blob/26cddd98f91a770f9c73f569f200674fda1ee705/pyannote/audio/pipelines/speaker_diarization.py#L76).

**Comment by mateosere** [comment]
Perfect thanks !
