### ISSUE TITLE
 Using pyannote-audio/tutorials/intro.ipynb with Google Colab

### ISSUE THREAD

**Issue by HanBiru** [pyannote/pyannote-audio#1038]
Hi!

I tried to use the intro.ipynb notebook under tutorial through google colab (since I do not have a GPU on my pc). 

**To Reproduce**
Run intro.ipynb with colab.

Under pip install you get:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.13.0+cu113 requires torch==1.12.0, but you have torch 1.11.0 which is incompatible.
torchtext 0.13.0 requires torch==1.12.0, but you have torch 1.11.0 which is incompatible..
```
And when importing modules you get:
```
OSError: /usr/local/lib/python3.7/dist-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN3c1022getCustomClassTypeImplERKSt10type_index
```
After this I tried to upgrade python in colab from 3.7 to 3.8 by using these commands before the pip installs:
```
!wget -O mini.sh https://repo.anaconda.com/miniconda/Miniconda3-py38_4.8.2-Linux-x86_64.sh
!chmod +x mini.sh
!bash ./mini.sh -b -f -p /usr/local
!conda install -q -y jupyter
!conda install -q -y google-colab -c conda-forge
!python -m ipykernel install --name "py38" --user
```
And the pip dependency conflict for torchtext disappeared. But the OSError remained (python3.7 was still in the path.)

Could you please give me any advice on how to use your notebook through colab? 
Is there any setting in google colab I have forgot to set up? (I got the Diarization Pipeline, as an example, to work on my pc locally, but since my specs are very slow I really want to use a cloud GPU instead.)

**Comment by hbredin** [comment]
I have updated the installation part of `intro.ipynb`.
Closing (but please re-open if this does not solve your initial problem).

**Comment by HanBiru** [comment]
Thank you so much! I tried the new installation on google colab and it seems to work fine now!
