### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'segmentation_step'

### ISSUE THREAD

**Issue by govindrathore27** [pyannote/pyannote-audio#1043]
Recently showing this error while using speaker diarization

**Comment by hbredin** [comment]
That is expected and is due to recent changes in the code base.
Please update to the latest version of pyannote.audio.

**Comment by govindrathore27** [comment]
Hey @hbredin I have updated the version it is still showing the same error so can you please tell me how to resolve it and please also update the documentation as well.
Thank You

**Comment by lindalibjchn** [comment]
I still have this issue, how to update the lastest version? 
I have done "pip install pyannote.audio", but it doesnot work.
