### ISSUE TITLE
How can I load a finetuned model after saving a local checkpoint? 

### ISSUE THREAD

**Issue by MerlinLaffitte** [pyannote/pyannote-audio#1045]
Hi @hbredin,

Thank you and the pyannote community for this amazing work! 

Context of my issue:
I am finetuning a segmentation model from your pretrained huggingface version with my custom pyannote.database dataset and everything works fine. I managed to use your tutorials (for instance https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/training_a_model.ipynb) and read the docs to reach this point but I am currently stuck on the saving of the checkpoints and the loading of these checkpoints. 

I am saving the checkpoints but when I try to reload the ckpt file using Model.from_pretrained I encounter an error : 
```
RuntimeError: Error(s) in loading state_dict for PyanNet:
	Unexpected key(s) in state_dict: "validation_metric.OptimalDiarizationErrorRate.threshold", "validation_metric.OptimalDiarizationErrorRateThreshold.threshold", "validation_metric.OptimalSpeakerConfusionRate.threshold", "validation_metric.OptimalMissedDetectionRate.threshold", "validation_metric.OptimalFalseAlarmRate.threshold". 
```

What did I miss in the method to load the checkpoints? I tried as well to pass the yml file to the method via the optionnal parameter 'hparams_file' , as indicated in https://github.com/pyannote/pyannote-audio/blob/develop/pyannote/audio/core/model.py  but I encounter similar errors. 

Thank you again for your work, I hope you can help me understand my problem, which seems really basic.

**Comment by hbredin** [comment]
Try using `strict=False` option.

```python
model = Model.from_pretrained(..., strict=False)
```

If that solves your issue, I would really appreciate if you could contribute a Pull Request adding this missing detail in the `training_a_model` notebook. That would most likely help other people facing the same problem.

**Comment by hbredin** [comment]
Cool! Looking forward to your PR!
