### ISSUE TITLE
inference call not accepting clean wav audio

### ISSUE THREAD

**Issue by chintanckg** [pyannote/pyannote-audio#1049]
Steps to Reproduce:

```
from pyannote.audio import Inference

inference = Inference("pyannote/embedding", window="whole")

emb1 = inference("lol.wav")
```

![image](https://user-images.githubusercontent.com/13482558/181433458-6913b9e3-5019-47b6-b556-c201ccfef476.png)

**Comment by hbredin** [comment]
Would you mind sharing a link to a Google Colab containing a self-contained minimum reproducible example that I can run to reproduce the error?
