### ISSUE TITLE
Apply onset / offset on raw VAD scores

### ISSUE THREAD

**Issue by YannisTevissen** [pyannote/pyannote-audio#1051]
Hello,

I need to get raw VAD scores through the `Inference` class but after that I'd need to apply onset / offset and min_duration as when I instantiate a `Pipeline` class with hyperparameters.
Could you suggest the best way to do so ?
Thanks a lot for your time and for the library

**Comment by manish-kumar-iisc** [comment]
[https://github.com/pyannote/pyannote-audio/issues/1028](https://github.com/pyannote/pyannote-audio/issues/1028)
see this
