### ISSUE TITLE
Show audio and rttm graph together in sync on play

### ISSUE THREAD

**Issue by AMITKESARI2000** [pyannote/pyannote-audio#1052]
Hi,
Just wanted to suggest a feature:
If rttm visual and audio can be seen together with a seek. Similar to this [blogpost ](https://www.scottcondron.com/jupyter/visualisation/audio/2020/10/21/interactive-audio-plots-in-jupyter-notebook.html) using [Holoviews](http://holoviews.org/) and [Panel](https://panel.holoviz.org/) by the [Anaconda](https://anaconda.org/) team. 
![image](https://user-images.githubusercontent.com/66141447/182044645-cf908711-eaca-43fd-83b1-34d4a082eda5.png)

Hope it lets you visualise the interaction!
Thanks

**Comment by hbredin** [comment]
Thanks for the suggestion which is strongly related to #832
Would you like to contribute this new feature?

Closing as we can continue this discussion in #832.
