### ISSUE TITLE
Using only Speaker change detection

### ISSUE THREAD

**Issue by Khimer** [pyannote/pyannote-audio#1054]
Does the library provide the use of Speaker change detection separately from the rest of the pipeline? I did not find such an opportunity in the code, thanks.

**Comment by hbredin** [comment]
pyannote.audio 1.x does provide speaker change detection (SCD) pipeline but pyannote.audio 2.x does not.

The main reason is that SCD is an ill-defined problem as soon as speakers overlap in time.

I'd suggest you try the [`pyannote/speaker-segmentation`](https://huggingface.co/pyannote/speaker-segmentation) pipeline that directly output (possibly overlapping) speech turns.
