### ISSUE TITLE
About write overlap labs to rttm

### ISSUE THREAD

**Issue by axuan731** [pyannote/pyannote-audio#1055]
I have a problem about how to write my overlab to rttm,for example:
overlap lab:
28.987 31.51 overlap
33.496 34.011 overlap
38.756 43.991 overlap
79.925 80.611 overlap
rttm:
SPEAKER bzlts 1 25.891000 2.880000 <NA> <NA> 4 <NA> <NA>
SPEAKER bzlts 1 28.771000 0.720000 <NA> <NA> 6 <NA> <NA>
SPEAKER bzlts 1 29.491000 1.440000 <NA> <NA> 2 <NA> <NA>
SPEAKER bzlts 1 30.931000 10.080000 <NA> <NA> 6 <NA> <NA>
SPEAKER bzlts 1 41.011000 2.880000 <NA> <NA> 2 <NA> <NA>
SPEAKER bzlts 1 43.891000 14.400000 <NA> <NA> 4 <NA> <NA>
SPEAKER bzlts 1 58.291000 1.440000 <NA> <NA> 6 <NA> <NA>
SPEAKER bzlts 1 59.731000 19.440000 <NA> <NA> 4 <NA> <NA>
SPEAKER bzlts 1 79.171000 6.480000 <NA> <NA> 2 <NA> <NA>

Does pyannote have any program to add my overlap lab to the rttm?
Thanks for helping!

**Comment by MariemNEJI1** [comment]
hi I am not sure if there is any function integrated within pyannote for the conversion. However you can do that with a simple file parsing and write the output in .rttm file.
this may help you i needed to convert from rttm to uem

```
def rttm2uem(rttm_file,uem_file):
 #     SPEAKER xx 13.953 10.096 <NA> <NA> spk2 <NA> <NA>
  # to
  #     xx NA 13.953 10.096
    with open(rttm_file,'r') as frttm, open(uem_file,'w') as fuem :
    
        for l in frttm.readlines():

            print(str(l.split()[1])+' NA '+str(l.split()[3])+' '+str(l.split()[4]),file=fuem)
```
