### ISSUE TITLE
Using Oracle SAD and SCD

### ISSUE THREAD

**Issue by swm1718** [pyannote/pyannote-audio#1056]
Hello - In issue #445 you kindly explained how to use the OracleSpeechTurnSegmentation to tell a pre-trained model to use the oracle SAD and SCD.  Those instructions no longer seem to work as the code was so comprehensively updated in version 2.0.  I am sure there is an easy answer as I see several references to oracle in the code, but I have not managed to get it to work.  How should it be done now?  Many thanks.  Simon

**Comment by hbredin** [comment]
Because I am slowly moving towards end-to-end speaker diarization, the new speaker diarization pipeline no longer relies on separate voice activity and/or speaker change detection modules.

Therefore, there is no easy solution to (my possibly incorrect undersanding of) your problem.
