### ISSUE TITLE
How can I prepare dataset to reproduce pyannote/segmentation@2022.07

### ISSUE THREAD

**Issue by akuzeee** [pyannote/pyannote-audio#1067]
Hi,

I would appreciate if you could provide a procedure to prepare the dataset to reproduce [pyannote/segmentation@2022.07](https://huggingface.co/pyannote/speaker-diarization/tree/main).

In my understanding, the model was trained using the dataset made of the concatenation of three corpus, as mentioned in the paper: https://arxiv.org/pdf/2104.04045.pdf. I have found [here](https://github.com/pyannote/AMI-diarization-setup/tree/main/pyannote) how to prepare the AMI dataset, but have not found anything about the composite data.

**Comment by akuzeee** [comment]
Thank you for your very helpful response. I can't decide immediately whether to use a paid dataset, so I don't sure if I can prepare such a script, but I will let you know if I make any progress.

**Comment by hbredin** [comment]
FYI, @FrenchKrab created a data preparation script for AISHELL-4.
It is available here: https://github.com/FrenchKrab/aishell4-pyannote
