### ISSUE TITLE
What formats of speech does the algorithm currently support?

### ISSUE THREAD

**Issue by JJ-Guo1996** [pyannote/pyannote-audio#1069]
Hi！What formats of speech does the algorithm currently support?

**Comment by hbredin** [comment]
Can you please clarify what you mean by "format of speech"?

**Comment by JJ-Guo1996** [comment]
> Can you please clarify what you mean by "format of speech"?

such as wav,mp3,ogg et.al

**Comment by hbredin** [comment]
Ah. Audio format, right! 

Anything that [torchaudio](https://github.com/pytorch/audio) can read since pyannote.audio relies on torchaudio for IO.

**Comment by rbracco** [comment]
Hi, I'm getting an error when trying to read MP3 files
`RuntimeError: Error opening '/home/rob/code/data/commonvoice/audios/common_voice_en_19968212.mp3': File contains data in an unknown format.` when calling `vad = pipeline("/home/rob/code/data/commonvoice/audios/common_voice_en_19968212.mp3")
`, it works fine for WAV files. Am I doing something wrong?

I followed the install instructions and I'm in a Conda env with python 3.8.13 and pyannote.audio version 2.1.1. Happy to provide more info if needed, thank you!

**Comment by hbredin** [comment]
pyannote.audio relies on torchaudio for reading audio.
Are you able to read this file directly with torchaudio?

**Comment by hbredin** [comment]
I guess this is a question for `torchaudio` rather than `pyannote.audio` cc @mthrok.

**Comment by mthrok** [comment]
Hi folks

> RuntimeError: Error opening 'sample.mp3': File contains data in an unknown format.

That error suggests that the file is corrupted.
Can you verify you can play the file in some other media player?
And if that works, can you tell me the version of your torch/torchaudio?
You  can do so by running `python -m 'torch.utils.collect_env'` command.

**Comment by fa16-030** [comment]
Hi @mthrok ,
I am using colab.
Audio file is fine, I have checked it using media player.
Before importing and loading model like this:
```
from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization@2.1", use_auth_token=True)
```

> audio = torchaudio.load('sample.mp3', format="mp3")

torchaudio is  working

But After importing and loading, 
its giving error:

> of an unknown format

and same error (unknown format) for this command :
`diarization = pipeline('sample.mp3')
`

and this dilarization command is working fine for ".wav" file

TORCH VERSION:
```
[pip3] numpy==1.21.6
[pip3] pytorch-lightning==1.6.5
[pip3] pytorch-metric-learning==1.6.3
[pip3] torch==1.12.1+cu113
[pip3] torch-audiomentations==0.11.0
[pip3] torch-pitch-shift==1.2.2
[pip3] torchaudio==0.12.1+cu113
[pip3] torchmetrics==0.10.3
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.13.1
[pip3] torchvision==0.13.1+cu113
```

**Comment by mthrok** [comment]
In that case, can you install ffmpeg?

```
!add-apt-repository -y ppa:savoury1/ffmpeg4
!apt-get -qq install -y ffmpeg
```

**Comment by fa16-030** [comment]
@mthrok ,Sorry to bother you again
I have checked it, but still getting error

![error](https://user-images.githubusercontent.com/111121180/203088537-591ea677-e0b4-4f27-8c69-45338149e780.png)
