### ISSUE TITLE
Question about the LOG_DIR

### ISSUE THREAD

**Issue by NeilsonZhu** [pyannote/pyannote-audio#107]
Hello

I am following the tutoral same_different_experiment. I found that in the very begining part. There is parameter that called LOG_DIR. It should be a path that store a pretrained model. However, I am a little confused that what the pretrained model it is? Is it the sequence embedding model? If so, when I start to use it, I don't have a pretrained model. I should initial a new one then train it. How do I get the pretrained model?

Thank you

**Comment by hbredin** [comment]
I guess you are refering to the TristouNet repo: https://github.com/hbredin/tristounet
This is no longer supported -- please follow pyannote-audio's speaker embedding tutorial instead.
