### ISSUE TITLE
How to get the output of the voice activity speech?

### ISSUE THREAD

**Issue by JJ-Guo1996** [pyannote/pyannote-audio#1070]
Hi ,input a raw audio with unvoice segment and how to get the output of the voice activity speech?

**Comment by hbredin** [comment]
See https://huggingface.co/pyannote/voice-activity-detection

**Comment by JJ-Guo1996** [comment]
> See https://huggingface.co/pyannote/voice-activity-detection

This only get the duration of the active voice, can i get the .wav file of the activity voice?

**Comment by hbredin** [comment]
Using [pydub](https://github.com/jiaaro/pydub), maybe?
