### ISSUE TITLE
TPU inference?

### ISSUE THREAD

**Issue by R4ZZ3** [pyannote/pyannote-audio#1082]
Has anyone tried running the pipeline with TPUs?
Any success?
Any examples?

**Comment by hbredin** [comment]
I would like to know that too! What did you try?

**Comment by R4ZZ3** [comment]
Nothing as of yet. I was just curious as I saw in the release notes that at least training some parts of the pipeline should be possible to train with TPUs "multi-GPU and TPU training thanks to [pytorch-lightning](https://pytorchlightning.ai/)"

I am currently running speaker-diarization pipeline as part of pipeline to gather pretraining material for ASR. It is currently running on my home GPU but I also have access to few v3-8 TPUs and thought if I could speed up the preprocessing part using those.

**Comment by R4ZZ3** [comment]
I spun up v3-8. 
Created conda env, pip python=3.8

Installed transformers, jax[flax], datasets, updated stuff with apt-get ..., installed pyaudio with pip.
Uploaded sample foo.wav to tpu and tried with the abovve
![image](https://user-images.githubusercontent.com/25264037/189714468-773bafbc-75ee-4355-b59a-dcd69e54575a.png)

**Comment by R4ZZ3** [comment]
![image](https://user-images.githubusercontent.com/25264037/189742622-6d538113-b7fa-456d-9927-72c3d70daa2d.png)
Also error with xla

**Comment by hbredin** [comment]
Without an actual access to TPUs, I am afraid I won't be able to help you here....

**Comment by R4ZZ3** [comment]
I will discuss with my friend in our project if we could setup you a machine to investigate this if you are interested.

**Comment by R4ZZ3** [comment]
Google colab offers TPUs so I can setup you a starting notebook there and give you a link here (If you have time and interest ofc).

**Comment by hbredin** [comment]
Sure! The last time I tried getting access to a TPU on Colab, it told me none were available so I thought one has to pay for it...

**Comment by R4ZZ3** [comment]
Ok, I will try that first but if I hit the same wall we will need to investigate how we can give safe and properly restricted access to our project TPUs

**Comment by R4ZZ3** [comment]
Ok, 

Seems that it is quite hard to get TPU in colab but in Kaggle it is more reliable. 20hrs for free/week.
I will try to setup the notebook in there.
