### ISSUE TITLE
Get Embedding segment of diarization pipeline

### ISSUE THREAD

**Issue by landEpita** [pyannote/pyannote-audio#1089]
Hello,

My goal would be to get the embedding of each Speaker from the diarization in order to do some identification afterwards.

I checked the code to add this feature (Return (Annotation, embedding)). There are several elements that I have trouble understanding.

1] the difference between chunks and frame for the return of `self.get_segmentations` ?
> shape: (num_chunks, num_frames, local_num_speakers)

i understand that chunks is 5s with pad of 0.5

2] how to calculate the embedding average of each segment ?
 
thank you for your work

**Comment by hbredin** [comment]
> Hello,
> 
> My goal would be to get the embedding of each Speaker from the diarization in order to do some identification afterwards.
> 
> I checked the code to add this feature (Return (Annotation, embedding)). There are several elements that I have trouble understanding.
> 
> 1] the difference between chunks and frame for the return of `self.get_segmentations` ?
> 
> > shape: (num_chunks, num_frames, local_num_speakers)
> 
> i understand that chunks is 5s with pad of 0.5

[This notebook](https://gist.github.com/hbredin/f7c3c2054a21dafe7e017acf0312a80f) provides an explanation of the shape

> 2] how to calculate the embedding average of each segment ?

[This tutorial](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/speaker_verification.ipynb) can probably help.
