### ISSUE TITLE
Issue in db.yml

### ISSUE THREAD

**Issue by NeilsonZhu** [pyannote/pyannote-audio#109]
Hello Bredin

I am trying to follow your feature-extraction tutorial. I followed the instruction that download the audio file in a folder called Recording_Data and create a db.yml file in .pyannote folder. My db.yml is 

AMI:
     - /home/Recording_Data/amicorpus/ES2002a/audio/{uri}.wav
     - /home/Recording_Data/amicorpus/ES2002b/audio/{uri}.wav
     - /home/Recording_Data/amicorpus/ES2002c/audio/{uri}.wav
     - /home/Recording_Data/amicorpus/ES2002d/audio/{uri}.wav
     - /home/Recording_Data/amicorpus/ES2003a/audio/{uri}.wav
     - /home/Recording_Data/amicorpus/ES2003b/audio/{uri}.wav
     - /home/Recording_Data/amicorpus/ES2003c/audio/{uri}.wav
     - /home/Recording_Data/amicorpus/ES2003d/audio/{uri}.wav
     - /home/Recording_Data/amicorpus/ES2004a/audio/{uri}.wav

When I tried to extract the features from audio files pyannote-speech-feature ${EXPERIMENT_DIR} AMI.SpeakerDiarization.MixHeadset I got the following error:

Traceback (most recent call last):
  File "/home/neilzhu/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/applications/feature_extraction.py", line 112, in process_current_file
    current_file['audio'] = file_finder(current_file)
  File "/home/neilzhu/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/database/util.py", line 297, in __call__
    raise ValueError(msg.format(uri=uri))
ValueError: Could not find file "ES2003a.Mix-Headset".

I checked that the file is in the folder. I really don't know what's happening about it

Neil

**Comment by bml1g12** [comment]
Try instead one line:
 AMI: /home/Recording_Data/amicorpus/*/audio/{uri}.wav

**Comment by NeilsonZhu** [comment]
I changed. The same issue.

**Comment by NeilsonZhu** [comment]
I got the reason.

**Comment by manuelhuber** [comment]
@NeilsonZhu How did you resolve this?

**Comment by chienducnguyen** [comment]
How did you resolve this? @NeilsonZhu

**Comment by chienducnguyen** [comment]
i stuck in this issue 
pyannote.audio.features.utils.PyannoteFeatureExtractionError: No precomputed features for "AMI/EN2002b.Mix-Headset".

**Comment by bml1g12** [comment]
Have you Precomputed the features as per the tutorial?

**Comment by chienducnguyen** [comment]
when i run this command "pyannote-speech-feature ${EXPERIMENT_DIR} AMI.SpeakerDiarization.MixHeadset" 
i stuck with AttributeError: 'Precomputed' object has no attribute 'dimensions_' :(

**Comment by Jcakilv** [comment]
@NeilsonZhu @manuelhuber How did you resolve this?

**Comment by manuelhuber** [comment]
@Jcakilv Not at all - I eventually built my own network and used a completely different corpus

**Comment by hbredin** [comment]
@Jcakilv can you please open a new issue with detailed instructions on how to reproduce the error you get? This very issue has been closed already a long time ago.
