### ISSUE TITLE
Running on Mac M1 using mps / GPU

### ISSUE THREAD

**Issue by acronomic** [pyannote/pyannote-audio#1091]
Hi, I've been trying over the last few days to get pyannote.audio to work with my mac m1 gpu, but judging from processing times (it takes about 10 min on a 2.5min file), I believe it keeps reverting to the cpu. I've made sure that Torch has access to the gpu, and I plan to try to modify some of model.device.type code to "mps".  However, I'm wondering are there other dependencies or sections of the code I would have to modify in order to get it to run on a mac gpu?

Thank you,
Michael

**Comment by hbredin** [comment]
I tried "mps" myself in 

```python
inference = Inference("pyannote/segmentation", device=torch.device("mps"), batch_size=32)
inference("audio.wav")
```

and it is actually much slower on "mps" than on "cpu".
Increasing `batch_size` does reduce the gap but "mps" is still slower than "cpu".

I believe this is because "mps" is still experimental and does not fully benefit from the M1 GPU yet. This is more a problem with PyTorch than pyannote.audio, I am afraid...

**Comment by gokeji** [comment]
I'm very new to pytorch or mps and was just digging around a bit to see if I can speed up pyannote-audio on my intel macbook. I tried installing the nightly build for pytorch which did seem to speed up inference for me.

From https://developer.apple.com/metal/pytorch/
`pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu`

Specifying `device=torch.device("mps")` made inference slower however, with both the nightly pytorch build or without. Leaving this observation here in case it helps someone.
