### ISSUE TITLE
Installation issues in mac M1 chip error: metadata-generation-failed

### ISSUE THREAD

**Issue by luisignaciomenendez** [pyannote/pyannote-audio#1093]
**Is your feature request related to a problem? Please describe.**
I followed the instructions at https://github.com/pyannote/pyannote-audio#installation to install pyannote. I have an environment running with python 3.8. However, an issue occurs while running the pip install 👍 
![Screenshot 2022-09-28 at 18 23 36](https://user-images.githubusercontent.com/62380208/192834281-4a8257c7-16d4-4a3d-8de4-68747feabb1c.png)

**Describe alternatives you've considered**
I've tried installing in my usual 3.9 environment but this does not do it as python can't import the package (it keeps stuck running). 

**Additional context**
I am sing a macbook pro M1 chip. Tried installing under the zsh terminal from mac and also another bash terminal from Atom and none of them work.

**Comment by rodigu** [comment]
![2024-02-07_18-05](https://github.com/pyannote/pyannote-audio/assets/58960796/1d0fde8d-cd12-4833-87f0-97a7098c5f9d)

Have the same issue on linux mint
