### ISSUE TITLE
Only doing segmentation when `num_speakers=1` for speaker diarization. 

### ISSUE THREAD

**Issue by xuqiantong** [pyannote/pyannote-audio#1094]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Some if/else branches to remove the diarization logic when num_speakers=1, so that only the segmentation part is kept. 

**Describe alternatives you've considered**
Nope

**Additional context**
When running on CPU, seems like the embedding extraction is the most time consuming part. Can we get around it when we are sure there is only one speaker in the audio?

**Comment by hbredin** [comment]
Speaker diarization with `num_speakers=1` is basically voice activity detection.

You could therefore use `pyannote/voice-activity-detection` in place of `pyannote/speaker-diarization`. 

But I do get your point that the speaker diarization pipeline could handle this corner case more efficiently. Would you like to contribute these `if/else` branches, via a PR? It could be just replacing the embedding+clustering steps by a fake clustering algorithm that simply assigns everything to one single cluster.
