### ISSUE TITLE
How to train/Finetune for Custom AD(Activity Detection), like laughing, etc

### ISSUE THREAD

**Issue by m-ali-awan** [pyannote/pyannote-audio#1097]
Hi all!

I am working on developing pipelines for Laughing, Crying etc. I want to achieve them, like VAD in pyannote pipeline. How can I use Pyannote for training purposes. Moreover, I want to use the pipeline on device: Android/IoS, so kindly also guide me in that direction as well..

Thanks

**Comment by hbredin** [comment]
Those are two very different questions.

Please open one issue per question to make it easier for people to find relevant info (and make sure to read open and closed issue first as those might have been answered already).

Regarding your first point, a PR has been merged recently in `develop` branch that should make it easy to train such pipelines (as long as you have access to labeled training data).

See [this notebook](https://github.com/pyannote/pyannote-audio/blob/551b2c4170bd3f10a30d6a052eb9d4b6e8ddce27/tutorials/multilabel_detection.ipynb) for an example focusing on non-speech/male-speech/female-speech classification.
