### ISSUE TITLE
cannot import name SpeakerChangeDetection from pyannote.audio.tasks

### ISSUE THREAD

**Issue by saadtariqaddo** [pyannote/pyannote-audio#1102]
from pyannote.audio.tasks import SpeakerChangeDetection
scd= SpeakerChangeDetection(protocol, duration=2., batch_size=32, num_workers=4)
speaker_change_detection_model = SimpleSegmentationModel(task=scd)
trainer = pl.Trainer(max_epochs=1)
_ = trainer.fit(speaker_change_detection_model)

![image](https://user-images.githubusercontent.com/93965918/195589974-5dcedf88-c906-4918-a82a-97523affa2d4.png)

**Comment by hbredin** [comment]
`SpeakerChangeDetection` task has been removed in version 2.x.
I recommend using the `Segmentation` task instead.

**Comment by saadtariqaddo** [comment]
I am trying to create a speaker diarization model. Initially i tried the pre-trained model and didn't achieved the desired results. The chunks that were generated from pre-trained speaker diarization were cropped from the end and speech was not finished in some of the chunks. Is it normal in pre-trained speaker diarization or do I need to create a model from scratch?

It latter is the case, what steps I need to perform to create a diarization model

**Comment by saadtariqaddo** [comment]
@hbredin Can you help me to understand how can i fully trained speaker-dairization from scratch
