### ISSUE TITLE
Help needed, total beginner

### ISSUE THREAD

**Issue by ItsMe-TJ** [pyannote/pyannote-audio#1110]
I'm about to ask a really dumb question, so beware! but I'm a total beginner when It comes to python and pyannote.

I have an audio file from a podcast where 2 people are talking, and I want to extract the individual speakers into 2 different files so basically.. all speaker 1 audio in one file, and speaker 2 in the other. I also want to use overlap detection to discard whenever they're talking over each other. How would I go about doing this?

Help much appreciated!

Thank you!

**Comment by nehat005** [comment]
You can try using pre-trained diarization model from pyannotate. 
I have just tried it out myself, you can use this [script](https://github.com/nehat005/SpeakerDiarizationProject/blob/pyannotate_diarization/pyannotate_inference.ipynb) as reference! (suggestion: use it on google colab as it's simple and easy to use for beginners)

With the diarized outputs which specify start and end time of a speaker's speech data,  you can simply cut the audio into segments, and save it in 2 different lists (one for each speaker), write it to wave format using any speech processing python library (such as [soundfile](https://pysoundfile.readthedocs.io/en/latest/)

Hope this helps!

**Comment by ItsMe-TJ** [comment]
Thank you, when you say "cut the audio into segments, and save it in 2 different lists". Do you mean manually going through the audio? Or is there an automated way of cutting the audio using the specified start and times.

**Comment by nehat005** [comment]
No not manually, you can simply write a script where you read the audio array and then index it from a certain speaker's start and end speaking time point, and collect those audio segments in an array.. you can also find such scripts in many open source diarization projects

**Comment by ItsMe-TJ** [comment]
Okay, thank you.. That sounds really complicated. I'll have to take a look and see If I can find a script like that,
