### ISSUE TITLE
finetune embedding model

### ISSUE THREAD

**Issue by Khimer** [pyannote/pyannote-audio#1117]
Hello! Your diarization system is something incredible! I use it to chronicle discussions/arguments with friends, but the problem is that my voice is very similar to my friend's and because of this, the diarization system often confuses us. I tried changing the segmentation and clustering parameters, as well as retraining the segmentation model on the recordings of our voices with him, but the system still confuses us. Perhaps additional training of the embedding model could solve this problem, but unfortunately I can’t find a manual for its finetuning, but judging by your answers in other questions, it used to be. Can I see it?
Overwhelming thanks!

**Comment by wasauce** [comment]
@Khimer - what app do you use to record you and your friends? Voice Memos?

**Comment by Khimer** [comment]
@wasauce we are located in different cities and use skype to communicate, it allows you to record calls

> @Khimer - what app do you use to record you and your friends? Voice Memos?
