### ISSUE TITLE
How to load the model or pipeline in. cache

### ISSUE THREAD

**Issue by yy835055664** [pyannote/pyannote-audio#1130]
Hello, excuse me, I have downloaded segmentation, how to call this pipeline from. cache？

**Comment by hbredin** [comment]
I have just updated the [FAQ](https://github.com/pyannote/pyannote-audio/blob/develop/FAQ.md#can-i-use-gated-models-and-pipelines-offline) with instructions on how to use pretrained models and pipelines offline.

**Comment by landEpita** [comment]
Thx for your help @hbredin. Do you know how can we use speechbrain/spkrec-ecapa-voxceleb offline ? we can't find a bin file on https://huggingface.co/speechbrain/spkrec-ecapa-voxceleb/tree/main

**Comment by hbredin** [comment]
This is rather a question for [speechbrain](https://github.com/speechbrain/speechbrain), not pyannote.audio. 

Once you find the solution, I'd gladly consider a PR adding it to the FAQ.
