### ISSUE TITLE
Unexpected keyword argument error when using speaker diarization pipeline

### ISSUE THREAD

**Issue by LazyG** [pyannote/pyannote-audio#1133]
I receive the following error about segmentation_step not being a recognized parameter, even though the documentation seems to indicate that it should be, https://github.com/pyannote/pyannote-audio/blob/develop/pyannote/audio/pipelines/speaker_diarization.py#L68.  Am I missing something or is this a bug of some sort?  I would appreciate guidance on how to resolve.  Thank you.

```
from pyannote.audio.pipelines import SpeakerDiarization

pipeline = SpeakerDiarization.from_pretrained('pyannote/speaker-diarization', use_auth_token=True)

 
dz = pipeline(file = '../Data/Outputs/test.wav',
              min_speakers = 2,
              max_speakers = 5,
              segmentation_step= 0.05 #default is 0.1
             )
```

Returns Error:
`TypeError: apply() got an unexpected keyword argument 'segmentation_step'`

I also get the same error when running 
```
from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained('pyannote/speaker-diarization', use_auth_token=True)
dz = pipeline(file = '../Data/Outputs/test.wav',
              min_speakers = 2,
              max_speakers = 5,
              segmentation_step= 0.05 #default is 0.1
             )
```

**Comment by Ca-ressemble-a-du-fake** [comment]
Based on this [answer](https://github.com/pyannote/pyannote-audio/discussions/1105#discussioncomment-3904118) you can change the segmentation step via :
`pipeline.segmentation.segmentation_step=0.05`

**Comment by LazyG** [comment]
@Ca-ressemble-a-du-fake , thank you.  I've confirmed that the answer you linked works.
