### ISSUE TITLE
‘2.1’ is not a valid semver code

### ISSUE THREAD

**Issue by jsullvan** [pyannote/pyannote-audio#1134]
This error occurs because the Pyannote version number is 2.1, but semver requires a 3 digit number. 

This problem can be hack fixed by navigating to '.../lib/python3.8/site-packages/pyannote/audio/core/model.py', and on line 422 adding the following lines of code:

if len(mine)==3:
   mine = mine+'.0'

However, this obviously should not be a permanent solution, as poetry or conda environments cannot be easily shared.

**Comment by hbredin** [comment]
pyannote.audio 2.1.1 has been released, that solves this problem.

**Comment by Ace-myu** [comment]
I am getting an error of "ValueError: 1.8.0rc0 is not valid SemVer string" - how can I resolve this?
Currently have:
Pyannote.audio 3.1.0
Torch 2.0.0 cpu
Torch audio 2.0.1 cpu
