### ISSUE TITLE
diarizing an audio with a flat transcript

### ISSUE THREAD

**Issue by jhdeov** [pyannote/pyannote-audio#1141]
**Is your feature request related to a problem? Please describe.**
I have sound files that are already transcribed in Praat. But transcriptions are just a single tier of words that different people have said. There's no hierarchical annotation. To illustrate, I have SRTs from YouTube interviews. The SRTs don't tell you who is speaking, they just list out the string of words uttered. Sometimes you'll see punctuation used to separate different speakers within an interval. 
It's not clear to me if there's a pre-existing task that can take a sound file + flat transcript, and return a diarized transcript where the pre-existing text is broken up across speakers. Example input and output is below (I made them up). 

Input: sound file + single-level or single-tier transcript with boundaries (start/end times)
<img width="1258" alt="input" src="https://user-images.githubusercontent.com/42621803/200717167-1844e3ea-830f-4460-b4fe-e9b3959e702f.png">

Output: a multi-tiered transcription that estimated what different people said, and tries to stay close to the original boundaries if possible
<img width="1221" alt="Screen Shot 2022-11-08 at 5 53 23 PM" src="https://user-images.githubusercontent.com/42621803/200717400-c4cdc6bf-972d-4506-849c-4570ba4d5880.png">

**Describe the solution you'd like**
I think I explained it above. It seems there's a [pipeline](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/applying_a_pipeline.ipynb) for when the input lacks a transcript. And a pipeline for when there's a gold manual transcription. But not when there's a transcript for all the words uttered (with rough start/end times), but not assigned across speakers. 

There are also [pipelines](https://github.com/lablab-ai/Whisper-transcription_and_diarization-speaker-identification-) for making pyannote create a diarization, and then have an ASR model like Whisper transcribe the new segments. But, in my case, I already have a manually transcribed transcript that's significantly more correct than the transcript that the ASR model would generate. My data is on a low-resource language, so the ASR capabilities aren't very good. 

**Describe alternatives you've considered**
I think one possible pipeline is:
a) apply a model on the audio file
b) take the generated diarization (timestamps and speakers)
c) for each pair of generated timestamps (start/end times), estimate the text for that pair by comparing against the original transcript

I think this could work. But I'm not sure how to personally go about it. Step (c) seems like it would involve a bit of probability and statistics. It might also get optimized if there was a forced alignment of words/phones?

**Additional context**
Although I'm thinking this in terms of Praat TextGrids, the result from step (c) could also be modeled by adding an extra variable like `text` for the diarization's output. E.g., from the README:
```
for turn, _, speaker in diarization.itertracks(yield_label=True):
    print(f"start={turn.start:.1f}s stop={turn.end:.1f}s speaker_{speaker} text={text}")
# start=0.2s stop=1.5s speaker_0 text="Hello my name is"
```

**Comment by Majdoddin** [comment]
Try [this](https://github.com/Majdoddin/nlp), combines
[openai/whisper](https://github.com/openai/whisper)'s transcription and pyannote-audio's diarization, with a nice formatting.

**Comment by hbredin** [comment]
I think what you are looking for is a combination of forced alignment and speaker diarization.
`pyannote` does not do forced alignment: have a look at [Montreal forced aligner](https://montreal-forced-aligner.readthedocs.io/en/latest/).

**Comment by Majdoddin** [comment]
> My main problem is that my language is a low-resource language, so Whisper's transcription is quite off. The original transcript is already manually corrected for content + has timestamps from an SRT.

In that case, it sounds like a genuine opportunity to fine-tune `whisper` to recognize this language. How many hours of transcribed audio do you have available?
