### ISSUE TITLE
Speechbrain speaker-diarization accuracy is really low

### ISSUE THREAD

**Issue by abbatea** [pyannote/pyannote-audio#1145]
Hello everyone, I tried the speaker diarization
`from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization@2.1",
                                    use_auth_token="ACCESS_TOKEN_GOES_HERE")

# apply the pipeline to an audio file
diarization = pipeline("audio.wav")

# dump the diarization output to disk using RTTM format
with open("audio.rttm", "w") as rttm:
    diarization.write_rttm(rttm)`

And tried this code on multiple files but got really low accuracy for 2 people. For example identifying a speaker as speaker00, another one as speaker01 and it suddenly switches, that when speaker00 speaks the ouput says the other one speaks)

Is there a way to make the code more accurate, or is there like an "confident-percentage" as an output per line?

Best Regards

**Comment by JBJoyce** [comment]
Since updating pyannote.audio version to 2.1.1 I have also noted a drastic reduction in accuracy in audio files which were correctly diarized prior to updating. Is there a way to use previous pretrained models?

**Comment by hbredin** [comment]
[This](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/adapting_pretrained_pipeline.ipynb) might help.

**Comment by wahab4321** [comment]
Hi bro you got something with accuracy?
