### ISSUE TITLE
Segmentation Fault when conducting change detection tutorial

### ISSUE THREAD

**Issue by Charliechen1** [pyannote/pyannote-audio#115]
Hi,

Everything seems ok for the feature extraction tutorial. But when I train the model following exactly what the tutorial asks me to do for change detection, I got segmentation fault. What might be probably the reason. Thank you for your help.

**Comment by hedonistrh** [comment]
Hi,

_I am not the owner of repository._ Can you share your exact error with codes and error message?

**Comment by Charliechen1** [comment]
Seems the project failed in catching this error. It's just 'segmentation fault' in C. No other information is provided..

**Comment by chienducnguyen** [comment]
@Charliechen1 can you tell me how i can find "~/.pyannote/db.yml" or i need to create a db.yml

**Comment by hedonistrh** [comment]
@chienducnguyen If you work on Jupyter Notebook, you can do like this.

> To create, your own db.yml, you can use any text editor. We should write the directory of AMI Corpus. In this case, it is  **AMI: ../pyannote-audio/amicorpus/*/audio/{uri}.wav**

After that, you can run this command.

`! cat ./.pyannote/db.yml | grep AMI`

**Comment by hedonistrh** [comment]
@chienducnguyen Can you check your data to understand you have or not EN2002b.Mix-Headset.wav :)

**Comment by chienducnguyen** [comment]
i already have EN2002b.Mix-Headset.wav and still got that issue :(

**Comment by Charliechen1** [comment]
You would like to download all the audios.

**Comment by chienducnguyen** [comment]
it still need EN2002b although i download it :/

**Comment by hedonistrh** [comment]
@chienducnguyen May you check the output of this command in the your terminal?

`pip show pyannote.audio
`
You should get the output which start with these information, if you use the latest version.

> 
> Name: pyannote.audio
> Version: 1.0.1

**Comment by chienducnguyen** [comment]
It's not show anything when i run the command

**Comment by chienducnguyen** [comment]
It show the same with you

**Comment by hedonistrh** [comment]
If you work on Jupyter Notebook, can you execute this code instead of yours.

`!pyannote-speech-feature tutorials/feature-extraction AMI.SpeakerDiarization.MixHeadset`

**Comment by hbredin** [comment]
Closing because the issue has diverged from the original issue (segmentation fault).
Please open a new issue for every new problem...

@Charliechen1 Segmentation faults have happened to me before. The culprit was `dlib` which was not installed correctly. If `import dlib` raises a segmentation fault, I suggest you try fixing this first...

**Comment by wuzl** [comment]
hi @hbredin, how to fix the segmentation faults error. import pyannote.audio.train return Segmentation fault

**Comment by hbredin** [comment]
Try `import dlib`. If you get a `Segmentation fault`, the culprit is likely to be `dlib`.
You're going to have to fix your `dlib` installation.
