### ISSUE TITLE
Bug: Not being able to install the required packages from the documentation

### ISSUE THREAD

**Issue by felpsio** [pyannote/pyannote-audio#1153]
Hi, 

When I try to install the required packages from the documentation:

`conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 -c pytorch`

I'm getting the following error:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - torchaudio==0.11.1

Current channels:

  - https://conda.anaconda.org/pytorch/osx-arm64
  - https://conda.anaconda.org/pytorch/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

After that, I tried to install the following packages versions:

`conda install pytorch==1.12.0 torchvision==0.12.0 torchaudio==0.12.0 -c pytorch`

But then, when I try to run the example I get:

```
 UserWarning: Failed to import soundfile. 'soundfile' backend is not available.
  warnings.warn("Failed to import soundfile. 'soundfile' backend is not available.")
```

I'm on a `Mac M1` and using `Python 3.8.13`.

Should I install other versions or just follow additional instructions for my case?

**Comment by rhenanbartels** [comment]
>  UserWarning: Failed to import soundfile. 'soundfile' backend is not available.
  warnings.warn("Failed to import soundfile. 'soundfile' backend is not available.")

@felpsio it looks like you need to install `libsndfile` on your system.

`brew install libsndfile` might do the trick

**Comment by felpsio** [comment]
Still didn't work :(.

I'm able to run now on a linux environment. But I also had to run:

`pip install PySoundFile sox` and `sudo apt-get install libsndfile1`.

Even on linux I still wasn't able to run on a mp3 file. I had to convert to .wav

**Comment by mayeaux** [comment]
I was running into similar problems on an M1 Mac, was able to install the deps using:
```
$ conda create -n pyannote python=3.9
$ conda activate pyannote
$ conda install pytorch torchaudio -c pytorch
$ pip install pyannote.audio
```

And then I was also missing `libsndfile` , `brew` and `pip` both swung and missed but: 
`$ conda install -c conda-forge libsndfile`
Solved the issue for me

**Comment by felpsio** [comment]
Thanks @mayeaux. Were you able to work with mp3 files?

**Comment by mayeaux** [comment]
Yup works for me using mp3 files. It takes a really long time to process but I think that's more a virtue of PyTorch's current poor support for M1.

**Comment by felpsio** [comment]
yep, makes sense. Thanks for sharing your experience :)

**Comment by yugaljain1999** [comment]
@mayeaux I am trying to build sagemaker endpoint, but getting same libsndfile error, so as per your answer I need to install libsndfile using conda, but can u tell me how I can add conda requirements.txt file in code folder? Like while deploying how sagemaker can install conda requirements like we install pip packages by adding requirements.txt file?
