### ISSUE TITLE
Device running out of memory

### ISSUE THREAD

**Issue by jain11vaibhav** [pyannote/pyannote-audio#1156]
I have a 16GB RAM machine. On running speech diarization by pyannote audio on a slightly larger file (around 800 MB), the RAM runs out of memory and the code crashes. Is there a way to optimize the diarization solution so that it can run on a large audio file (as big as 5 GB)?
Is there any leak of memory which can be fixed or any other way so that a large audio can be processed?

**Comment by hbredin** [comment]
Thanks for reporting this. Others have complained about memory issue [already](https://github.com/pyannote/pyannote-audio/issues?q=memory).

This is not currently on my priority list but I'd be happy to have a look at a [memory profiler](https://github.com/bloomberg/memray) report -- showing exactly where the (potential) leak happens.
