### ISSUE TITLE
i can't install pyannote.audio 

### ISSUE THREAD

**Issue by chienducnguyen** [pyannote/pyannote-audio#116]
i'm stuck with chocolate>=0.6 when install pyannote

**Comment by arossetto** [comment]
I had this issue too. Try installing chocolate first, then installing pyannote.audio. That fixed the problem for me

The chocolate documentation is here: http://chocolate.readthedocs.io/
This is the command I used:
pip install git+https://github.com/AIworx-Labs/chocolate@master

**Comment by chienducnguyen** [comment]
thanks for your help.
But now i'm stuck when tell pyannote the db.yml
in the command
$ cat ~/.pyannote/db.yml | grep AMI
AMI: /path/to/ami/amicorpus/*/audio/{uri}.wav
no such file or dir: pyannote/db.yml

**Comment by chienducnguyen** [comment]
i had downloaded it but when i run command in extracion 
"$ export EXPERIMENT_DIR=tutorials/feature-extraction
$ pyannote-speech-feature ${EXPERIMENT_DIR} AMI.SpeakerDiarization.MixHeadset" 

i got this issue "AttributeError: 'Precomputed' object has no attribute 'dimensions_'"

**Comment by hbredin** [comment]
Closing because the original issue (installation of `pyannote.audio`) is resolved.
Please open a new issue for every new problem...
