### ISSUE TITLE
Speaker diarization is not working in Huggingface hub and local

### ISSUE THREAD

**Issue by nattu22** [pyannote/pyannote-audio#1163]
Hi team,

Greetings! and great job...

After a such a longtime got your speaker diarization model. It was working fine for last month. Now you added tokens for the model, able to generate and given the token. But it showing url not found error. Can you guys check the error fix the code please.

PFA screenshot for your reference. Same error in local setup also.

![image](https://user-images.githubusercontent.com/53460886/203571391-69f3f702-5720-435d-bb4e-ee1209666815.png)

**Comment by kouohhashi** [comment]
I have same issue.

I could not run the model on the Colab neither.

<img width="1269" alt="Screen Shot 2022-11-30 at 4 41 32 PM" src="https://user-images.githubusercontent.com/5446294/204737051-ebae4b22-2ae1-49cf-b048-083ea4bd810e.png">

**Comment by kouohhashi** [comment]
I found a reason.
It turned out I didn't follow the instruction and I failed to agree on the term.

If you open https://huggingface.co/pyannote/speaker-diarization and accept the term, somehow that agreement was not valid but if I open segmentation and accepted the term it worked.

**Comment by kouohhashi** [comment]
BTW, upgrading pyannote.audio may work.
