### ISSUE TITLE
diarization pipeline crashes on very long files 

### ISSUE THREAD

**Issue by laphang** [pyannote/pyannote-audio#1165]
I'm using speaker diarization pipeline, and it's running as expected for small files, and files up to 1 hr. (the 1 hr file takes around 3 mins) 

I'm running on an AWS Sagemaker Studio notebook, using the pytorch 1.10 gpu container, on a g4dn.xlarge instance. 

However, I'm getting crashes for longer files (eg 3.5 hrs).
- for the 3.5 hr file, it always crashes (not intermittent)
- I get the notebook popup below, saying that the kernel has died
- looking at instance metrics, the (non GPU) memory is not full. 
- there's no other output in the notebook describing the error 

I've tried getting some internal progress with `pipeline._segmentation.progress_hook = print`, the segmentation seems to complete, so the crash is occuring after that. 

![image](https://user-images.githubusercontent.com/24724502/203696608-7d5bb6fa-c75c-4428-aad5-2e9f9a48003a.png)

**Comment by abbatea** [comment]
Hello, are you running the following code?:
`from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization@2.1",
                                    use_auth_token="ACCESS_TOKEN_GOES_HERE")


# apply the pipeline to an audio file
diarization = pipeline("audio.wav")

# dump the diarization output to disk using RTTM format
with open("audio.rttm", "w") as rttm:
    diarization.write_rttm(rttm)`

If not can you please share the code?

Do you get a correct diarization for the one hour long files?

**Comment by laphang** [comment]
Hi, the code is fairly similar. Basically without the `2.1`, and loading in an mp3 using ffmpeg (via tranformers utils) and feeding it in from memory, and not writing it out to file (accessing from memory) 

Yes the diarization is correct for the shorter files (including 1 hr file). 

the crash is on the line `diarization = pipeline(audio_in_mem)`

```
from pyannote.audio import Pipeline
from transformers.pipelines import audio_utils

pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization",
use_auth_token="ACCESS_TOKEN_GOES_HERE")

with open(mp3_filename, "rb") as f:
    inputs = f.read()
audio = audio_utils.ffmpeg_read(inputs, 16000) 
audio_in_mem = {'waveform': torch.from_numpy(audio.reshape(1,-1)), "sample_rate": 16000}

diarization = pipeline(audio_in_mem)

for turn, _, speaker in diarization.itertracks(yield_label=True):
    print(f"start={turn.start:.1f}s stop={turn.end:.1f}s speaker_{speaker}")
```

**Comment by laphang** [comment]
@mflage I was able to run the 3.5 hr file by spinning up a g4dn.2xlarge instead (which has a 32GB RAM vs 16GB on the xlarge). But not a workaround in terms of making the code run more efficiently. 

The issue #1216 linked above looks interesting, but I haven't tried it out.
