### ISSUE TITLE
File contains data in an unknown format.

### ISSUE THREAD

**Issue by k3ybladewielder** [pyannote/pyannote-audio#1170]
Code:
```
from huggingface_hub import notebook_login, login
from pyannote.audio import Model, Inference
import torchaudio

token = '1234'
model = Model.from_pretrained("pyannote/segmentation", use_auth_token=True, token=token, duration=1)

AUDIO_FILE = '/dbfs/mnt/abc/audio.wav'

waveform, sample_rate = torchaudio.load(AUDIO_FILE)

audio_in_memory = {"waveform": waveform, "sample_rate": sample_rate}
output = inference(audio_in_memory)
output
```
I receive this error output when run this code above:
"_Error opening '/dbfs/mnt/abc/audio.wav': File contains data in an unknown format_"

I checked the audio file and its ok

**Comment by hbredin** [comment]
Closing as this is a [torchaudio](https://github.com/pytorch/audio) issue, not pyannote.audio.

**Comment by k3ybladewielder** [comment]
I also have the same issue with code below

```
from huggingface_hub import notebook_login, login
from pyannote.audio import Model, Inference

token = '123'
model = Model.from_pretrained("pyannote/segmentation", use_auth_token=True, token=token, duration=1)

AUDIO_FILE = '/dbfs/mnt/abc/audio.wav'

inference = Inference(model, step=1)
output = inference(AUDIO_FILE)
output

```
I follow [this tutorial](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/applying_a_model.ipynb)

**Comment by k3ybladewielder** [comment]
> Closing as this is a [torchaudio](https://github.com/pytorch/audio) issue, not pyannote.audio.

I also have the same issue with code below

```
from huggingface_hub import notebook_login, login
from pyannote.audio import Model, Inference

token = '123'
model = Model.from_pretrained("pyannote/segmentation", use_auth_token=True, token=token, duration=1)

AUDIO_FILE = '/dbfs/mnt/abc/audio.wav'

inference = Inference(model, step=1)
output = inference(AUDIO_FILE)
output

```
I follow [this tutorial](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/applying_a_model.ipynb)

**Comment by mthrok** [comment]
@k3ybladewielder If you can share the audio data, I can look into it.

**Comment by k3ybladewielder** [comment]
> @k3ybladewielder If you can share the audio data, I can look into it.

It's confidential
