### ISSUE TITLE
pyannote/speaker-diarization not available on HF

### ISSUE THREAD

**Issue by roberto-tedesco** [pyannote/pyannote-audio#1173]
The example code listed in https://huggingface.co/pyannote/speaker-diarization does not work, as the model "pyannote/speaker-diarization@2.1" is not found. In general, it seems that "pyannote/speaker-diarization" is not available.

**Comment by roberto-tedesco** [comment]
Note that, on the https://huggingface.co/pyannote/speaker-diarization web page, the following message appears: " This model could not be loaded by the inference API." Is that related to the error I face trying to run the example code?

**Comment by kaylC4** [comment]
Hi, I have the same error.
Here a way to reproduce it:
!pip install git+https://github.com/philschmid/pyannote-audio.git@hub0.10 --upgrade
!pip install -q speechbrain
!pip install librosa
!pip install soundfile

# Pre-Processing ------------------------------------------
import librosa
import soundfile as sf

# Pyannote ------------------------------------------------
from pyannote.audio import Audio
from IPython.display import Audio as IPythonAudio
from pyannote.database.util import load_rttm
from pyannote.core import Segment, notebook
from pyannote.audio import Pipeline
from pyannote.audio import Inference

# Prepare pipeline for diarization, audio object to cut wav and inference to create speaker embedding
pipeline   = Pipeline.from_pretrained('pyannote/speaker-diarization')

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
[/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_errors.py](https://localhost:8080/#) in hf_raise_for_status(response, endpoint_name)
    212     try:
--> 213         response.raise_for_status()
    214     except HTTPError as e:

4 frames
HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/pyannote/speaker-diarization/resolve/2.1/config.yaml

The above exception was the direct cause of the following exception:

RepositoryNotFoundError                   Traceback (most recent call last)
[/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_errors.py](https://localhost:8080/#) in hf_raise_for_status(response, endpoint_name)
    240                 + "\nIf the repo is private, make sure you are authenticated."
    241             )
--> 242             raise RepositoryNotFoundError(message, response) from e
    243 
    244         elif response.status_code == 400:

RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-638f1455-587fbca514fbeca06b1a3920)

Repository Not Found for url: https://huggingface.co/pyannote/speaker-diarization/resolve/2.1/config.yaml.
Please make sure you specified the correct `repo_id` and `repo_type`.
If the repo is private, make sure you are authenticated.

**Comment by kaylC4** [comment]
I try with:
1- Demand access to repository on HF
2- Open a specific auth token in HF, for both Diarization and then Segmentation

3- Try new code like:

access_token = MY TOKEN

and both:
pipeline   = Pipeline.from_pretrained('pyannote/speaker-diarization',use_auth_token=access_token)
or:
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization@2.1",use_auth_token=access_token)

It load a first model but then it gives another error:
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
[/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_errors.py](https://localhost:8080/#) in hf_raise_for_status(response, endpoint_name)
    212     try:
--> 213         response.raise_for_status()
    214     except HTTPError as e:

7 frames
[/usr/local/lib/python3.8/dist-packages/requests/models.py](https://localhost:8080/#) in raise_for_status(self)
    940         if http_error_msg:
--> 941             raise HTTPError(http_error_msg, response=self)
    942 

HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/pyannote/segmentation/resolve/2022.07/pytorch_model.bin

The above exception was the direct cause of the following exception:

RepositoryNotFoundError                   Traceback (most recent call last)
[<ipython-input-14-8f67d89c6ef9>](https://localhost:8080/#) in <module>
      5 
      6 #pipeline   = Pipeline.from_pretrained('pyannote/speaker-diarization',use_auth_token=access_token)
----> 7 pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization",use_auth_token=access_token)
      8 audio      = Audio(sample_rate=mySampleRate, mono=True)
      9 inference  = Inference("pyannote/embedding",window="whole",device="cuda")

[/usr/local/lib/python3.8/dist-packages/pyannote/audio/core/pipeline.py](https://localhost:8080/#) in from_pretrained(cls, checkpoint_path, hparams_file, use_auth_token, cache_dir)
     96             pipeline_name, default_module_name="pyannote.pipeline.blocks"
     97         )
---> 98         pipeline = Klass(**config["pipeline"].get("params", {}))
     99 
    100         # freeze  parameters

[/usr/local/lib/python3.8/dist-packages/pyannote/audio/pipelines/speaker_diarization.py](https://localhost:8080/#) in __init__(self, segmentation, segmentation_step, embedding, embedding_exclude_overlap, clustering, embedding_batch_size, segmentation_batch_size)
    114         seg_device, emb_device = get_devices(needs=2)
    115 
--> 116         model: Model = get_model(segmentation)
    117         model.to(seg_device)
    118 

[/usr/local/lib/python3.8/dist-packages/pyannote/audio/pipelines/utils/getter.py](https://localhost:8080/#) in get_model(model)
     66 
     67     elif isinstance(model, Text):
---> 68         model = Model.from_pretrained(model, strict=False)
     69 
     70     elif isinstance(model, Mapping):

[/usr/local/lib/python3.8/dist-packages/pyannote/audio/core/model.py](https://localhost:8080/#) in from_pretrained(cls, checkpoint, map_location, hparams_file, strict, use_auth_token, cache_dir, **kwargs)
    781                 model_id, filename=HF_PYTORCH_WEIGHTS_NAME, revision=revision
    782             )
--> 783             path_for_pl = cached_download(
    784                 url=url,
    785                 library_name="pyannote",

[/usr/local/lib/python3.8/dist-packages/huggingface_hub/file_download.py](https://localhost:8080/#) in cached_download(url, library_name, library_version, cache_dir, user_agent, force_download, force_filename, proxies, etag_timeout, resume_download, use_auth_token, local_files_only, legacy_cache_layout)
    619                 timeout=etag_timeout,
    620             )
--> 621             hf_raise_for_status(r)
    622             etag = r.headers.get("X-Linked-Etag") or r.headers.get("ETag")
    623             # We favor a custom header indicating the etag of the linked resource, and

[/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_errors.py](https://localhost:8080/#) in hf_raise_for_status(response, endpoint_name)
    240                 + "\nIf the repo is private, make sure you are authenticated."
    241             )
--> 242             raise RepositoryNotFoundError(message, response) from e
    243 
    244         elif response.status_code == 400:

RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-638f1962-318291c668e18de02a4ec018)

Repository Not Found for url: https://huggingface.co/pyannote/segmentation/resolve/2022.07/pytorch_model.bin.
Please make sure you specified the correct `repo_id` and `repo_type`.
If the repo is private, make sure you are authenticated.

**Comment by Cordo-van-Saviour** [comment]
I encountered the same bug. I get the same error when trying to run it from the UI and using cURL

<img width="732" alt="Screenshot 2022-12-09 at 13 55 15" src="https://user-images.githubusercontent.com/16446722/206707245-4fae2e13-98a5-46a1-bf73-ace59b1bb066.png">

<img width="565" alt="Screenshot 2022-12-09 at 13 56 57" src="https://user-images.githubusercontent.com/16446722/206707827-867c77a9-eddb-4136-afd7-17fc136a25b0.png">
