### ISSUE TITLE
How to parallelize the process across GPUs?

### ISSUE THREAD

**Issue by bakermanbrian** [pyannote/pyannote-audio#1176]
I am looking to add diarization along with transcription in a project I'm working on. I was able to break up the audio by silent breaks and get parallelization working for transcription. I am unclear how I would do the same for diarization. Is there any good way to do this?

**Comment by hbredin** [comment]
[This loop](https://github.com/pyannote/pyannote-audio/blob/cab76ecf47debe7feeed985c9c998993c1fb5cf4/pyannote/audio/pipelines/speaker_diarization.py#L340) is where most of the processing time is spent.

Distributing batches across GPUs might help.
I'd gladly consider a PR adding this features.

Related issue and discussion: #1164 #1155
