### ISSUE TITLE
No matching distribution found for chocolate>=0.6

### ISSUE THREAD

**Issue by dhillonr** [pyannote/pyannote-audio#118]
While installing pyannote.audio :
Collecting chocolate>=0.6 (from pyannote.audio)
Could not find a version that satisfies the requirement chocolate>=0.6 (from pyannote.audio) (from versions: )
No matching distribution found for chocolate>=0.6 (from pyannote.audio)

Please help !

**Comment by lixikun** [comment]
hi, Dear Friend, is it solved?

**Comment by hbredin** [comment]
`chocolate` requirement has been removed in `develop` branch (which will become `pyannote-audio`2.0).

Until it is released, please install `pyannote-audio` from the `develop` branch:

```bash
git clone https://github.com/pyannote/pyannote-audio.git
cd pyannote-audio
git checkout develop
pip install -e .
```
