### ISSUE TITLE
 from pyannote.audio.signal import SpeechSegmentation

### ISSUE THREAD

**Issue by ItsMe-TJ** [pyannote/pyannote-audio#1186]
I'm trying to run a script, but it says:

"    from pyannote.audio.signal import SpeechSegmentation
ModuleNotFoundError: No module named 'pyannote.audio.signal'"

doing pip freeze I can see pyannote.audio, and all the other modules except pyannote.audio.signal, so It obviously Isn't installed, but the thing is I can't install it. Feels like I've tried everything.

Help would be appreciated!

Thanks

**Comment by hbredin** [comment]
There is no such thing as `pyannote.audio.signal.SpeechSegmentation` in current version. Closing.
