### ISSUE TITLE
speaker diarization accuracy issue

### ISSUE THREAD

**Issue by wahab4321** [pyannote/pyannote-audio#1192]
I am using pyannotate/speaker-diarization and writting the result of speakers to RTTM file but accuracy is very low. In the audio two speakers are talking but in my cause after downloading RTTM file only one speaker is showing. Please support.

Thanks

Regards,
Wahab Khan

**Comment by hbredin** [comment]
See the [FAQ](https://github.com/pyannote/pyannote-audio/blob/develop/FAQ.md#pretrained-pipelines-do-not-produce-good-results-on-my-data-what-can-i-do).
