### ISSUE TITLE
(Memory Leak?) Some memory cache is not deleted

### ISSUE THREAD

**Issue by Jeronymous** [pyannote/pyannote-audio#1196]
I noticed that, when running diarization, there is some additional memory use (up to ~500M) even if the diarization model/pipeline is cleared.

This can be reproduced with the following program:
```
from pyannote.audio import Pipeline
import os
import psutil
import math
import soundfile as sf
import tempfile

def sinusoid(freq, duration, sample_rate = 16000):
    return [math.sin(2.0*math.pi*float(freq)*(float(i)/float(sample_rate))) for i in range(int(duration * sample_rate))]

def temp_audio_file(duration):
    data = sinusoid(100, duration/4) + sinusoid(200, duration/4) + sinusoid(400, duration/4) + sinusoid(800, duration/4)
    f = tempfile.mktemp(suffix=".wav")
    sf.write(f, data, 16000)
    return f

def test_speaker_diarization(num_sec, token = "hf_XXX"): # <- USE YOUR HUGGINGFACE TOKEN HERE
    pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization@2.1", use_auth_token = token)
    audio_file = temp_audio_file(num_sec)
    diarization = pipeline(audio_file, num_speakers = 2)
    os.remove(audio_file)

def print_memory_usage(name = ""):
    mm = psutil.Process().memory_info().rss / (1024 * 1024)
    print(f"Memory usage {name}: {mm} MB")

print_memory_usage(0)
for duration in [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]:
    test_speaker_diarization(duration)
    print_memory_usage(duration)
```
(note: the sinusoid stuff is a workaround to avoid having [issue #1166](https://github.com/pyannote/pyannote-audio/issues/1166))

This prints the following memory usages:
```
Memory usage 0: 835.50390625 MB
Memory usage 1: 953.80078125 MB
Memory usage 2: 991.98828125 MB
Memory usage 4: 1023.36328125 MB
Memory usage 8: 1125.31640625 MB
Memory usage 16: 1270.25390625 MB
Memory usage 32: 1339.2890625 MB
Memory usage 64: 1339.2578125 MB
Memory usage 128: 1323.26171875 MB
Memory usage 256: 1324.6171875 MB
Memory usage 512: 1299.50390625 MB
```
Is there some cache that can be cleared to avoid this?

**Comment by hbredin** [comment]
Memory leaks have been reported before but looking at this is definitely not at the top of my TODO list right now. 

That being said, if you dive deeper into this (e.g. with a memory profiler) and pin point where this leak comes from, it would probably make it bubble up my TODO list.

**Comment by Jeronymous** [comment]
For sure I would be happy to contribute instead of letting the hard work to you.

For now I narrowed down that the main part of the leak comes from the embeddings computation in class `SpeechBrainPretrainedSpeakerEmbedding`:
```
      embeddings = (
            self.classifier_.encode_batch(signals, wav_lens=wav_lens)
            .squeeze(dim=1)
            .cpu()
            .numpy()
        )
```
and more precisely from the forward of class `ECAPA_TDNN` in SpeechBrain.
But I still don't understand the real source of the problem, neither see any workaround to that.
It might come from torch, but I see very few discussions about RAM management and problems in torch (most of memory issues are about CUDA). Maybe these ones are relevant, but remained unanswered:
- https://github.com/pytorch/pytorch/issues/68114
- https://github.com/pytorch/pytorch/issues/83914

**Comment by gmat** [comment]
To free up gpu's ram test this
```python
import torch
torch.cuda.empty_cache()
```
maybe it could be called by pyannote at the end of a diarization

**Comment by Barabazs** [comment]
> To free up gpu's ram test this
> 
> ```python
> import torch
> torch.cuda.empty_cache()
> ```
> 
> maybe it could be called by pyannote at the end of a diarization

The issue is for CPU RAM not GPU.
