### ISSUE TITLE
Is any of my data uploaded to cloud servers when I use these models?

### ISSUE THREAD

**Issue by maxwellbind** [pyannote/pyannote-audio#1197]
Hi there,

I am looking to use pyannote-audio for a task at work, and it looks fantastic. 

The audio files I want to transcribe are sensitive, so I wanted to make extra sure that, while using this library, none of them will be put onto any servers besides ones we own. Is that the case - that all of the training, fine-tuning, and prediction, are done on my own computers? i.e., there is no cloud compute involved?

I saw the FAQ section for using the model in a non-gated way, but from what I saw, that section doesn't address my question directly. (Forgive me if it does and I missed it).

Thanks!!

**Comment by hadware** [comment]
If you use Pyannote-audio locally - that is: on your own machine, with your own GPUs -  there is absolutely no reason for any data to leave your computer. Everything pyannote-audio will be doing will be on your computer.
