### ISSUE TITLE
Is the pyannote 2.0 speaker-diarization model available for offline use?

### ISSUE THREAD

**Issue by anuragkumar95** [pyannote/pyannote-audio#1199]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by simonManydata** [comment]
The model is cached inside `CACHE_DIR` after the first download (`~/.cache/torch/pyannote`).

You can control the caching directory by modifying the env variable `PYANNOTE_CACHE`.

**Comment by Alejandroid17** [comment]
How can I use the cache files offline? ( In "production" I dont have internet connection).

Reading the method `.from_pretrained(...)` docs:

```python
def from_pretrained(...) -> "Pipeline":
"""Load pretrained pipeline

Parameters
----------
checkpoint_path : Path or str
    Path to pipeline checkpoint, or a remote URL,
    or a pipeline identifier from the huggingface.co model hub.
hparams_file: Path or str, optional
use_auth_token : str, optional
    When loading a private huggingface.co pipeline, set `use_auth_token`
    to True or to a string containing your hugginface.co authentication
    token that can be obtained by running `huggingface-cli login`
cache_dir: Path or str, optional
    Path to model cache directory. Defauorch/pyannote" when unset.
"""
```

Analysing the cached files I have:
```
.../blobs/f9e1fc93c4458ec26993785b4b43c7e309bad03f
.../refs/2.1
.../snapshots/25bcc7e3631933a02af5ee39379797d704aee3f8
```

What would the checkpoint (`checkpoint_path`) be?

Thanks for everything, I'm new to these things :)

**Comment by hbredin** [comment]
Other option: see [FAQ](https://github.com/pyannote/pyannote-audio/blob/develop/FAQ.md#can-i-use-gated-models-and-pipelines-offline)
