### ISSUE TITLE
How to select threshold and min_cluster_size values in clustering after I finetuned embedding model ?

### ISSUE THREAD

**Issue by dungnguyen98** [pyannote/pyannote-audio#1211]
Hi. Thanks for sharing great repository.
I have a question.
I finetuned embedding model in speaker diarization pipeline. After that, I don't know how to set threshold and min_cluster_size params in config.yaml file.
Can you give me some advices ?

**Comment by hbredin** [comment]
[This tutorial](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/adapting_pretrained_pipeline.ipynb) should help you do that.
