### ISSUE TITLE
cannot pickle '_thread.RLock' object

### ISSUE THREAD

**Issue by acampbellblack** [pyannote/pyannote-audio#1223]
Following the adapting_pretrained_pipeline.ipynb tutorial.

Running on Windows 10, using Pytorch with CUDA 11.6.

TypeError                                 Traceback (most recent call last)
Cell In[7], line 46
     41 from pytorch_lightning import Trainer
     42 trainer = Trainer(accelerator="gpu", 
     43                   callbacks=callbacks, 
     44                   max_epochs=20,
     45                   gradient_clip_val=0.5)
---> 46 trainer.fit(model)

File e:\pyannote-audio\venv\lib\site-packages\pytorch_lightning\trainer\trainer.py:770, in Trainer.fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    751 r"""
    752 Runs the full optimization routine.
    753 
   (...)
    767     datamodule: An instance of :class:`~pytorch_lightning.core.datamodule.LightningDataModule`.
    768 """
    769 self.strategy.model = model
--> 770 self._call_and_handle_interrupt(
    771     self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    772 )

File e:\pyannote-audio\venv\lib\site-packages\pytorch_lightning\trainer\trainer.py:723, in Trainer._call_and_handle_interrupt(self, trainer_fn, *args, **kwargs)
    721         return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
    722     else:
...
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)

TypeError: cannot pickle '_thread.RLock' object

**Comment by acampbellblack** [comment]
Solved - on Windows in
`task = Segmentation(protocol, 
                    duration=model.specifications.duration, 
                    max_num_speakers=len(model.specifications.classes), 
                    batch_size=32,
                    num_workers=0, # set this to zero on Windows or bug will occur later (ACB)
                    loss="bce", 
                    vad_loss="bce")`
num_workers must be 0.
This is a problem with pytorch.

**Comment by wzyloveywh** [comment]
Hello, I also encountered the same problem in the voice_activity_detection.ipynb tutorial. Could you please describe the solution process in detail?
