### ISSUE TITLE
Speaker diarization : error when no active speakers in files ?

### ISSUE THREAD

**Issue by FrenchKrab** [pyannote/pyannote-audio#1237]
I haven't investigated this much yet @hbredin , but given this code:

```python
import torch
from pyannote.database import FileFinder, registry

registry.load_database("path/to/aishell4/database_tmp.yml")

# initialize 'only_words' experimental protocol
aishell = registry.get_protocol("AISHELL4.SpeakerDiarization.TestTest", preprocessors={"audio": FileFinder()})

from pyannote.audio import Model, Inference, Pipeline
from pyannote.audio.core.io import Audio
from pyannote.audio.tasks import Segmentation
import pytorch_lightning as pl

task = Segmentation(aishell, max_speakers_per_chunk=3, max_speakers_per_frame=3, duration=5.0)
model = Model.from_pretrained("pyannote/segmentation", use_auth_token="my_token")
model.task = task
task.setup()

trainer = pl.Trainer(max_epochs=2, max_steps=1)
model.setup("fit")
trainer.validate(model)  # error on this line
```

I get an error (see : [message.txt](https://github.com/pyannote/pyannote-audio/files/10481820/message.txt) for full logs).

The test was made with a development dataset containing only one file, which had it's UEM describe a small time region with no active speaker (as described in the RTTM).
As soon as another UEM "window" containing speech is added, or if the initial silent window is extended to include speech, the validation proceeds correctly.

**Comment by hbredin** [comment]
Working on this... Does that also happen when `max_speakers_per_frame` is None ?

**Comment by FrenchKrab** [comment]
Yes
