### ISSUE TITLE
Metrics on audio files

### ISSUE THREAD

**Issue by Uncertain-Quark** [pyannote/pyannote-audio#1240]
How do we compute metrics on audio files on locally trained models or any models in general? For instance, I am trying to compute DetectionPrecisionRecallFMeasure for overlap speech detection task.

However, the output of the model is a sliding window feature and I am not sure how to convert it to pyannote Annotation in order to compute the metric. Any help would be great

**Comment by hbredin** [comment]
You'd have to wrap it into an overlapped speech detection pipeline: 
https://huggingface.co/pyannote/overlapped-speech-detection.

**Comment by Uncertain-Quark** [comment]
Thank you
