### ISSUE TITLE
WARNING: Newbie to pyannote! (How to change segmentation duration)

### ISSUE THREAD

**Issue by Dec1lent** [pyannote/pyannote-audio#1243]
I'm looking for a way to more precisely detect quick speech between 2 speakers in a podcast. 

The problem I have is that some of the speech is rather short eg. Yes, no and so on. It seems like the default segmentation time is 250 ms if I remember correct. I have now just slowed the audio file down to 0,25 speed and it seems to detect all segments now. But Its also insecure about who is speaking at what time. I dont have any custom trained models or pipelines, I use the default as I dont have a single understanding on how to (Yes I have read a bit of the documentation) [this](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/adapting_pretrained_pipeline.ipynb) 

Another thing that happens when slowing the audio file is that some of the segments seems to be  come multiple minutes long and strech over multiple other segments.

**Comment by BrightXiaoHan** [comment]
Hi, have you solved this?
