### ISSUE TITLE
Releasing ground truth rttm files for datasets

### ISSUE THREAD

**Issue by Spectra456** [pyannote/pyannote-audio#1249]
Hi. Can you please provide ground truth rttm files for datasets that you use for tests? I saw you have rttm output files from your pipeline, but it's impossible to calculate metrics for them without ground truth files. Thanks!

**Comment by hbredin** [comment]
Unfortunately, I am not allowed to share those as they are part of their respective datasets (with their own license agreement). 

Out of curiosity, may I ask why you would like to compute metrics without having access to the dataset yourself?

**Comment by Spectra456** [comment]
Oh, what I meant was to publishing free datasets rttms files, like AMI, AISHELL …

**Comment by hbredin** [comment]
[This repo](https://github.com/FrenchKrab/datasets-pyannote) is a first step in that direction.
