### ISSUE TITLE
Same speaker id in different audio files. (speaker-diarization)

### ISSUE THREAD

**Issue by AmphibianDev** [pyannote/pyannote-audio#1254]
**Is your feature request related to a problem? Please describe.**
I what to have the same speaker id for the same person in different files.

**Describe the solution you'd like**
A easy way to give the pipeline the voices that I want to search for: voice0 (SPEAKER_00), voice1 (SPEAKER_01)

**Additional context**
I have multiple files that I want to use with the `pyannote/speaker-diarization` pipeline
But I want to have the same id for the SPEAKERs which are common between the files. (in the .rttm) 
Or at least for 2 SPEAKERs that I am looking for.

I'm sorry if this can already be done and I don't know how. And if so, can anyone point me in the right direction?

This is my code so far:
```
folder_path = 'myFolder'
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization", use_auth_token="...")

for filename in os.listdir(folder_path):
    file_path = os.path.join(folder_path, filename)
    file, extension = os.path.splitext(file_path)

    if os.path.isfile(file_path) and extension == ".wav":
        diarization = pipeline(file_path)

        with open(file + ".rttm", "w") as rttm:
            diarization.write_rttm(rttm)
```

**Comment by k3ybladewielder** [comment]
Since the assign of label actually is random, you can try to append the audio files and execute the pipeline in one unique audio file

**Comment by AmphibianDev** [comment]
Yes, that's what I did, I added the sound of the voices I want to search for at the beginning of the audio file, so I know the labels for them are always at the beginning.
