### ISSUE TITLE
Unable to install pyannote.audio due to torch=0.4 not found

### ISSUE THREAD

**Issue by pkb01** [pyannote/pyannote-audio#126]
I am unable to install "pyannote.audio". Since, it is looking for torch==0.4(torch version 0.4) while doing "pip install pyannote.audio" but torch==0.4 is not available rather torch==0.4.1 is available.

Please help me with this. I guess most of us would have encountered this problem.

Thanks !!

**Comment by hbredin** [comment]
Next version will rely on pytorch 1.0. Closing for now.
