### ISSUE TITLE
Segmentation Fault (Core Dumped)

### ISSUE THREAD

**Issue by saadtariq-ds** [pyannote/pyannote-audio#1281]
I have imported from pyannote.audio.models.segmentation import PyanNet and when it is executed my code fails and it returns Segmentation Fault (Core Dumped). What could be the possible reason for this error and how it can be correct

**Comment by fabiocat93** [comment]
same for me if "transformers" is in the same environment

**Comment by fabiocat93** [comment]
I will follow up on this. I have `dlib` properly installed in the environment, but still, get the segmentation fault message. I am saying this because i saw that in another thread dlib was pointed to be the reason of this error

**Comment by fablau** [comment]
I can confirm having the same issue, specifically after installing Transformers version 4.27.1. Any ideas about it?

**Comment by fablau** [comment]
Additionally, I get this warning at the start, right after the library is loaded:

```
/usr/local/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
```

Never happened before I installed Transformers.

**Comment by ashu5644** [comment]
@saadtariq-ds, @fablau, @fabiocat93, I am also facing same issue "Segmentation Fault (Core Dumped)" while executing `from pyannote.audio import Pipeline` code. Did you find any solutions ?

**Comment by fabiocat93** [comment]
With the latest version of pyannote-audio doesn't happen to me anymore

**Comment by fablau** [comment]
I switched to demucs instead ;)
