### ISSUE TITLE
How to get the index of array from diarization, thank you

### ISSUE THREAD

**Issue by junyongyou** [pyannote/pyannote-audio#1286]
After diarization, we get the Annotation with the time of segmentation. I am wondering if we can get the indices of each segment in the audio array? Thanks a lot.

**Comment by junyongyou** [comment]
Of course I can get the indices from the time and sampling rate, but I am just wondering if the indices of segments are already contained in the diarization result, but I cannot find. Thank you.

**Comment by hbredin** [comment]
No, they are not provided by the pipeline. 
You have to compute the indices yourself.
