### ISSUE TITLE
How to fintune on AliMeeting dataset? 

### ISSUE THREAD

**Issue by SrWYG** [pyannote/pyannote-audio#1288]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/9276709/225836235-bdc3a3af-0928-4cdf-921f-dcf3521702bf.png)
The report of pyannote 2.1 show your finetuned result on AliMeeting dataset .
But AliMeeting dataset seems only provide the TextGrid file which only annotes one speaker for each audio file(wav).
So, i want to know how you finetune the segment model on AliMeeting. 
Thank you. ^^

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by hbredin** [comment]
I have downloaded recording and supervision sets provided in [`lhotse`](https://lhotse.readthedocs.io) as `jsonl.gz` files.

Then, I have run [this script](https://gist.github.com/hbredin/a8cfef6655a784afb1913f0f3f2759a5) to convert them to RTTMs and UEMs for use with [`pyannote.database`](https://github.com/pyannote/pyannote-database).

Would you be willing to contribute a dataset preparation script in [`datasets-pyannote`](https://github.com/FrenchKrab/datasets-pyannote) maintained by @FrenchKrab?

**Comment by pengzhendong** [comment]
AliMeeting contains “far” and “near” microphones with 8 channels. Which one did you process? Why did you assert `channel == 0`? @hbredin
