### ISSUE TITLE
Inferencing on CPU instead of GPU: why?

### ISSUE THREAD

**Issue by fablau** [pyannote/pyannote-audio#1289]
For some reason, pyannote-audio is using the CPU instead of the GPU, and I have no idea why.

Is there a way to tell pyannote to use the GPU instead?

Thanks in advance.

**Comment by fablau** [comment]
My apologies for the lack of details, I am working on diarization, and here is my current code:

```
from pyannote.audio import Pipeline

fileOutWav = sys.argv[1] 
spkrsNo = int(sys.argv[2])
fileDiary = sys.argv[3]

pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization",
											use_auth_token="xxxxxxxxxxxxxx")

# 4. apply pretrained pipeline
diarization = pipeline(fileOutWav, num_speakers=spkrsNo)

# 5. print the result

with open(fileDiary, mode='w') as file_object:
	for turn, _, speaker in diarization.itertracks(yield_label=True):
		print(f"start={turn.start:.2f}s stop={turn.end:.2f}s speaker_{speaker}", file=file_object)
```

The above script is called as a subprocess from another script.

Please, let me know if you need any further details.

**Comment by fablau** [comment]
Ok, it looks like I fixed the problem by applying an "apt update" and "apt upgrade." No idea why, but that fixed the problem. Now pyannote is back using the GPU ;)

**Comment by fablau** [comment]
Yes! This time it was perfect! Thank you so much! I appreciated your prompt fix.

Keep it up!

**Comment by Majdoddin** [comment]
seems your problem is related to #1306

**Comment by fablau** [comment]
Thank you @Majdoddin but I am on Linux with a CUDA GPU, not on Mac.

**Comment by Majdoddin** [comment]
I got that problem on Colab (linux), and I could resolve it by the [workaround](https://github.com/pyannote/pyannote-audio/issues/1306#issuecomment-1495590187) there, so it is not specific to Mac.

**Comment by fablau** [comment]
I see now, thank you!

**Comment by paulgb** [comment]
The workaround did not work for me, but this did:

```python
pipeline = pipeline.to(0)
```

0 refers to the device in torch's list of devices, which you can list like this:

```python
import torch
for i in range(torch.cuda.device_count()):
    print(f"{i}: {torch.cuda.get_device_name(i)}")
```

**Comment by fablau** [comment]
Awesome, thank you!

**Comment by GreatDarrenSun** [comment]
> It works for me
