### ISSUE TITLE
Conda package for pyannote-audio

### ISSUE THREAD

**Issue by FriederikeBrezing** [pyannote/pyannote-audio#1308]
Are there any plans to provide pyannote-audio as a conda package? 

It would greatly simplify our dependency handling.

**Comment by hbredin** [comment]
Nope. No plan for a `conda` package. Sorry.

**Comment by hbredin** [comment]
That being said, if pyannote.audio (a **free** open-source project) is critical to your business, you (your company) might consider sponsoring its development... Feel free to contact me via email if interested.

**Comment by FriederikeBrezing** [comment]
Thanks for the quick reply! We might get back to you on that at some point but not in the immediate future.
