### ISSUE TITLE
Is that possible to convert the model to ONNX then use it in C++

### ISSUE THREAD

**Issue by leohuang2013** [pyannote/pyannote-audio#1322]
Is that possible to convert the model to ONNX then use it in C++ for speaker diarization? Thanks.

**Comment by pengzhendong** [comment]
https://github.com/pengzhendong/pyannote-audio

**Comment by kfsky** [comment]
@pengzhendong 

I am looking to implement the speaker-diarization of pyannote with ONNX. I've been referring to this link: https://github.com/pengzhendong/pyannote-onnx. However, the repository linked doesn't seem to have the speaker-diarization output implemented.

I want to make the necessary adjustments myself, but pyannote's speaker-diarization operates by loading multiple models. Considering this, I'm unsure how to proceed with the modifications. I would appreciate it if you could provide me with advice or instructions on the specific steps or methods to follow.

**Comment by pengzhendong** [comment]
@kfsky
Could you provide the link of `but pyannote's speaker-diarization operates by loading multiple models`?

**Comment by kfsky** [comment]
@pengzhendong 
I have been referring to this notebook: https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/applying_a_pipeline.ipynb. When executing the following section of the notebook, multiple models get downloaded:

```python
Copy code
from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization@develop", use_auth_token=True)
```
Therefore, I believe these multiple models are necessary for the conversion to ONNX. Is my understanding incorrect?

**Comment by pengzhendong** [comment]
@kfsky 
There are two models:
1. https://huggingface.co/pyannote/segmentation
2. https://huggingface.co/speechbrain/spkrec-ecapa-voxceleb

The first one is used to segment the audio (pengzhendong/pyannote-onnx does the same thing):
![image](https://github.com/pyannote/pyannote-audio/assets/10704539/26251a8e-0907-4ae8-8e5a-fdb246326de0)
The second one is used to get the embeddings of the segments.

**Comment by kfsky** [comment]
@pengzhendong 
> The second one is used to get the embeddings of the segments.

Could you possibly share some ideas on the steps to follow when incorporating the second model into pyannote-onnx?

**Comment by pengzhendong** [comment]
@kfsky Please refer this file: https://github.com/pyannote/pyannote-audio/blob/develop/pyannote/audio/pipelines/speaker_diarization.py

**Comment by mark95** [comment]
@kfsky Did you manage to export the whole diarization pipeline to ONNX?

**Comment by thewh1teagle** [comment]
I'm also looking to convert pyannote model to onnx format and then use it from Rust with [ort](https://github.com/pykeio/ort)
Did anyone manged to use it in c++?
