### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 80000 but got size 79659 for tensor number 30 in the list

### ISSUE THREAD

**Issue by Pkoiralap** [pyannote/pyannote-audio#1324]
I was experiencing this issue and was able to solve it using guard rails around the waveform creation process. However, I believe there should be a better way to do this and that's why I am not creating a PR with the fix. If you think this fix works, I can submit a PR. 

So in the [audio/pipelines/speaker_diarization.py](https://github.com/pyannote/pyannote-audio/blob/develop/pyannote/audio/pipelines/speaker_diarization.py#L319-L325) file. i.e. this bit here:
```
# chunk: Segment(t, t + duration)
# masks: (num_frames, local_num_speakers) np.ndarray
waveform, _ = self._audio.crop(
    file,
    chunk,
    duration=duration,
    mode="pad",
)
# waveform: (1, num_samples) torch.Tensor
...
```

creates a tensor of a different size than what is expected. The simple fix I am using for now is:
```
# chunk: Segment(t, t + duration)
# masks: (num_frames, local_num_speakers) np.ndarray
waveform, _ = self._audio.crop(
    file,
    chunk,
    duration=duration,
    mode="pad",
)
# waveform: (1, num_samples) torch.Tensor
if waveform.shape[1] < num_samples:
    pad_num = int(num_samples - waveform.shape[1])
    waveform = torch.nn.functional.pad(waveform, (0, pad_num), "constant", 0)
```

This is hacky, but it works for me. Also because I didn't have a lot of time reading through the code, I am not sure if this is the right fix for the problem.  As I said earlier, depending on whether this is a 'good' fix, I can create a PR accordingly.

Thanks

**Comment by hbredin** [comment]
Would you mind narrowing down when this problem occurs?

This is most likely a bug in the implementation of the `mode="pad"` option which is already supposed to handle this corner case...

**Comment by nickyreinert** [comment]
As this error still occurs, an FWIWF: For me it sounded like a problem with the available memory, so a quick fix is splitting the incoming audio into parts. This fixed the problem for me, example:
```
sound = AudioSegment.from_mp3("input.mp3")
halfway_point = len(sound) / 2 
part = sound[:halfway_point]
part.export("part_1.mp3", format="mp3")
```
