### ISSUE TITLE
Usage on simple audio (not in db.yml)

### ISSUE THREAD

**Issue by pikaliov** [pyannote/pyannote-audio#133]
Good evening.
I trained SAD, SpeakerEmbedding and SpeakerChange using AMI dataset.
I wrote code to load model, weights. But i don't know how to use it with wild data, not standart db.
So how i can use pretrained models on numpy-arrays from own wav-files? Should i create everytime own db?Or it's not impossible?

**Comment by hbredin** [comment]
I am currently working on an easy way to do that. This will be part of next release.
I cannot promise any ETA, though. 

For now, the easiest way is indeed to create a new DB for each new collection.
