### ISSUE TITLE
Difficulty accessing pyannote segmentation, embedding, and speaker diarization.

### ISSUE THREAD

**Issue by KevinHoffman1** [pyannote/pyannote-audio#1349]
I have been having difficulty using Hugging Face. We suspect it is due to being unable to accept permission on the hugging face websites of segmentation, embedding, and speaker diarization. We have done everything we can do to try to accept permission on each respective website and use the correct tokens. I have ensured pop-ups are not blocked and no other cause lies in the way, and yet it still seems permission is not being accepted. Thus, this error comes up when trying to instantiate the code. 
![Screenshot (183)](https://user-images.githubusercontent.com/122998754/234698208-35d7169b-2e56-4c91-aebd-de83661dadcb.png)

**Comment by jeremy110** [comment]
You seem to have an extra blank in use_auth_token??
