### ISSUE TITLE
Waveform new assertion error

### ISSUE THREAD

**Issue by MinhNguyen99AI** [pyannote/pyannote-audio#1350]
Hi, I have this piece of code that used to run smoothly, but for some reasons, it no longer works. Attached is the screenshot of the code. The code below also used in this video on youtube: https://www.youtube.com/watch?v=MVW746z8y_I&ab_channel=1littlecoder
![image](https://user-images.githubusercontent.com/48023706/234796398-c996b1fc-92a0-4e91-ab24-403c919f5151.png)
Do you guys have any suggestion?

**Comment by FrenchKrab** [comment]
If you're using the develop branch, check out commit 2623cf19807db19c7234880ee173739293e28254
The assert probably doesn't pass because the Audio is no longer automatically downmixed. Relevant part of the changelog :
```
BREAKING(io): multi-channel audio is no longer downmixed to mono by default. You should update how pyannote.audio.core.io.Audio is instantiated:

    replace Audio() by Audio(mono="downmix");
    replace Audio(mono=True) by Audio(mono="downmix");
    replace Audio(mono=False) by Audio().
```

**Comment by agonzalezreyes** [comment]
Change the line `audio = Audio()` to `audio = Audio(mono="downmix")` and it should work as expected.
