### ISSUE TITLE
Pyannote not detecting GPU and running only on CPU

### ISSUE THREAD

**Issue by Oheed911** [pyannote/pyannote-audio#1354]
I have Two gpu's in my remote server, but the problem is when i load the pyannote model `pipeline = Pipeline.from_pretrained(
        'pyannote/speaker-diarization', use_auth_token='my_token here')`  and then ` diarization = pipeline(file_path, num_speakers=2)
    diarizationStr = str(diarization).split("\n")` it does not run on GPU, it runs on CPU. I am also running Nemo diarization in the same code and it runs fine on the GPU, what could be the possible issue with this.

**Comment by joazoa** [comment]
I had the same issue with dev, setting the device manually seems to solve the issue.

**Comment by Oheed911** [comment]
yes, thank you. Setting it manually fixed the issue.
`pipeline=pipiline.to(0)` fixed the issue for me. Does any one why it is not selecting the gpu by itself?

**Comment by uselessai** [comment]
If you're having trouble running the model on your GPU, the issue could be related to your installation of PyTorch and CUDA. Here's a simple test you can run to help diagnose the issue:

Open your PyTorch script in a text editor.

Paste the following code snippet at the top of your script:

device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

Save your changes and run your script.

If your script prints "cuda" to the console, it means that PyTorch is able to find and use your GPU. However, if it prints "cpu", it means that PyTorch is unable to use your GPU and is defaulting to using your CPU instead.

If you're seeing "cpu" printed to the console, your PyTorch and CUDA installation may not be set up correctly. You should check that you have installed the correct versions of PyTorch and CUDA that are compatible with your GPU. You may also need to configure your system's environment variables to ensure that PyTorch is able to find and use CUDA.

**Comment by sorgfresser** [comment]
@uselessai thanks for the remark, but it is certainly not caused by that. While `"cuda" if torch.cuda.is_available() else "cpu"` returns `"cuda"`, `pyannote` will still use `CPU` for some reason. Still, it's a good way to find out whether it is caused by `pytorch` or `pyannote`.

**Comment by mllife** [comment]
I checked the pipeline code and it doesn't have code to select CUDA/GPU without config file, that is why its not working automatically

**Comment by mllife** [comment]
> pipeline=pipiline.to(0)

can you explain more, or provide a code snippet for example?

**Comment by Oheed911** [comment]
` pipeline = Pipeline.from_pretrained(
        'pyannote/speaker-diarization', use_auth_token='your_token_here')
    pipeline = pipeline.to(0)`

**Comment by bakermanbrian** [comment]
Running into this issue. pipeline.to(0) did not work for me, unfortunately.

**Comment by Oheed911** [comment]
can you share your code here so I can take a look into it, also Is you pytorch configured?

**Comment by bakermanbrian** [comment]
Thanks so much! Here's the simplified workflow of what I've been running that still is able to repro the issue:
https://github.com/bakermanbrian/gcpwhisppyan

I do have pytorch installed and it should be detecting, although happy to try any additional suggestions. 

Quick note: I have tried to make this work with the recommended `pip install -qq https://github.com/pyannote/pyannote-audio/archive/refs/heads/develop.zip` and did the pipeline.to(0), but I ran into the exact same issue.

**Comment by ironninja33** [comment]
When I use `pipeline = pipeline.to(0)`, I get the following error:

```
File ~/anaconda3/envs/audio_processing/lib/python3.10/site-packages/pyannote/audio/utils/reproducibility.py:69, in fix_reproducibility(device)
     68 def fix_reproducibility(device: torch.device):
---> 69     if (device.type == "cuda") and (
     70         torch.backends.cuda.matmul.allow_tf32 or torch.backends.cudnn.allow_tf32
     71     ):
     72         torch.backends.cuda.matmul.allow_tf32 = False
     73         torch.backends.cudnn.allow_tf32 = False

AttributeError: 'int' object has no attribute 'type'
```

Looks like the `0` passed to pipeline.to() is looking for an object which has an attribute named `type`. I installed the same way as @bakermanbrian. Also, `torch.cuda.is_available()` returns `True` for me.

**Comment by antoine-briand** [comment]
> Hello,
> 
> Same issue here. I'm using a Tesla T4 GPU. When running the test, torch sees the cuda GPU.
> 
> ```python
> import torch
> device = "cuda" if torch.cuda.is_available() else "cpu"
> print(device)
> cuda
> ```
> 
> But then when I try to run the Pipeline using :
> 
> ```python
>  pipeline = Pipeline.from_pretrained( 'pyannote/speaker-diarization', use_auth_token='your_token_here') 
>  pipeline = pipeline.to(0)
> ```
> 
> I get the following error :
> 
> ```python
> Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/home/ec2-user/anaconda3/envs/whisper/lib/python3.9/site-packages/pyannote/audio/core/pipeline.py", line 297, in __call__
>    fix_reproducibility(getattr(self, "device", torch.device("cpu")))
>  File "/home/ec2-user/anaconda3/envs/whisper/lib/python3.9/site-packages/pyannote/audio/utils/reproducibility.py", line 69, in fix_reproducibility
>    if (device.type == "cuda") and (
> AttributeError: 'int' object has no attribute 'type'
> ```
> 
> nvidia-smi output says :
> 
> ```
> (whisper) [ec2-user@ip-172-31-40-147 pyannote-whisper]$ nvidia-smi
> Thu Jun  1 13:11:30 2023
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
> | N/A   46C    P0    27W /  70W |   6024MiB / 15360MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |    0   N/A  N/A     69429      C   python                           6020MiB |
> +-----------------------------------------------------------------------------
> ```
> 
> I see there is a request for Cuda 11.8 support, is it related ? Should we downgrade ?
> 
> OpenAi Whisper is working fine with this GPU setup.

Ok ... solution was simple, I just did the following :

```python
import torch
 pipeline = pipeline.to(torch.device('cuda:0'))
 ```
 
 Now my GPU is working 
 
 ```
 Every 2.0s: gpustat                                                                                                                                                             ip-XXXeu-west-3.compute.internal: Thu Jun  1 13:55:19 2023

ip-XXXXX.eu-west-3.compute.internal  Thu Jun  1 13:55:19 2023  525.105.17
[0] Tesla T4 | 62°C,  **59 %** |  2451 / 15360 MB | ec2-user(2446M)
```

**Comment by kenenbek** [comment]
The problem still exists in version 4.0.1
