### ISSUE TITLE
How to run Speaker Diarization on GPU rather than CPU

### ISSUE THREAD

**Issue by woshizhishixuebao** [pyannote/pyannote-audio#1363]
When I was running the demo,it cant run on GPU correctly. I try to use *pipeline = pipeline.to(devices)*,but it raise *AttributeError(msg)   AttributeError: 'VoiceActivityDetection' object has no attribute 'to'*

**Comment by mllife** [comment]
try: pipeline = pipeline.to(torch.device("cuda"))

**Comment by pourmand1376** [comment]
> try: pipeline = pipeline.to(torch.device("cuda"))

AttributeError: 'SpeakerDiarization' object has no attribute 'to'
