### ISSUE TITLE
How can I identify speaker names from voiceprints?

### ISSUE THREAD

**Issue by ShunyaYamagami** [pyannote/pyannote-audio#1369]
When performing diarization on a conversation with multiple speakers, I want to not only recognize that different individuals are speaking but also simultaneously identify who is speaking and even detect their pre-registered names. I believe that recognizing the speaker names from their pre-registered voiceprints would be a good approach. Does pyannote provide a best practice for this out of the box?

**Comment by hbredin** [comment]
> Does pyannote provide a best practice for this out of the box?

Not yet. But there is an ongoing PR getting us closer to this feature: https://github.com/pyannote/pyannote-audio/pull/1346

**Comment by mickalleny2k** [comment]
> When performing diarization on a conversation with multiple speakers, I want to not only recognize that different individuals are speaking but also simultaneously identify who is speaking and even detect their pre-registered names. I believe that recognizing the speaker names from their pre-registered voiceprints would be a good approach. Does pyannote provide a best practice for this out of the box?

Do you know how to do this ? I need to do this. Please advise. Thanks in advance.

**Comment by mickalleny2k** [comment]
Do you know how to do this ? 
I need to do this. 
Please advise. 
Thanks in advance.

**Comment by alexey-akulinin** [comment]
> Do you know how to do this ? I need to do this. Please advise. Thanks in advance.

I used a workaround for this: extract audio samples of known speakers (10-15 seconds of continuous speech should be enough), then concat them in one audio file, so this audio file with samples will contain all known speakers and you are aware of the order of speakers. Then concat this file with a full audio, you get a slightly longer file (with samples in the beginning of it).

Process this new full file and you'll be able to spot all known speakers in it.
