### ISSUE TITLE
Diarization pipeline output variability with different CUDA versions. 

### ISSUE THREAD

**Issue by popcornell** [pyannote/pyannote-audio#1370]
Hi, 

I just want to report I observed quite a large variability in the output of the pyannote diarization pipeline if I change the CUDA version on my side. 
For example, switching between `torch 1.13.1-py3.9_cuda11.7_cudnn8.5.0_0 --> 1.13.1-py3.9_cuda11.6_cudnn8.3.2_0` by running: 
- `conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia`
- `conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.6 -c pytorch -c nvidia`

In my case quite changes the output of the pipeline. 
For example a simple script such as (I use an audio from CHiME-6 but with other long audio files I observed it as well):

```python
from pyannote.audio import Model, Pipeline
import torch
import soundfile as sf


torch.manual_seed(0)
audio, fs = sf.read("/raid/users/popcornell/chime7espnet/egs2/chime7_task1/diar_asr1/chime7_task1/chime6/audio/dev/S02_U06.CH1.wav")
audio = torch.from_numpy(audio).float()
pipeline = Pipeline.from_pretrained(
        "pyannote/speaker-diarization",
        use_auth_token="PUT_YOUR_TOKEN")
#pretrained_pipeline.cuda()
out_seg = pipeline({"waveform": audio[None, ...], "sample_rate": fs})

with open("predictions.rttm", "w") as f:
    f.write(out_seg.to_rttm())
```

I get slighly different predictions.rttm outputs when switching the CUDA version. 
**The relative DER (no collar) of the two predictions is 12% and is a lot.** 
On the CHiME-7 challenge diarization baseline https://github.com/espnet/espnet/tree/master/egs2/chime7_task1/diar_asr1 I observe the same and is leading to difficulties in replicating the diarization baseline unfortunately (up to 8% DER difference has been observed between different participants).

The two RTTMs are attached here as .txt files as GitHub does not allow .rttm (116 for 11.6 CUDA and 117 for 11.7). 
[predictions_116.txt](https://github.com/pyannote/pyannote-audio/files/11460876/predictions_116.txt)
[predictions_117.txt](https://github.com/pyannote/pyannote-audio/files/11460873/predictions_117.txt)

I also attach info about my conda environment here. 
[conda_env_info.txt](https://github.com/pyannote/pyannote-audio/files/11460882/conda_env_info.txt)
as well as the explicit conda config file to reproduce the environment `conda install --name myenv --file cornell_env.txt `
[cornell_env.txt](https://github.com/pyannote/pyannote-audio/files/11460889/cornell_env.txt)

Info about my system too by running: 
```bash
wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
python collect_env.py
```
is attached: 
[output_collect_env.txt](https://github.com/pyannote/pyannote-audio/files/11460916/output_collect_env.txt)

I think it is coming from the embedding extraction and clustering step and not from segmentation because the segmentation seems consistent till the second decimal digit when swithcing CUDA

**Comment by hbredin** [comment]
Thanks @popcornell for the detailed bug report.

Can you please share the `artifacts.pkl` files resulting from this sample piece of code (for at least 2 different CUDA configurations) ?

This should help us pinpoint where the problem is coming from.

```python
import pickle
from pyannote.audio.pipelines.utils.hook import logging_hook
file = {"audio": "/path/to/audio.wav"}
file["diarization"] = pipeline(file, hook=hook)
with open("artifacts.pkl", "wb") as f:
    pickle.dump(file, f)
```

**Comment by popcornell** [comment]
Hi Hervé, sorry for the late update. 

Here are the files for 11.6 CUDA and 11.7 CUDA. 
I had to use gdrive because files over 25 MB are not allowed on GitHub. 

https://drive.google.com/file/d/1sEimBFylumaXeeSSWaZa_TjMVBKAUTSD/view?usp=share_link

**Comment by hbredin** [comment]
Hmmmm. Did I miss something? The diarization outputs [seem identical](https://gist.github.com/hbredin/88301f69eb1ad86969aacb14159794a7
)...

**Comment by popcornell** [comment]
My bad, the CUDA version did not change for some reason between the two runs. 
I have updated the files and should be correct

```bash
>>> der = DiarizationErrorRate()
>>> der(b["diarization"], a["diarization"])
/raid/users/popcornell/CHiME6/test_chime7/espnet/tools/venv/lib/python3.9/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
0.12118828433555145
```
the difference seems 12% DER on my side.

**Comment by hbredin** [comment]
Thanks. There is indeed huge difference, even for the segmentation step.
Could you also share the `pickle` when run on CPU?

**Comment by hbredin** [comment]
Possibly related: https://discuss.pytorch.org/t/cuda-11-7-causing-large-calculation-discrepancy/171344/2

**Comment by hbredin** [comment]
Did you run this on Ampere devices?

https://pytorch.org/docs/stable/notes/cuda.html#tensorfloat-32-tf32-on-ampere-devices

**Comment by popcornell** [comment]
Yes A100 on a DGXA100 system. 

My bet is that this is something on Pytorch side rather than Pyannote anyway. Just raised this issue so we can confirm or not. 

If it is Pytorch issue, such huge difference (despite even the fact the code is open-source) is kinda of a major scientific problem.
Considering I have made effort in trying to make it replicable by open-sourcing the code you can imagine how issues like these cast doubts on most of the works out there (as most do not even share the code either).

**Comment by hbredin** [comment]
Even so, could you try them both with the following?

```python
torch.backends.cuda.matmul.allow_tf32 = False
torch.backends.cudnn.allow_tf32 = False
```

**Comment by hbredin** [comment]
Great! Would this "fix" be a good solution?
https://github.com/pyannote/pyannote-audio/pull/1381

**Comment by popcornell** [comment]
Yeah it looks good

**Comment by hbredin** [comment]
I might as well raise an error rather than just warn, what do you think?
As a user, which option would you prefer?

* Option 1: `raise` an error so that it won't even run if the user does not disable TF32
* Option 2: `warn` that they should disable TF32 (with the risk that they miss the warning)
* Option 3: disable TF32 automatically and `warn` the user that we did it for them

**Comment by popcornell** [comment]
I think that for inference should be fine in most applications. I did not observe a significant slow down either.

**Comment by ci21-cgarijo** [comment]
Hi! I read the whole PR and I was wondering what did happen at the end with this issue?
I'm using `pyannote.embedding` to detect unique speakers and I'm getting a warning that has brought me to this thread. The thing is that the warning I get is the opposite to what is posted here:
```sh
ReproducibilityWarning: TensorFloat-32 (TF32) has been disabled as it might lead to reproducibility issues and lower accuracy.
It can be re-enabled by calling
   >>> import torch
   >>> torch.backends.cuda.matmul.allow_tf32 = True
   >>> torch.backends.cudnn.allow_tf32 = True
See https://github.com/pyannote/pyannote-audio/issues/1370 for more details.
```
where I have deactivated by default the tf32 operations and the warning message just recommends the opposite: to enable back tf32 operations.

How could this end up like this?

**Comment by runfish5** [comment]
same issue.

**Comment by ymoslem** [comment]
@runfish5 Have you managed to solve it?

**Comment by ymoslem** [comment]
@runfish5 When I ran the code in the Terminal, it showed an extra error:
```bash
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or dir
```

So, I installed:
```bash
apt update
apt install libcudnn8=8.9.5.*-1+cuda11.8
```

Now all of these files are available at: `/usr/lib/x86_64-linux-gnu/`

Then
```bash
pip3 install whisperx
apt install ffmpeg -y
```

**Comment by ci21-cgarijo** [comment]
@runfish5 
Did you get also the ReproducibilityWarning when you ran that code after solving the issue with the cudnn libraries?
You said your session crashes, but what error are you getting?
In my case, pyannote executes normally, but my concern was about that ReproducibilityWarning I was getting and that also this thread just confused me more because what is said here is the opposite to what the warning message is printing!

**Comment by runfish5** [comment]
Even same with 
```
!pip install git+https://github.com/m-bain/whisperx.git --upgrade
```

**Comment by runfish5** [comment]
Still same issue when I switch from `L4` to `A100` GPU.

Or use:
`compute_type = "float32"`
Or use:
`batch_size = 8`

**Comment by rodrigob** [comment]
Same issue, why was this ticket closed ? What was the solution in the end ?

**Comment by iasolis** [comment]
Ubuntu 24.04.1 LTS
GPU - 4090, Driver Version: 550.144.03 , CUDA Version: 12.4
torch==2.7.0, pyannote.audio==3.3.2

I am encountering the same warning. What could be the problem and how can it be resolved?

```
ReproducibilityWarning: TensorFloat-32 (TF32) has been disabled as it might lead to reproducibility issues and lower accuracy.
It can be re-enabled by calling
   >>> import torch
   >>> torch.backends.cuda.matmul.allow_tf32 = True
   >>> torch.backends.cudnn.allow_tf32 = True
See https://github.com/pyannote/pyannote-audio/issues/1370 for more details.

```

**Comment by Geometrein** [comment]
I also get this warning:
```
ReproducibilityWarning: TensorFloat-32 (TF32) has been disabled as it might lead to reproducibility issues and lower accuracy.
It can be re-enabled by calling
   >>> import torch
   >>> torch.backends.cuda.matmul.allow_tf32 = True
   >>> torch.backends.cudnn.allow_tf32 = True
See https://github.com/pyannote/pyannote-audio/issues/1370 for more details.
````
despite the model being run on CUDA T4 with specifically with floar16 compute type:

```
Model Params: MODEL_ARCHITECTURE='large-v3', COMPUTE_TYPE='float16', DEVICE=device(type='cuda')
```
