### ISSUE TITLE
How to uninstall the pyannote?

### ISSUE THREAD

**Issue by DiaosWang** [pyannote/pyannote-audio#1372]
I use the anaconda and in Linux.  **I just want to uninstall the pyannote in `one-env`, and install it in `other-env` again.** But I cannot uninstall it when :
   `pip uninstall pyannote`
the WARNING is :
  `WARNING: Skipping pyannote as it is not installed.`

But when I find the pyannote, the output is as follows:
![image](https://github.com/pyannote/pyannote-audio/assets/47164366/7fba7448-3720-466a-b850-6869a8d3f166)

Anyone can help me ? 
Thank you very much indeed！

**Comment by pierre-pedrito** [comment]
Hello,
Have you tried the request: pipenv uninstall <packagename> ?
Have a nice day
