### ISSUE TITLE
Speaker reidentification

### ISSUE THREAD

**Issue by Vermeille** [pyannote/pyannote-audio#1383]
Hello,

The project I am currently working on needs to identify speakers. Having the audio segments labeled "Speaker 0" to Speaker N" is cool, but labels "Yann LeCun", "Yoshua Bengio" etc are much better.

I am willing to contribute the feature and was thinking of implementing it the following way:

1. Have the user have a directory with speaker samples (`speakers/Yann_LeCun.wav`, `speakers/Yoshua_Bengio.wav`, etc)
2. Get a speaker embedding for each file (Time avg pool? Max pool? Attention is out of the equation since it needs)
3. Optional: store the embeddings on disk (safetensors)
4. [When doing the speaker clustering](https://github.com/pyannote/pyannote-audio/blob/a58153662b9a11485681c2a259d36e75d7243f2b/pyannote/audio/pipelines/speaker_diarization.py#L500), assign each speaker embedding to a centroid (hungarian algorithm?) and use the speaker labels.

What do you think?

Related to: https://github.com/pyannote/pyannote-audio/issues/1310 . Could be an implementation starting point and have two birds with one stone.

**Comment by hbredin** [comment]
To backup my "recurrent request" claim, here is a poll that I recently posted on Twitter (where speaker tracking ~= speaker reidentification)

https://twitter.com/hbredin/status/1647146368782270464

**Comment by flyingleafe** [comment]
@Vermeille in the meanwhile, yes, you can use the PR branch and simply compare the embeddings returned by the pipeline with the known embeddings by cosine distance, then relabel the annotation accordingly.
