### ISSUE TITLE
Bug report. Installation fail.

### ISSUE THREAD

**Issue by actuallyrizzn** [pyannote/pyannote-audio#1388]
I've attempted to install pyannote.audio via pip on a variety of machines, and pip gets all the way through the process and fails at the installation phase. 

Running latest stable of Ubuntu/Python.

Here's the last bit, after all the dependencies are downloaded.

<tt>

Collecting greenlet!=0.4.17
  Downloading greenlet-2.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (613 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 613.7/613.7 KB 38.4 MB/s eta 0:00:00
Collecting MarkupSafe>=2.1.1
  Downloading MarkupSafe-2.1.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting mdurl~=0.1
  Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard>=2.2.0->pytorch-lightning<1.7,>=1.5.4->pyannote.audio) (3.2.0)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/lib/python3/dist-packages (from rsa<5,>=3.1.4->google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning<1.7,>=1.5.4->pyannote.audio) (0.4.8)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec->huggingface-hub>=0.8.1->pyannote.audio) (3.3)
Building wheels for collected packages: antlr4-python3-runtime, docopt, julius, audioread
  Building wheel for antlr4-python3-runtime (setup.py) ... done
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.9.3-py3-none-any.whl size=144575 sha256=8ea6785ec5a7c36f0f4f8b28187801a859cab77857e6befdac29053ec66bed25
  Stored in directory: /root/.cache/pip/wheels/12/93/dd/1f6a127edc45659556564c5730f6d4e300888f4bca2d4c5a88
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13723 sha256=af1984badc2c1736d7b933e4eb0d566df9f143d6491cbe43c8d00871bd17c44a
  Stored in directory: /root/.cache/pip/wheels/fc/ab/d4/5da2067ac95b36618c629a5f93f809425700506f72c9732fac
  Building wheel for julius (setup.py) ... done
  Created wheel for julius: filename=julius-0.2.7-py3-none-any.whl size=21895 sha256=236f184d22206e7604de83c2ddec662f8a4d936e6fe577b8b4bb5fa130ff1fbd
  Stored in directory: /root/.cache/pip/wheels/b9/b2/05/f883527ffcb7f2ead5438a2c23439aa0c881eaa9a4c80256f4
  Building wheel for audioread (setup.py) ... done
  Created wheel for audioread: filename=audioread-3.0.0-py3-none-any.whl size=23706 sha256=63637de91b6ace7bb22a548332022da301c6f8ee543381877b62ebd4244c0b06
  Stored in directory: /root/.cache/pip/wheels/da/4b/39/c5f6c4ee93b43281dda4dab5ac5f2bdf9d11074d427493cd55
Successfully built antlr4-python3-runtime docopt julius audioread
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 389, in run
    to_install = resolver.get_installation_order(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
    weights = get_topological_weights(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
    assert len(weights) == expected_node_count
AssertionError
rizzn@digitalocean-ubuntu-nyc1-s-16vcpu-64gb

</tt>

**Comment by sanderpick** [comment]
Long shot, but if you're using conda you might be running into this issue: https://github.com/conda/conda/issues/9392. The install will fail with the error above if you're in a vanilla conda env but your `pip` and `python` are not properly scoped to your env. tl;dr, make sure `which pip` is not pointing to your OS version.
