### ISSUE TITLE
[Security] vulnerability issue in Sphinx-2.2.2 and ipython-7.16.3 

### ISSUE THREAD

**Issue by ohensf** [pyannote/pyannote-audio#1390]
hi, 
our automated tools have detected a vulnerability in Sphinx-2.2.2 and ipython-7.16.3. 

https://security.snyk.io/package/pip/Sphinx/2.2.2
https://security.snyk.io/package/pip/ipython/7.16.3

Do you have any plans to upgrade these libraries?

**Comment by hbredin** [comment]
PR welcome!
