### ISSUE TITLE
hubconf.py missing in pyannote-audio directory  in Colab environment

### ISSUE THREAD

**Issue by malajb** [pyannote/pyannote-audio#1392]
Hello,
I have been using pyannote-audio for speaker diarisation with ' emb' as the pretrained model 
(model_emb = torch.hub.load('pyannote/pyannote-audio', 'emb',force_reload=True)))

Written code was working fine in Google Colab till Aug 2022 and recently when I re-executed the already executed file, error is shown as 
"FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/torch/hub/pyannote_pyannote-audio_main/hubconf.py'".

Packages installed were as follows
!pip install pyannote.audio==1.1.1
import pyannote.audio.features --> Code executed with no error with this packages

As mentioned in the git hub query 
'Missing hubconf.py in pyannote-audio_develop #599"
I had changed the  pyannote.audio version to 1.1.2 but still the error occurs. This error occurs in Google colab( In stand alone systems desktop or laptop if the hubconf.py file is copied to the path /root/.cache/torch/hub/pyannote_pyannote-audio_main/hubconf.py project works fine) . Kindly give a solution for the issue in Google colab where the files are automatically downloaded during execution.

**Comment by palvinderbhatia** [comment]
I am facing same issue.

**Comment by serosh1** [comment]
any idea how to resolve the issue

**Comment by Sivakgpian** [comment]
i also have same issue

**Comment by eyaler** [comment]
solution:
```
!pip install pyannote.core==4.1 pyannote.pipeline==1.5.2 pyannote.audio==1.1.1
!wget -nc https://raw.githubusercontent.com/pyannote/pyannote-audio/1.1.1/hubconf.py -P /root/.cache/torch/hub/pyannote_pyannote-audio_main
!wget -nc https://raw.githubusercontent.com/pyannote/pyannote-audio/1.1.1/hubconf.py -P /root/.cache/torch/hub/pyannote_pyannote-audio-hub_master
import torch
import pyannote.core #https://github.com/pyannote/pyannote-audio/issues/561
pipeline = torch.hub.load('pyannote/pyannote-audio', 'dia', trust_repo=True)
```
