### ISSUE TITLE
Benchmark VAD on AVA dataset

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#140]

**Comment by hbredin** [comment]
https://github.com/alainray/ava_downloader might help

**Comment by hbredin** [comment]
This could be useful as well: 
https://github.com/cvdfoundation/ava-dataset

cc @MarvinLvn (just in case you want to benchmark our best model on AVA ;-))

**Comment by MarvinLvn** [comment]
Noted ! I'd really like to find the time to do that ! :) 
We could even compare performances of the best voice-type-classifier, with the best adversarially trained VAD !

**Comment by hbredin** [comment]
Hey @MarvinLvn, would you mind reporting the performance of `torch.hub.load('pyannote/pyannote-audio', 'sad')` pretrained model on AVA in here? 

Then, I'll close this issue (but at least we'll have the numbers here).

**Comment by MarvinLvn** [comment]
Here's the results obtained on the AVA dataset with `torch.hub.load('pyannote/pyannote-audio', 'sad')` for various thresholds.

![torch_hub_load_AVA](https://user-images.githubusercontent.com/11290637/83121830-19d2a400-a0d3-11ea-94a5-b5387a24b741.png)

The same results in a table : 

|threshold|TP|TN|FP|FN|TPR|FPR|
 |     :---:      |     :---:      |     :---:      |     :---:      |     :---:      |     :---:      |     :---:     |    
|0.000|75572.220|    0.000|68427.780|    0.000|1.000|1.000|
|0.050|74812.140| 8882.800|59544.980|  760.080|0.990|0.870|
|0.100|74110.760|16706.340|51721.440| 1461.460|0.981|0.756|
|0.150|73437.160|22478.990|45948.790| 2135.060|0.972|0.671|
|0.200|72771.680|27045.710|41382.070| 2800.540|0.963|0.605|
|0.250|72089.080|30871.820|37555.960| 3483.140|0.954|0.549|
|0.300|71388.880|34162.420|34265.360| 4183.340|0.945|0.501|
|0.350|70664.380|37028.880|31398.900| 4907.840|0.935|0.459|
|0.400|69907.410|39589.830|28837.950| 5664.810|0.925|0.421|
|0.450|69122.770|41919.390|26508.390| 6449.450|0.915|0.387|
|0.500|68276.440|44075.700|24352.080| 7295.780|0.903|0.356|
|0.550|67392.530|46128.440|22299.340| 8179.690|0.892|0.326|
|0.600|66447.270|48078.770|20349.010| 9124.950|0.879|0.297|
|0.650|65407.560|49955.010|18472.770|10164.660|0.865|0.270|
|0.700|64257.090|51765.150|16662.630|11315.130|0.850|0.244|
|0.750|62986.280|53625.020|14802.760|12585.940|0.833|0.216|
|0.800|61516.230|55529.660|12898.120|14055.990|0.814|0.188|
|0.850|59717.580|57575.320|10852.460|15854.640|0.790|0.159|
|0.900|57287.570|59864.130| 8563.650|18284.650|0.758|0.125|
|0.950|53249.390|62735.950| 5691.830|22322.830|0.705|0.083|
|1.000|    0.000|68427.780|    0.000|75572.220|0.000|0.000|

All metrics should be derivable from TP, TN, FP and FN.

The best results reported in the literature as of 28th of May, 2020 : 

| True Positive Rate (Recall) | False Positive Rate (Fallout)| Training Set | Ref.
| :---         |     :---:      |          ---: |          ---: |
|0.945 | 0.315 | Movies | [here](http://150.162.46.34:8080/icassp2019/ICASSP2019/pdfs/0004105.pdf)
|0.917 | 0.315 | AudioSet | [here](https://arxiv.org/pdf/1808.00606.pdf)
