### ISSUE TITLE
Multi-batch inference of VAD pipeline

### ISSUE THREAD

**Issue by hannan72** [pyannote/pyannote-audio#1404]
I want to run VAD pipeline in multi-batch but it seems that pipeline is not capable of run multi-batch inferences. However I have tested the Segmentation model and run it multi-batch properly.
I am running on CUDA with the following code:

**A. Single batch pipeline inference** (works properly): 
```
from pyannote.audio.pipelines import VoiceActivityDetection as VoiceActivityDetectionPipeline
from pyannote.audio import Model, Pipeline
from pyannote.audio.utils.signal import Binarize
from scipy.io import wavfile
AUDIO_FILE = "sample.wav"
sample_rate, waveform_np = wavfile.read(AUDIO_FILE)
offline_model = Model.from_pretrained("pyannote/vad_pytorch_model.bin").to('cuda')
pipeline = VoiceActivityDetectionPipeline(segmentation=offline_model, step=1.0)
initial_params = {"onset": 0.7, "offset": 0.55, 
                  "min_duration_on": 0.0, "min_duration_off": 0.0}
pipeline.instantiate(initial_params)
waveform = torch.from_numpy(waveform_np/32768.0).float().unsqueeze(dim=0).to(device=torch.device('cuda'))
# waveform_shape: (channel, data) = (1, 174313)
audio_in_memory = {"waveform": waveform, "sample_rate": sample_rate}
result = pipeline(audio_in_memory)
```

**B. Multi batch pipeline inference** (got error):
```
waveform = torch.from_numpy(waveform_np/32768.0).float().unsqueeze(dim=0).to(device=torch.device('cuda')).unsqueeze(dim=0)
# waveform_shape: (batch_size, channel, data) = (1, 1, 174313)
batched_waveform = torch.cat((waveform,waveform,waveform,waveform), dim=0)
# batched_waveform_shape: (batch_size, channel, data) = (4, 1, 174313)
audio_in_memory = {"waveform": batched_waveform, "sample_rate": sample_rate}
result = pipeline(audio_in_memory)
```
It raises the following error:
``` ValueError: 'waveform' must be provided as a (channel, time) torch Tensor. ```

**C. Single batch inference of just segmentation model** (works properly):
```
waveform = torch.from_numpy(waveform_np/32768.0).float().unsqueeze(dim=0).to('cuda')
output = offline_model(waveform)
# waveform_shape: (channel, data) = (1, 174313)
# output_shape: (batch_size, segments, speakers) = (1, 642, 3)
```

**D. Multi batch inference of just segmentation model** (works properly):
```
waveform = torch.from_numpy(waveform_np/32768.0).float().unsqueeze(dim=0).unsqueeze(dim=0).to('cuda')
# waveform_shape: (batch_size, channel, data) = (1, 174313)
batched_waveform = torch.cat((waveform, waveform, waveform, waveform),dim=0).cuda()
# batched_waveform_shape: (batch_size, channel, data) = (4, 1, 174313)
output = offline_model(batched_waveform)
# output_shape: (batch_size, segments, speakers) = (4, 642, 3)
```

Is it possible to run pipeline in multi-batch (case B) successfully?

**Comment by hbredin** [comment]
Short answer: no.

Long answer: the `Inference` class used internally in the `VoiceActivityDetection` pipeline already does some kind of batching (by chunking a long file into shorter chunks). You can use the `inference_kwargs` to increase the batch size of this internal chunking to make things faster (but this is not the kind of batch that you are looking for).

**Comment by hbredin** [comment]
Also options C and D will not give you optimal results because the model was trained with chunks of 5s so it is not a good idea to give it longer or shorter waveforms.

That is the whole point of the `Inference` class: chunking with the correct duration.
