### ISSUE TITLE
Can I use pyannote speaker diarization without hugginface token or is there any way to download and use the model do do diarization.

### ISSUE THREAD

**Issue by shanky100** [pyannote/pyannote-audio#1410]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by sheetalmathur** [comment]
I would also like to know the same, can i use the pyannote without hugging face model?

**Comment by hbredin** [comment]
Please read the FAQ. The FAQtory bot did a good job pointing to the answer...

**Comment by nlp03** [comment]
I am also interested in understanding whether it is possible to utilize Pyannote independently, without relying on Hugging Face model keys.

**Comment by shanky100** [comment]
> 

I see that the model is gated, is it mandatory to have the huggingface token in order to use these models or  this model is developed and hosted by hugginface.
Also what information it collects in order to provide access.

It would be helpful, if I could get few answers due to data privacy issues and some access related issues faced in accessing huggingface.

**Comment by LouieBHLu** [comment]
In the FAQ,  it only refers to the offline usage of segmentation I guess. What about diarization then?

**Comment by ExtReMLapin** [comment]
The FAQ didn't really help me, what I did on my side it I used the token and specified a custom download path, which later will be working without the token, for example : 


```
os.environ["HF_DATASETS_OFFLINE"] = "1"
os.environ['TRANSFORMERS_CACHE'] = diarization_path
os.environ['TORCH_HOME'] = diarization_path
os.environ['HF_HOME'] = diarization_path
os.environ['PYANNOTE_CACHE'] = diarization_path
```

then turn all the sym links into real files and it should work, the offline turorial thing was unreadable so I did this and it works like a charm

**Comment by mllife** [comment]
> os.environ["HF_DATASETS_OFFLINE"] = "1"
> os.environ['TRANSFORMERS_CACHE'] = diarization_path
> os.environ['TORCH_HOME'] = diarization_path
> os.environ['HF_HOME'] = diarization_path
> os.environ['PYANNOTE_CACHE'] = diarization_path

can you shed some more details on the code changes and files placement you did?

**Comment by ExtReMLapin** [comment]
What will happen is the first time you load it using your token it will download it to the diarization_path path, the next time, you should be able to plug out your ethernet cable and it will auto-download it because it will find it in the cache folder. This way : 

````python
diarize_pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization@2c6a571d14c3794623b098a065ff95fa22da7f25")
```

From memory i got the `2c6a571d14c3794623b098a065ff95fa22da7f25` by manually exploring the `diarization_path` variable value (which ends up just being a absolute path inside my code folder) and it was just the folder name.

I'm leaving my house in few mins to go to the office, once I get here i'll give you more details

**Comment by ExtReMLapin** [comment]
This is (one of)) the folder I end up with after my changes and I load it with the code posted above.


![image](https://github.com/pyannote/pyannote-audio/assets/3909752/6b065469-66fb-4124-baf6-55eeff1bc242)

Please note the snapshot id in the path that I used in the function in my previous message

**Comment by mllife** [comment]
This is working, thanks.

**Comment by mllife** [comment]
@ExtReMLapin , can you take a look my previous comment

**Comment by mllife** [comment]
@ExtReMLapin model files are now loading from offline cache after I added the env vars. but I still have to use "use_auth_token" in the code.
what changes to do in the code?
```
  device = "cuda" if torch.cuda.is_available() else "cpu"
  # TODO - update this
  diarization_model = Pipeline.from_pretrained(
      checkpoint_path="pyannote/speaker-diarization@2c6a571d14c3794623b098a065ff95fa22da7f25",
      use_auth_token="hf_xxxxxxxxxxxxx",
  )
  diarization_model = diarization_model.to(torch.device(device))
```

**Comment by ExtReMLapin** [comment]
I got out of bed, brain's booting.

Right now I don't see why it could not work on your end can you show the full error stack ?

**Comment by mllife** [comment]
@ExtReMLapin , this is the full error
```
Traceback (most recent call last):
  File "/Users/xXOL/Projects/annotations/check_pyannote_offline.py", line 18, in <module>
    diarization_model = Pipeline.from_pretrained(
  File "/Users/xXOL/Projects/annotations/venv/lib/python3.8/site-packages/pyannote/audio/core/pipeline.py", line 88, in from_pretrained
    config_yml = hf_hub_download(
  File "/Users/xXOL/Projects/annotations/venv/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/Users/xXOL/Projects/annotations/venv/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './diarization_model/models--pyannote--speaker-diarization/snapshots/2c6a571d14c3794623b098a065ff95fa22da7f25/'. Use `repo_type` argument if needed.
```

**Comment by ExtReMLapin** [comment]
The error you posted shows your line of code isn't the one from this message https://github.com/pyannote/pyannote-audio/issues/1410#issuecomment-1672571268

Use the one from my message

**Comment by mllife** [comment]
The model loaded is None. If I don't add "use_auth_token"
<img width="1350" alt="Screenshot 2023-08-11 at 4 55 40 PM" src="https://github.com/pyannote/pyannote-audio/assets/69006366/28c739b6-1c09-4f4d-9de1-3859ebc5430d">
<img width="1256" alt="Screenshot 2023-08-11 at 4 58 17 PM" src="https://github.com/pyannote/pyannote-audio/assets/69006366/ae43dc14-386a-4ba9-8c73-ea257f00b822">

**Comment by ExtReMLapin** [comment]
Whole code is at the office and models are at the office, and I got this day off. So i'll be able to help next week

**Comment by mllife** [comment]
thanks, will wait for the update.

**Comment by ExtReMLapin** [comment]
Alright, this is how my localized folder looks

![image](https://github.com/pyannote/pyannote-audio/assets/3909752/cd2cebae-8109-459b-a6a6-3519e9a873a1)

![image](https://github.com/pyannote/pyannote-audio/assets/3909752/ddde7a8b-4a31-4159-92da-d87902367212)

In this folder there used to be symbolic links, copy/paste managed to turn them into real files.


my pip freeze : 

`transformers @ git+https://github.com/huggingface/transformers.git@460b844360131c99d3dd4dbd9c08545ea2e6ac9e`

```
pyannote.algorithms==0.8
pyannote.audio==2.1.1
pyannote.core==5.0.0
pyannote.database==5.0.0
pyannote.metrics==3.2.1
pyannote.parser==0.8
pyannote.pipeline==2.3
```


As for the code : 

```python
import torch
from pyannote.audio import Pipeline

import numpy as np
diarize_pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization@2c6a571d14c3794623b098a065ff95fa22da7f25")

if torch.cuda.is_available():
    diarize_pipeline = diarize_pipeline.to("cuda")

def diarize(audio_path, num_spk=None):
    
    diarization = diarize_pipeline(audio_path, num_speakers=num_spk)
    diarization_list = list()
    for turn, _, speaker in diarization.itertracks(yield_label=True):
        diarization_list.append([turn.start, turn.end, speaker])
    print(diarization_list)
    return diarization_list

```

and in another file included sooner : 

```python
import os
#load config and if path is relative path, convert to absolute path
import json

with open("config.json") as f:
    data_json = json.load(f)



diarization_path = data_json["diarization_path"]
if not os.path.isabs(diarization_path):
    diarization_path = os.path.abspath(diarization_path) + "/"
    




os.environ["HF_DATASETS_OFFLINE"] = "1"
os.environ['TRANSFORMERS_CACHE'] = diarization_path
os.environ['TORCH_HOME'] = diarization_path
os.environ['HF_HOME'] = diarization_path
os.environ['PYANNOTE_CACHE'] = diarization_path



```

**Comment by mllife** [comment]
@ExtReMLapin , thanks for your detailed response.
But i am unable to install the modules required due to conflicts.
```
The conflict is caused by:
    The user requested pyannote.core==5.0.0
    pyannote-algorithms 0.8 depends on pyannote.core>=1.3.1
    pyannote-audio 2.1.1 depends on pyannote.core<5.0 and >=4.4
```
If I am changing anything, then I am getting
```
  ERROR: Failed building wheel for hmmlearn
  Running setup.py clean for hmmlearn
Failed to build hmmlearn
```
Can you tell about the python version being used? or anything else I can do?
