### ISSUE TITLE
pyannote.audio 1.0.1 require torch==0.4, caused segment fault

### ISSUE THREAD

**Issue by yahcong** [pyannote/pyannote-audio#142]
Requirement already satisfied: pyannote.audio in ./miniconda3/lib/python3.6/site-packages (1.0.1)
Requirement already satisfied: chocolate>=0.6 in ./miniconda3/lib/python3.6/site-packages (from pyannote.audio) (0.6)
Requirement already satisfied: pyYAML>=3.12 in ./miniconda3/lib/python3.6/site-packages (from pyannote.audio) (3.13)
Requirement already satisfied: pyannote.metrics>=1.7 in ./miniconda3/lib/python3.6/site-packages (from pyannote.audio) (1.8.1)
Requirement already satisfied: pyannote.database>=1.3.2 in ./miniconda3/lib/python3.6/site-packages (from pyannote.audio) (1.5.5)
Requirement already satisfied: audioread>=2.1.5 in ./miniconda3/lib/python3.6/site-packages (from pyannote.audio) (2.1.6)
Requirement already satisfied: torch==0.4 in ./miniconda3/lib/python3.6/site-packages (from pyannote.audio) (0.4.0)

**Comment by hbredin** [comment]
Please give more details. I don't see any error in there...

**Comment by yahcong** [comment]
$python -c "import dlib,torch"
segmentation fault
$demess
....
[178618.451313] dlib.cpython-36[3483]: segfault at 0 ip 000055b6b3ff0370 sp 00007ffe64325fd0 error 4 in dlib.cpython-36m-x86_64-linux-gnu.so[55b6b3f88000+9b0000]

dlib==19.16,torch==0.4.0

Torch version changed to 1.00,this error no longer appears

**Comment by hbredin** [comment]
Looks like this is an issue with your `dlib` installation and has nothing to do with pyannote.audio.
Closing.
