### ISSUE TITLE
Enhancement: No cache_dir parsing to SpeechBrainPretrainedSpeakerEmbedding

### ISSUE THREAD

**Issue by JSchmie** [pyannote/pyannote-audio#1422]
Hello, 

I am using:

    pyannote-audio            2.1.1
    pyannote-core              4.5
    pyannote-database      4.1.3
    pyannote-metrics         3.2.1
    pyannote-pipeline        2.3 

While I am setting up a local installation of your speaker diarization model, using Speechbrains speaker Embedding, I discovered that you do not pass through your cache_dir to the  `SpeechBrainPretrainedSpeakerEmbedding` instead you use:

    self.classifier_ = SpeechBrain_EncoderClassifier.from_hparams(
            source=self.embedding,
            savedir=f"{CACHE_DIR}/speechbrain",
            run_opts={"device": self.device},
            use_auth_token=use_auth_token,
        )

Where CACHE_DIR is:

    CACHE_DIR = os.getenv(
        "PYANNOTE_CACHE",
        os.path.expanduser("~/.cache/torch/pyannote"),)

So even when cache_dir is set up in `Pipeline.from_pretrained(....,cache_dir= "some_path")` it will not be used by `SpeechBrainPretrainedSpeakerEmbedding`. 
This is indeed a problem which can easily be overcome by set up the env variable  `"PYANNOTE_CACHE"` but it seems to be easy to fix since the `cache_dir` variable already exists in the Pipeline and might be useful in future versions of your Code. 

I hope this helped. 

Best regards and thank you for your great work on this project.
Jacob

**Comment by Lorenzoncina** [comment]
Any solution to this issue? I-m also trying to setup a local installation of the speaker diarization pipeline
