### ISSUE TITLE
AttributeError: module 'pyannote.audio.pipelines' has no attribute 'SpeakerSegmentation'

### ISSUE THREAD

**Issue by mahesh-ctrl** [pyannote/pyannote-audio#1423]
from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("pyannote/speaker-segmentation", use_auth_token= token )

AttributeError                            Traceback (most recent call last)
[<ipython-input-26-e238cb22d1ea>](https://localhost:8080/#) in <cell line: 2>()
      1 from pyannote.audio import Pipeline
----> 2 pipeline = Pipeline.from_pretrained("pyannote/speaker-segmentation", use_auth_token= token )

1 frames
[/usr/local/lib/python3.10/dist-packages/pyannote/core/utils/helper.py](https://localhost:8080/#) in get_class_by_name(class_name, default_module_name)
     66         class_name = tokens[-1]
     67 
---> 68     return getattr(import_module(module_name), class_name)

AttributeError: module 'pyannote.audio.pipelines' has no attribute 'SpeakerSegmentation'

**Comment by hbredin** [comment]
I guess you tried using this pipeline from `develop` branch.
`pyannote/speaker-segmentation` is only supported in version `2.x`.

**Comment by mahesh-ctrl** [comment]
Yes I used:  
pip install -qq https://github.com/pyannote/pyannote-audio/archive/refs/heads/develop.zip
Would it be sufficient if I use:
pip install pyannote.audio==2.1.1

**Comment by mahesh-ctrl** [comment]
After installing pyannote.audio==2.1.1 faced the error:

OSError: sndfile library not found

Resolved the error with:

conda install -c conda-forge librosa

Thank you for the assistance
