### ISSUE TITLE
commercial use??

### ISSUE THREAD

**Issue by YooSungHyun** [pyannote/pyannote-audio#1429]
https://huggingface.co/pyannote/segmentation
in huggingface hub, model tag in MIT license, and i think input data is used all free data.
but i can found this message

``` text
For commercial enquiries and scientific consulting, please contact [me](mailto:herve@niderb.fr).
For [technical questions](https://github.com/pyannote/pyannote-audio/discussions) and [bug reports](https://github.com/pyannote/pyannote-audio/issues), please check [pyannote.audio](https://github.com/pyannote/pyannote-audio) Github repository.
```

so i can not using this model for my commercial program?
how can i use it? use v1.1.1? or if i trained my private data, then i can use it?

**Comment by hbredin** [comment]
`pyannote.audio` is MIT-licensed.
Pretrained models on [hf.co](http://hf.co/) are MIT-licensed as well.
You can do anything that the MIT license allows.

**Comment by YooSungHyun** [comment]
@hbredin thx for comment , but why that mention(about commercial enquire) meaning?

**Comment by hbredin** [comment]
Because one might need some help making the most of those models in your commercial products, e.g. through scientific consulting or (better) tech transfer.

**Comment by YooSungHyun** [comment]
Thx that is already too much good for me!
