### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 0

### ISSUE THREAD

**Issue by metheofanis** [pyannote/pyannote-audio#1431]
I get runtime error running the following code:

```
from pyannote.audio import Pipeline
import torch

pipeline = Pipeline.from_pretrained(
        "pyannote/speaker-diarization@2.1",
        use_auth_token='hf_xxxxxx')  # My auth token here

pipeline.to(torch.device('cuda')) # switch to gpu

diarization = pipeline('C:/path/to/file/test3min.mp3')
print(diarization)
```

The full error is:

> RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 80000 but got size 79368 for tensor number 12 in the list.

If I replace the .mp3 file with .wav file, the no error happens. Only for .mp3

**Comment by hc20k** [comment]
Also having this issue, but only on shorter audio samples (< 1hr)
