### ISSUE TITLE
Providing models in SafeTensors format

### ISSUE THREAD

**Issue by ohensf** [pyannote/pyannote-audio#1434]
Hi,
We are currently utilizing models in our project stored in pickle format. However, after exploring the advantages of SafeTensors in terms of improved security we believe that it will provide us with an extra layer of security and protection against potential vulnerabilities. 
[model link](https://huggingface.co/pyannote/segmentation)

We wish to inquire about the plans or timeline, if any, regarding the update of models from pickle to SafeTensors:
* Are there any plans to update the models to SafeTensors?
* If yes, is there a projected timeline for this migration?

**Comment by hbredin** [comment]
There is no such plan as I currently focus on improving speaker diarization accuracy (my main job as an [academic](https://scholar.google.com/citations?user=l1AFL_AAAAAJ&hl=en&oi=ao) research scientist).

That being said, if you are with a company, specific (and useful!) features like this one could easily be added via the local tech transfer office.
