### ISSUE TITLE
A small problem with the Application chapter of the pyannote-pipeline tutorial

### ISSUE THREAD

**Issue by yahcong** [pyannote/pyannote-audio#144]
The default value for subset is development in pyannote-pipeline .
So if run"pyannote-pipeline train --forever ${EXPERIMENT_DIR} AMI.SpeakerDiarization.MixHeadset"as described in the train section,the TRAIN_DIR corresponds to:
"TRAIN_DIR=${EXPERIMENT_DIR}/train/AMI.SpeakerDiarization.MixHeadset.development" not "TRAIN_DIR=${EXPERIMENT_DIR}/train/AMI.SpeakerDiarization.MixHeadset.train" described in  Application chapter of the tutorial

**Comment by hbredin** [comment]
Thanks.  0c7f9cb fixes this and will be part of next release.
