### ISSUE TITLE
Speaker tag across rttm files for fine-tuning

### ISSUE THREAD

**Issue by Kirankumar2609** [pyannote/pyannote-audio#1440]
Should all the rttm files have unique speaker tags?

For eg., If there are three audio files and all of them have two different speakers (within files and across files too). Can the tags be made like (Speaker_00, Speaker_01) for all these three files or should it be (Speaker_00, Speaker_01) for first file, (Speaker_02, Speaker_03) for second file and (Speaker_04, Speaker_05) for third file?

**Comment by ChinmayPatil11** [comment]
It is not necessary to have unique speaker tags across multiple audio files for unique speakers. You can have tags Speaker_00 and Speaker_01 across all audios regardless of them being the same speaker or not.
