### ISSUE TITLE
Which branche should we refer to

### ISSUE THREAD

**Issue by hadware** [pyannote/pyannote-audio#145]
Hello, thanks for all this work, it's really impressive.

I'm trying to follow the tutorial on the github page, however i'm having some troubles. I noticed that the "default" branch on the github repo is `develop`, and looking at the version number in the pipy repo (1.0.1) I think this it's probably still a packaging of the `master` branch.

If I want to reproduce some of your results, would you advise to install from pip and follow the `master` branch's tutorial, or install directly from your repo (using `setup.py`) and follow the `develop` branch's?
Is the develop branch stable enough?

**Comment by hbredin** [comment]
Until `pyannote.audio 2.0` is released, you are better off using the `develop` branch.   
Note that `2.0` will not be that different from the current status of `develop` branch.

**Comment by hadware** [comment]
Ok great, thanks for the quick answer.
