### ISSUE TITLE
Diarization extremely slow

### ISSUE THREAD

**Issue by abdulnim** [pyannote/pyannote-audio#1452]
I was using whisperx for transcription and diarization(pyannote) and the speed was okay. I wanted to use only diarization so switched to using pyannote. for some strange reason, a 50-minute audio was taking 43  minutes. 
it was only then I found out that if I just load FasterWhisper or WhisperX(which is also using Faster Whisper as base) the time of diarization decreases to 3.5 minutes. 
```
#model = WhisperModel("tiny", device="cuda", compute_type='int8')
#model = whisperx.load_model("tiny", device="cuda", compute_type='float16'))
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization",use_auth_token="")
```

if I uncomment any of the model the pipeline just take 3.5 minutes otherwise the same code takes 43 minutes.
I am running the script on A100 GPU

**Comment by hbredin** [comment]
Closing as latest version no longer relies on ONNX runtime which was most likely the culprit.

Please update to [`pyannote.audio 3.1`](https://github.com/pyannote/pyannote-audio/releases/tag/3.1.0) and [`pyannote/speaker-diarization-3.1`](https://hf.co/pyannote/speaker-diarization-3.1) (and open new issues if needed).
