### ISSUE TITLE
Diarization ~50x slower than stated benchmark

### ISSUE THREAD

**Issue by venkr** [pyannote/pyannote-audio#1453]
From the huggingface repo, the stated speed is 2.5% real-time:
```
Real-time factor
Real-time factor is around 2.5% using one Nvidia Tesla V100 SXM2 GPU (for the neural inference part) and one Intel Cascade Lake 6248 CPU (for the clustering part).

In other words, it takes approximately 1.5 minutes to process a one hour conversation.
```

However, from my initial experiments, I've experienced a real-time factor of 122% (processing a 10 minute audio file in 12 minutes). Here's my precise reproduction information:

- Tested via a Runpod Cloud GPU, using an Nvidia V100 FHHL pod (with 8x vCPUs and 23 GB of RAM). I picked this to attempt to be as close to the initial experimental conditions.
- Used a base Torch 2.0.1 image, and then installed the repo via: `pip install -qq https://github.com/pyannote/pyannote-audio/archive/refs/heads/develop.zip`
- Ran the code from the repo README, with the timing code added as follows:

```
from pyannote.audio import Pipeline
import time
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization",
                                    use_auth_token="hf_TOKEN")

t = time.time()
diarization = pipeline("./interview.wav")
print(f"Elapsed {time.time() - t}")

for turn, _, speaker in diarization.itertracks(yield_label=True):
    print(f"start={turn.start:.1f}s stop={turn.end:.1f}s speaker_{speaker}")
```

It seems like this is CPU-bottlenecked, from the Runpod pod stats - for most of when I've checked the CPU has been at close to 100% while the GPUs been idling. I'm currently also running a 39-minute long audio file, I'll update with further information once that's done running.

I hope this info is precise enough to repro it - but please feel free to lmk if there's anything else I can do to help diagnose this.

**Comment by venkr** [comment]
Update, the 38 minute file took about 35 minutes, so a 68% real-time factor, which is better, but still about 30x slower than the benchmark.

**Comment by abdulnim** [comment]
can you try just initializing a whisper model before creating a diarization pipeline?
```
model = WhisperModel("tiny", device="cuda", compute_type='int8')
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization",use_auth_token="hf_TOKEN")
```
this looks very strange but for some reason my speed got very fast with this.

**Comment by sorgfresser** [comment]
It's not cpu bottlenecked, you simply didn't use the gpu i suppose. Can you try adding `.to('cuda')` at the end of 
```python
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization",
                                    use_auth_token="hf_TOKEN")
```
so it's 

```python
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization",
                                    use_auth_token="hf_TOKEN").to("cuda")
```

**Comment by Prakash2403** [comment]
In my case, it was an onnxruntime dependency issue. It was using the CPU for calculating the embedings. Here are the steps I took:

* Ensure that the onnxruntime device is GPU. I had to explicitly install it by running
```
pip install onnxruntime-gpu==1.15 # By default, 1.16 gets installed
``` 
* Ensure that the `onnxruntime` version is `1.15`. Again had to explicitly run 
```
pip install onnxruntime==1.15 # If you follow the instructions mentioned in GitHub repo, it will install 1.16
```

Some helpful debugging tips:
* Attach a hook for monitoring the bottleneck
```
from pyannote.audio.pipelines.utils.hook import ProgressHook
with ProgressHook() as hook:
    diarization = pipeline("audio.wav", hook=hook)
```

This helped me in figuring out that the bottleneck is in embedding step. 

* Here's how you can check the onnxruntime device
```
import onnxruntime as ort
print(ort.get_device())
```

You have to make sure that 
* CuDNN version is >=8.24 and  <=8.7.0 
* CUDA version is >=11.6 and <=11.8 
* onnxruntime version is 1.15 (any patch version will do)
* onnxruntime-gpu version is 1.15 (any patch version will do)

Source: https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements

**Comment by jfsantos** [comment]
I am having a similar issue, however just installing the right version of onnxruntime and onnxruntime-gpu did not help. It is still taking ~15 minutes for a 17 minute long file, probably because I'm on a newer version of CUDA. Any tips on how this could be fixed for different CUDA versions?

**Comment by tomschelsen** [comment]
@Prakash2403 thanks, for which pyannote version is that ? 3.0.1 ?

**Comment by Prakash2403** [comment]
@tomschelsen Yes, the `pyannote.audio` version is `3.0.1`. Here are other pyannote-related packages I am using
```
pyannote.audio==3.0.1
pyannote.core==5.0.0
pyannote.database==5.0.1
pyannote.metrics==3.2.1
pyannote.pipeline==3.0.1
```

**Comment by Prakash2403** [comment]
Hey @jfsantos The CUDA version has to be compatible with the ONNX runtime CUDA version(s). The link [I quoted earlier](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements) specifies which CUDA version is compatible with which ONNX runtime version.

If you don't use the correct combination, the processing shifts to CPU

**Comment by jfsantos** [comment]
Just a heads-up: I'm having an issue accessing pyannote/speaker-diarization-3.1:

```
**Revision Not Found for url: https://huggingface.co/pyannote/speaker-diarization/resolve/3.1/config.yaml.**
```
