### ISSUE TITLE
AttributeError: module 'pyannote.audio.pipelines' has no attribute 'SpeakerSegmentation'

### ISSUE THREAD

**Issue by K2O7I** [pyannote/pyannote-audio#1455]
Hi, I try to use **pyannote/speaker-segmentation** based on https://huggingface.co/pyannote/speaker-segmentation
But got the error:
![image](https://github.com/pyannote/pyannote-audio/assets/75080160/cbc1d200-a089-4355-be27-13a9e03e00d0)

**Comment by jeremy110** [comment]
maybe you can try this https://huggingface.co/pyannote/segmentation
