### ISSUE TITLE
WinError 1314

### ISSUE THREAD

**Issue by elena-theresa-weber** [pyannote/pyannote-audio#1457]
Hey, I am trying to load the pipeline from_pretrained but I get an OSError. 

`OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\Users\\elena\\.cache\\huggingface\\hub\\models--speechbrain--spkrec-ecapa-voxceleb\\snapshots\\5c0be3875fda05e81f3c004ed8c7c06be308de1e\\hyperparams.yaml' -> 'C:\\Users\\elena\\.cache\\torch\\pyannote\\speechbrain\\hyperparams.yaml'`

I know that I can avoid that by running it as an administrator, however, I cannot get these rights. Is there a workaround? 

Thanks!

**Comment by hbredin** [comment]
Closing as `pyannote.audio` does not support Windows.
