### ISSUE TITLE
Planned release of new version

### ISSUE THREAD

**Issue by maltelueken** [pyannote/pyannote-audio#1460]
I was wondering if there is already a planned date/time frame for a new release of pyannote.audio?

I would like to use some of the new features in the development branch in my project. However, I cannot use the development version because I want to publish my project on PyPI but only versions which are also released there.

My current solution is to integrate the code from the development branch directly into my project (see [this](https://github.com/mexca/mexca/pull/95) PR, however, using a new release of pyannote.audio would be much more elegant and sustainable.

**Comment by hbredin** [comment]
No ETA, sorry.

**Comment by maltelueken** [comment]
I will close this since a new version has been released! Thanks!
