### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Firstname Lastename/.pyannote/db.yml'

### ISSUE THREAD

**Issue by monosakkarid** [pyannote/pyannote-audio#147]
Hi

I tried to follow the code in pyannote-audio/tutorials/models/pretrained/, but I get the error: 

Traceback (most recent call last):
  File "C:/Users/Firstname Lastname/PycharmProjects/Main/text.py", line 24, in <module>
    preprocessors = {'audio': FileFinder()}
  File "C:\Users\Firstname Lastename\PycharmProjects\Main\venv\lib\site-packages\pyannote\database\util.py", line 85, in __init__
    with open(config_yml, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Firstname Lastname/.pyannote/db.yml'

I have tried to fix it, but I don't understand what is wrong. I have tried uninstalling and installing packages a couple of times, but it does not seem to work. I  have yml and other required packages installed in my python environment, so I don't think that is was causing the problem. The file pyannote/db.yml is not in my directory, but I have no idea how I can install this at the wanted location. How can I solve this?

Another question I how I can tell python where AMI and MUSAN dataset is located. According to pyannote-audio/tutorials/models/speech_activity_detection/, I should use these commands:

$ cat ~/.pyannote/db.yml | grep AMI
AMI: /path/to/ami/amicorpus/*/audio/{uri}.wav
$ cat ~/.pyannote/db.yml | grep MUSAN
MUSAN: /path/to/musan/{uri}.wav

I have tried them, but I only get errors. I'm also fairly new to bach on windows and have some problems understanding how I can use this. I usually use pip to install packages. 

Thanks for your time!

**Comment by hbredin** [comment]
You have to create this `~/.pyannote/db.yml` file manually -- `pyannote.audio` does not create it for you.

You have to fill it with the `AMI: ...` and `MUSAN: ...` lines manually.
This will tell `pyannote.database` where to look for the dataset.

**Comment by monosakkarid** [comment]
Sorry. How can I create the yml file?

**Comment by hbredin** [comment]
Any text editor will do.
