### ISSUE TITLE
Did any hugging face permissions change with the release of 3.0?

### ISSUE THREAD

**Issue by maxchehab** [pyannote/pyannote-audio#1474]
I'm still using 2.1.1 and this morning around 1am PST started to get Huggingface permission errors.

```python
Pipeline.from_pretrained('pyannote/speaker-diarization', use_auth_token=HF_TOKEN)

Could not download 'pyannote/speaker-diarization' pipeline.
It might be because the pipeline is private or gated so make
sure to authenticate. Visit https://hf.co/settings/tokens to
create your access token and retry with:

   >>> Pipeline.from_pretrained('pyannote/speaker-diarization',
   ...                          use_auth_token=YOUR_AUTH_TOKEN)

If this still does not work, it might be because the pipeline is gated:
visit https://hf.co/pyannote/speaker-diarization to accept the user conditions.
```

I've accepted the user conditions for both the `segmentation` and `speaker-diarization` models and the model was working fine before 1am PST.

Is it possible that permissions were changed in Huggingface that would impact 2.1.1 users?

**Comment by hbredin** [comment]
That is strange. Can you please try again?

**Comment by hbredin** [comment]
At some point, I renamed `pyannote/speaker-diarization` to `pyannote/speaker-diarization-2.1`, thinking that Huggingface would also forward the authorization.

So I have just renamed it back to `pyannote/speaker-diarization`.

cc @julien-c are you aware of this problem with gated models? when you rename it, authorizations seem to be removed?

**Comment by maxchehab** [comment]
Confirmed the pipeline is working now - first successful download at 9:05 am PST.

I suggest we keep the name for now to support 2.1.1

**Comment by remic33** [comment]
Seems to be working now, thanks @hbredin

**Comment by Dannypeja** [comment]
Weirdly I am having this issue when I use whisperX inside Docker.
A few days ago it was working fine, and I think I did not break it..

```
Could not download 'pyannote/speaker-diarization-3.0' pipeline.
It might be because the pipeline is private or gated so make
sure to authenticate. Visit https://hf.co/settings/tokens to
create your access token and retry with:

   >>> Pipeline.from_pretrained('pyannote/speaker-diarization-3.0',
   ...                          use_auth_token=YOUR_AUTH_TOKEN)
   ```
