### ISSUE TITLE
Running without "wespeaker-voxceleb-resnet34-LM"

### ISSUE THREAD

**Issue by doublex** [pyannote/pyannote-audio#1476]
Is it possible to run version 3 without `wespeaker-voxceleb-resnet34-LM`?

**Comment by hbredin** [comment]
You can use any supported speaker embedding in place of `[hbredin/wespeaker-voxceleb-resnet34-LM](https://huggingface.co/hbredin/wespeaker-voxceleb-resnet34-LM)`. 

See [`pyannote.audio.pipelines.speaker_verification.PretrainedSpeakerEmbedding`](https://github.com/pyannote/pyannote-audio/blob/db24eb6c60a26804b1f07a6c2b39055716beb852/pyannote/audio/pipelines/speaker_verification.py#L704-L754) for a list of supported models.

It should be as simple as downloading [this configuration file](https://huggingface.co/pyannote/speaker-diarization-3.0/blob/main/config.yaml), updating [this line](https://huggingface.co/pyannote/speaker-diarization-3.0/blob/main/config.yaml#L7) and [that line](https://huggingface.co/pyannote/speaker-diarization-3.0/blob/f0bab59df2d6364d465d63162abc2fa3b3102c35/config.yaml#L17), and then load it with 

```python
from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("config.yml")
```

Note however that the reason why I chose this speaker embedding for version 3.0.0 is that it is the one that gave me the best result. I'd love to hear the reason why you would like to change it? Research? Any other reasons?

**Comment by doublex** [comment]
@hbredin 
Thanks for your answer.
`onnxruntime` is slow (runs on the CPU). There is a dropin-replacement `onnxruntime-gpu` which uses CUDA - but using `onnxruntime` is cumbersome....

**Comment by hbredin** [comment]
Would switching to `onnxruntime-gpu` solve the issue?
Does it also support CPU?

**Comment by doublex** [comment]
Yes - but it does not support running on the CPU - 😠😠😠😠
My knowledge is limited.

**Comment by hbredin** [comment]
Could you try with this and let me know if that allows to run on GPU on your side?

!pip install https://github.com/pyannote/pyannote-audio/archive/refs/heads/fix/onnxruntime-gpu.zip

All it does is switch from `onnxruntime` to `onnxruntime-gpu` which [does seem](https://colab.research.google.com/drive/1zOzEJjQJpW902j7Q5_5PxGob4E1zn9A9?usp=sharing) to also support CPU

**Comment by hbredin** [comment]
You would not know. You have to tune this threshold.
You could also use [`pyannote/speaker-diarization-2.1`](https://hf.co/pyannote/speaker-diarization-2.1) [configuration file](https://huggingface.co/pyannote/speaker-diarization/blob/main/config.yaml#L15) as a reasonable starting point.

**Comment by hbredin** [comment]
Closing as latest version no longer relies on ONNX `hbredin/wespeaker-voxceleb-resnet34-LM` and this solves the original issue.

Please update to [`pyannote.audio 3.1`](https://github.com/pyannote/pyannote-audio/releases/tag/3.1.0) and [`pyannote/speaker-diarization-3.1`](https://hf.co/pyannote/speaker-diarization-3.1) (and open new issues if needed).
