### ISSUE TITLE
ONNX-ified PyannoteAudioPretrainedSpeakerEmbedding Class

### ISSUE THREAD

**Issue by frznkshn** [pyannote/pyannote-audio#1477]
[Here](https://github.com/pyannote/pyannote-audio/blob/d169fd37708d5f913b71841f84e93dd8cbefd174/pyannote/audio/pipelines/speaker_verification.py#L389), you have added a new class called WeSpeakerPretrainedSpeakerEmbedding, which enables inference through an ONNX-ified embedding model. Wasn't it possible to apply the inference through the ONNX-ified model directly to the [PyannoteAudioPretrainedSpeakerEmbedding class](https://github.com/pyannote/pyannote-audio/blob/d169fd37708d5f913b71841f84e93dd8cbefd174/pyannote/audio/pipelines/speaker_verification.py#L608)?

**Comment by hbredin** [comment]
I don't know how to do that but if you do, contributions are more than welcome!

**Comment by hbredin** [comment]
FYI: https://github.com/pyannote/pyannote-audio/issues/1537

**Comment by hbredin** [comment]
Closing as latest version no longer relies on ONNX runtime. 
Please update to [`pyannote.audio 3.1`](https://github.com/pyannote/pyannote-audio/releases/tag/3.1.0) and [`pyannote/speaker-diarization-3.1`](https://hf.co/pyannote/speaker-diarization-3.1) (and open new issues if needed).
