### ISSUE TITLE
Conda env setup errors

### ISSUE THREAD

**Issue by hadware** [pyannote/pyannote-audio#148]
When running `python setup.py develop` in the pyannote conda env, I get this error:

`error: tqdm 4.28.1 is installed but tqdm>=4.29.1 is required by {'pyannote.pipeline'}`

This is solved by `pip install --upgrade tqdm` then rerunning `python setup.py develop`

I'm sorry if this should have been posted in the pyannote.pipeline repo.

**Comment by hbredin** [comment]
Not sure where this error comes from.  

I believe all `pyannote.*` packages have `tqdm >= ...` dependency requirements. 
Do you have any idea where it could come from? I am confused...

**Comment by hadware** [comment]
Me neither, I tried searching for similar errors but to no avail. Maybe just drop the dependency since tqdm is preinstalled with anaconda?
