### ISSUE TITLE
Increasing embedding batch size in pyannote/speaker-diarization-3.0

### ISSUE THREAD

**Issue by landEpita** [pyannote/pyannote-audio#1486]
Hello, 
I noticed that in version 3.0, the batch size for embeddings is set to 1. Is it possible to increase this batch size to speed up the inference? What other measures can be taken to accelerate the inference process? Thank you.

**Comment by hbredin** [comment]
The way `pyannote/speaker-diarization-3.0` uses `hbredin/wespeaker-voxceleb-resnet34-LM` speaker embedding does not allow batching this part of the inference for now. So, setting `embedding_batch_size` to a higher value will not speed things up...

... unless you switch to `pyannote/embedding` or `speechbrain/spkrec-ecapa-voxceleb`

... in which case you would get slightly lower accuracy.

**Comment by landEpita** [comment]
Thank you for your response. Do you think we can deploy the model with TensorRT? I also noticed in the code that we can use Nvidia's embedding with Nemo. What are your thoughts on Nvidia's model?

**Comment by hbredin** [comment]
> Do you think we can deploy the model with TensorRT? 

I see no reason why you could not. I'd love to hear back from you when/if you try!

> I also noticed in the code that we can use Nvidia's embedding with Nemo.
> What are your thoughts on Nvidia's model?

I only tested NeMo speaker embedding models in the past, and have not played with its diarization capabilities. [My conclusion](https://x.com/hbredin/status/1567806634931490820?s=20) at the time was that NeMo TitaNet was almost on par with speechbrain's embedding. I did not try NeMo recently so there might be a better speaker embedding now...

**Comment by hbredin** [comment]
Closing as it reads like the original questions has been answered.

That being said, I recommend switching to `pyannote.audio` 3.1 and `pyannote/speaker-diarization-3.1` that do support increasing `embedding_batch_size`.

**Comment by v-nhandt21** [comment]
Dear @hbredin , how can I inference audios in batching parallel in pyannote?

'''model.inference({"waveform": audio, "sample_rate": self.sample_rate})'''

And for confirmation, can pyannote support for embedding_batch_size in 3.1?
