### ISSUE TITLE
requirements.txt only accounts for packages >= and does not impose a limitation

### ISSUE THREAD

**Issue by guilhermehge** [pyannote/pyannote-audio#1487]
I've been working with pyannote for a while and from time to time when I build a new image, some packages get updated and my code stops working due to incompatibilities. It just happened with pytorch. [Pytorch just updated to version 2.1.0 (4h ago)](https://pypi.org/project/torch/#history) and, when running my code, I got the following message: `RuntimeError: cuDNN version incompatibility: PyTorch was compiled  against (8, 9, 2) but found runtime version (8, 5, 0). PyTorch already comes bundled with cuDNN. One option to resolving this error is to ensure PyTorch can find the bundled cuDNN.one possibility is that there is a conflicting cuDNN in LD_LIBRARY_PATH.`

The docker image I'm using is this one: `nvidia/cuda:11.7.1-cudnn8-runtime-ubuntu20.04`

As a suggestion, I recommend that pyannote's requirements have a >= and < restrictions, just like faster_whisper does, e.g:
```
ctranslate2>=3.17,<4
tokenizers>=0.13,<0.15
onnxruntime>=1.14,<2
```

In this case, for torch, I believe the requirement should be: 
`torch>=2.0.0,<=2.0.1, since 2.1 can break stuff.

I know that I can lock my environment so the versions do not change, but I believe it would be beneficial to the library in general to fix the versions that it was tested on.

**Comment by hbredin** [comment]
Well, let's say that, in the past, people have complained about `pyannote` being too restrictive on dependency versions... so I am not sure what to do here to content everyone :)


One solution would be to improve continuous integration and unit tests.
Would you like to contribute this to the project?

**Comment by guilhermehge** [comment]
Fair enough. It was just a suggestion anyway. I can just do a `pip freeze` on my side.

"For a while" I meant like a month working with it, not much though, but yes, I can try contributing.
