### ISSUE TITLE
Bug? when using pyannote/speaker-diarization-3.0

### ISSUE THREAD

**Issue by Dpham181** [pyannote/pyannote-audio#1488]
I tried to load three audio files wav with 16k on wishperx. The first two audio files got really good result when doing speaker diarization. But for the last audio file there was two speakers in the conversation with the same tone "man". The 3.0 version did not even distinct the speakers at all somehow. In addition, i went back to pyannote/speaker-diarization@2.1 it worked fine. This could be a bug or something else if anyone here has any slight on this topic

**Comment by hbredin** [comment]
Marking this as `cannot_reproduce` until you provide some example files (and corresponding manual annotations) where this happens.
