### ISSUE TITLE
Yaafe requirements

### ISSUE THREAD

**Issue by hadware** [pyannote/pyannote-audio#149]
Is the Yaafe library still required? It seemed some of the documentation (and Yaml configurations) have been set to use Librosa in its stead. Should I pull request modifications that remove the dependency and usage of this librairy? (which seems like a fairly good idea, since it's not as neatly packaged and documented as librosa).

**Comment by hbredin** [comment]
I'd like to keep the option of using Yaafe for two reasons:
- it is faster than `librosa` (at least for MFCC)
- it allows online feature extraction (which would be useful for a future real-time speaker diarization demo)

**Comment by hadware** [comment]
Ok, thanks for clarifying this. I just wanted to be sure.
