### ISSUE TITLE
Progress Bar for web applications like Dash Plotly, Streamlit

### ISSUE THREAD

**Issue by KobaKhit** [pyannote/pyannote-audio#1490]
**Is your feature request related to a problem? Please describe.**

It is related to this ticket https://github.com/pyannote/pyannote-audio/pull/1185 and would ba an extension of an existing progress bar hook.

**Describe the solution you'd like**

Ability to either pass tqdm instance to hook parameter or return a counter.

**Describe alternatives you've considered**

I tried to stream/redirect stdout and it has limitations.

**Additional context**
Add any other context about the feature request here.

I created this Streamlit app https://speech-to-chat.streamlit.app/ and would like the users to be able to see the progress of the diarization pipeline.

**Comment by hbredin** [comment]
I think the existing hook API already allows to do that.
I agree that this would need a bit of work on your side but it should be possible already.

```python
class YourCustomHook:
    def __init__(self, your_tqdm_progress_bar):
        self.your_tqdm_progress_bar = your_tqdm_progress_bar

    def __call__(
        self,
        step_name: Text,
        step_artifact: Any,
        file: Optional[Mapping] = None,
        total: Optional[int] = None,
        completed: Optional[int] = None,
    ):
        # your custom code goes here

hook = YourCustomHook(...)
pipeline(..., hook=hook)
```

Or maybe I misundertood what you are looking for...

**Comment by KobaKhit** [comment]
This is exactly what I want. Thanks for example. I will try it out.
