### ISSUE TITLE
Tracing a Specific Section of the Code

### ISSUE THREAD

**Issue by frznkshn** [pyannote/pyannote-audio#1492]
For some reason, I am reviewing a portion of your code. In [this line](https://github.com/pyannote/pyannote-audio/blob/2cf14909d6f321d80913af7141c91aa9e659120c/pyannote/audio/core/pipeline.py#L238), you have used a method called 'apply,' which is not defined anywhere in this script. I have concluded that it might inherit from the parent class, i.e., ['_Pipeline.'](https://github.com/pyannote/pyannote-audio/blob/2cf14909d6f321d80913af7141c91aa9e659120c/pyannote/audio/core/pipeline.py#L44C27-L44C27) However, after searching for the relevant function, I couldn't find any trace of the 'apply' method [here](https://github.com/pyannote/pyannote-pipeline/blob/588a2035f0f162301d64f9df7acc607bd20c7f37/pyannote/pipeline/pipeline.py#L45). Could you please help me locate where this method originates?

**Comment by hbredin** [comment]
Each pipeline has its own `apply` method (where the actuall processing happen).
* [VoiceActivityDetection.apply](https://github.com/pyannote/pyannote-audio/blob/ad8a9e9d405343c5a93ccc11b641d0a2e8842a0d/pyannote/audio/pipelines/voice_activity_detection.py#L175)
* [SpeakerDiarization.apply](https://github.com/pyannote/pyannote-audio/blob/ad8a9e9d405343c5a93ccc11b641d0a2e8842a0d/pyannote/audio/pipelines/speaker_diarization.py#L423)
* you got the idea...
