### ISSUE TITLE
Supported Audio Formats and Pre-processing Checks in pyannote

### ISSUE THREAD

**Issue by GolanSolver** [pyannote/pyannote-audio#1495]
Hello pyannote maintainers and community,

I'm currently integrating pyannote into a project and was wondering about its audio compatibility. Specifically:

1. **Supported Formats:** Which audio formats (e.g., .wav, .mp3, .flac, etc.) are supported by pyannote out of the box? I'd like to know so that I can ensure the audio files I use are compatible.

2. **Pre-processing Check:** Does pyannote perform any pre-checks on the audio files before processing them? For instance, if an unsupported or corrupted audio file is passed, does pyannote identify this and raise an error or warning?

Having clarity on these aspects will be very helpful as I look to integrate pyannote more seamlessly into my workflows.

Thank you for your assistance and for the great work on this tool!

Best regards,

**Comment by hbredin** [comment]
> Which audio formats (e.g., .wav, .mp3, .flac, etc.) are supported by pyannote out of the box? I'd like to know so that I can ensure the audio files I use are compatible.

`pyannote.audio` relies on `torchaudio` internally.
So, anything supported by `torchaudio` should be supported by `pyannote.audio`.

> Does pyannote perform any pre-checks on the audio files before processing them? For instance, if an unsupported or corrupted audio file is passed, does pyannote identify this and raise an error or warning?

Not really, no.

Note that every `pyannote` pipeline also supports pre-loaded audio files using the following syntax:

```python
import torchaudio
waveform, sample_rate = torchaudio.load(AUDIO_FILE)
# type(waveform) = torch.Tensor
# waveform.shape = (1, num_samples)
# waveform.dtype = torch.float32

output = pipeline({"waveform": waveform, "sample_rate": sample_rate})
```

With the above, *you* can take care of checking that everything went smoothly when loading the audio file.
