### ISSUE TITLE
How to save the plot as a jpg and predicted rttms as a file for each test file?

### ISSUE THREAD

**Issue by sucv** [pyannote/pyannote-audio#1497]
Dear author, I have a question about how to save the plot and prediction when I called the code snippet below. Seems that I cannot find any example from the ipynb tutorials. Thanks in advance!

```python
    for file in dataset.test():
        # apply pretrained pipeline
        file["pretrained pipeline"] = pretrained_pipeline(file)

        # evaluate its performance
        metric(file["annotation"], file["pretrained pipeline"], uem=file["annotated"])
```

**Comment by hbredin** [comment]
There is no easy way to save plots. You would have to dive into [`pyannote.core` code](https://github.com/pyannote/pyannote-core/blob/13a43c2cd3a297591cbaac4625920479cdcebe6a/pyannote/core/notebook.py#L300).

Saving `Annotation` instances to RTTM file can be done with [`Annotation.write_rttm`](http://pyannote.github.io/pyannote-core/reference.html?highlight=write_rttm#pyannote.core.Annotation.write_rttm)

**Comment by Approximetal** [comment]
> There is no easy way to save plots. You would have to dive into [`pyannote.core` code](https://github.com/pyannote/pyannote-core/blob/13a43c2cd3a297591cbaac4625920479cdcebe6a/pyannote/core/notebook.py#L300).
> 
> Saving `Annotation` instances to RTTM file can be done with [`Annotation.write_rttm`](http://pyannote.github.io/pyannote-core/reference.html?highlight=write_rttm#pyannote.core.Annotation.write_rttm)

Sometimes different speakers seem to be plotted with the same color, how can I change that?
![image](https://github.com/pyannote/pyannote-audio/assets/25227045/8bf02cda-7aa9-493d-9eca-98054dc5e99c)

**Comment by alephpi** [comment]
well I think saving plot is really a necessary functionality. if we can export the annotation object as a matplotlib plot, it will also be easier to modify the plots.
