### ISSUE TITLE
Removing the anaconda parameter for the install

### ISSUE THREAD

**Issue by hadware** [pyannote/pyannote-audio#150]
Conda's a great choice as a virtual environnement for python, but requiring the anaconda package is, I think, useless. It preinstalls way too many packages, and you already took the time to specify all your dependencies in each of your repos.

Worse, on two of my machines, the pip/conda packages was the cause of a binary mess that caused this pretty error:

`Importerror:  /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found`

I fixed it by reinstalling my conda environnement without installing anaconda. ( `conda create env --name pyannote python3.6`).
Moreover, this type of install prevented the former error reported in #148 .

As a side note, maybe you should add the install line for yaafe in the installation tutorial : 

`conda install -c conda-forge yaafe`

I can pull-request all those propositions if you validate them.

**Comment by hbredin** [comment]
We could also not mention `conda` at all right and simply stick with `pip install pyannote.audio`.
Except maybe for the `yaafe` part...

**Comment by hadware** [comment]
In theory yeah it should work find without conda, except for yaafe (without at least some troubles).

**Comment by hbredin** [comment]
I did remove the `chocolate` dependency in favor of the new `pyannote.pipeline` package (based on `optuna`, which is easier to install and seems better maintained than `chocolate`).

Coming back to your original pull request proposal: yes, we can skip the `anaconda` part in the installation instructions. Please go ahead 👍

**Comment by hadware** [comment]
![image](https://user-images.githubusercontent.com/5477031/52798973-44812080-3079-11e9-8614-3a2f49625462.png)

**Comment by hadware** [comment]
This is fixed by #153
