### ISSUE TITLE
Shared speaker embeddings across batch of audio streams.

### ISSUE THREAD

**Issue by FredHaa** [pyannote/pyannote-audio#1502]
**Is your feature request related to a problem? Please describe.**
I have a use case where i need to diarize a file containing multiple tracks, where each track corresponds to a separate microphone which all record concurrently. If I run each track individually through pyannote, the speaker IDs I cannot trust that speaker IDs correlates to the same person.

My current solution is to concatenate tracks, run them through pyannote as a single stream, and then fixing the speaker timings afterwards.

**Describe the solution you'd like**
The possibility to input a batch of streams. Each stream would be segmented individually, and then clustered using the same embedding space.

**Comment by hbredin** [comment]
> I have a use case where i need to diarize a file containing multiple tracks, where each track corresponds to a separate microphone which all record concurrently. 

Can you please clarify your use case?
Are those microphones in the same room? recording the same conversation? Are they synchronized?

**Comment by hbredin** [comment]
Sorry for the delay. 

I think we should sit together and talk for me to really understand and help you with your use case.
I am [available for contracting](https://herve.niderb.fr/consulting) if this is something you'd consider

**Comment by FredHaa** [comment]
Well, my hack works fine, so not much sense in paying for consulting there. This feature request was mostly about that the interface would be nicer if you could input a batch, and I believe it would be beneficial in a vast number of use cases, not just my own.

However, I am interested in hearing about the premium models, so I'll send an email.
