### ISSUE TITLE
ModuleNotFoundError: No module named 'pyannote.core'

### ISSUE THREAD

**Issue by Heavenbest** [pyannote/pyannote-audio#1506]
When I execute the following code I get an error message。

from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("./models")

# send pipeline to GPU (when available)
import torch
pipeline.to(torch.device("cuda"))

# apply pretrained pipeline
diarization = pipeline("008-53.500-57.050.wav")

# print the result
for turn, _, speaker in diarization.itertracks(yield_label=True):
    print(f"start={turn.start:.1f}s stop={turn.end:.1f}s speaker_{speaker}")

error message : 

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from pyannote.audio import Pipeline
  File "/data/pengshan/TYedu_202308/pyannote-audio/pyannote/audio/__init__.py", line 29, in <module>
    from .core.inference import Inference
  File "/data/pengshan/TYedu_202308/pyannote-audio/pyannote/audio/core/inference.py", line 33, in <module>
    from pyannote.core import Segment, SlidingWindow, SlidingWindowFeature
ModuleNotFoundError: No module named 'pyannote.core'

**Comment by arrrrr3186** [comment]
How did you resolved it?

**Comment by ObstcalsShi** [comment]
How did you resolved it?
