### ISSUE TITLE
Error when calling local model，（speaker-diarization-3.0）

### ISSUE THREAD

**Issue by Heavenbest** [pyannote/pyannote-audio#1508]
When I execute the following code I get an error message。

from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("./models/config.yaml")

# send pipeline to GPU (when available)
import torch
pipeline.to(torch.device("cuda"))

# apply pretrained pipeline
diarization = pipeline("test.wav")

![image](https://github.com/pyannote/pyannote-audio/assets/22997054/8b20ad93-f279-4a48-aefb-c6d753adc372)

I have downloaded the required model and saved it locally for calling. The specific directory is as follows. When running, an error is reported. The config.yaml is as follows.

![image](https://github.com/pyannote/pyannote-audio/assets/22997054/f422016a-4791-4931-bb6f-a84ac264cc2e)

**Comment by ColtonBehannon** [comment]
Same issue being faced here. There exists another thread (https://github.com/pyannote/pyannote-audio/issues/1410) where someone seems to have found a way around it but it's not straightforward. The method you followed here seems like it should work as it follows the directions in the tutorial for VAD (https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/applying_a_pipeline.ipynb).

**Comment by hbredin** [comment]
Renaming `speaker-embedding.onnx` into something that contains the `wespeaker` string should do the trick (e.g. `wespeaker-embedding.onnx`) .

**Comment by Heavenbest** [comment]
thanks for your reply.  @ColtonBehannon ..
When I verify based on the example of (https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/applying_a_pipeline.ipynb), the error message is as follows:
![image](https://github.com/pyannote/pyannote-audio/assets/22997054/0d7b2c6c-4aa7-4839-8b9b-e0f19c238e74)
I am running it on Google colab, can you help me find out the reason? Thanks

**Comment by Heavenbest** [comment]
@hbredin thanks ,after changing the model name according to the method you mentioned, the program can run normally. Thank you very much.

**Comment by hbredin** [comment]
FYI: https://github.com/pyannote/pyannote-audio/issues/1537

**Comment by hbredin** [comment]
Latest version no longer relies on ONNX runtime. 
Please update to [`pyannote.audio 3.1`](https://github.com/pyannote/pyannote-audio/releases/tag/3.1.0) and [`pyannote/speaker-diarization-3.1`](https://hf.co/pyannote/speaker-diarization-3.1) (and open new issues if needed).
