### ISSUE TITLE
issue while training speech_activity_detection

### ISSUE THREAD

**Issue by rohithkodali** [pyannote/pyannote-audio#151]
getting the follwing error when i try to train the speech activity detection models

pyannote-speech-detection train --gpu --to=1000 ${EXPERIMENT_DIR} AMI.SpeakerDiarization.MixHeadset
database is  /home/rohit/.pyannote/db.yml
Traceback (most recent call last):
  File "/home/rohit/anaconda3/envs/pyannote/bin/pyannote-speech-detection", line 11, in <module>
    sys.exit(main())
  File "/home/rohit/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/applications/speech_detection.py", line 351, in main
    application = SpeechActivityDetection(experiment_dir, db_yml=db_yml)
  File "/home/rohit/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/applications/speech_detection.py", line 204, in __init__
    self.model_ = Architecture(n_features, n_classes,**self.config_['architecture'].get('params', {}))
TypeError: __init__() got an unexpected keyword argument 'instance_normalize'

**Comment by hbredin** [comment]
I just update the README to warn that tutorials are based on the `develop` branch.
Please install from source:

```bash
$ git clone https://github.com/pyannote/pyannote-audio.git
$ cd pyannote-audio
$ pip install .
```

**Comment by rnunziata** [comment]
Thanks...I saw the devel branch in the drop down on the left and assumed that it meant that the clone url on the right was the devel branch .... it is not. you have to do a git checkout.
Thank you for this update.

**Comment by benjisympa** [comment]
I have used also `conda install -c anaconda cmake` to compile lib on a condo environment.
