### ISSUE TITLE
Small typo in your HuggingFace README

### ISSUE THREAD

**Issue by carlos-aguayo** [pyannote/pyannote-audio#1513]
https://huggingface.co/pyannote/embedding/blob/main/README.md?code=true#L67

That line should be
```
inference = Inference(model, window="whole", device=torch.device("cuda"))
```
instead of
```
inference = Inference(model, window="whole", device="cuda")
```

**Comment by hbredin** [comment]
Thanks. [Fixed!](https://huggingface.co/pyannote/embedding/blob/main/README.md#running-on-gpu)
