### ISSUE TITLE
Failed to run get_speech_segments due to RuntimeError: Failed to decode audio

### ISSUE THREAD

**Issue by reubinoff** [pyannote/pyannote-audio#1515]
after upgrading from version 2.1.1 to 3.0.0 (failed to install 3.0.1 due to [bug](https://github.com/pyannote/pyannote-audio/issues/1505)) I get an error when running get_speech_segments.
my code:
```
path = self.resample_to_expected_sample_rate(file_path, self.EXPECTED_VAD_SAMPLE_RATE)
check_vad = VAD.from_hparams(source="speechbrain/vad-crdnn-libriparty")
boundaries = check_vad.get_speech_segments(audio_file=path, speech_th=self.speech_threshold, double_check=True)
```

in version 3.0.0 I got the error:

> 9.641 Resampling to new sample rate 16000 to path: /tmp/tmpslw9o6ji/c2344d82-f11a-45a9-8056-85139b03eb44.wav
> (…)libriparty/resolve/main/hyperparams.yaml: 100%|██████████| 2.29k/2.29k [00:00<00:00, 8.08MB/s]
> (…)crdnn-libriparty/resolve/main/model.ckpt: 100%|██████████| 453k/453k [00:00<00:00, 28.0MB/s]
> (…)briparty/resolve/main/mean_var_norm.ckpt: 100%|██████████| 1.06k/1.06k [00:00<00:00, 7.04MB/s]
> 11.42 Traceback (most recent call last):
> 11.42   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
> 11.42     return _run_code(code, main_globals, None,
> 11.42   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
> 11.42     exec(code, run_globals)
> 11.42   File "/app/till/app.py", line 120, in <module>
> 11.42     main(job_data_from_env)
> 11.42   File "/app/till/utils.py", line 9, in wrapper
> 11.42     result = func(*args, **kwargs)
> 11.42   File "/app/till/app.py", line 86, in main
> 11.42     result = _test_classification(file_index_path, test_file_path)
> 11.42   File "/app/till/app.py", line 34, in _test_classification
> 11.42     vad = ap.voice_activity_check(test_file)
> 11.42   File "/app/till/utils.py", line 9, in wrapper
> 11.42     result = func(*args, **kwargs)
> 11.42   File "/app/till/audio_helper.py", line 33, in voice_activity_check
> 11.42     boundaries = check_vad.get_speech_segments(audio_file=path, speech_th=self.speech_threshold, double_check=True)
> 11.42   File "/usr/local/lib/python3.10/site-packages/speechbrain/pretrained/interfaces.py", line 2045, in get_speech_segments
> 11.42     prob_chunks = self.get_speech_prob_file(
> 11.42   File "/usr/local/lib/python3.10/site-packages/speechbrain/pretrained/interfaces.py", line 1241, in get_speech_prob_file
> 11.42     large_chunk, fs = torchaudio.load(
> 11.42   File "/usr/local/lib/python3.10/site-packages/torchaudio/_backend/utils.py", line 203, in load
> 11.42     return backend.load(uri, frame_offset, num_frames, normalize, channels_first, format, buffer_size)
> 11.42   File "/usr/local/lib/python3.10/site-packages/torchaudio/_backend/ffmpeg.py", line 334, in load
> 11.42     return load_audio(os.path.normpath(uri), frame_offset, num_frames, normalize, channels_first, format)
> 11.42   File "/usr/local/lib/python3.10/site-packages/torchaudio/_backend/ffmpeg.py", line 100, in load_audio
> 11.42     return torch.ops.torchaudio.compat_load(src, format, filter, channels_first)
> 11.42   File "/usr/local/lib/python3.10/site-packages/torch/_ops.py", line 692, in __call__
> 11.42     return self._op(*args, **kwargs or {})
> 11.42 RuntimeError: Failed to decode audio.

**Comment by hbredin** [comment]
Wrong repo? Did you mean to open a [`speechbrain`](https://github.com/speechbrain/speechbrain) issue?
