### ISSUE TITLE
issue in using pretrained models

### ISSUE THREAD

**Issue by rohithkodali** [pyannote/pyannote-audio#152]
hi i have been following the pretrained models tutorial but i have an issue with loading the models. it says

SAD_MODEL = (/pyannote/pyannote-audio/tutorials/models/speech_activity_detection/train/'
'AMI.SpeakerDiarization.MixHeadset.train/weights/0280.pt')
  File "/home/rohit/PycharmProjects/pyannote/temp.py", line 31, in <module>
    sad = SequenceLabeling(model=SAD_MODEL,feature_extraction=mfcc_extractor)
  File "/home/rohit/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/labeling/extraction.py", line 76, in __init__
    self.model = model.eval().to(self.device)
AttributeError: 'str' object has no attribute 'eval'

is there any way to load the model or am i doing something wrong in loading

**Comment by hbredin** [comment]
I think this is the same issue as #151 .
You need to use the `develop` branch of `pyannote.audio`.
