### ISSUE TITLE
How to train the model in the article  pyannote.audio speaker diarization pipeline at VoxSRC 2023?

### ISSUE THREAD

**Issue by zuowanbushiwo** [pyannote/pyannote-audio#1521]
Hi  Herve
The benchmark results from this article are much better than those from huggingface. How should we train the `#9 model `in the article?

article：
![image](https://github.com/pyannote/pyannote-audio/assets/3354428/ff59ea1f-1fdc-42f9-885c-b33a44097abb)

huggingface：
![image](https://github.com/pyannote/pyannote-audio/assets/3354428/c8633b3f-3386-4af2-8008-9a3b1316e558)

**Comment by hbredin** [comment]
The paper reports DERs with 250ms forgiveness collar (official VoxSRC evaluation metric). 

The Hugginface page reports DERs without forgiveness collar (which I strongly believe the community should use)

More details about evaluation metrics can be found in my talk (around 00:16:30): https://umotion.univ-lemans.fr/video/9513-speech-segmentation-and-speaker-diarization/
