### ISSUE TITLE
These voice can not split correctly

### ISSUE THREAD

**Issue by lucasjinreal** [pyannote/pyannote-audio#1524]
[asr_res_240-243_1_audio.zip](https://github.com/pyannote/pyannote-audio/files/13236093/asr_res_240-243_1_audio.zip)

the output time and label 

```
start=0.0s stop=2.4s speaker_SPEAKER_00
start=0.4s stop=1.4s speaker_SPEAKER_01
```

but the speaker are clearly 2 speaker first and later, how to precisely get the splitter time in the middle?

**Comment by hbredin** [comment]
Without providing details about the code you tried, it is kind of difficult to tell.
Here are my 2 cents applying the pretrained `pyannote/segmentation-3.0` model: it looks like it does manage to do the job...

```python
AUDIO = "asr_res_240-243_1_audio.mp3"

from pyannote.audio import Audio
io = Audio(mono="downmix", sample_rate=16000)
waveform, sample_rate = io(AUDIO)
audio = {"waveform": waveform, "sample_rate": sample_rate}

from pyannote.audio import Inference
inference = Inference("pyannote/segmentation-3.0", window="whole")
prediction = inference(audio)

from matplotlib import pyplot as plt
plt.plot(prediction)
plt.legend(['speaker#1', 'speaker#2', 'speaker#3'])
```

![output](https://github.com/pyannote/pyannote-audio/assets/1080837/dbe1ca80-112c-46e4-a9bf-213a6c90af18)

**Comment by lucasjinreal** [comment]
@hbredin  hi, the audio acutially only have 2 people, the first period is person1, and rest is a man voice.

the cliff of speaker3 seems detected the later man voice, but how can i tell, (i actually just need split 2 person), this cliff is exactly what I want?
