### ISSUE TITLE
Hello， I get an Error with the feature extraction method

### ISSUE THREAD

**Issue by painshine** [pyannote/pyannote-audio#1526]
About the feature embedding：https://huggingface.co/hbredin/wespeaker-voxceleb-resnet34-LM
When I download the model file and use it as follow:
get_embedding = PretrainedSpeakerEmbedding("./speaker-embedding.onnx")

I get an Error:
/usr/local/lib/python3.10/dist-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
1244 "functionality.")
1245
-> 1246 magic_number = pickle_module.load(f, **pickle_load_args)
1247 if magic_number != MAGIC_NUMBER:
1248 raise RuntimeError("Invalid magic number; corrupt file?")

UnpicklingError: invalid load key, '\x08'

How can I fix it? Thank you sincerely!

**Comment by hbredin** [comment]
FYI: https://github.com/pyannote/pyannote-audio/issues/1537

**Comment by hbredin** [comment]
Closing as latest version no longer relies on ONNX runtime. 
Please update to [`pyannote.audio 3.1`](https://github.com/pyannote/pyannote-audio/releases/tag/3.1.0) and [`pyannote/speaker-diarization-3.1`](https://hf.co/pyannote/speaker-diarization-3.1) (and open new issues if needed).
