### ISSUE TITLE
Can I simplify Inference  in this case?

### ISSUE THREAD

**Issue by zuowanbushiwo** [pyannote/pyannote-audio#1527]
Hi  hbredin

Thanks your open source! I read the article pyannote.audio speaker diarization pipeline at VoxSRC 2023. The entire speaker diarization pipeline contains 3 parts: local end-to-end neural speaker segmentation with 10-seconds windows with 1-second stride，neural speaker embedding of each speaker of each window, and agglomerative hierarchical clustering.

If I have a 2-minute audio clip, and I'm sure there are only 3 speakers in the entire clip,  Can I remove the speaker embedding and clustering,  only use one global  end-to-end neural speaker segmentation using  the entire speech as input?  Will there be any speaker confusion problem if I do this?  Or are there other adverse effects?

Thanks！

**Comment by hbredin** [comment]
> If I have a 2-minute audio clip, and I'm sure there are only 3 speakers in the entire clip, Can I remove the speaker embedding and clustering, only use one global end-to-end neural speaker segmentation using the entire speech as input? Will there be any speaker confusion problem if I do this? Or are there other adverse effects?

I'd suggest you try and report back :-)

**Comment by hbredin** [comment]
Closing as it reads like the initial question has been anwered.
