### ISSUE TITLE
Pyannote.speaker_diarization giving 401 Client Error

### ISSUE THREAD

**Issue by zuowanbushiwo** [pyannote/pyannote-audio#1530]
I’ve accepted the terms for all of pyannote’s models and still getting this error，why ? How to fix? Thanks!

![image](https://github.com/pyannote/pyannote-audio/assets/3354428/ebf23365-5cf2-4127-af86-7e0a181434b1)

**Comment by hbredin** [comment]
I'd suggest you ask Huggingface directly as this interface is (I think) out of my control.
cc @Vaibhavs10 @julien-c

**Comment by Vaibhavs10** [comment]
Thanks for the tag here @hbredin. We're looking into this, will ping here as soon as I have an update! 🤗

**Comment by b4zz4** [comment]
Same problem without solution

```
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/pyannote/speaker-diarization/resolve/2.1/config.yaml (Request ID: Root=1-690a4e63-31a8816374cdf96b7724b682;7674bcbe-b4bc-4b78-8b40-c6bad95dfb8e)
```
