### ISSUE TITLE
Pipeline always runs on CPU

### ISSUE THREAD

**Issue by mauricekleine** [pyannote/pyannote-audio#1536]
No matter which device I pass to `pipeline.to`, the pipeline always runs on the CPU. This happens on my Macbook (`torch.device("mps")`) as well as on Runpod with a Nvidia H100 (`torch.device("cuda:0")`).

In my code, I create a 'diarizator' using pyannotate and a 'transcriber' using Whisper. The instantiation of both is pretty much the same. The transcriber correctly runs on the GPU, but the diarizator keeps using the CPU. See code below:

```python
def get_diarizator(auth_token):
    device = (
        torch.device("cuda:0") if torch.cuda.is_available() else torch.device("mps")
    )
    model_id = "pyannote/speaker-diarization-3.0"

    pipeline = Pipeline.from_pretrained(
        model_id,
        use_auth_token=auth_token,
    )

    pipeline.to(device)

    return pipeline

def get_transcriber():
    device = (
        torch.device("cuda:0") if torch.cuda.is_available() else torch.device("mps")
    )
    model_id = "openai/whisper-large-v3"

    processor = WhisperProcessor.from_pretrained(
        model_id, language="dutch", task="transcribe"
    )

    return pipeline(
        "automatic-speech-recognition",
        chunk_length_s=30,
        device=device,
        feature_extractor=processor.feature_extractor,
        generate_kwargs={"language": "Dutch", "task": "transcribe"},
        model=model_id
        tokenizer=processor.tokenizer,
    )
```

How do I get the diarization pipeline to honor the device passed to `pipeline.to`?

**Comment by rarejobtechYuma** [comment]
I have the same issue on google colab, GPU is in used, but doesn't seems work properly.
2 weeks ago it took me less then 2 min to run on my test data, now it take more than an hour.

**Comment by hbredin** [comment]
Closing as latest version no longer relies on ONNX runtime. 
Please update to [`pyannote.audio 3.1`](https://github.com/pyannote/pyannote-audio/releases/tag/3.1.0) and [`pyannote/speaker-diarization-3.1`](https://hf.co/pyannote/speaker-diarization-3.1) (and open new issues if needed).

**Comment by mauricekleine** [comment]
@hbredin I can confirm, everything is working as expected. Thanks!

**Comment by bluusun** [comment]
Works only on CPU for me using the sample code. CPU is at 100%. Using pyannote/speaker-diarization-3.1 and latest version from pip. Other code has no problems using my cuda. Python also shows it.

**Comment by bluusun** [comment]
Using device: cuda
torchvision is not available - cannot save figures

----

import torch
from pyannote.audio import Pipeline

# Check if CUDA is available and set the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Initialize the pipeline with a specific pretrained model
pipeline = Pipeline.from_pretrained(
    "pyannote/speaker-diarization-3.1",
    use_auth_token="hf_"
)

# Load the pipeline onto the device
pipeline.to(device)

# Load your audio file and apply the diarization pipeline
diarization = pipeline("output.wav")

# Print the diarization results
for turn, _, speaker in diarization.itertracks(yield_label=True):
    start = turn.start
    end = turn.end
    print(f"Start: {start:.1f}s, End: {end:.1f}s, Speaker: {speaker}")

nvidia-smi
Tue Dec 12 22:39:00 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:02:00.0  On |                  N/A |
| 30%   51C    P2   175W / 350W |   2673MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|

 1133 root      20   0   18.6g   5.0g 853324 S 431.6   2.0   9:55.34 python3 test.py
