### ISSUE TITLE
Pre-trained models make the tutorial instruction fail

### ISSUE THREAD

**Issue by hadware** [pyannote/pyannote-audio#154]
This is pretty simple: the pretrained models `.pt` files make the command

`pyannote-speech-detection train --from=0 --to=1000 ${EXPERIMENT_DIR} AMI.SpeakerDiarization.MixHeadset` 

fail. I've thoroughly tried to tweak the command's options (adding `--from` option), but i coulnd't get it to run to 1000 epochs without some kind of error.

**Comment by hbredin** [comment]
Are you referring to the following error message?

```bash
FileExistsError: [Errno 17] File exists: 'tutorials/models/speech_activity_detection/train/AMI.SpeakerDiarization.MixHeadset.train/weights'
```

If so, I will catch the error and make it clear that the directory should be removed first...

**Comment by hbredin** [comment]
Since e0b73c1, you now get a more explicit error message:

```bash
$ pyannote-speech-detection train [REDACTED]/tutorials/models/speech_activity_detection AMI.SpeakerDiarization.MixHeadset
You are about to overwrite pretrained models in "[REDACTED]/tutorials/models/speech_activity_detection/train/AMI.SpeakerDiarization.MixHeadset.train/weights" directory. If you want to train a new model from scratch, first (backup and) remove the directory.
```

Does this solve this issue?

**Comment by hadware** [comment]
Yes, that does it. Maybe we could add an option to overwrite all previous weights when running the train script?

**Comment by hbredin** [comment]
Yes, we could. Not sure it is that helpful though... 
I'd rather have users remove the directory manually to hold them responsible.

Closing as I think the initial issue is solved.
