### ISSUE TITLE
Overlap in the audio

### ISSUE THREAD

**Issue by YashThakran** [pyannote/pyannote-audio#1543]
Hi, I have been using pyaanote for speaker diarization, and the results seem to be mostly good. However, I have observed some issues when there is an overlap of multiple speakers in the audio, pyannote labels it as any of the single speakers. 

Is there any way to fix this problem or improve performance in case of overlaps?

I have tried embedding_exclude_overlap param but it doesn't help.

**Comment by hbredin** [comment]
Your best guess is to finetune the segmentation model on your own data.
See [this tutorial](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/training_a_model.ipynb).

Also, I'd be happy to have a look at a short excerpt of your file where this does not work as expected.
