### ISSUE TITLE
TypeError: numpy() takes no keyword arguments

### ISSUE THREAD

**Issue by magicse** [pyannote/pyannote-audio#1548]
```
import os
import torch
from pyannote.audio import Pipeline, Model
from pyannote.audio.pipelines.utils.hook import ProgressHook

pipeline = Pipeline.from_pretrained(
   "pyannote/speaker-diarization-3.0"
)
pipeline.to(torch.device("cpu"))

with ProgressHook() as hook:
    diarization = pipeline("Media/denoised_vocals.wav", hook=hook)

# print the result
for turn, _, speaker in diarization.itertracks(yield_label=True):
    print(f"start={turn.start:.1f}s stop={turn.end:.1f}s speaker_{speaker}")
```
speaker-embedding.onnx: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 26.5M/26.5M [00:28<00:00, 939kB/s]
segmentation     ---------------------------------------- 100% 0:00:09
speaker_counting ---------------------------------------- 100% 0:00:00
embeddings       ----------------------------------------   1% -:--:--
Traceback (most recent call last):
  File "Z:\test_diarization.py", line 38, in <module>
    diarization = pipeline("Media/denoised_vocals.wav", hook=hook)
  File "C:\Python38\lib\site-packages\pyannote\audio\core\pipeline.py", line 325, in __call__
    return self.apply(file, **kwargs)
  File "C:\Python38\lib\site-packages\pyannote\audio\pipelines\speaker_diarization.py", line 515, in apply
    embeddings = self.get_embeddings(
  File "C:\Python38\lib\site-packages\pyannote\audio\pipelines\speaker_diarization.py", line 347, in get_embeddings
    embedding_batch: np.ndarray = self._embedding(
  File "C:\Python38\lib\site-packages\pyannote\audio\pipelines\speaker_verification.py", line 610, in __call__
    input_feed={"feats": masked_feature.numpy(force=True)[None]},
TypeError: numpy() takes no keyword arguments

**Comment by hbredin** [comment]
`numpy()` does take `force` keyword argument [since torch 1.13](https://pytorch.org/docs/1.13/generated/torch.Tensor.numpy.html#torch-tensor-numpy).

`pyannote.audio` [requires `torch >= 2.0.0`](https://github.com/pyannote/pyannote-audio/blob/8b975bb5575121d034e12e94405625df69eefb97/requirements.txt#L16).

You need to update `torch`.
