### ISSUE TITLE
Running pyannote.audio on Raspberry Pi 5

### ISSUE THREAD

**Issue by swm35** [pyannote/pyannote-audio#1555]
Dear @hbredin

Do you know if anyone has got pyannote.audio working on a Raspberry Pi 5?  I have been trying to get diart + Whisper running to create live captions distinguishing speakers, but keep getting a "Segmentation fault" error message.  After some discussion with @juanmc2005 on the diart GitHub for issue 200 (https://github.com/juanmc2005/diart/issues/200), we pinpointed the problem to the line that runs the pyannote/segmentation model.

It is not clear whether it is a memory overload issue or something else.  My RPi5 has 8GB RAM, which I thought would be easily enough for the 1.48 million parameters in this pyannote.audio model.  Searching through the issues on the pyannote.audio GitHub site, I see a couple of references to segmentation faults, though those issues seem rather different to the ones here.

Any thoughts would be greatly appreciated.

Kind regards

Simon

**Comment by hbredin** [comment]
Most likely a [pytorch problem](https://github.com/pytorch/pytorch/issues/97226).

**Comment by swm35** [comment]
Thank you @hbredin.  I tried a number of pytorch packages on that link without success, then I noticed that @juanmc2005 updated the diart environment.yml file and it is working now using that.  The only change I can see in that environment.yml file is to switch from python 3.8 to 3.10.  Not sure why python 3.10 is necessary, but I am pleased it is working on my RPi5 now.

**Comment by csukuangfj** [comment]
@swm35 

I suggest that you have a look at [sherpa-onnx](https://github.com/k2-fsa/sherpa-onnx).

It provides C++ APIs for speaker diarization using speaker segmentation models from pyannote-audio.

It also supports whisper for speech recognition.

You can run sherpa-onnx on Raspberry Pi.
