### ISSUE TITLE
Audio file formats – nothing other than .wav supported on HF

### ISSUE THREAD

**Issue by rkapur102** [pyannote/pyannote-audio#1559]
I'm having issues in multiple contexts (SpeechBox pipeline, running Pyannote through HF individually as per the documentation samples) with diarization on .m4a, .mp4, and .mp3 files. .wav files work just fine, but in some contexts I do not have the storage or bandwidth to convert them due to resource constraints. Is this a known issue / what is the workaround? Or is anything other than .wav simply unpredictable in terms of performance?

**Comment by hbredin** [comment]
`pyannote` relies on `torchaudio` to read audio files.
If `torchaudio.load` can load a file, it is supported.
If `torchaudio.load` cannot load a file, it is not supported.
