### ISSUE TITLE
For the great results in the ``premium`` column on the benchmark table

### ISSUE THREAD

**Issue by JiJiJiang** [pyannote/pyannote-audio#1561]
Hello,

Thanks very much for your wonderful open-source work on speaker diarization.
I am just curious about the ``premium`` column on the [benchmark](https://github.com/pyannote/pyannote-audio#benchmark) table. The results are amazing and the running speed is fast. (As you mention, it takes less than 1m00s to process 1h of audio)
What is different between the ``premium`` pipeline and the [v3.1](https://hf.co/pyannote/speaker-diarization-3.1) pipeline? Are there any post-processing skills or better models are finetuned?  Hope to get your reply, thanks!

Best wishes,
Hongji Wang

**Comment by hbredin** [comment]
Unfortunately, I cannot say much about this pipeline as this is still a work in progress that has not yet been published.

That being said, I'd  be happy to run the pipeline myself on one or two sample files of yours if you are interested.

**Comment by JiJiJiang** [comment]
Understand... Thank you for your answer. Hope it published soon.
