### ISSUE TITLE
Speaking and singing segmentation

### ISSUE THREAD

**Issue by SetoKaiba** [pyannote/pyannote-audio#1564]
**Is your feature request related to a problem? Please describe.**
I want to identify the voice is speaking or singing.

**Describe the solution you'd like**
Additional tag for speaking or speech for speaker-diarization.

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by hbredin** [comment]
You can definitely use `pyannote.audio` to train such a model.
See [this tutorial](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/add_your_own_task.ipynb)
However, you'll need labeled training data.

**Comment by SetoKaiba** [comment]
> You can definitely use `pyannote.audio` to train such a model. See [this tutorial](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/add_your_own_task.ipynb) However, you'll need labeled training data.

Thank you. I see. Will it be trained as built-in in the future?

**Comment by hbredin** [comment]
I have no plan in training such a model... but one should never say never ;-)
