### ISSUE TITLE
Cannot use the embedding model of pipeline-3.1 in offline.

### ISSUE THREAD

**Issue by zhao-huan** [pyannote/pyannote-audio#1565]
The embedding model in pipeline-3.1 is wespeaker-ResNet. I want to use pipeline in offline. But when loading the embedding model, the class PretrainedSpeakerEmbedding in speaker_verification.py only has ONNX. It occurs as an error. I do not know how to use the config.yaml file in pyannote/wespeaker-voxceleb-resnet34-LM.

**Comment by Flyvannn** [comment]
> The embedding model in pipeline-3.1 is wespeaker-ResNet. I want to use pipeline in offline. But when loading the embedding model, the class PretrainedSpeakerEmbedding in speaker_verification.py only has ONNX. It occurs as an error. I do not know how to use the config.yaml file in pyannote/wespeaker-voxceleb-resnet34-LM.

Hi, I'm having the same problem, is there a solution?

**Comment by Flyvannn** [comment]
![image](https://github.com/pyannote/pyannote-audio/assets/59273374/f996ff65-c8e0-4869-8506-beb3782c5f91)

**Comment by Flyvannn** [comment]
> ![image](https://private-user-images.githubusercontent.com/59273374/291238044-f996ff65-c8e0-4869-8506-beb3782c5f91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4OTQyMjMsIm5iZiI6MTcwMjg5MzkyMywicGF0aCI6Ii81OTI3MzM3NC8yOTEyMzgwNDQtZjk5NmZmNjUtYzhlMC00ODY5LTg1MDYtYmViMzc4MmM1ZjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDEwMDUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MzQ0ZGZiMWNiYjQ2ZTk1OWI0NTllMzRkZTVkZWYyNjZkMjZhOGY3YzMzNmU5MzQwNjMwZWQzYzM1Zjg0NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FdzOMnDOXUD5oIczrqTEfYx5p9NLGZdvd6Z-uu5BYMs)

I find this, the folder must contain 'pyannote'.
