### ISSUE TITLE
Support resampling in RawAudio.crop

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#157]
A little off-topic, there is a problem with the augmentation of NIST SRE files, many of which have 8000 sample rate. The MUSAN database used for augmentation has 16K sampling rate, so it leads to a conflict. Any other databases with 8K noise?

_Originally posted by @pkorshunov in https://github.com/pyannote/pyannote-audio/pull/156#issuecomment-465974840_

**Comment by hbredin** [comment]
I am not aware of such database (but I did not look very far...)

One could still convert MUSAN to 8kHz, right?
This is actually what is already happening: `AddNoise` converts it on the fly to the provided sample rate, rightN

**Comment by pkorshunov** [comment]
I don't think `AddNoise` converts the sample to 8000, because you add the noise here:
https://github.com/pyannote/pyannote-audio/blob/e0b73c10d38a048e4c61240a8c0220fe2529b035/pyannote/audio/augmentation/noise.py#L111

And it calls the same crop() function as for original data, where sampling_rate of the MUSAN file is 16000 which is not the same as the self.sampling_rate=8000 (the one that I set in the config.yml), so it breaks here:
https://github.com/pyannote/pyannote-audio/blob/e0b73c10d38a048e4c61240a8c0220fe2529b035/pyannote/audio/features/utils.py#L280

**Comment by hbredin** [comment]
Oh, I see. `RawAudio.crop` does not (yet?) support resampling...

Now, I remember. I actually purposely prevented that because generation of training samples is the bottleneck and I did not want resampling to make it even slower... 

Hmmmm. Not sure what to do... 
I was half kidding when I wrote earlier that we could make `RawAudio` convert (and save to disk) every new file it encounters with the wrong sampling rate. 

One problem I see is that we would also need a way to update the "audio" key (used by `RawAudio` to know which file to use) to automagically link to this new converted file, without first trying (and failing) to crop the original file.

I am changing the title of this issue to "Support resampling in RawAudio.crop" because I think we diverged a bit :)

**Comment by pkorshunov** [comment]
It may be faster to resample on the fly, especially, if it is done after cropping (so only the necessary part of the file is resampled), than saving the file to disk and reading from disk. I think disk IO is slower than resampling.

**Comment by pkorshunov** [comment]
So, may be it would be better to resample right after here: https://github.com/pyannote/pyannote-audio/blob/e0b73c10d38a048e4c61240a8c0220fe2529b035/pyannote/audio/features/utils.py#L288

**Comment by hbredin** [comment]
Once we figure out how to solve #156, it does make sense to only resample the sub-sequence (and not the whole file).

**Comment by pkorshunov** [comment]
I just updated #156 to resample on the fly. It's a bit ugly but so far it seems to work.

**Comment by hbredin** [comment]
Fixed in b0a7856.
