### ISSUE TITLE
Removing torchaudio.set_audio_backend("soundfile")

### ISSUE THREAD

**Issue by Pikauba** [pyannote/pyannote-audio#1576]
The call to `torchaudio.set_audio_backend("soundfile")` in  https://github.com/pyannote/pyannote-audio/blob/6580e6c8d6e4431778438ce1e7d591aae8688f58/pyannote/audio/core/io.py#L43 leads to the following deprecation warning: 

**UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call. torchaudio.set_audio_backend("soundfile")**

In order to remove this warning caused by a deprecated feature of torchvision, we could simply remove it as it is no op.

Indeed, as stated in the torchvision documentation of [torchaudio.set_audio_backend](https://pytorch.org/audio/stable/generated/torchaudio.set_audio_backend.html#torchaudio-set-audio-backend)

"This function has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call."

So this could be removed without any harm.

**Comment by hbredin** [comment]
Would you mind opening a PR?

**Comment by Pikauba** [comment]
As described in your link, 

"In 2.2, the legacy global backend mechanism will be removed. Utility functions [get_audio_backend()](https://pytorch.org/audio/stable/generated/torchaudio.get_audio_backend.html#torchaudio.get_audio_backend) and [set_audio_backend()](https://pytorch.org/audio/stable/generated/torchaudio.set_audio_backend.html#torchaudio.set_audio_backend) become no-op."

Considering that for now pyannote-audio has a requirement fir torchaudio >= 2.0.0, should we wait for the pyannote-audio to upgrade the version before we proceed to this change?

**Comment by hbredin** [comment]
I would consider increasing to `torchaudio>=2.2.0` as long as there are not too many breaking changes.
