### ISSUE TITLE
False Alarms vs Misses

### ISSUE THREAD

**Issue by picheny-nyu** [pyannote/pyannote-audio#1584]
I have a diarization application in which I prefer to have fewer false alarms at the expense of more misses. Can this be controlled during fine tuning?

Thanks
Michael

**Comment by hbredin** [comment]
Not in 3.x, no. 

I am considering adding back the option but cannot provide an ETA though. 

Can you say more about your use case?

**Comment by picheny-nyu** [comment]
Using the output to identify sections of speech in parent-toddler conversations to transcribe as input for unsupervised speech recognition fine-tuning. Figure better to miss questionable segments than train on false alarms.

**Comment by hbredin** [comment]
I would then use `pyannote/segmentation` for this purpose, wrapped in a voice activity detection pipeline that comes with onse/offset thresholds:

https://huggingface.co/pyannote/segmentation#voice-activity-detection

**Comment by picheny-nyu** [comment]
Thanks. I do need diarization, though - I want to process the adult and toddler speech separately. Would you suggest I just use a downleveled version of the diarization pipeline that still uses VAD?

**Comment by hbredin** [comment]
Yes.
