### ISSUE TITLE
dlib install ; Building wheels for collected packages: dlib

### ISSUE THREAD

**Issue by rnunziata** [pyannote/pyannote-audio#159]
dlib failed to install....
env: ubuntu16.04
complains about variable not being set?

```
Building wheels for collected packages: dlib
  Running setup.py bdist_wheel for dlib ... error
  Complete output from command /home/rjn/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-wm28gf7v/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-55v9nh0o --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  package init file 'dlib/__init__.py' not found (or not a regular file)
  running build_ext
  Building extension for Python 3.6.8 |Anaconda custom (64-bit)| (default, Dec 30 2018, 01:22:34)
  Invoking CMake setup: 'cmake /tmp/pip-install-wm28gf7v/dlib/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-wm28gf7v/dlib/build/lib.linux-x86_64-3.6 -DPYTHON_EXECUTABLE=/home/rjn/anaconda3/bin/python -DCMAKE_BUILD_TYPE=Release'
 .
.
.
  CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  cusolver (ADVANCED)
      linked by target "dlib" in directory /tmp/pip-install-wm28gf7v/dlib/dlib

```

**Comment by hbredin** [comment]
Looks like a problem with `dlib`, not `pyannote-audio`. 
https://github.com/davisking/dlib/issues/1687

**Comment by PaulLerner** [comment]
Hi @rnunziata did you manage to fix it ? 
I have a similar error : `CMake must be installed to build the following extensions: dlib`
After a search [some forum](https://stackoverflow.com/questions/48503646/where-should-i-install-cmake/52564271) suggested to `pip install cmake` then `pip install dlib`. CMake was (a priori) correctly installed but dlib gets blocked at `Building wheel for dlib (setup.py)`. Same thing if I launch `pip install .` again.

**Comment by rnunziata** [comment]
sorry I have not worked on this project in awhile I did get my project to
work but I can not remember how I got around this issue.

**Comment by Ajithkumarkk9** [comment]
> Hi @rnunziata did you manage to fix it ? I have a similar error : `

i have same problem can u suggesst me solution for that
