### ISSUE TITLE
'NoneType' object has no attribute 'eval'

### ISSUE THREAD

**Issue by xxm1668** [pyannote/pyannote-audio#1603]

**Comment by clement-pages** [comment]
Could you please share a Google Colab that we can run to reproduce the error (and have more context about when this error occurs)?

**Comment by nikhilsos** [comment]
Faced same issue at first, sharing here for others who might do so. You need to authenticate by providing your company/ university name and website at both  https://huggingface.co/pyannote/segmentation-3.0  and  https://huggingface.co/pyannote/speech-separation-ami-1.0
