### ISSUE TITLE
fine tuning the pretrained model wespeaker-voxceleb-resnet34-LM 

### ISSUE THREAD

**Issue by Emo3032** [pyannote/pyannote-audio#1605]
How can i fine tune the pretrained model with my own audio files for speaker verification?
There is no particular tutorial for it and i'm lost

**Comment by hbredin** [comment]
This is not (yet) supported.

**Comment by wsstriving** [comment]
> How can i fine tune the pretrained model with my own audio files for speaker verification? There is no particular tutorial for it and i'm lost

You can check [wespeaker ](https://github.com/wenet-e2e/wespeaker)for the model training, and then plug it to pyannote
