### ISSUE TITLE
Diarized speech after audio duration

### ISSUE THREAD

**Issue by Valahaar** [pyannote/pyannote-audio#1611]
### Tested versions

I tested on this environment:

```
pyannote.audio==3.1.0
pyannote.core==5.0.0
pyannote.database==5.0.1
pyannote.metrics==3.2.1
pyannote.pipeline==3.0.1
torch==2.1.1
torch-audiomentations==0.11.0
torch-pitch-shift==1.2.4
torchaudio==2.1.1
```

### System information

Ubuntu 22.04 - pyannote 3.1.0

### Issue description

Hi! I've encountered a strange problem with an audio file (that was upsampled from 8 kHz, not sure if this is relevant in any way):
using this snippet with my audio file, pyannote outputs a diarization that goes over the length of the audio itself. I cannot share the audio publicly but I would be happy to provide it privately should the need arise.

```python
import torch
from pyannote.audio import Pipeline

pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization-3.1", use_auth_token='XXX')

audio = torch.load('debug.pt')
waveform, sr = audio['waveform'], audio['sample_rate']
print(waveform.shape, sr, waveform.shape[1] / sr)

dz = pipeline(audio)

print(dz)
```

output:
```torch.Size([1, 445440]) 16000 27.84
[ 00:00:00.008 -->  00:00:01.825] A SPEAKER_00
[ 00:00:01.943 -->  00:00:03.421] B SPEAKER_00
[ 00:00:03.455 -->  00:00:06.918] C SPEAKER_00
[ 00:00:07.224 -->  00:00:08.684] D SPEAKER_00
[ 00:00:08.853 -->  00:00:10.483] E SPEAKER_00
[ 00:00:10.602 -->  00:00:14.677] F SPEAKER_00
[ 00:00:14.966 -->  00:00:20.059] G SPEAKER_00
[ 00:00:20.365 -->  00:00:21.994] H SPEAKER_00
[ 00:00:22.062 -->  00:00:27.631] I SPEAKER_00
[ 00:00:27.903 -->  00:00:28.005] J SPEAKER_00
```

The last row is out of bounds. I can fix it by `.crop`ping to `(0, 27.84)`, but that does not seem like the right way to handle this.

Let me know if I can help in any other way, thanks!

### Minimal reproduction example (MRE)

/

**Comment by hbredin** [comment]
Can you please show the output of `print(waveform.shape, sr, waveform.shape[1] / sr)`?

**Comment by Valahaar** [comment]
Sorry, I was sure to have included it in the original snippet. Here it is:
```python

torch.Size([1, 445440]) 16000 27.84
```

**Comment by hbredin** [comment]
Would definitely be easier and faster if you shared the audio file and a Google Colab I can just run...

In the meantime, yes, `diarization.crop(...)` should do the trick.
