### ISSUE TITLE
Error with accented speaker labels

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#1612]
We get the following error when training with databases that contains speakers with accented characters (like french REPERE).

```
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 3: ordinal not in range(128)
```

This is where the error happens.

https://github.com/pyannote/pyannote-audio/blob/9e4ec5f6e0b0f5d60c557981fc680e8cebf78f5b/pyannote/audio/core/task.py#L598

**Comment by hbredin** [comment]
A similar issue is [that one](https://github.com/pyannote/pyannote-audio/issues/1608).

@clement-pages could you have a look?

**Comment by clement-pages** [comment]
I'm looking at it right now
