### ISSUE TITLE
Readme: Please add links to the two user agreements we must make

### ISSUE THREAD

**Issue by zackees** [pyannote/pyannote-audio#1618]
### Tested versions

Please put the links to the user agreements. This will really improve usage of these models as this is the biggest barrier to using this product.

Compliments to the developer of this AI model. This is top notch stuff.

### System information

Windows 3060

### Issue description

See above about adding links to readme.

### Minimal reproduction example (MRE)

8

**Comment by hbredin** [comment]
User agreement links have been listed [here](https://github.com/pyannote/pyannote-audio#tldr) for a while.

Feel free to let me know what I should do to make them more visible.

**Comment by zackees** [comment]
Check it again, there is no final link to the agreement.

Github -> pyannote 3.1 -> pyannote 3.0 -> pyannote 3.0 (self references, so loop)

Accept pyannote/speaker-diarization-3.1 user conditions
https://github.com/pyannote/pyannote-audio?tab=readme-ov-file#tldr

Accept pyannote/segmentation-3.0 user conditions
https://huggingface.co/pyannote/segmentation-3.0

Accept pyannote/segmentation-3.0 user conditions
https://huggingface.co/pyannote/segmentation-3.0 (duplicate)

**Comment by hbredin** [comment]
Links are correct. If you don't see the user agreement form on Huggingface, it probably is because you already accepted them.

<img width="734" alt="image" src="https://github.com/pyannote/pyannote-audio/assets/1080837/bee9a6ad-d932-4a29-a021-b8f52df9c1fb">
