### ISSUE TITLE
NameError: name 'baseline' is not defined

### ISSUE THREAD

**Issue by nehalmathew1996** [pyannote/pyannote-audio#1639]
### Tested versions

According to the documentation which I followed on hugging face I faced this issue.
To reproduce it attaching this for reference

### System information

windows11 - pyannot - python 3.11

### Issue description

No description of the initializing 'baseline' parameter while segmentation.
Any help would be appreciated
<img width="474" alt="image" src="https://github.com/pyannote/pyannote-audio/assets/82964954/5f078aa5-3bc2-403b-a72a-58e00aeebdeb">

### Minimal reproduction example (MRE)

https://colab.research.google.com/drive/1fzTlOAtHb9YsLK1_5qQEhoJQMcO3iO9R?usp=sharing

**Comment by FrenchKrab** [comment]
I haven't looked into the _Resegmentation_ task, but according to the comment below you need to provide a pyannote.core.Annotation object as baseline, so you'll probably need to load an RTTM file (standard format used to store annotations)
```python
from pyannote.database.util import load_rttm
baseline = load_rttm("my_baseline.rttm")
```

Usually you either get RTTMs from the reference annotations of the dataset (ground truth), or from an existing pipeline which you applied to the file (model prediction) and then saved with `annotation.write_rttm`, [see this pipeline and its doc for examples](https://huggingface.co/pyannote/speaker-diarization-3.1).

And in case you just need to perform speaker diarization (and not resegmentation), the pipeline linked above should get you there easily.
