### ISSUE TITLE
Why v3.1 uses cpu instead of GPU in the embedding part

### ISSUE THREAD

**Issue by ouyang982020** [pyannote/pyannote-audio#1653]
### Tested versions

3.1

### System information

A100-GPU

### Issue description

GPU is only used When segmentation
![image](https://github.com/pyannote/pyannote-audio/assets/75766732/aa69fe22-91b0-4feb-ae0b-60275bbae613)
![image](https://github.com/pyannote/pyannote-audio/assets/75766732/95311fa5-0de9-41d4-8804-e12c3c198a67)
![image](https://github.com/pyannote/pyannote-audio/assets/75766732/9b78a519-251a-4fbc-8055-f47966396bf5)
![image](https://github.com/pyannote/pyannote-audio/assets/75766732/7dceddaf-1e9c-4c6c-9575-529c5ed7b5ba)

### Minimal reproduction example (MRE)

none

**Comment by hbredin** [comment]
Would you mind sharing a link to a Google Colab that one can just click and run to reproduce the issue?

**Comment by ouyang982020** [comment]
Thanks for the reminder, this is my code
https://colab.research.google.com/drive/1n9U03dgyBM6gMA5uh48uPNfEWMjiMMsG?usp=sharing

**Comment by ouyang982020** [comment]
Thanks for the reply. I think I found the problem. There was an error in path selection. I need to include pyannote in the path.

**Comment by Dinxin** [comment]
What is the problem? Can you explain? I ran into the same problem.

**Comment by h-ann** [comment]
works fine for torch==2.0.0 and pyannote.audio==3.1.1

**Comment by wildwind0** [comment]
> Thanks for the reply. I think I found the problem. There was an error in path selection. I need to include pyannote in the path.

Could you please explain what "include pyannote in the path" specifically means? I've encountered the same issue.

**Comment by cod3r0k** [comment]
I have the same issue, process is done in CPU not in GPU. Can you help me ?

```
pipeline = Pipeline.from_pretrained(
    "pyannote/speaker-diarization@2.1",
    use_auth_token=ACCESS_TOKEN
).to(device)

wav_path="./sample.wav"
diarization = pipeline(wav_path)
```
