### ISSUE TITLE
Trying to use pretrain on single wav

### ISSUE THREAD

**Issue by rnunziata** [pyannote/pyannote-audio#166]
the following gets error following example in pretrain readme.md. Is there an additional call to be made? Works fine if you let if find the data file on its own. ""test_file = next(protocol.test())

```
test_file = {'uri': 'filename', 'audio': '/media/rjn/fe292271-3ffe-42fe-9f14-53671ee3cf94/AMI/db_download/amicorpus/EN2001a/audio/EN2001a.Mix-Headset.wav'}

# ... or use a file provided by a pyannote.database plugin
# in this example, we are using AMI first test file.
from pyannote.database import get_protocol
from pyannote.database import FileFinder
preprocessors = {'audio': FileFinder()}
protocol = get_protocol('AMI.SpeakerDiarization.MixHeadset',
                        preprocessors=preprocessors)

```

```

Traceback (most recent call last):
  File "pretrain.py", line 93, in <module>
    notebook.plot_annotation(test_file['annotation'], ax=ax[0])
KeyError: 'annotation'

```

**Comment by hbredin** [comment]
`notebook.plot_annotation(test_file['annotation'])` assumes that there is an `"annotation"` key in `test_file` directory. Either provide one (as a [pyannote.core.Annotation](http://pyannote.github.io/pyannote-core/structure.html#annotation) instance) or just skip this line (this is just for displaying the manual reference anyway...)

**Comment by rnunziata** [comment]
thanks
