### ISSUE TITLE
ImportError: 'speechbrain' must be installed to use 'speechbrain/spkrec-ecapa-voxceleb' embeddings. Visit https://speechbrain.github.io for installation instructions.

### ISSUE THREAD

**Issue by YugwonWon** [pyannote/pyannote-audio#1661]
### Tested versions

- Reproducible 3.1 more

### System information

ubuntu 18 pyannote.audio==3.1.1

### Issue description

When I install pyannote.audio from python, it also installs the speechbrain package, but it doesn't create a pretrained folder. Originally, the old version had a speechbrain folder, and inside it was a pretrained folder. I installed the new version of pyannote while setting up a new venv, and this happened. I copied the contents of the old version's pretrained folder and ran it, but the function pretrainer.load_collected(device="cpu") on line 141 of interpaces.py doesn't expect a value of device. What should I do?

### Minimal reproduction example (MRE)

https://colab.research.google.com/drive/1edF4nPYc8CuTa7gAgr-_9opWeQe1LhED?usp=sharing

**Comment by lgq-liao** [comment]
from speaker_verification.py 
the following import will fail as well, 
```
from speechbrain.pretrained import (
        EncoderClassifier as SpeechBrain_EncoderClassifier,
    )
```
because spechbrain does NOT have **pretrained** module

**Comment by hbredin** [comment]
Currently being look at in PR #1659

**Comment by leolulu** [comment]
Did you upgrade your code to 3.1 according to the README?

```
Install [pyannote.audio](https://github.com/pyannote/pyannote-audio) with pip install pyannote.audio
Accept [pyannote/segmentation-3.0](https://hf.co/pyannote/segmentation-3.0) user conditions
Accept [pyannote/speaker-diarization-3.1](https://hf.co/pyannote/speaker-diarization-3.1) user conditions
Create access token at [hf.co/settings/tokens](https://hf.co/settings/tokens).

from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained(
    "pyannote/speaker-diarization-3.1",
    use_auth_token="HUGGINGFACE_ACCESS_TOKEN_GOES_HERE")
```

**Comment by YugwonWon** [comment]
I modified the code to match the readme and it worked, thank you.

**Comment by leminhnguyen** [comment]
Change from:
```
from speechbrain.pretrained import (
        EncoderClassifier as SpeechBrain_EncoderClassifier,
    )
```
to
```
    from speechbrain.inference.speaker import (
        EncoderClassifier as SpeechBrain_EncoderClassifier,
    )
```
Will solve the issue!!!

**Comment by gittb** [comment]
> Change from:
> 
> ```
> from speechbrain.pretrained import (
>         EncoderClassifier as SpeechBrain_EncoderClassifier,
>     )
> ```
> 
> to
> 
> ```
>     from speechbrain.inference.speaker import (
>         EncoderClassifier as SpeechBrain_EncoderClassifier,
>     )
> ```
> 
> Will solve the issue!!!

Reopening, The above change from @leminhnguyen was still needed when running the `pyannote/speech-separation-ami-1.0` pipeline.

Would you like me to make a PR to update `speaker_verification.py` to avoid future issues for users?

**Comment by hbredin** [comment]
Version [3.3.1](https://github.com/pyannote/pyannote-audio/releases/tag/3.3.1) fixes this issue.
