### ISSUE TITLE
'speechbrain' must be installed to use 'speechbrain/spkrec-ecapa-voxceleb' embeddings.

### ISSUE THREAD

**Issue by ijean** [pyannote/pyannote-audio#1677]
### Tested versions

pyannote.audio version 3.1.1
speechbrain 1.0.0

### System information

Windows 11 x64

### Issue description

Hello, 
I've successfully installed pyannote-audio (accepted the licenses) and was able to do speaker diarization on an audio file with two speakers. 

I try to follow one of your tutorials https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/speaker_verification.ipynb

The code crashes at:

```
model = PretrainedSpeakerEmbedding(
    "speechbrain/spkrec-ecapa-voxceleb",
    device=torch.device("cuda"))

```

with 'speechbrain' must be installed to use 'speechbrain/spkrec-ecapa-voxceleb' embeddings. Visit https://speechbrain.github.io for installation instructions.

I've installed speechbrain with "pip install speechbrain" but I still get the same error.

Any suggestion ?

Thanks for all your great work,
Jean

### Minimal reproduction example (MRE)

https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/speaker_verification.ipynb

**Comment by ijean** [comment]
I found a temporary workaround:

```
pip uninstall speechbrain
pip install speechbrain==0.5.16
```

**Comment by davidlee1102** [comment]
> pip install speechbrain==0.5.16

Amazing, I faced with the problem also, and thank you for your solution

**Comment by ahmetkipkip** [comment]
> I found a temporary workaround:
> 
> ```
> pip uninstall speechbrain
> pip install speechbrain==0.5.16
> ```

That works, thanks
