### ISSUE TITLE
Can not reproduce "adapting_pretrained_pipeline.ipynb" on local machine

### ISSUE THREAD

**Issue by jyhan03** [pyannote/pyannote-audio#1698]
### Tested versions

- pip=23.1.2
- python=3.10.12
- pyannote.audio=2.1.1
- pyannote.core=4.5
- pyannote.database=4.1.3
- pyannote.metrics=3.2.1
- pyannote.pipeline=2.3

### System information

CentOS 7.9 - pyannote.audio=2.1.1

### Issue description

Hi, thanks for the great work! 
When I follow [https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/adapting_pretrained_pipeline.ipynb](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/adapting_pretrained_pipeline.ipynb) and run code on Colab, everything is fine. But when I try to run the same code on my local machine, there is always an issue from `pyannote-database info AMI-SDM.SpeakerDiarization.mini
     `: `UnknownExtra: typer 0.12.3 has no such extra feature 'all'`. 

I tried to install the same version of python/pip/pyannote as the Colab, but the problem is still there. Any suggestions to solve it? Thanks. 
     
     

### Minimal reproduction example (MRE)

https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/adapting_pretrained_pipeline.ipynb

**Comment by hbredin** [comment]
Try updating pyannote.database to `5.1.0`.

**Comment by jyhan03** [comment]
> Try updating pyannote.database to `5.1.0`.

Solved. Many thanks.

**Comment by jyhan03** [comment]
Maybe there are some incompatible issues. Multi-GPU works for pyannote3.1.
