### ISSUE TITLE
Clustering: Threshold error

### ISSUE THREAD

**Issue by toanquachp** [pyannote/pyannote-audio#170]
There seems to be an error when using threshold = True for HierarchicalClustering (the name might be wrong). As I inspected, this is due to Scipy complaining that it only accepts float, str, to convert to `int` or `float`, while the given input is 'Uniform'. My temporary solution is turn threshold off (threshold = False). 

Would love to hear an update for this!

**Comment by hbredin** [comment]
Can you please provide me with a few lines of code showing the error.

I remember fixing a (apparently related) bug in pyannote.pipeline 1.1
https://github.com/pyannote/pyannote-pipeline/commit/5c5cf72a973c63cb1397376bef90a4cdc18d7abc

Are you using the latest version of pyannote.pipeline?
Are you using the develop branch of pyannote.audio?

**Comment by hbredin** [comment]
Closing as I believe pyannote.pipeline 1.1 solved this issue.
