### ISSUE TITLE
DER above zero when using Oracle Segmentation & Oracle Clustering

### ISSUE THREAD

**Issue by mn-j** [pyannote/pyannote-audio#1715]
### Tested versions

- Reproducible in 3.1.1 

### System information

Ubuntu 22.04.4 LTS - pyannote 3.1.1

### Issue description

I am running the speaker-diarization-3.1 pipeline on the AMI test set with an oracle configuration. Meaning, oracle segmentations (using the pyannote.audio.pipelines.utils.oracle_segmentation function), and oracle clustering (which also makes use of the oracle_segmentation function again). Embeddings are skipped since the pipeline is working with oracle clustering.  With this configuration, I get an average DER of 0.49% (0% missed detection, 0.48% false alarm, and 0% confusion). 

I am not able to justify any DER above 0 with this configuration, so I hope someone else could have a clue of what might be causing this.

### Minimal reproduction example (MRE)

Google collab notebook sadly not yet working

**Comment by hbredin** [comment]
The difference most likely comes from the temporal discretization happening during oracle segmentation.

**Comment by mn-j** [comment]
Indeed, this was the cause. Thank you for the quick reply!
