### ISSUE TITLE
How to map the transcribed text with their respective speakers in speaker diarization? 

### ISSUE THREAD

**Issue by ThiruRJST** [pyannote/pyannote-audio#1718]
### Tested versions

Reproducible in 3.1

### System information

Ubuntu-20.04

### Issue description

I installed PyAnnote-3.1 and used speaker-diarization-3.1 for my project purpose. When I ran the pipeline, it gave me a rttm file as an output but the speakers were not mapped with their respective texts transcribed from it. Is there any workaround to achieve this?

### Minimal reproduction example (MRE)

https://colab.research.google.com/github/pyannote/pyannote-audio/blob/develop/tutorials/MRE_template.ipynb

**Comment by hbredin** [comment]
pyannote does not do speech-to-text (what was said?). It only does speaker diarization (who spoke when?).

**Comment by ThiruRJST** [comment]
@hbredin Thank you for the confirmation
