### ISSUE TITLE
When's the next release? (for numpy 2.0 compatibility)

### ISSUE THREAD

**Issue by sbyrne-ellevest** [pyannote/pyannote-audio#1741]
Any news on when the release that is compatible with numpy 2.0 will be cut? I know that its been merged in, but wondering when it will be in an official release.

**Comment by hbredin** [comment]
No ETA unfortunately, due to limit resources on our side.

Note than you can install pyannote from the develop branch source directly.

**Comment by hbredin** [comment]
3.3.2 has just been released with numpy 2.x fix.
