### ISSUE TITLE
VAD model

### ISSUE THREAD

**Issue by adriondragon** [pyannote/pyannote-audio#1754]
### Tested versions

no

### System information

no

### Issue description

I want to download a VAD model to my local machine, but I can't find where to download it.

### Minimal reproduction example (MRE)

I want to download a VAD model to my local machine, but I can't find where to download it.

**Comment by qalabeabbas49** [comment]
Segmentation model is the VAD. You can find it here https://huggingface.co/pyannote/segmentation-3.0

**Comment by clement-pages** [comment]
Hey @adriondragon, did qalabeabbas49 answer your question ?

**Comment by coreeey** [comment]
> Hey @adriondragon, did qalabeabbas49 answer your question ?

Can i use segmentation-3.0 to fine-tune a VAD model?

**Comment by clement-pages** [comment]
You can finetune `pyannote/segmentation-3.0` on your own data, then use it like this:
```python
from pyannote.audio.pipelines import VoiceActivityDetection
pipeline = VoiceActivityDetection(segmentation=model)
HYPER_PARAMETERS = {
  # remove speech regions shorter than that many seconds.
  "min_duration_on": 0.0,
  # fill non-speech regions shorter than that many seconds.
  "min_duration_off": 0.0
}
pipeline.instantiate(HYPER_PARAMETERS)
vad = pipeline("audio.wav")
# `vad` is a pyannote.core.Annotation instance containing speech regions
```
where `model` is your finetuned `pyannote/segmentation-3.0`.

**Comment by coreeey** [comment]
> You can finetune `pyannote/segmentation-3.0` on your own data, then use it like this:
> 
> ```python
> from pyannote.audio.pipelines import VoiceActivityDetection
> pipeline = VoiceActivityDetection(segmentation=model)
> HYPER_PARAMETERS = {
>   # remove speech regions shorter than that many seconds.
>   "min_duration_on": 0.0,
>   # fill non-speech regions shorter than that many seconds.
>   "min_duration_off": 0.0
> }
> pipeline.instantiate(HYPER_PARAMETERS)
> vad = pipeline("audio.wav")
> # `vad` is a pyannote.core.Annotation instance containing speech regions
> ```
> 
> where `model` is your finetuned `pyannote/segmentation-3.0`.
Thanks

**Comment by clement-pages** [comment]
The questions asked in this issue having beed answered, I close it. Feel free to open a new one if you have more question about VAD model.
