### ISSUE TITLE
numpy.NAN crash

### ISSUE THREAD

**Issue by KiARC** [pyannote/pyannote-audio#1758]
### Tested versions

- Reproducible in 3.3.1, current latest version

### System information

Linux dev container, no GPU

### Issue description

This issue has already been fixed in #1732, but after months that PR hasn't made it into a release. A patch really should be released, because as it stands the latest stable version of the library **does not work when NumPy>=2 is present**. These kinds of patches should be made available ASAP so that people can use the library. Could a 3.1.2 release be created in order to make the patch available?

### Minimal reproduction example (MRE)

Colab unfortunately is not cooperating right now, but if pyannote is used in an environment with numpy>=2 it will crash. Again, this is a fixed issue, but the patch has not been released.

**Comment by hbredin** [comment]
Just released 3.3.2 with latest fix.

**Comment by KiARC** [comment]
Thank you so much, I really appreciate the quick response.
