### ISSUE TITLE
Dependency errors while running the evaluation notebook for the speech separation uploaded recently

### ISSUE THREAD

**Issue by BNarayanaReddy** [pyannote/pyannote-audio#1767]
### Tested versions

There is a small dependancy error that making unable to instatiate the speech separation pipeline using the command.
<code>from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained(
    "pyannote/speech-separation-ami-1.0", use_auth_token=True)
</code>
The corrected dependency is using pyannote-audio version 3.3 instead of 3.1.1 bcoz, in colab it is installing the pyannote-audio 3.1.1 instead.
Solution : 
<code>
!pip install -qq speechbrain==0.5.16
!pip install -qq ipython==7.34.0
!pip install -qq ipywidgets openai-whisper whisperx==3.1.5 meeteval
!pip install -qq pyannote.audio[separation]==3.3.0
</code>

### System information

Google Colab - pyannote-audio 3.1.1

### Issue description

Bug, while loading the speech separation pre-trained model 
```
# use the following instead
!pip install -qq pyannote.audio[separation]==3.3.0
```

### Minimal reproduction example (MRE)

https://colab.research.google.com/drive/1aheD77AeF7Eq5jmTCrA5ODEBkOolrWAz?usp=sharing

**Comment by hbredin** [comment]
@clement-pages, can you please have a look and provide a fix?

**Comment by BNarayanaReddy** [comment]
Solution :
<code>
!pip install -qq pyannote.audio[separation]==3.3.0
</code>

**Comment by hbredin** [comment]
Thanks @BNarayanaReddy. Would you mind opening a PR?

**Comment by BNarayanaReddy** [comment]
yes sure

**Comment by BNarayanaReddy** [comment]
Solved the issue for those who run in google colab.
