### ISSUE TITLE
Speaker embeddings with context

### ISSUE THREAD

**Issue by geniki** [pyannote/pyannote-audio#177]
Hello,

I'd like to calculate speaker embeddings for, say, 1s segments but have the model see "context" of 0.25s on both sides of the segment (i.e. calculate the embedding of 1.5s of data). Is there an existing way to do this?

I see some of the options in `features` have a `get_context_duration()` method but it doesn't seem to be operational.

**Comment by hbredin** [comment]
`get_context_duration` is not meant for this and will probably disappear in the future.

One way of doing it would be to train the model on 1.5s windows, precompute the embeddings, and manually update file `metadata.yml` to change `duration` from 1.5 to 1 and shift `start` by 250ms.

But I am not sure this is what you have in mind. Can you please clarify?
In particular, how do you expect the network to use this additional  250ms context?
Does this relate to [this issue](https://github.com/pyannote/pyannote-audio/issues/158)?

**Comment by geniki** [comment]
Thanks, yes, I think editing `metadata.yml` this way will achieve what I need. I wanted to do what section 3.1 in [this paper](https://www.danielpovey.com/files/2017_icassp_diarization_embeddings.pdf) talks about. I was hoping for less of a workaround but I gather it's not implemented.

**Comment by hbredin** [comment]
Thanks for the clarification.

This could be implemented as a `context` parameter added to [`SequenceLabeling`](https://github.com/pyannote/pyannote-audio/blob/c8bd4f260337d67a9a59d54f3ee5c6c3e4d0f374/pyannote/audio/labeling/extraction.py#L42) and [`SequenceEmbedding`](https://github.com/pyannote/pyannote-audio/blob/c8bd4f260337d67a9a59d54f3ee5c6c3e4d0f374/pyannote/audio/embedding/extraction.py#L36) classes. 

I'd gladly consider merging a pull request adding this feature: I won't have time to do it myself.

Closing for now. Please re-open if needed.
