### ISSUE TITLE
Speech Separation cracking the volume too high

### ISSUE THREAD

**Issue by ajtopper** [pyannote/pyannote-audio#1770]
### Tested versions

-Reproducible in pyannote 3.3.1 - speech separation ami 1.0

### System information

ubuntu 24 - pyannote 3.3.1 - speech separation ami 1.0

### Issue description

Hello folks, 

I'm using  [Speech Separation ami 1.0](https://huggingface.co/pyannote/speech-separation-ami-1.0) and when there is separation by speakers, the final files end up with very high volume, with the entire waveform being distorted and clipped. 

Is there any way to control this output volume?

Here have a example:
https://drive.google.com/file/d/11Ber2v9HTKUaHWs4hCEbgoo9s4gPBlKC/view?usp=sharing

Thanks.

### Minimal reproduction example (MRE)

https://colab.research.google.com/drive/1Yr2xGz-UL4gpElyLGV8HzE5bfhGgOFIN?usp=sharing

**Comment by clement-pages** [comment]
Hey @ajtopper, your issue should be fixed by #1730.

**Comment by ajtopper** [comment]
> Hey @ajtopper, your issue should be fixed by #1730.

Works perfectly, thanks!
