### ISSUE TITLE
How to use features normalisation

### ISSUE THREAD

**Issue by geniki** [pyannote/pyannote-audio#178]
I see that `features/normalization.py` implements a couple of useful normalisations/standardisations but I'm unsure where in the code it would be best to add them. Any thoughts?

**Comment by hbredin** [comment]
It used to be passed directly to feature extractors with the (now removed) "normalization" parameter - in the same way there is an "augmentation" parameter. 

It is no longer supported and will likely be removed in next release. 
Instead, most PyTorch models now have a "instance_normalize" option: when set to True, normalization is done on the fly by the model (hence quicker if done on GPU). 

If you are interested in fancier normalization, I’d be happy to merge pull requests adding PyTorch normalization layers/modules.

**Comment by geniki** [comment]
Makes sense to simplify although doing it when the features get to the model means you can't use local context around the example (say 0.5s on either side) or standardise at the file level.

Many thanks for the clarification what the plan is going forward.

**Comment by hbredin** [comment]
I agree that file-wise standardization (or at least using a sliding window a few seconds long) is usually the way to go. However, in my experience, it did not bring any improvement compared to sequence-wise standardization. 

Furthermore, the current trend is to get rid completely of hand-crafted features (like MFCCs) and work from the waveform directly: this is what I plan to do as well. 

I am closing this issue. Please re-open it if needed.
