### ISSUE TITLE
ToTaToNet Model Weights not Updated when Disabling Fine-Tuning of WavLM

### ISSUE THREAD

**Issue by ruixCMU** [pyannote/pyannote-audio#1789]
### Tested versions

- Reproducible in 3.3.2

### System information

AWS g5.2xlarge instance, US-EAST-1, Community AMIs, ami-0ea5e9630dcf98849; GPU: NVIDIA A10G

### Issue description

For ToTaToNet, when I disable the finetuning of WavLM, the model weights do not update. Reason is that the automatic_optimization flag is hard coded to be False in the __init__() function of ToTaToNet.

### Minimal reproduction example (MRE)

https://colab.research.google.com/drive/1TXDAN-ns2yOzkIgGGYUKMW0rzsjC-G4-?usp=sharing

**Comment by clement-pages** [comment]
Fixed by 9a2368bf6792ed8bea04eb2ce75d2b635121bab6
