### ISSUE TITLE
Info about change detection

### ISSUE THREAD

**Issue by giorgionanfa** [pyannote/pyannote-audio#179]
Hi, i would like to use the speaker change detection using my audio test files, without creating a database. So i am reading the tutorial in https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/models/speaker_change_detection#training
At the "application" phase, i should follow the indications here https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/models/pretrained
So i think i should modify the code in change_detection.py in the section "apply", according to your modifications in the tutorial. Is it correct?
After having realized these modifications, the speaker change detection will work for different languages audio files or only for English?
Thank you in advance,
Giorgio

**Comment by hbredin** [comment]
Hi Giorgio. Thanks for your interest in `pyannote-audio`.

> Hi, i would like to use the speaker change detection using my audio test files, without creating a database. So i am reading the tutorial in https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/models/speaker_change_detection#training

Do you want to train a model on your own set of data, or simply apply the provided pre-trained model?

> At the "application" phase, i should follow the indications here https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/models/pretrained
> So i think i should modify the code in change_detection.py in the section "apply", according to your modifications in the tutorial. Is it correct?

It depends on what you want to achieve. Following this tutorial will allow you to apply a pre-trained model on your own data, yes.

> After having realized these modifications, the speaker change detection will work for different languages audio files or only for English?

As stated in the tutorial, a model trained on AMI (meeting room, English) will probably only work on similar data.

**Comment by giorgionanfa** [comment]
Thanks for your answer. I have understood how to solve the problem, applying the provided pre-trained model to my data, and verified that it works only for similar data.
