### ISSUE TITLE
Can't download the MUSAN dataset

### ISSUE THREAD

**Issue by xdr94** [pyannote/pyannote-audio#197]
Hi hbredin,

I want to run the speech_activity_detection project. When i download the MUSAN dataset from http://www.openslr.org/17/, the speed of downloading is very slow and needs several days.  Can you share the MUSAN dataset in other ways?

Any help appreciated.
Thanks.

**Comment by hbredin** [comment]
Please contact the dataset providers directly. 

In the meantime, you could still train a model without data augmentation (i.e. by removing the corresponding section in the configuration file).
