### ISSUE TITLE
pyannote-speaker-embedding required duration as an argument

### ISSUE THREAD

**Issue by Rehan-Ahmad** [pyannote/pyannote-audio#200]
Hi, 
In tutorial https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/models/speaker_embedding, `pyannote-speaker-embedding apply` requires duration argument too which is not mentioned. 

What should be value of duration ? I tried to set 1, 0.5, 0.025 (25ms) but this gives error: `ValueError: inconsistent "sliding_window"`

**Comment by hbredin** [comment]
Thanks for reporting the missing `--duration` option. 98fa2cb should fix the issue.

Since the model was trained using sequences with duration between 500ms and 1.5s, using any duration between them should be fine.
