### ISSUE TITLE
Can't install requeriments (pytorch error)

### ISSUE THREAD

**Issue by polazaro** [pyannote/pyannote-audio#201]
I am trying to install the requeriments inside my conda enviroment and I obtain this error:

![image](https://user-images.githubusercontent.com/43273072/61657082-69319200-acc2-11e9-92c2-de99ad4a8164.png)

**Comment by hbredin** [comment]
I cannot reproduce this error.

Did you follow the [installation instructions](https://github.com/pyannote/pyannote-audio#installation)?

**Comment by polazaro** [comment]
Yes I did, step by step

**Comment by lizfischer** [comment]
I'm also having this issue. Windows 10, Python 3.7.1, pip 19.2.1.

![image](https://user-images.githubusercontent.com/7800842/61814692-32689280-ae0e-11e9-9723-39f78b5d011c.png)

**Comment by hbredin** [comment]
This might be an issue with `pytorch` not being available on PyPI for this combination of OS and Python version. Does `pip install torch` work?

@polazaro What is your OS and Python version? 

You might need to follow installation instructions available [here](https://pytorch.org/get-started/locally/)

**Comment by polazaro** [comment]
I already fixed the problem. You have to install with conda statement before pip installing the requirements.

**Comment by hbredin** [comment]
Hmmmm. So you did not follow the instructions in the first place, right?
I just want to make sure installation instructions work for everyone...

**Comment by polazaro** [comment]
I just installed pytorch with conda after creating the environment and before pip installing everything

**Comment by hbredin** [comment]
OK. Thanks. 

So, basically I need to add something like  `conda install pytorch -c pytorch` to the installation instructions, right?

**Comment by polazaro** [comment]
Yes, in my case conda install worked for me.

**Comment by chuanliubuxi137** [comment]
Hi, Does anyone run pyannote with Cycharm?
foward to answer

**Comment by hbredin** [comment]
Closing this stalled issue. Please re-open if needed.
