### ISSUE TITLE
Can't use pyannote-pipeline command

### ISSUE THREAD

**Issue by xdr94** [pyannote/pyannote-audio#206]
Hi hbredin,

I run the 'pyannote-pipeline train ...' command and I obtain this error:
-bash: pyannote-pipeline: command not found

Any help appreciated.
Thanks.

**Comment by chuanliubuxi137** [comment]
Hi,I want to run this 'pyannote with python IDE Cycharm in windows OS. Is it right?
the tutorial says " you will learn how to perform feature extraction using pyannote-speech-feature command line tool"
Where and how to use command line tool
Thank you

**Comment by hbredin** [comment]
Package [`pyannote.pipeline`](https://github.com/pyannote/pyannote-pipeline) provides the `pyannote-pipeline` command line tool.

It is also a dependency of `pyannote.audio` so it should be installed automatically when installing `pyannote.audio`. Are you sure everything went OK when installing `pyannote.audio`?

**Comment by xdr94** [comment]
@hbredin I have solved this issue by reinstall  the pyannote.audio. Thanks a lot !
