### ISSUE TITLE
Compare embeddings

### ISSUE THREAD

**Issue by melih1996** [pyannote/pyannote-audio#207]
How to compare embeddings to identify the person ? I get 3 embeddings from 2 people and there is no such a significant distance when the embeddings belong to a same person and when embeddings belong to different people.

By the way, I wrote the code below to compare the embeddings. 

```
def compare(arr1,arr2):
	result = []
	b=arr1 == arr2
	if b:
		print("Same")
	for i in range(len(arr1)):
		for j in range(len(arr2)):
			if b:
				if i == j:
					continue
			result.append(np.linalg.norm(arr1[i]-arr2[j]))
	result=np.asarray(result)
	return np.mean(result)
```

**Comment by hbredin** [comment]
Are you using the pre-trained embedding network? 

If so, it was optimized for cosine distance, not euclidean distance.
You can tell by looking at the following line in the configuration file: https://github.com/pyannote/pyannote-audio/blob/1d88c5816e7a176d53faaf12d5edbc24f0ee562f/tutorials/models/speaker_embedding/config.yml#L36

**Comment by hbredin** [comment]
Closing this stalled issue. Please re-open if needed.
