### ISSUE TITLE
Tutorial for using pyannote-audio (link broken)

### ISSUE THREAD

**Issue by happypanda5** [pyannote/pyannote-audio#212]
Hi

Is there a colab tutorial for using voice activity detection on custom dataset using pretrained models from pyannote?

The tutorial linked to [here](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/models/pretrained) shows a **page not found**.

**Comment by hbredin** [comment]
Thanks for reporting the broken link.
It is now fixed: https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/own_data/pretrained
