### ISSUE TITLE
Data augmentation with your own dataset

### ISSUE THREAD

**Issue by glebss** [pyannote/pyannote-audio#213]
Hi 
I didn't quite understand how I can do data augmentation with my own dataset. I tried create different .yml configs with all databases, paths, etc. but it didn't work out. 
Can anyone explain how can I create my own dataset for data augmentation and use it while training? 
Any help is appreciated. 
Thanks in advance.

**Comment by hbredin** [comment]
Hi @glebss. Thanks for your interest in pyannote.audio.

Can you please clarify what you want to achieve exactly? Do you want to apply data augmentation (e.g. adding noise from MUSAN) on your own dataset or do you want to use your own noise database?

**Comment by hbredin** [comment]
Can you also please let me know what you tried already?

**Comment by glebss** [comment]
Hi @hbredin 
What I tried so far:
I created config.yml file for my dataset the same way you explain it here https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/own_data/train and also created .rttm file with annotations. Then I changed data_augmentation section in experiment config.yml by changing "collection" string in accordance with the name I declared in dataset config.yml file. Also I added "db_yml" line to this section with the path to dataset configuration file. 
Furthermore I tried creating config.yml describing both main dataset and dataset for augmentation.
Actually my goal was to augment my training data with not whole MUSAN database but only with it's "noise" part. Eventually I just changed collection line in experiment configuration from "MUSAN.Collection.BackgroundNoise" to "MUSAN.Collection.Noise" and it worked out. 
Although I achieved my goal but still it would be great and useful to know how can one augment training data with its own dataset.

**Comment by hbredin** [comment]
Thanks for your update. I better understand what you wanted to achieve.

For now, creating your own data data augmentation database is not easy nor documented.

To make it easy, one would need to update `pyannote.database` to support custom `Collection` protocol. [For now, it only supports `SpeakerDiarization` protocols.](https://github.com/pyannote/pyannote-database/blob/4708aa3b0a392d97a66c25e626cb4b5eb65f146f/pyannote/database/custom.py#L252-L257) 

Would you be interested in contributing such a feature? 
I would be happy to review a pull request

**Comment by hbredin** [comment]
FYI,`pyannote.database` has been updated to support custom `Collection` protocol.
See https://github.com/pyannote/pyannote-database#collections for details.
