### ISSUE TITLE
ValueError: Could not find any protocol for "AMI" database. 

### ISSUE THREAD

**Issue by chrisspen** [pyannote/pyannote-audio#216]
I've installed the develop branch and I'm attempting to execute the tutorial code [here](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/own_data/pretrained), but it immediately fails with the error.

     ValueError: Could not find any protocol for "AMI" database. Please refer to pyannote.database documentation to learn how to define them: https://github.com/pyannote/pyannote-database

Unfortunately, the provided documentation link doesn't explain what AMI is nor how to install it. Oddly, there seems to be no mention of AMI at the provided link at all. If AMI is required to use pyannotate, it would be appreciated if there was some explanation for what that is and how to install it.

**Comment by hbredin** [comment]
[AMI](https://github.com/pyannote/pyannote-db-odessa-ami) is a dataset that can be used to benchmark speaker diarization systems. It is not required to use `pyannote.audio`.

Please follow the tutorials in order to get a better idea.

**Comment by chrisspen** [comment]
Thank you. Like I said, I was following a tutorial, but it doesn't link to that package for loading the AMI files.
