### ISSUE TITLE
Issue when processing too much data

### ISSUE THREAD

**Issue by jiayu2B** [pyannote/pyannote-audio#217]
Hi, I found an issue when using pyannote with database I created. The thing is that the training speed is too slow, nearly 10s/batch, and impossible to train. 
I think the reason is that I used my database, which contains 5 million .npy files ( 900 GB), 30 million lines of .mdtm and 5 million lines of .uem files. Perhaps GPU cannot hold that much, and it use CPU instead.
When I use 5 thousand .npy files, this problem disappeared, and the training speed is 10 batchs/s.
Do you know the reason why this issue occurs? And how can I fix it? 
Thank you!

**Comment by hbredin** [comment]
Closing this stalled issue. Please re-open if needed.
