### ISSUE TITLE
the default value of bidirectional in models

### ISSUE THREAD

**Issue by yinruiqing** [pyannote/pyannote-audio#22]
In `pyannote-audio/pyannote/audio/labeling/models.py`. 
The default value of `bidirectional ` should be in
`{False, 'ave', 'concat'}` . Not `True`.

**Comment by hbredin** [comment]
You're right. Docstring even says it should be 'concat'.
For simple bugs like that, can you provide a pull request? I'll merge it quickly...

**Comment by yinruiqing** [comment]
I have done. I create a new branch, and when I did the pull request, it also includes some old commits. You can ignore them.
