### ISSUE TITLE
Use pytorch-lightning

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#227]
Looks like [pytorch-lightning](https://williamfalcon.github.io/pytorch-lightning/) could advantageously replace `pyannote.audio.trainer`.

**Comment by hbredin** [comment]
https://towardsdatascience.com/from-pytorch-to-pytorch-lightning-a-gentle-introduction-b371b7caaf09

**Comment by mogwai** [comment]
Closed by #407
