### ISSUE TITLE
Error when Validate Speaker Embedding on DIHARD dataset

### ISSUE THREAD

**Issue by jukaradayi** [pyannote/pyannote-audio#230]
Hi, 

I'm trying to run the Speaker Diarization Pipeline on the DIHARD dataset and I'm encountering error in the Speaker-Embedding step (the SAD & SCD steps went fine). 

First, I noticed that the [speaker embedding tutorial](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/models/speaker_embedding) does not seem to be up to date, as the validation step asks for a `--duration` (using the same config.yml file).

The Speaker Embedding training runs without error, but when I try to run the validation, I obtain the following error on file tst/DH_0168 :  

```
$pyannote-speaker-embedding validate baseline_mfcc_model_speaker_embedding/train/X.SpeakerDiarization.DIHARD_all.train/ X.SpeakerDiarization.DIHARD_all --gpu --duration=2.0 --subset=test

Traceback (most recent call last):
  File "/home/jkaradayi/.conda/envs/pyannote-mps/bin/pyannote-speaker-embedding", line 11, in <module>
    load_entry_point('pyannote.audio', 'console_scripts', 'pyannote-speaker-embedding')()
  File "/scratch2/jkaradayi/projects/MPS_ICASSP19/pyannote-audio/pyannote/audio/applications/speaker_embedding.py", line 659, in main
    in_order=in_order)
  File "/scratch2/jkaradayi/projects/MPS_ICASSP19/pyannote-audio/pyannote/audio/applications/base.py", line 347, in validate
    validation_data=validation_data)
  File "/scratch2/jkaradayi/projects/MPS_ICASSP19/pyannote-audio/pyannote/audio/applications/speaker_embedding.py", line 284, in validate_epoch
    validation_data=validation_data)
  File "/scratch2/jkaradayi/projects/MPS_ICASSP19/pyannote-audio/pyannote/audio/applications/speaker_embedding.py", line 466, in _validate_epoch_diarization
    msg = (f'No embedding for {turn:s} in {uri:s}.')
TypeError: unsupported format string passed to Segment.__format__ 
```

When I try to run the validation step using a smaller duration, it works (although the file it failed on previously is 10s long, so I'm not sure why it failed), but yields negative values:

```
$ pyannote-speaker-embedding validate baseline_mfcc_model_speaker_embedding/train/X.SpeakerDiarization.DIHARD_all.train/ X.SpeakerDiarization.DIHARD_all --gpu --duration=0.5 --subset=test

coverage@0.90purity | Epoch #16 = -8.56435% (best) | Epoch #16 = -8.56435%: : 0iteration [04:45, ?iteraticoverage@0.90purity | Epoch #16 = -8.56435% (best) | Epoch #16 = -8.56435%: : 1iteration [04:45, 285.93s/iteration]
```

Do you have any insight on what might be going wrong ?

Thank you in advance, 

-J

**Comment by hbredin** [comment]
> First, I noticed that the [speaker embedding tutorial](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/models/speaker_embedding) does not seem to be up to date, as the validation step asks for a `--duration` (using the same config.yml file).

I'd happily merge a pull request on the tutorial fixing this discrepancy.

> The Speaker Embedding training runs without error, but when I try to run the validation, I obtain the following error on file tst/DH_0168 :
> 
> ```
>   File "/scratch2/jkaradayi/projects/MPS_ICASSP19/pyannote-audio/pyannote/audio/applications/speaker_embedding.py", line 466, in _validate_epoch_diarization
>     msg = (f'No embedding for {turn:s} in {uri:s}.')
> TypeError: unsupported format string passed to Segment.__format__ 
> ```

Commit  b8dd622 fixes this `TypeError` but you will still get a `ValueError`.
Apparently, a speech turn in one of the file has no corresponding embeddings.
Re-run with the above fix and it should tell you which one: from there, you should be able to infer what went wrong.
 
> When I try to run the validation step using a smaller duration, it works (although the file it failed on previously is 10s long, so I'm not sure why it failed), but yields negative values:

> ```
> coverage@0.90purity | Epoch #16 = -8.56435% (best) | Epoch #16 = -8.56435%: : 0iteration [04:45, ?iteraticoverage@0.90purity | Epoch #16 = -8.56435% (best) | Epoch #16 = -8.56435%: : 1iteration [04:45, 285.93s/iteration]
> ```

Negative values are "normal" behavior. It simply means that no threshold can get you a 90% purity. 
-8% means that the best you can do with the current model is 90-8=82%. Use --purity=0.8 option to ask for 80% purity and you should get positive coverage.

That being said, it seems ambitious to train speaker embeddings on DIHARD, especially since we don't have absolute (ie corpus-wide) labels as far as I know.

**Comment by hbredin** [comment]
By the way, I recently trained a pipeline on DIHARD.
Results are available in Table 5 of [this paper](https://arxiv.org/abs/1911.01255).

If you are looking for output RTTMs, I plan to make them public as well.

**Comment by jukaradayi** [comment]
Thanks for the paper and the info ! Indeed, we're going to train on another dataset than DIHARD for the speaker embedding, as you said. 
But just for debugging, I still have some issues. Now I manage to run the validation, I have a positive value for the coverage, but I end up with the following **params.yml** file in the validate folder (ran an experiment on just 1 epoch for debugging purposes, but I had the same resultats for a fully trained network):
`coverage@0.70purity: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - f8
  - 0
  - 1
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  mGBpUIDAzD8=
epoch: 1
`

**Comment by hbredin** [comment]
Commit f5fc4ca should fix this.

**Comment by jukaradayi** [comment]
Works perfectly now, thanks a lot ! (we can close the issue)
