### ISSUE TITLE
DomainAware has an error on develop branch

### ISSUE THREAD

**Issue by Mymoza** [pyannote/pyannote-audio#242]
When I try to run a training for the `DomainAwareSpeechActivityDetection` with the current develop branch, I get this error:

``` 
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/train/schedulers.py", line 317, in on_train_start
    super().on_train_start(trainer)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/train/schedulers.py", line 61, in on_train_start
    trainer.base_learning_rate_ = self.auto_lr(trainer)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/train/schedulers.py", line 144, in auto_lr
    loss = trainer.batch_loss(batch)['loss']
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/labeling/tasks/speech_activity_detection.py", line 299, in batch_loss
    domain_scores = self.activation_(self.domain_classifier_(intermediate))
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/models/models.py", line 163, in forward
    output, hidden = self.rnn_(features)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 559, in forward
    return self.forward_tensor(input, hx)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 539, in forward_tensor
    output, hidden = self.forward_impl(input, hx, batch_sizes, max_batch_size, sorted_indices)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 519, in forward_impl
    self.check_forward_args(input, hx, batch_sizes)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 490, in check_forward_args
    self.check_input(input, batch_sizes)
  File "/home/mpgill/anaconda3/envs/pyannote/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 149, in check_input
    expected_input_dim, input.dim()))
RuntimeError: input must have 3 dimensions, got 2
```

I don't know what is causing it yet, just creating the issue for reference

**Comment by hbredin** [comment]
I think AutoLR does not support multiple losses.

Did you set the learning rate manually in the configuration file?
If not, it will default to using AutoLR to automagically guess the best learning rate.

**Comment by Mymoza** [comment]
Here's my config file: 

```
task:
   name: DomainAwareSpeechActivityDetection
   params:
      duration: 2.0      # sequences are 2s long
      batch_size: 64     # 64 sequences per batch
      domain: domain
      attachment: -1
      per_epoch: 1       # one epoch = 1 day of audio

data_augmentation:
   name: AddNoise                                   # add noise on-the-fly
   params:
      snr_min: 10                                   # using random signal-to-noise
      snr_max: 20                                   # ratio between 10 and 20 dBs
      collection: MUSAN.Collection.BackgroundNoise  # use background noise from MUSAN
                                                    # (needs pyannote.db.musan)
feature_extraction:
   name: RawAudio      # use MFCC from librosa
   params:
     sample_rate: 16000

architecture:
   name: pyannote.audio.models.PyanNet
   params:
     rnn:
        unit: LSTM
        hidden_size: 128
        num_layers: 2
        bidirectional: True
     ff:
        hidden_size: [128, 128]

scheduler:
   name: CyclicScheduler        # use cyclic learning rate (LR) scheduler
   params:
      learning_rate: auto       # automatically guess LR upper bound
      epochs_per_cycle: 14      # 14 epochs per cycle
```

My learning rate is set manually with the `scheduler` parameter if I understand well. 

It doesn't work since this commit: https://github.com/pyannote/pyannote-audio/commit/20196b8a6927d9362fb1e144f280addfce382cfb 

I tried with the previous commit #214 and it worked fine, and since #211 I get this error... 

`I think AutoLR does not support multiple losses.`
If you're talking about the domain branch loss and the VAD loss, then there was always 2 losses, right?

**Comment by hbredin** [comment]
@MarvinLvn any insights? 

FYI @Mymoza,  all experiments in [this paper](https://arxiv.org/abs/1910.10655) have been done with:
- domain-adversarial scenario
- attachment = 0
- MSELoss

Also, I am not sure negative attachment is still supported.

**Comment by MarvinLvn** [comment]
@Mymoza

1° I can't really make sense of a negative attachment, so I think it might be preferable to go with a positive attachment : 
attachment := 0 for branching straight after sincnet
attachment := 1 for branching after your first LSTM layer
attachment := 2 for branching after your second LSTM layer

Negative attachment is supported since python support negative indexing. Therefore, if your model contain 2 LSTM layers, and you provide an attachment whose value is -1, you'll put the domain classification branch after the last layer. Since my_list[-1] in python, means "last value of my_list"

2° You don't provide any configuration for the architecture corresponding to the domain classification branch. Therefore, it uses the default configuration for the RNN, which is, according to the docstring : 

```
    n_features : `int`
        Input feature shape.
    unit : {'LSTM', 'GRU'}, optional
        Defaults to 'LSTM'.
    hidden_size : `int`, optional
        Number of features in the hidden state h. Defaults to 16.
    num_layers : `int`, optional
        Number of recurrent layers. Defaults to 1.
    bias : `boolean`, optional
        If False, then the layer does not use bias weights. Defaults to True.
    dropout : `float`, optional
        If non-zero, introduces a Dropout layer on the outputs of each layer
        except the last layer, with dropout probability equal to dropout.
        Defaults to 0.
    bidirectional : `boolean`, optional
        If True, becomes a bidirectional RNN. Defaults to False.
    concatenate : `boolean`, optional
        Concatenate output of each layer instead of using only the last one
        (which is the default behavior).
    pool : {'sum', 'max', 'last', 'x-vector'}, optional
        Temporal pooling strategy. Defaults to no pooling.
```

As you can see, in the default configuration, no pooling is applied, and that is why you get the dimension error. You give 2 seconds long sub-sequences to this branch, and you ask for a prediction on the domain which is a property at the scale of the sub-sequence.
To be a bit more explicit : 

```
1 sub-sequence = N predictions on SPEECH/NON-SPEECH  ## This is a frame scale property
1 sub-sequence = 1 prediction on the domain ## This is a subsequence scale property 
```

Therefore, you have to apply pooling ! 
That being said, it might be wiser to check directly that a pooling strategy has been provided by the user in the **__init__** function of the **DomainAwareSpeechActivityDetection** class though ...

Can you take care of that @Mymoza ?

**Comment by Mymoza** [comment]
Oh, I understand now! Thank you for your explanation! 

Yes, I can do that. 

I wasn't sure if you prefer a default pooling strategy `rnn.update({'pool' : 'sum'})` to be used or to raise an error, I suggested something in this PR: #241.

**Comment by hbredin** [comment]
Closing because the original issue has been solved.
 Will look at the PR when I find the time.
