### ISSUE TITLE
Detailed Explanation of Speech Activity Detection Algorithm

### ISSUE THREAD

**Issue by picheny-nyu** [pyannote/pyannote-audio#252]
The documentation points to an article which references a paper by Gelly and Gauvain on VAD. However, that paper seems to only be focused on speech recognition WER and seems to require a complete word transcription. I am therefore not sure it is relevant for explaining how VAD works in pyannote. Can this be clarified?

**Comment by hbredin** [comment]
Section 2 of [this preprint](https://arxiv.org/abs/1910.10655) describes what is currently implemented in `pyannote.audio`.

If you followed [this tutorial](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/models/speech_activity_detection), the difference with the above preprint is that features are handcrafted (MFCC) rather than jointly trained with the network ([SincNet](https://arxiv.org/abs/1808.00158)).

**Comment by picheny-nyu** [comment]
Thanks again very much! How are the default MFCCs computed? (How many filters, are deltas being used, etc). 

Also I am running 8 KHz data. I assume the noises being used for data augmentation are being downsampled?

**Comment by hbredin** [comment]
> Thanks again very much! How are the default MFCCs computed? (How many filters, are deltas being used, etc).

The configuration file contains those details in the `feature_extraction` part.

> Also I am running 8 KHz data. I assume the noises being used for data augmentation are being downsampled?

If you use the configuration file as is, the opposite is happening. Your data is upsampled to 16 KHz.
See `sample_rate: 16000` in `feature_extraction` part. Make it `sample_rate: 8000`.

**Comment by picheny-nyu** [comment]
Thanks again for the response. I do have the sample rate set to 8000.

feature_extraction:
   name: LibrosaMFCC      # use MFCC from librosa
   params:
      e: False            # do not use energy
      De: True            # use energy 1st derivative
      DDe: True           # use energy 2nd derivative
      coefs: 19           # use 19 MFCC coefficients
      D: True             # use coefficients 1st derivative
      DD: True            # use coefficients 2nd derivative
      duration: 0.025     # extract MFCC from 25ms windows
      step: 0.010         # extract MFCC every 10ms
      sample_rate: 8000  # convert to 16KHz first (if needed)

**Comment by hbredin** [comment]
Closing the issue as I believe it is solved. Please re-open if needed.
