### ISSUE TITLE
How to create the figure

### ISSUE THREAD

**Issue by yining4869** [pyannote/pyannote-audio#262]
Hi @hbredin,
I followed the steps give from https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/models/overlap_detection. And I'm curious about how to create the figure as shown below, the link you gave isn't available now.
![results](https://user-images.githubusercontent.com/24437017/71508094-ac231180-28c1-11ea-8522-146a27ffc797.png)

**Comment by hbredin** [comment]
I just fixed the broken link.
