### ISSUE TITLE
Resegmentation module is not available: No module named 'pyannote.audio.utils'

### ISSUE THREAD

**Issue by couch-potahto** [pyannote/pyannote-audio#266]
As per the tutorials, I ran `pyannote-change-detection train --cpu --to=1000 --subset=train ${EXPERIMENT_DIR} AMI.SpeakerDiarization.MixHeadset` but the console returned the following error:
`(pyannote_duo) root@DESKTOP-M99DC4S:/mnt/c/Users/willi/Desktop/pyannote_audio_project# pyannote-change-detection train --cpu --to=1000 --subset=train ${EXPERIMENT_DIR} AMI.SpeakerDiarization.MixHeadset
Resegmentation module is not available: No module named 'pyannote.audio.utils'
Usage:
  pyannote-change-detection train [options] <experiment_dir> <database.task.protocol>
  pyannote-change-detection validate [options] [--every=<epoch> --chronological --purity=<purity>] <train_dir> <database.task.protocol>
  pyannote-change-detection apply [options] [--step=<step>] <validate_dir> <database.task.protocol>
  pyannote-change-detection -h | --help
  pyannote-change-detection --version`

May I know how I can fix this issue?
Thank you!

**Comment by hbredin** [comment]
Option `--cpu` does not exist: training is done on CPU by default. 
Just drop the erroneous `--cpu` option and it should train...

**Comment by MarvinLvn** [comment]
*pyannote/audio/labeling/tasks/resegmentation.py*

line 47 : 

`from pyannote.audio.utils.path import mkdir_p`

should be changed to : 

`from pyannote.audio.util import mkdir_p`

Example of good call : 

*pyannote/audio/features/precomputed.py*
line 40
`from pyannote.audio.util import mkdir_p`

**Comment by MarvinLvn** [comment]
I've just created the PR

**Comment by hbredin** [comment]
Thank @MarvinLvn. 

The PR is merged but I still believe this issue was related to the use of --cpu option. 

The message `Resegmentation module is not available: No module named 'pyannote.audio.utils'` was just a warning.

@couch-potahto Can you please confirm that removing --cpu option solves your issue?

**Comment by couch-potahto** [comment]
@MarvinLvn @hbredin 
Removing --cpu still causes the same error to pop up, and I have done as @MarvinLvn has done by changing the faulty import which fixes the problem. 

Thank you for both your help!
