### ISSUE TITLE
Speaker Embedding validate unable to find embedding for some label (files).

### ISSUE THREAD

**Issue by alamnasim** [pyannote/pyannote-audio#270]
Hi,
I am running pyannote-audio for my hinglish dataset which contain almost 100k entries in my train.rttm and 5302 speakers. I am having a problem with the speaker_embedding validate part.   
When I train speaker embedding for 200 epochs only because training took lot of time. After training I got specs.yml which contains 1737 entries in classes. 

When I run:
pyannote-speaker-embedding validate --every=1 --gpu --purity=0.8 --duration=0.5 --subset=test ${TRAIN_DIR} odiosd.SpeakerDiarization.Hinglish

I got this error :
![Screenshot from 2020-01-14 15-04-45](https://user-images.githubusercontent.com/26841776/72347178-8be6b580-36fd-11ea-9d44-63612d16d2fa.png)

If I all the annotation corresponding to this file is deleted still i get the same error.
So I am not able to understand why do I get this error? please help me!

If i try to create a new virtual environment and do fresh installation all the installation command run sucessfully but  when i import datbases, i got this error:
>>>from pyannote.database import get_databases
error:

File "/home/ubuntu/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/parser/annotation/repere.py", line 33, in <module>
    from pyannote.core.scores import Unknown
ModuleNotFoundError: No module named 'pyannote.core.scores'

Help me to resolve this error

Thanks
Nasim

**Comment by hbredin** [comment]
Looks like there are multiple issues here. 
For next time, please open one issue per actual problem.

> I am running pyannote-audio for my hinglish dataset which contain almost 100k entries in my train.rttm and 5302 speakers. I am having a problem with the speaker_embedding validate part.
> When I train speaker embedding for 200 epochs only because training took lot of time. After training I got specs.yml which contains 1737 entries in classes.

Can you please share your `config.yml`? It might be due to the `label_min_duration` parameter that is used to remove speakers with less than `label_min_duration` seconds of speech. This is to prevent the system from overfitting on those particular speakers. See https://github.com/pyannote/pyannote-audio/blob/82f7cf6690f1a1182dbedc454d06de61cc59a51e/pyannote/audio/embedding/approaches/triplet_loss.py#L64-L66

> When I run:
> pyannote-speaker-embedding validate --every=1 --gpu --purity=0.8 --duration=0.5 --subset=test ${TRAIN_DIR} odiosd.SpeakerDiarization.Hinglish
> 
> I got this error :

For next time, please avoid screenshot of code. Copy-adn-paste is much more useful, because it is searchable.

> If I all the annotation corresponding to this file is deleted still i get the same error.
> So I am not able to understand why do I get this error? please help me!

Looks like this file contains annotated segments that are outside of the actual duration of the file.
What is the actual duration of the file according to `get_audio_duration`?

```python
>>> from pyannote.audio.features.utils import get_audio_duration
>>> get_audio_duration({'audio': '/path/to/faulty/file.wav'})
```

> If i try to create a new virtual environment and do fresh installation all the installation command run sucessfully but when i import datbases, i got this error:
> 
> > > > from pyannote.database import get_databases
> > > > error:
> 
> File "/home/ubuntu/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/parser/annotation/repere.py", line 33, in
> from pyannote.core.scores import Unknown
> ModuleNotFoundError: No module named 'pyannote.core.scores'

This is due to the recent release of `pyannote.core 3.3` that removes `pyannote.core.scores` completely. I just updated `pyannote.parser` to version 0.8: it should solve this issue.

**Comment by alamnasim** [comment]
Thanks a lot.



> Looks like there are multiple issues here.
> For next time, please open one issue per actual problem.

Yes sure I will take care of this next time.



> Can you please share your `config.yml`? It might be due to the `label_min_duration` parameter that is used to remove speakers with less than `label_min_duration` seconds of speech. This is to prevent the system from overfitting on those particular speakers.

feature_extraction:
   name: Precomputed      # use MFCC from librosa
   params:
      root_dir: tutorials/feature_extraction

architecture:
   name: ClopiNet
   params:
     instance_normalize: True
     rnn: LSTM
     recurrent: [256, 256, 256]
     linear: [256]
     bidirectional: True
     pooling: sum
     batch_normalize: True
     normalize: True

approach:
   name: TripletLoss
   params:
     metric: cosine
     clamp: sigmoid
     margin: 0.0
     min_duration: 0.500
     max_duration: 1.500
     sampling: all
     per_fold: 20
     per_label: 3
     per_epoch: 1
     label_min_duration: 60


> For next time, please avoid screenshot of code. Copy-adn-paste is much more useful, because it is searchable.

Yes sure.



> This is due to the recent release of `pyannote.core 3.3` that removes `pyannote.core.scores` completely. I just updated `pyannote.parser` to version 0.8: it should solve this issue.

yes i have 0.7.1 is installed, ok i will change it to 0.8.

Thank You so much.

**Comment by alamnasim** [comment]
Yes, there was a problem in that file that it was audio file was  not complete while annotation outside audio length.

I am running it again, i will let you know.

Thanks

**Comment by hbredin** [comment]
Great! Closing because the initial issue is solved. 
I am still interested in your final feedback though.
