### ISSUE TITLE
Problem of Zero GPU-Util while High GPU memory usage and High CPU usage

### ISSUE THREAD

**Issue by yining4869** [pyannote/pyannote-audio#271]
Hi, I found the GPU memory usage is very high(by changing the batch-size) but the GPU-util is always being zero when training the model with the AMI dataset or my own dataset(10GB). Btw, the CPU usage is also very high. It cause the training process being too slow, nearly 50s/batch. Then I want to accelerate the training process by setting multi-threads but I can only find the parameter n_jobs using in the "validate" module. So I wonder the way that I can specify the numbers of the threads(Maybe use the Dataloader(), I guess?) And do you know the reason why this issue occurs? Is there any appropriate way to adopt GPU during training the model?
Thanks so much!

**Comment by hbredin** [comment]
I just pushed a major update to pyannote.audio in `develop` branch.

The batch generation process has been greatly optimized and this should solve your issue. Can you please try again by updating to the latest version available in `develop` branch and following the (updated) tutorials again? 

In particular, there is now a `--parallel=N` option that makes the batch generator use (at most) that many background threads. You might not notice a big difference for the first few batches but  you will eventually, once the batch generator reaches its cruising speed (it automagically adapts the number of threads after a little while). I'd be happy to hear feedback about it.

**Comment by yining4869** [comment]
> I just pushed a major update to pyannote.audio in `develop` branch.
> 
> The batch generation process has been greatly optimized and this should solve your issue. Can you please try again by updating to the latest version available in `develop` branch and following the (updated) tutorials again?
> 
> In particular, there is now a `--parallel=N` option that makes the batch generator use (at most) that many background threads. You might not notice a big difference for the first few batches but you will eventually, once the batch generator reaches its cruising speed (it automagically adapts the number of threads after a little while). I'd be happy to hear feedback about it.

Thanks for you quick reply! I'll test the new version as soon as possible and give the feedback to you.

**Comment by yining4869** [comment]
Hi,
I've test the new version and the problem of Zero GPU-Util is truly fixed. The training speed is really fast compared from the old version. Thanks so much for all the work you have done.
But there are some issues in the new tutorials. There is a error if I follow the pyannote-audio/tutorials/data_preparation/ directly:

> ValueError: Could not find any protocol for "AMI" database. 

I fix this error by using the following command just like the old version:

> pip install pyannote.db.odessa.ami

But when I installed the AMI plugin, the database.yml file is thought to save to the following default location which is the same as the old version:

> ~/.pyannote/database.yml

So if I use the command in the new tutorial:

> $ export PYANNOTE_DATABASE_CONFIG=${TUTORIAL_DIR}/database.yml

It will cause the error:
ValueError: Could not find file "EN2001a.Mix-Headset".
Here is some suggestion for your new tutorial. 
Thanks again for releasing code as open source!

**Comment by yining4869** [comment]
Sorry, I just saw the **pyannote-audio/tutorials/feature_extraction/**
and the error I met can be all solved by following the above tutorial.
Thx!

**Comment by hbredin** [comment]
Closing this issue as the original problem has been solved.
Please open a new one about `pyannote.database` if needed.
