### ISSUE TITLE
Generate RTTM files for Speaker Change Points

### ISSUE THREAD

**Issue by couch-potahto** [pyannote/pyannote-audio#285]
I have followed the tutorial for using the pretrained models on my own data for speaker change detection and I was wondering how I could generate an RTTM file containing the speaker change points with my results

Thank you for your time once again

**Comment by hbredin** [comment]
This should do the trick:

```python
speech_turns = partition.crop(speech)
with open('result.rttm', 'w') as fp:
    speech_turns.to_annotation().write_rttm(fp)
```

I recommend you read [pyannote.core documentation](pyannote.github.io/pyannote-core/) to learn more about what you can do with those `pyannote.core.Timeline` and `pyannote.core.Annotation` instances.

**Comment by hbredin** [comment]
Closing stalled (fixed?) issue. Please re-open if needed.
