### ISSUE TITLE
[Cont.] Reproducing results of "pyannote.audio" and "overlap-aware diarization" papers

### ISSUE THREAD

**Issue by yat011** [pyannote/pyannote-audio#292]
Hi,
I applied the pretrained SAD model in [https://github.com/pyannote/pyannote-audio/tree/develop/models/sad/ami/712d7e3184](https://github.com/pyannote/pyannote-audio/tree/develop/models/sad/ami/712d7e3184) on the AMI development set and test set.  
However, I got the results which are slighty different from params.yml and the paper.

For development, the detection error rate which I got is 5.69, but the detection_error_rate in the provided params.yml is 5.8
There are also differences in test set.

I attach the generated results for your reference.

[AMI.SpeakerDiarization.MixHeadset.test.eval.txt](https://github.com/pyannote/pyannote-audio/files/4138753/AMI.SpeakerDiarization.MixHeadset.test.eval.txt)
[AMI.SpeakerDiarization.MixHeadset.development.eval.txt](https://github.com/pyannote/pyannote-audio/files/4138754/AMI.SpeakerDiarization.MixHeadset.development.eval.txt)

Using setup:
pyannote-audio commit 62b8eee17eabd476e0ac4f3bf1b995ba6b2b87ee

Thanks a lot for your help in advance.

_Originally posted by @yat011 in https://github.com/pyannote/pyannote-audio/issues/263#issuecomment-580674762_

**Comment by hbredin** [comment]
It looks like you are missing
* 2 files in test set (`EN2002a.Mix-Headset` and `EN2002c.Mix-Headset`).
* 5 files in development set (`IB4002.Mix-Headset`, `IB4003.Mix-Headset`, `IB4004.Mix-Headset`, `IB4010.Mix-Headset`, `IB4011.Mix-Headset`)

This explains the difference. I guess you are using `pyannote.db.odessa.ami` instead of the evaluation protocol defined in the [data preparation tutorial](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/data_preparation).

**Comment by yat011** [comment]
Oh, I see. Yes, I am using pyannote.db.odessa.ami.
Let me follow the tutorial instead of using pyannote.db.odessa.ami

So, for the papers, you are the data preparation tutorial. Is that right?

Thanks a lot for the quick reply and help!

**Comment by hbredin** [comment]
Yes, numbers in the paper use the data described in the data preparation tutorial.

**Comment by yat011** [comment]
Thanks a lot!
I can reproduce the SAD result on AMI.

Btw,  the DER of pyannote with overlap in Table 5 in the pyannote.audio paper is 24.8.
In the overlap-aware paper, the DER in Table3 is 23.8.  
May I know the reason of the difference?

**Comment by hbredin** [comment]
The difference comes from the fact that *overlap-aware* paper uses VB resegmentation, while *pyannote-audio* paper uses LSTM resegmentation.

**Comment by yat011** [comment]
Got it. Thanks a lot!
