### ISSUE TITLE
Use of Speaker Embeddings for Clustering

### ISSUE THREAD

**Issue by tjtalkar** [pyannote/pyannote-audio#293]
I was able to extract out speaker embeddings for unlabeled recordings that I want to be able to diarize and then separate out audio that will be labeled for each speaker in the recording. As of now, I understand that we can create the speaker embeddings on the unlabeled file, but how would I take the extra step of matching each embedding to a particular speaker using the speaker diarization pipeline to cluster? 

More specifically - if this helps, I'm a little confused as to how to use the Speaker Diarization Pipeline on my set of data, as I'm not sure whether the sad/scd/embeddings that are precomputed can be from the pretrained models? And furthermore, how would I need to format my own data to be able to apply any precomputed pipeline on it (for example, the AMI?). I wasn't able to see anything specific about unlabeled datasets.

Thank you!

**Comment by tjtalkar** [comment]
More specifically - if this helps, I'm a little confused as to how to use the Speaker Diarization Pipeline on my set of data, as I'm not sure whether the sad/scd/embeddings that are precomputed can be from the pretrained models? And furthermore, how would I need to format my own data to be able to apply any precomputed pipeline on it (for example, the AMI?). I wasn't able to see anything specific about unlabeled datasets.

**Comment by hbredin** [comment]
> More specifically - if this helps, I'm a little confused as to how to use the Speaker Diarization Pipeline on my set of data, as I'm not sure whether the sad/scd/embeddings that are precomputed can be from the pretrained models? 

Yes, you can use sad/scd/emb precomputed from pretrained models (though, it is obviously better to use models trained on annotated data similar to your test data).

> And furthermore, how would I need to format my own data to be able to apply any precomputed pipeline on it (for example, the AMI?). I wasn't able to see anything specific about unlabeled datasets.

For unlabeled datasets, the [data preparation tutorial](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/data_preparation) still holds. The only difference is that you have to remove the `annotation` entries in the `database.yml` file.

**Comment by tjtalkar** [comment]
Thank you! I'll follow the data preparation tutorial for the unlabeled data then, and then use it as a testing set.

When it mentions the path to the precomputed sad/scd/emb files, then, is that to anything that was computed on the pretrained model set? Is that the path to the params.yaml file or would we need to go through the entire pipeline training on the desired dataset, and save out files into the "training" directory?

Thanks!

**Comment by hbredin** [comment]
> When it mentions the path to the precomputed sad/scd/emb files, then, is that to anything that was computed on the pretrained model set? Is that the path to the params.yaml file or would we need to go through the entire pipeline training on the desired dataset, and save out files into the "training" directory?

The [speaker diarization pipeline tutorial](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/pipelines/speaker_diarization) does assume that you trained your own SAD, SCD and EMB models. 

However, it can actually rely on pretrained models by first running the following commands that will use pretrained models to populate `/path/to/precomputed`:

```bash
$ mkdir -p /path/to/precomputed
$ pyannote-audio sad apply --gpu --pretrained=sad_ami /path/to/precomputed YourDatabase.SpeakerDiarization.YourProtocol
$ pyannote-audio scd apply --gpu --pretrained=scd_ami /path/to/precomputed YourDatabase.SpeakerDiarization.YourProtocol
$ pyannote-audio emb apply --gpu --pretrained=emb_voxceleb /path/to/precomputed YourDatabase.SpeakerDiarization.YourProtocol
```

Then, you can update the configuration file to contain these lines:

```yaml
      sad_scores: /path/to/precomputed/sad_ami
      scd_scores: /path/to/precomputed/scd_ami
      embedding: /path/to/precomputed/emb_voxceleb
```

**Comment by hbredin** [comment]
Closing the issue. Please re-open if needed.
