### ISSUE TITLE
error while using my pretrained model 

### ISSUE THREAD

**Issue by greatforu** [pyannote/pyannote-audio#299]
I am working on the native language and I have trained the model for SAD and SCP but it is showing EXPANDUSER error. 

from pyannote.audio.features import Pretrained

sad = Pretrained(validate_dir='/home/mayank/hocdemo/pyannote-models/sad_model/0079.pt')
scd = Pretrained(validate_dir='/home/mayank/hocdemo/pyannote-models/scd_model/0020.pt')
''' I even gave just the path as directory i.e., /home/mayank/hocdemo/pyannote-models/sad_model
but this also shows expand user issue '''

AttributeError                            Traceback (most recent call last)
<ipython-input-78-b44ff12aa1a8> in <module>
      1 from pyannote.audio.features import Pretrained
----> 2 sad = Pretrained(validate_dir='/home/mayank/hocdemo/pyannote-models/sad_model/0079.pt')
      3 scd = Pretrained(validate_dir='/home/mayank/hocdemo/pyannote-models/scd_model/0020.pt')

~/anaconda/envs/pyannote/lib/python3.7/site-packages/pyannote/audio/features/pretrained.py in __init__(self, validate_dir, epoch, augmentation, duration, step, batch_size, device, return_intermediate)
     72                        model_path: str = "/home/kamal/hocdemo/pyannote-models/sad_model/0079.pt"
     73                        return_intermediate = None):
---> 74 
     75         self.validate_dir = validate_dir.expanduser().resolve(strict=True)
     76 

AttributeError: 'str' object has no attribute 'expanduser'

Any help will be Appreciated, Thanks!

**Comment by juanmc2005** [comment]
Hi,
This is certainly a bug, because I see the typing of `validate_dir` accepts strings in `pretrained.py`.
In the meantime, can you try using ```Pretrained(validate_dir=Path('/path/to/your/model'))``` ? using the `Path` class from `pathlib` should solve your problem.

**Comment by hbredin** [comment]
Thanks for catching this bug.
This is now fixed in `develop` branch.
