### ISSUE TITLE
Yaafe with Python 3

### ISSUE THREAD

**Issue by tracek** [pyannote/pyannote-audio#30]
Hey,

Guess we both were looking forward to the Python 3 support on yaafe. Check it out, it works well for me:
https://github.com/Yaafe/Yaafe

**Comment by hbredin** [comment]
Thanks for pinging me. 

I actually made it happen :-) 
See https://github.com/Yaafe/Yaafe/pull/43

The "develop" branch has been updated and the next release will no longer rely on Python 2.7. See https://github.com/pyannote/pyannote-audio/commit/5b1430dc7076c26b1f7ec7b5e539c2420e54b05e#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by tracek** [comment]
I knew I saw your name somewhere :). Thanks a lot!
