### ISSUE TITLE
Changing Sampling Rate Fails in SAD

### ISSUE THREAD

**Issue by picheny-nyu** [pyannote/pyannote-audio#300]
I downsampled the AMI and Musan data bases to 8 KHz. I changed the sampling rate in config.yml from the tutorial/models section  from 16000 to 8000.  

I get the error message:

**ValueError: Expected input batch_size (37184) to match target batch_size (75136).**

I attach the traceback as well. 

I assume something else needs to be changed in the config file but I don't know what. 

Training:   0%|                                      | 0/200 [00:00<?, ?epoch/s]

Epoch #1:   0%|                                      | 0/675 [00:00<?, ?batch/s][ATraceback (most recent call last):
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/pyannote-feb32020/bin/pyannote-audio", line 8, in <module>
    sys.exit(main())
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/pyannote-feb32020/lib/python3.7/site-packages/pyannote/audio/applications/pyannote_audio.py", line 333, in main
    app.train(protocol, **params)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/pyannote-feb32020/lib/python3.7/site-packages/pyannote/audio/applications/base.py", line 214, in train
    for _ in iterations:
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/pyannote-feb32020/lib/python3.7/site-packages/pyannote/audio/train/trainer.py", line 418, in fit_iter
    loss = self.batch_loss(batch)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/pyannote-feb32020/lib/python3.7/site-packages/pyannote/audio/labeling/tasks/base.py", line 631, in batch_loss
    mask=mask),
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/pyannote-feb32020/lib/python3.7/site-packages/pyannote/audio/labeling/tasks/base.py", line 539, in loss_func
    reduction='mean')
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/pyannote-feb32020/lib/python3.7/site-packages/torch/nn/functional.py", line 1836, in nll_loss
    .format(input.size(0), target.size(0)))
**ValueError: Expected input batch_size (37184) to match target batch_size (75136).**

Training:   0%|▏                             | 1/200 [00:03<10:40,  3.22s/epoch]

**Comment by hbredin** [comment]
Can you please provide the content of your configuration file? 

Also, when did you last update your pyannote-audio codebase? 
(I am asking because a [bug](https://github.com/pyannote/pyannote-audio/issues/289) related to sampling rates was [recently fixed](https://github.com/pyannote/pyannote-audio/commit/0e004789f49859b98de667c913e96321993d13c1) in `develop` branch.)

**Comment by picheny-nyu** [comment]
Here is what I am using. I tried changing the  sample rate to 8000 producing the above error. The download was done Feb. 3 - please tell me if this is all fixed now. It looks like I may have to provide some parameters explicitly to sincnet though. It all runs if I leave it at 16000, by the way...but I suspect that may be "wrong". 

# A speech activity detection model is trained.
# Here, training relies on 2s-long audio chunks,
# batches of 64 audio chunks, and saves model to
# disk every one (1) day worth of audio.
task:
   name: SpeechActivityDetection
   params:
      duration: 2.0
      batch_size: 64
      per_epoch: 1

# Data augmentation is applied during training.
# Here, it consists in additive noise from the
# MUSAN database, with random signal-to-noise
# ratio between 5 and 20 dB
data_augmentation:
   name: AddNoise
   params:
      snr_min: 5
      snr_max: 20
      collection: MUSAN.Collection.BackgroundNoise

# Since we are training an end-to-end model, the
# feature extraction step simply returns the raw
# waveform.
feature_extraction:
   name: RawAudio
   params:
     sample_rate: 16000

# We use the PyanNet architecture in Figure 2 of
# pyannote.audio introductory paper. More details
# about the architecture and its parameters can be
# found directly in PyanNet docstring.
architecture:
   name: pyannote.audio.models.PyanNet
   params:
      rnn:
         unit: LSTM
         hidden_size: 128
         num_layers: 2
         bidirectional: True
      ff:
         hidden_size: [128, 128]

# We use a constant learning rate of 1e-2
scheduler:
   name: ConstantScheduler
   params:
      learning_rate: 0.01

**Comment by juanmc2005** [comment]
Notice that the feature extraction sample rate in that config file is 16000, have you tried changing this value?

**Comment by picheny-nyu** [comment]
Yes, that is how I got the error at the top in the first place - I changed the value to 8000. It looks to me that I have to pass sincnet a sample_rate parameter as well but was hoping one of the developers could verify that this was actually needed and I am not doing something else wrong.

**Comment by juanmc2005** [comment]
Ok I've just checked, the default sample rate for SincNet is indeed 16000.
You should change it both in feature extraction and in sincnet:

```yaml
sincnet:
    sample_rate: 8000
```

**Comment by hbredin** [comment]
Is the problem solved?

**Comment by picheny-nyu** [comment]
Yes, sorry - above fix worked like a charm. May be worth adding to the documentation.

**Comment by alonshoa** [comment]
ValueError: Expected input batch_size (37184) to match target batch_size (75136).

I had the same issue as @picheny-nyu, in the OVL flow. but adding the param above to the configuration file was half the solution for me.
when I did the change in the config I got exception regarding trying to get ("skip") a value from the configuration dictionary that does not exist. I had to add a parameter skip to the config, and also add an unused param to the init of the sincnet class.
I'm on win 10 pro, with anaconda
I used FISHER dataset and I used MUSAN that I downsampled to 8KHz

**Comment by hbredin** [comment]
Hey @alonshoa, sorry for the delay in answering.

Would you mind sharing your exact `config.yml` so that I can look into this?

**Comment by alonshoa** [comment]
its the same as the OVL toturial but with 
```
feature_extraction:
   name: RawAudio
   params:
      sample_rate: 8000

```

it failed with trying to get ("skip") a value error message. in models.py in pynet init, before the call to sincnet.
I removed the code that try to get it, because I wanted to use sincnet and not MFCCs so I figured that I can.
