### ISSUE TITLE
Possible Error in Validation Section for Speech Activity Detection

### ISSUE THREAD

**Issue by couch-potahto** [pyannote/pyannote-audio#301]
As described by the validation section, when the command
```
`$ export TRN_DIR=${EXP_DIR}/train/AMI.SpeakerDiarization.MixHeadset.train
$ pyannote-audio sad validate --subset=develop --gpu --to=200 --every=10 ${TRN_DIR} `AMI.SpeakerDiarization.MixHeadset`
```
 is run, an error will be produced as such
`AttributeError: 'SpeakerDiarization' object has no attribute 'develop'.`

To solve this, I edited the command to
``$ pyannote-audio sad validate --subset=development --gpu --to=200 --every=10 ${TRN_DIR} `AMI.SpeakerDiarization.MixHeadset`` `and it works

**Comment by picheny-nyu** [comment]
Agree. You beat me to it (in terms of posting!).

**Comment by hbredin** [comment]
Thanks for catching this. This is now fixed.

For next time and easy fixes like this one, feel free to click the "Edit" button directly on Github: this will open a PR for you that I can merge in just one click!
