### ISSUE TITLE
Speaker Diarization Tutorial fails on `apply` stage

### ISSUE THREAD

**Issue by couch-potahto** [pyannote/pyannote-audio#304]
Dear @hbredin ,
When I run `pyannote-pipeline apply ${TRAIN_DIR}/params.yml AMI.SpeakerDiarization.MixHeadset ` as per the speaker diarization tutorial, I get the following error:

`File "/mnt/sdc1/william/fyp_env/bin/pyannote-pipeline", line 10, in <module>
    sys.exit(main())
  File "/mnt/sdc1/william/fyp_env/lib/python3.7/site-packages/pyannote/pipeline/experiment.py", line 426, in main
    experiment = Experiment.from_train_dir(train_dir, training=False)
  File "/mnt/sdc1/william/fyp_env/lib/python3.7/site-packages/pyannote/pipeline/experiment.py", line 156, in from_train_dir
    xp.mtime_ = datetime.fromtimestamp(os.path.getmtime(params_yml))
  File "/home/emre/data3/anaconda3/lib/python3.7/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
NotADirectoryError: [Errno 20] Not a directory: '/mnt/sdc1/william/pyannote_audio_project/tutorials/pipelines/speaker_diarization/train/AMI.SpeakerDiarization.MixHeadset.development/params.yml/params.yml'
`

Please do advice on how I can fix this issue. Thank you

**Comment by hbredin** [comment]
This tutorial indeed needs to be updated -- feel free to create a PR ;-)

```bash
pyannote-pipeline apply ${TRAIN_DIR} AMI.SpeakerDiarization.MixHeadset
```
should solve your problem and will create a bunch of file in `${TRAIN_DIR}/apply`

**Comment by couch-potahto** [comment]
I will if I am able to fix any errors next time!

Regarding the issue, I've already tried

`pyannote-pipeline apply ${TRAIN_DIR} AMI.SpeakerDiarization.MixHeadset`

Unfortunately it returns a key error which I can't quite troubleshoot.

`File "/mnt/sdc1/william/fyp_env/bin/pyannote-pipeline", line 10, in <module>
    sys.exit(main())
  File "/mnt/sdc1/william/fyp_env/lib/python3.7/site-packages/pyannote/pipeline/experiment.py", line 426, in main
    experiment = Experiment.from_train_dir(train_dir, training=False)
  File "/mnt/sdc1/william/fyp_env/lib/python3.7/site-packages/pyannote/pipeline/experiment.py", line 157, in from_train_dir
    xp.pipeline_.load_params(params_yml)
  File "/mnt/sdc1/william/fyp_env/lib/python3.7/site-packages/pyannote/pipeline/pipeline.py", line 461, in load_params
    return self.instantiate(params['params'])
KeyError: 'params'
`

**Comment by couch-potahto** [comment]
@hbredin 
Forgive me for the abrupt comments but I took the liberty to go into
`python3.7/site-packages/pyannote/pipeline/pipeline.py",` to check line 461 which is producing the error and after some print statements I changed the following statement from 

`with open(params_yml, mode='r') as fp:
        params = yaml.load(fp, Loader=yaml.SafeLoader)
return self.instantiate(params['params'])
`
to

`with open(params_yml, mode='r') as fp:
        params = yaml.load(fp, Loader=yaml.SafeLoader)
return self.instantiate(params)
`

which now causes the apply code to run properly. Unfortunately I'm new at this pull request thing so I do not know how to make one for the pyannote package.

**Comment by hbredin** [comment]
As I was saying, the diarization pipeline tutorial is outdated: [`pyannote-pipeline`](https://github.com/pyannote/pyannote-pipeline/) has been updated **after** the tutorial was written. 

That being said, it looks like you did not run the `pyannote-pipeline train ...` part yourself, did you? You used the (outdated) provided `params.yml`, right? This probably explains the error you get. 

Had you run `pyannote-pipeline train ... ` yourself, the content of `params.yml` would be correct and you would not need this fix.

**Comment by couch-potahto** [comment]
Ah okay thank you very much!
