### ISSUE TITLE
Request for brief documentation how to use pretrained model with fine-tuning to change to different speaker embeddings

### ISSUE THREAD

**Issue by daniel347x** [pyannote/pyannote-audio#307]
Greetings!  I am hoping to use pyannote, and I have been studying the documentation and (a little bit) the code, but it is not clear to me if it is possible to start with the pre-trained models and fine-tune it with a relatively small amount of data from a custom dataset with different speakers (and a different number of speakers) to "switch" from the pretrained speaker count and speaker embeddings, to my own (smaller number of) speakers / speaker embeddings.

I would like to use the system for diarization of my own dataset with only a very limited number of annotated samples from my dataset (preferably 0, but a small number would work).

Is this possible, or must I have a full set of data annotated data from my dataset in order to train the system for diarization on my own dataset with its unique speakers and number of speakers?

**Comment by hbredin** [comment]
> Greetings! I am hoping to use pyannote, and I have been studying the documentation and (a little bit) the code, but it is not clear to me if it is possible to start with the pre-trained models and fine-tune it with a relatively small amount of data from a custom dataset with different speakers (and a different number of speakers) to "switch" from the pretrained speaker count and speaker embeddings, to my own (smaller number of) speakers / speaker embeddings.

It was not possible until very recently but recent commits in the `develop` branch made it possible. [This tutorial](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/finetune) explains how to fine-tune a pretrained model. It illustrates the process for speech activity detection but will work the same for speaker embedding: simply replace `sad` by `emb` and you should be good to go.

> I would like to use the system for diarization of my own dataset with only a very limited number of annotated samples from my dataset (preferably 0, but a small number would work).

What you are looking for is unsupervised (= using no annotation) adaptation of pretrained models. 
This is kind of tricky and still a research question. `pyannote.audio` does not support this out of the box. 

> Is this possible, or must I have a full set of data annotated data from my dataset in order to train the system for diarization on my own dataset with its unique speakers and number of speakers?

As it is right now, you should at least provide some annotated data. One way of bootsrapping the annotation would be to apply pretrained models to pre-annotate it and then proceed with manual checking/correction, in an active learning manner.

**Comment by hbredin** [comment]
Closing the issue. Please re-open if needed.
