### ISSUE TITLE
Trouble with tutorial for pretrained model: Visualization

### ISSUE THREAD

**Issue by robertosc** [pyannote/pyannote-audio#314]
Hi
I'm having trouble graphing the first and eight row of the visualization part of pretrained model tutorial.  In this part of the code:
```
#1st row: reference annotation
notebook.plot_annotation(test_file['annotation'], ax=ax[0], time=False)
ax[0].text(notebook.crop.start + 0.5, 0.1, 'reference', fontsize=14)
```
It gives me this error: "KeyError: 'annotation'", am I missing a file address in here or missing a file somewhere? I tried addressing the .test.rttm files of the AMI file, but didn't work either. 

Thanks.

**Comment by hbredin** [comment]
The error message ssimply ays that there is no `'annotation'` key in `test_file` dictionary.

Did you run this line from the tutorial?
```python
test_file = {'uri': 'filename', 'audio': '/path/to/your/filename.wav'}
```

If yes, don't. This is just meant for when you want to run the model on a specific file without going through the process of defining a proper protocol (like you did with AMI).

**Comment by ooza** [comment]
@robertosc 
Did you resolve the problem?
I have tried with my own data using this line
test_file = {'uri': 'filename', 'audio': '/path/to/your/filename.wav'}
but I'm still getting the same error as yours
@hbredin 
Should I annotate the file that I want to test ??
Thanks

**Comment by serene9199** [comment]
Hi,
I had a similar issue while trying it with my own audio file. But I got the diarised output when I tried the following:
`OWN_FILE = {'audio': '/path_to_your_audio_file'}`
`import torch`
`pipeline = torch.hub.load('pyannote/pyannote-audio', 'dia')`
`diarization = pipeline(OWN_FILE)`

**Comment by ooza** [comment]
@serene9199 
Thanks a lot for your help!
Th error was resolved. Now, I'm trying to visualise the result using notebook as recommended by the author and I'm getting this error:
KeyError: 'annotation'
As I understood I should annotate the test file as explained in the data preparation tutorial, Am I right? If yes, how did you proceed to annotate it and where should I put the reference file?
Thanks again

**Comment by hbredin** [comment]
You don't have to annotate your data to visualize the result. 
Just skip the lines that plot the (missing, in your case) reference annotation.

**Comment by ooza** [comment]
@hbredin 
Thanks for your quick reply.
I got just one speaker but my input file includes two.
Am I missing something?
Knowing that I'm working on French  and German languages and my corpus is small and not annotated. Any advice will be appreciated and thanks a lot for this great job you made.
