### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ChristopherLu** [pyannote/pyannote-audio#32]
Hi, when I run `pip install "pyannote.audio==0.3"`, I got the following error msg:

In file included from _pysndfile.cpp:471:0:
  pysndfile.hh:55:21: fatal error: sndfile.h: No such file or directory
   #include <sndfile.h>
                       ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pysndfile
  Running setup.py clean for pysndfile
Failed to build pysndfile

**Comment by hbredin** [comment]
Did you follow the installation procedure? In particular, did you run `conda install -c conda-forge yaafe` first?

**Comment by ChristopherLu** [comment]
Yes, 

(py35-pyannote-audio) hongkaiw@hongkaiw-gpu:~/xiaoxuan_lu/scan/audio_scan/others$ conda install -c conda-forge yaafe
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/hongkaiw/anaconda2/envs/py35-pyannote-audio:
#
yaafe                     0.70                     py35_2    conda-forge

**Comment by hbredin** [comment]
Sorry. I cannot reproduce this issue locally.
I just re-ran everything from scratch and it worked.
In particular, `libsndfile` is installed along with `yaafe`:

```
conda install -c conda-forge yaafe
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /people/bredin/anaconda2/envs/pyannote_audio_#32:

The following NEW packages will be INSTALLED:

    argtable2:  2.13-1            conda-forge
    bzip2:      1.0.6-1           conda-forge
    eigen:      3.3.3-0           conda-forge
    fftw:       3.3.6-1           conda-forge
    lapack:     3.6.1-1           conda-forge
    libflac:    1.3.1-0           conda-forge
    libogg:     1.3.2-0           conda-forge
    libsndfile: 1.0.27-1          conda-forge
    libvorbis:  1.3.5-0           conda-forge
    lzo:        2.06-0
    mpg123:     1.24.0-1          conda-forge
    yaafe:      0.70-py35_2       conda-forge

The following packages will be UPDATED:

    anaconda:   4.4.0-np112py35_0             --> custom-py35_0
    h5py:       2.7.0-np112py35_0             --> 2.7.0-np112py35_1 conda-forge
    hdf5:       1.8.17-1                      --> 1.8.18-0          conda-forge
    pytables:   3.3.0-np112py35_0             --> 3.4.2-np112py35_1 conda-forge

Proceed ([y]/n)? y
```

**Comment by ChristopherLu** [comment]
Sorry, the previous problem solved.

But the new one is;
`AttributeError: '_NamespacePath' object has no attribute 'sort'` when I try to use pip install. Should I use the `Anaconda3` (for now I only have `Andaconda2`). Or, is there  a pyannote-audio version of py2.7? I remember the previous one is based on py27. Thx

**Comment by hbredin** [comment]
Can you please let me know how you solved the first problem?

For the second problem, you have to update `pip` and `setuptools` first.
```
pip install -U pip
pip install -U setuptools
```

I will update the documentation with those two lines.

**Comment by ChristopherLu** [comment]
I just deactivate the `pyannote` conda envand re-activate it again (perhaps we may need source sth. after install yaafe, I am very new to the conda created env, so I just brute-force de-activate...).  

I tried `pip install -U pip`, but got the same error
`AttributeError: '_NamespacePath' object has no attribute 'sort'`

**Comment by hbredin** [comment]
Please start again from scratch following the updated installation instructions available at https://github.com/pyannote/pyannote-audio#installation

**Comment by ChristopherLu** [comment]
I tried from the scratch, but still got the same problem.

**Comment by hbredin** [comment]
The problem comes from an outdated `setuptools` package.
If `pip install -U setuptools` does not work for you, then I am out of ideas on how to solve your problems...

**Comment by hbredin** [comment]
What does `pip list` return? 
Which version of `pip` ? 
Which version of `setuptools`?

**Comment by ChristopherLu** [comment]
All right. When I deactivate the env `pyannote` and run `pip install -U setuptools`, I got successful msg `Requirement already up-to-date: setuptools in /home/myname/anaconda2/lib/python2.7/site-packages`.
But it seems that the current pyannote is based on py35... 
Can I build pyannote with py27? I successfully built all previous pyannote....

**Comment by hbredin** [comment]
You can use py27 -- but I cannot promise I will support it in the future.
I am convinced this is not the issue, though...

Can you please provide the output of `pip list` (in the activated environment)?

**Comment by ChristopherLu** [comment]
output of `pip list`:

alabaster (0.7.10)
anaconda-client (1.6.3)
anaconda-navigator (1.6.2)
anaconda-project (0.6.0)
asn1crypto (0.22.0)
astroid (1.4.9)
astropy (1.3.2)
Babel (2.4.0)
backports.shutil-get-terminal-size (1.0.0)
beautifulsoup4 (4.6.0)
bitarray (0.8.1)
blaze (0.10.1)
bleach (1.5.0)
bokeh (0.12.5)
boto (2.46.1)
Bottleneck (1.2.1)
cffi (1.10.0)
chardet (3.0.3)
click (6.7)
cloudpickle (0.2.2)
clyent (1.2.2)
colorama (0.3.9)
contextlib2 (0.5.5)
cryptography (1.8.1)
cycler (0.10.0)
Cython (0.25.2)
cytoolz (0.8.2)
dask (0.14.3)
datashape (0.5.4)
decorator (4.0.11)
distributed (1.16.3)
docutils (0.13.1)
entrypoints (0.2.2)
et-xmlfile (1.0.1)
fastcache (1.0.2)
Flask (0.12.2)
Flask-Cors (3.0.2)
gevent (1.2.1)
greenlet (0.4.12)
h5py (2.7.0)
HeapDict (1.0.0)
html5lib (0.999)
idna (2.5)
imagesize (0.7.1)
ipykernel (4.6.1)
ipython (5.3.0)
ipython-genutils (0.2.0)
ipywidgets (6.0.0)
isort (4.2.5)
itsdangerous (0.24)
jdcal (1.3)
jedi (0.10.2)
Jinja2 (2.9.6)
jsonschema (2.6.0)
jupyter (1.0.0)
jupyter-client (5.0.1)
jupyter-console (5.1.0)
jupyter-core (4.3.0)
lazy-object-proxy (1.2.2)
llvmlite (0.18.0)
locket (0.2.0)
lxml (3.7.3)
MarkupSafe (0.23)
matplotlib (2.0.2)
mistune (0.7.4)
mpmath (0.19)
msgpack-python (0.4.8)
multipledispatch (0.4.9)
navigator-updater (0.1.0)
nbconvert (5.1.1)
nbformat (4.3.0)
networkx (1.11)
nltk (3.2.3)
nose (1.3.7)
notebook (5.0.0)
numba (0.33.0)
numexpr (2.6.2)
numpy (1.12.1)
numpydoc (0.6.0)
odo (0.5.0)
olefile (0.44)
openpyxl (2.4.7)
packaging (16.8)
pandas (0.20.1)
pandocfilters (1.4.1)
partd (0.3.8)
pathlib2 (2.2.1)
patsy (0.4.1)
pep8 (1.7.0)
pexpect (4.2.1)
pickleshare (0.7.4)
Pillow (4.1.1)
pip (9.0.1)
ply (3.10)
prompt-toolkit (1.0.14)
psutil (5.2.2)
ptyprocess (0.5.1)
py (1.4.33)
pycosat (0.6.2)
pycparser (2.17)
pycrypto (2.6.1)
pycurl (7.43.0)
pyflakes (1.5.0)
Pygments (2.2.0)
pylint (1.6.4)
pyodbc (4.0.16)
pyOpenSSL (17.0.0)
pyparsing (2.1.4)
pytest (3.0.7)
python-dateutil (2.6.0)
pytz (2017.2)
PyWavelets (0.5.2)
PyYAML (3.12)
pyzmq (16.0.2)
QtAwesome (0.4.4)
qtconsole (4.3.0)
QtPy (1.2.1)
requests (2.14.2)
rope-py3k (0.9.4.post1)
scikit-image (0.13.0)
scikit-learn (0.18.1)
scipy (0.19.0)
seaborn (0.7.1)
setuptools (27.2.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
snowballstemmer (1.2.1)
sortedcollections (0.5.3)
sortedcontainers (1.5.7)
Sphinx (1.5.6)
spyder (3.1.4)
SQLAlchemy (1.1.9)
statsmodels (0.8.0)
sympy (1.0)
tables (3.4.2)
tblib (1.3.2)
terminado (0.6)
testpath (0.3)
toolz (0.8.2)
tornado (4.5.1)
traitlets (4.3.2)
unicodecsv (0.14.1)
wcwidth (0.1.7)
Werkzeug (0.12.2)
wheel (0.29.0)
widgetsnbextension (2.0.0)
wrapt (1.10.10)
xlrd (1.0.0)
XlsxWriter (0.9.6)
xlwt (1.2.0)
zict (0.1.2)
'

**Comment by ChristopherLu** [comment]
output of `pip --version`:

pip 9.0.1 from /home/myname/anaconda2/envs/pyannote/lib/python3.5/site-packages (python 3.5)

**Comment by hbredin** [comment]
Please update `setuptools`. 

You are using an old version that does not behave well with namespace packages...

**Comment by ChristopherLu** [comment]
I did try update setuptools, but then the problem comes. See the output of running `pip install -U pip setuptools`:

[Errno 2] No such file or directory: '/home/myname/anaconda2/envs/pyannote/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg'

**Comment by hbredin** [comment]
Ignore this error message -- run `pip install -U setuptools` once again and then check again with `pip list` that you have `setuptools (36.0.1)`

**Comment by ChristopherLu** [comment]
OK, see output of `pip list | grep setuptools`:
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
setuptools (36.0.1)

Then I run `pip install pyannote.audio`, it gives:

In file included from _pysndfile.cpp:471:0:
    pysndfile.hh:55:21: fatal error: sndfile.h: No such file or directory
     #include <sndfile.h>
                         ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

**Comment by hbredin** [comment]
Come on! You're almost there! You solved this `sniffle` problem before!

**Comment by ChristopherLu** [comment]
No, this time the deactivate trick does not work...

**Comment by ChristopherLu** [comment]
No. Even with this, the `AttributeError: '_NamespacePath' object has no attribute 'sort'` come again....

Anyway, will look it tomorrow. I guess this is my problem.

**Comment by hbredin** [comment]
Did you succeed?

**Comment by ChristopherLu** [comment]
Hi I succeed in another computer. I do not know why the previous issue happened. Thx

**Comment by glynpu** [comment]
I also meet this problem on my computer today.  After setting setuptools version to 36.6.0 and installing gcc in the anaconda virtual environment, this problem is solved. However, I am not sure there is any relationship between this problem and these two packages and I am still confused about the reason to this problem.

comamnd for setuptools version specification: 
`pip install setuptools==36.6.0`

command for installing [gcc(from](https://anaconda.org/anaconda/gcc) ):
`conda install -c anaconda gcc `

The version was chose according to another computer of mine, on which pyannote.audio is successfully installed.

**Comment by stanislavkozlovski** [comment]
if running on an M1 mac, do:
```
conda install -c conda-forge libsndfile
```
