### ISSUE TITLE
I want to  train the speaker embedding model with my own data,How to prepare the data?

### ISSUE THREAD

**Issue by wuqiangch** [pyannote/pyannote-audio#320]
Hi,@hbredin.I want to train the speaker embedding model with my own data.My database looks like:
data-clean/G2143/G2143_S0189.wav 
data-clean/G2143/G2143_S0159.wav 
data-clean/G2143/G2143_S0184.wav 
...
data-clean/G4923/G4923_S0113.wav 
data-clean/G4923/G4923_S0160.wav 
data-clean/G4923/G4923_S0198.wav 
...
data-clean-reverb/G2143/G2143_S0189.wav 
data-clean-reverb/G2143/G2143_S0159.wav 
data-clean-reverb/G2143/G2143_S0184.wav 
....
data-clean-reverb/G4923/G4923_S0113.wav 
data-clean-reverb/G4923/G4923_S0160.wav 
data-clean-reverb/G4923/G4923_S0198.wav 
...
But the format is different from voxceleb. and "G4923" and "G2143" are different persons' name. 
How to prepare the data for training my own model?
Thanks!!!

**Comment by hbredin** [comment]
You should follow the [data preparation tutorial](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/data_preparation) to create a new `YourData.SpeakerDiarization.YourProtocol` protocol (even though, in practice, this has nothing to do with speaker diarization).

I understand that each file contains exactly one speaker so you should prepare MDTM and UEM files like that:

```
# in train.mdtm
SPEAKER data-clean/G2143/G2143_S0189 1 0 {file_duration} <NA> <NA> G2143 <NA> <NA>
# in train.uem
data-clean/G2143/G2143_S0189 1 0.000 {file_duration}
```
where `{file_duration}` is replaced by the actual file duration.

**Comment by wuqiangch** [comment]
@hbredin Hi， I have a try like your note. But I got some errors "TypeError: Cannot cast array from dtype('O') to dtype('float64') according to the rule 'safe'" and 'ValueError: could not convert string to float: '<NA>''.I think the format of MDTM and UEM  is wrong. The format of MDTM  and RTTM is same?

**Comment by wuqiangch** [comment]
1>train.mdtm
SPEAKER dataset/SPK_0132/G0132_S0456_T10 1 0.000 2.46 <NA> <NA> SPK_0132 <NA> <NA>
SPEAKER dataset/SPK_0132/G0132_S0457_T10 1 0.000 3.54 <NA> <NA> SPK_0132 <NA> <NA>
SPEAKER dataset/SPK_0132/G0132_S0458_T10 1 0.000 2.95 <NA> <NA> SPK_0132 <NA> <NA>
SPEAKER dataset/SPK_0132/G0132_S0459_T10 1 0.000 2.24 <NA> <NA> SPK_0132 <NA> <NA>
SPEAKER dataset/SPK_0132/G0132_S0460_T10 1 0.000 2.15 <NA> <NA> SPK_0132 <NA> <NA>
SPEAKER dataset/SPK_0132/G0132_S0461_T10 1 0.000 2.3 <NA> <NA> SPK_0132 <NA> <NA>
SPEAKER dataset/SPK_0132/G0132_S0462_T10 1 0.000 3.02 <NA> <NA> SPK_0132 <NA> <NA>
SPEAKER dataset/SPK_0132/G0132_S0463_T10 1 0.000 4.15 <NA> <NA> SPK_0132 <NA> <NA>
SPEAKER dataset/SPK_0132/G0132_S0464_T10 1 0.000 4.37 <NA> <NA> SPK_0132 <NA> <NA>
SPEAKER dataset/SPK_0132/G0132_S0465_T10 1 0.000 2.54 <NA> <NA> SPK_0132 <NA> <NA>
......
2>train.uem
dataset/SPK_0132/G0132_S0456_T10 1 0.000 2.46
dataset/SPK_0132/G0132_S0457_T10 1 0.000 3.54
dataset/SPK_0132/G0132_S0458_T10 1 0.000 2.95
dataset/SPK_0132/G0132_S0459_T10 1 0.000 2.24
dataset/SPK_0132/G0132_S0460_T10 1 0.000 2.15
dataset/SPK_0132/G0132_S0461_T10 1 0.000 2.3
dataset/SPK_0132/G0132_S0462_T10 1 0.000 3.02
dataset/SPK_0132/G0132_S0463_T10 1 0.000 4.15
dataset/SPK_0132/G0132_S0464_T10 1 0.000 4.37
dataset/SPK_0132/G0132_S0465_T10 1 0.000 2.54
......
3>database.yml
Databases:
     MUSAN: /Speaker-Diarization-By-DeepLearning/pyannote-audio/tutorials/data_preparation/AMI/database/musan/{uri}.wav
      CHSPEAKER:/Speaker-Data/Speaker-Diarization/Speaker-Recognition/{uri}.wav
Protocols:
      CHSPEAKER:
      SpeakerDiarization:
         AllChDataset:
           train:
              annotation: /Speaker-Data/Speaker-Diarization/Speaker-Recognition/train.mdtm
              annotated: /Speaker-Data/Speaker-Diarization/Speaker-Recognition/train.uem
4>train script:
pyannote-audio  emb train --subset=train --to=250 --parallel=8 ${EXP_DIR} CHSPEAKER.SpeakerDiarization.AllChDataset

**Comment by wuqiangch** [comment]
SPEAKER dataset/SPK_0132/G0132_S0465_T10 1 0.000 2.54 <NA> <NA> SPK_0132 <NA> <NA>

**Comment by hbredin** [comment]
> @hbredin Hi， I have a try like your note. But I got some errors "TypeError: Cannot cast array from dtype('O') to dtype('float64') according to the rule 'safe'" and 'ValueError: could not convert string to float: '''.I think the format of MDTM and UEM is wrong. The format of MDTM and RTTM is same?


Sorry. My mistake. My previous comment should read RTTM (not MDTM):

```
# in train.rttm
SPEAKER data-clean/G2143/G2143_S0189 1 0 {file_duration} <NA> <NA> G2143 <NA> <NA>
# in train.uem
data-clean/G2143/G2143_S0189 1 0.000 {file_duration}
```

**Comment by wuqiangch** [comment]
@hbredin,It's ok now.Thanks. 
I have another quetion. In the config.yml ,the duration is 2.0s.But if the duration of one  train file is less than 2s, how to deal with?
The same quetion in  the example "pyannote-audio / tutorials / pretrained / model / ".How to extract the embedding of one segment if the  duration  of one segment is less than 2s？Thanks again.

**Comment by hbredin** [comment]
> @hbredin,It's ok now.Thanks.
> I have another quetion. In the config.yml ,the duration is 2.0s.But if the duration of one train file is less than 2s, how to deal with?

Files shorter than duration used for training are automatically removed from the training set.

> The same quetion in the example "pyannote-audio / tutorials / pretrained / model / ".How to extract the embedding of one segment if the duration of one segment is less than 2s？Thanks again.

Even though the model was trained on 2s audio chunks, it can still be applied on shorter segments.

Calling `embeddings = emb(test_file)` will work just fine and will only contain one embedding.
FYI, the API also supports something like `embeddings = emb.crop(test_file, segment)`.

**Comment by hbredin** [comment]
Closing this issue as the original question has been answered.
Please reopen a new one if needed.
