### ISSUE TITLE
Issue when loading the protocol for applying pre-trained pipeline/models on my own data

### ISSUE THREAD

**Issue by dawei-liang** [pyannote/pyannote-audio#321]
Hello,

I am following the tutorials to load the pre-trained pipeline/models on my own data. I copied the following instruction: 

from pyannote.database import get_protocol
from pyannote.database import FileFinder

preprocessors = {'audio': FileFinder()}
protocol = get_protocol('AMI.SpeakerDiarization.MixHeadset',
                        preprocessors=preprocessors)

Yet I got the following error message:

KeyError                                  Traceback (most recent call last)
~/anaconda3/envs/tf/lib/python3.7/site-packages/pyannote/database/__init__.py in get_database(database_name, preprocessors, **kwargs)
KeyError: 'AMI'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-141-1a495c59c337> in <module>
      4 preprocessors = {'audio': FileFinder('/home/dawei/research-socialbit/pyannote-audio/tutorials/data_preparation/database.yml')}
ValueError: Could not find any protocol for "AMI" database. Please refer to pyannote.database documentation to learn how to define them: https://github.com/pyannote/pyannote-database

I was following exactly the way in the tutorials to prepare the AMI/Musan data and modified the database.yml with my own directory. But I am still keep getting the error. Not sure if there can be any suggestions on that? Is it that I specified something incorrectly when calling the get_protocol()?

Thanks for your time!

**Comment by hbredin** [comment]
No need to open the same issue twice. This does not help.

I already answered in the original one. 
Please, continue the discussion [here](https://github.com/pyannote/pyannote-database/issues/37).
