### ISSUE TITLE
Applying Pretrained Speaker Diarization Pipeline

### ISSUE THREAD

**Issue by tjtalkar** [pyannote/pyannote-audio#326]
Hello - I had posted in #293 about applying the speaker diarization pipeline to a new file, and saw that a new tutorial had been updated in #295 (https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/pretrained/pipeline). However, when I tried to run it, I get the error that:

`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-36c6d306f5e1> in <module>
      1 import torch
----> 2 pipeline = torch.hub.load('pyannote/pyannote-audio:develop', 'dia_ami')
      3 
      4 # one can use their own file like this...
      5 test_file = {'uri': '200106_1614', 'audio': '/Users/ta28438/Documents/20200106/200106_1614.wav'}

/usr/local/lib/python3.7/site-packages/torch/hub.py in load(github, model, *args, **kwargs)
    362     hub_module = import_module(MODULE_HUBCONF, repo_dir + '/' + MODULE_HUBCONF)
    363 
--> 364     entry = _load_entry_from_hubconf(hub_module, model)
    365 
    366     model = entry(*args, **kwargs)

/usr/local/lib/python3.7/site-packages/torch/hub.py in _load_entry_from_hubconf(m, model)
    235 
    236     if func is None or not callable(func):
--> 237         raise RuntimeError('Cannot find callable {} in hubconf'.format(model))
    238 
    239     return func

RuntimeError: Cannot find callable dia_ami in hubconf`

Is there anything else I need to be installing? I see that there should be a pretrained.yml file in the hubconf.py, but I can't seem to find it.

Thank you for your time and help!

**Comment by hbredin** [comment]
This might be due to an old version of `hubconf.py` being cached by `pytorch`.
Can you please remove `~/.cache/torch/hub` directory and try again?

Also, depending on the type of conversation you have, you might be better off using `dia_dihard` (or simply `dia`) instead of `dia_ami`.

See `https://github.com/pyannote/pyannote-audio-hub`  for more info and a link to a Google Colab that you can try directly.

**Comment by tjtalkar** [comment]
Removing the cache worked! And yes, I've changed it to use dia_dihard instead of dia_ami given the dataset that I am working with. Thank you for your help!
