### ISSUE TITLE
Cannot find my Pretrained model

### ISSUE THREAD

**Issue by picheny-nyu** [pyannote/pyannote-audio#328]
I successfully trained an sad model. I want to create sad scores as part of the speaker diarization pipeline. I thought I am passing the weights correctly to the pyannote-audio script but the model is never found and the script aborts. Here is the output of my bash script with tracing on. 

This is the error message I get. 

RuntimeError: Cannot find callable /misc/vlgscratch4/PichenyGroup/picheny/headcam/headcam-code-try2/models/speech_activity_detection/train/AMI.SpeakerDiarization.MixHeadset.train/weights/0101.pt in hubconf

For readability, I have boldfaced the commands in the script.

**++ export EXP_DIR=models/speaker_diarization**
++ EXP_DIR=models/speaker_diarization
**++ cd /misc/vlgscratch4/PichenyGroup/picheny/headcam/headcam-code-try2**
**++ export PYANNOTE_DATABASE_CONFIG=/misc/vlgscratch4/PichenyGroup/picheny/headcam/headcam-code-try2/database.yml**
++ PYANNOTE_DATABASE_CONFIG=/misc/vlgscratch4/PichenyGroup/picheny/headcam/headcam-code-try2/database.yml
**++ sad_model=/misc/vlgscratch4/PichenyGroup/picheny/headcam/headcam-code-try2/models/speech_activity_detection/train/AMI.SpeakerDiarization.MixHeadset.train/weights/0101.pt**
**++ ls /misc/vlgscratch4/PichenyGroup/picheny/headcam/headcam-code-try2/models/speech_activity_detection/train/AMI.SpeakerDiarization.MixHeadset.train/weights/0101.pt**
/misc/vlgscratch4/PichenyGroup/picheny/headcam/headcam-code-try2/models/speech_activity_detection/train/AMI.SpeakerDiarization.MixHeadset.train/weights/0101.pt
**++ pyannote-audio sad apply --step=0.1 --pretrained=/misc/vlgscratch4/PichenyGroup/picheny/headcam/headcam-code-try2/models/speech_activity_detection/train/AMI.SpeakerDiarization.MixHeadset.train/weights/0101.pt --subset=dev models/speaker_diarization AMI.SpeakerDiarization.MixHeadset**
Using cache found in /home/map22/.cache/torch/hub/pyannote_pyannote-audio_develop
Traceback (most recent call last):
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/pyannote-feb32020/bin/pyannote-audio", line 8, in <module>
    sys.exit(main())
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/pyannote-feb32020/lib/python3.7/site-packages/pyannote/audio/applications/pyannote_audio.py", line 406, in main
    apply_pretrained(validate_dir, protocol, **params)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/pyannote-feb32020/lib/python3.7/site-packages/pyannote/audio/applications/base.py", line 514, in apply_pretrained
    step=step)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/pyannote-feb32020/lib/python3.7/site-packages/torch/hub.py", line 364, in load
    entry = _load_entry_from_hubconf(hub_module, model)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/pyannote-feb32020/lib/python3.7/site-packages/torch/hub.py", line 237, in _load_entry_from_hubconf
    raise RuntimeError('Cannot find callable {} in hubconf'.format(model))
RuntimeError: Cannot find callable /misc/vlgscratch4/PichenyGroup/picheny/headcam/headcam-code-try2/models/speech_activity_detection/train/AMI.SpeakerDiarization.MixHeadset.train/weights/0101.pt in hubconf

**Comment by hbredin** [comment]
Can you try emptying your torch.hub cache? 
```
$ rm -r /home/map22/.cache/torch/hub
```
and also make sure to use the last version of the codebase.

**Comment by hbredin** [comment]
Sorry this probably won't work either. Will try to fix this in the coming days.

**Comment by picheny-nyu** [comment]
OK, thanks - the workaround will be fine but if you can fix it it would be great!

**Comment by hbredin** [comment]
This should be fixed since b494803. 
Please let me know how it goes.

**Comment by picheny-nyu** [comment]
Having trouble obtaining new pyannote code; running under Conda and it won't install: 

pyannote-feb32020 is the Conda env where I originally installed pyannote 

Try1:
(pyannote-feb32020) [map22@lion4 headcam-code-try2]$ conda update pyannote-audio
PackageNotInstalledError: Package is not installed in prefix.
  prefix: /misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/pyannote-feb32020
  package name: pyannote-audio

Try2:
(pyannote-feb32020) [map22@lion4 headcam-code-try2]$ pip install pyannote-audio --upgrade
Collecting pyannote-audio
  Downloading pyannote.audio-1.0.1-py3-none-any.whl (140 kB)
     |████████████████████████████████| 140 kB 9.5 MB/s 
Requirement already satisfied, skipping upgrade: tqdm>=4.11.2 in /misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/pyannote-feb32020/lib/python3.7/site-packages (from pyannote-audio) (4.42.1)
Requirement already satisfied, skipping upgrade: sortedcontainers>=2.0.4 in /misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/pyannote-feb32020/lib/python3.7/site-packages (from pyannote-audio) (2.1.0)
Collecting python-speech-features==0.6
  Downloading python_speech_features-0.6.tar.gz (5.6 kB)
Requirement already satisfied, skipping upgrade: scikit-learn>=0.19.1 in /misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/pyannote-feb32020/lib/python3.7/site-packages (from pyannote-audio) (0.22.1)
ERROR: Could not find a version that satisfies the requirement torch==0.4 (from pyannote-audio) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 0.4.1, 0.4.1.post2, 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0)
ERROR: No matching distribution found for torch==0.4 (from pyannote-audio)

Try3:
(pyannote-feb32020) [map22@lion4 headcam-code-try2]$ pip install pyannote --upgrade
ERROR: Could not find a version that satisfies the requirement pyannote (from versions: none)
ERROR: No matching distribution found for pyannote

Suggestions appreciated. Also trying to copy things by hand from the new release, failing with that also.....

**Comment by hbredin** [comment]
I have just published a pre-release of pyannote.audio on PyPI to make it easier to install.
Can you try with `pip install pyannote.audio==2.0a0`?

Otherwise, if you want to use the latest `develop` version:
```bash
$ cd pyannote-audio # where you cloned the pyannote.audio repository
$ git checkout develop
$ git pull
$ pip install -e .
```

**Comment by picheny-nyu** [comment]
Now I get the message:
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (scipy 1.4.1 (/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/pyannote-feb32020/lib/python3.7/site-packages), Requirement.parse('scipy<1.4.0'), {'optuna'})

I am going to set up a clean environment and install from scratch, maybe it is just getting confused.

**Comment by picheny-nyu** [comment]
Clean environment helped a lot. But now I get this message. 

Using cache found in /home/map22/.cache/torch/hub/pyannote_pyannote-audio_master
Development set: 2it [00:13,  6.67s/it]
Traceback (most recent call last):
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/pyannote-mar272020/bin/pyannote-audio", line 8, in <module>
    sys.exit(main())
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/pyannote-mar272020/lib/python3.7/site-packages/pyannote/audio/applications/pyannote_audio.py", line 434, in main
    apply_pretrained(validate_dir, protocol, **params)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/pyannote-mar272020/lib/python3.7/site-packages/pyannote/audio/applications/base.py", line 557, in apply_pretrained
    pipeline.instantiate(pretrained.pipeline_params_)
  File "/misc/vlgscratch4/PichenyGroup/picheny/anaconda3/envs/pyannote-mar272020/lib/python3.7/site-packages/pyannote/audio/features/wrapper.py", line 269, in __getattr__
    return getattr(self.scorer_, name)
AttributeError: 'Pretrained' object has no attribute 'pipeline_params_'

Here is how I call:
pyannote-audio sad apply --step=0.1 --pretrained=/misc/vlgscratch4/PichenyGroup/picheny/headcam/headcam-code-try2/models/speech_activity_detection/train/AMI.SpeakerDiarization.MixHeadset.train/weights/0101.pt --subset=development models/speaker_diarization AMI.SpeakerDiarization.MixHeadset

and under models/speaker_diarization I have a config.yml that looks like:

pipeline:
  name: pyannote.audio.pipeline.speaker_diarization.SpeakerDiarization
  params:
    # replace {{EXP_DIR}} by its actual value
    sad_scores: models/speaker_diarization/sad_ami
    scd_scores: models/speaker_diarization/scd_ami
    embedding: models/speaker_diarization/emb_ami

Is that wrong?

**Comment by hbredin** [comment]
This is now fixed in `develop` branch (not on PyPI) but SAD scores should have been extracted correctly even with this error message (that happens **after** scores being extracted).

Note however, that you should replace `model/speaker_diarization` by `model/speaker_diarization/sad` in your call, otherwise subsequent calls to `pyannote-audio scd apply` and `pyannote-audio emb apply` will all try to put scores in the same `model/speaker_diarization` directory.

Your `config.yml` should then read

```yaml
sad_scores: models/speaker_diarization/sad
scd_scores: models/speaker_diarization/scd
embedding: models/speaker_diarization/emb
```

**Comment by picheny-nyu** [comment]
Yes, I see the scores were extracted! But are you saying you just made an update - and if so - how do I get it? 

Here is how I set up my conda environment:

cd /misc/vlgscratch4/PichenyGroup/picheny
conda create -n pyannote-mar272020 python=3.7
source activate pyannote-mar272020
conda install pytorch torchvision cudatoolkit=9.2 -c pytorch
mkdir pyannote-mar272020
cd pyannote-mar272020
mkdir pyannote-audio
cd pyannote-audio
git checkout develop
pip install .

**Comment by hbredin** [comment]
```bash
$ git clone git@github.com:pyannote/pyannote-audio.git
$ cd pyannote-audio
$ git checkout develop
$ git pull
$ pip install -e .
```

**Comment by picheny-nyu** [comment]
Fails:

(pyannote-mar272020) [map22@vine8 pyannote-mar272020]$ ls -al
total 4
drwx--S---.  3 map22 cilvr   36 Mar 27 10:31 .
drwxrwsr-x. 11 map22 cilvr 4096 Mar 27 10:31 ..
drwx--S---.  2 map22 cilvr   10 Mar 27 10:31 pyannote-audio
(pyannote-mar272020) [map22@vine8 pyannote-mar272020]$ git clone git@github.com:pyannote/pyannote-audio.git
Cloning into 'pyannote-audio'...
The authenticity of host 'github.com (140.82.113.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
RSA key fingerprint is MD5:16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.113.3' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
(pyannote-mar272020) [map22@vine8 pyannote-mar272020]$

**Comment by picheny-nyu** [comment]
git clone https://github.com/pyannote/pyannote-audio.git was the right command

**Comment by picheny-nyu** [comment]
Pleased to say I was finally able to run the pipeline and get an initial diarization number. I have a lot of tuning to do - I have very noisy data and losing a lot from SAD - but I made it all the way through!!! Not sure if you have any suggestions - I am worried that the data augmentation could be causing problems as it may be masking the many events that have low volume.

**Comment by hbredin** [comment]
Glad you made it to **THE** number! 

Closing this issue as the initial problem is now solved.
Please open a new issue if needed...
