### ISSUE TITLE
GPU Cuda out of memory issues

### ISSUE THREAD

**Issue by tomseinen** [pyannote/pyannote-audio#330]
Your work looks great and I really would like to use your sad,scd,ovl,emb models for my research. 
But I am having issues with Cuda going out of memory when I apply your models to a AMI testfile (ES2002a.Mix-Headset.wav).
Code i run:
```
import torch
sad = torch.hub.load('pyannote/pyannote-audio', 'sad_ami')
test_file = {'uri': 'filename', 'audio': '.../ES2002a.Mix-Headset.wav'}
sad_scores = sad(test_file)
```
which returns the following runtime error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<timed exec> in <module>

.....

~/anaconda3/envs/pyannote/lib/python3.7/site-packages/torch/nn/functional.py in instance_norm(input, running_mean, running_var, weight, bias, use_input_stats, momentum, eps)
   1683     return torch.instance_norm(
   1684         input, weight, bias, running_mean, running_var,
-> 1685         use_input_stats, momentum, eps, torch.backends.cudnn.enabled
   1686     )
   1687 

RuntimeError: CUDA out of memory. Tried to allocate 104.00 MiB (GPU 0; 3.82 GiB total capacity; 2.42 GiB already allocated; 26.25 MiB free; 2.52 GiB reserved in total by PyTorch)
```
My system and settings (All clean install):
```
Ubuntu 18.04.4 LTS
GeForce GTX 1650, 4gb
nvidia driver Version: 435.21 
CUDA Version: 10.1
Anaconda3
pytorch '1.4.0'
conda '10.1'
pyannote.audio version '2.0.a0+2.gf5017ca'
```
Loading the sad model takes 1.3 gb in my gpu memory, running the model on the testfile directly brings it up to 3.3gb and it returns the error.
Is it not possible to use the gpu when you only have 4gb? Or do you think something else is going wrong? Would love to hear your thoughts on this, and if let me know if you need more info,
Thank you!

**Comment by hbredin** [comment]
Default batch size is 32. You can reduce it by passing the option ˋbatch_size=16ˋ (or lower) to ˋtorch.hub.load`.

**Comment by hbredin** [comment]
Closing stalled issue. Please re-open if needed.
