### ISSUE TITLE
Overlapping tag ?

### ISSUE THREAD

**Issue by Raska** [pyannote/pyannote-audio#333]
Hello everyone !
To test pyannote.audio, i would like annotate my own data for training. I read the pyannote.audio documentation and some AMIcorpus publications about the annotation but I have difficulties to understand how speakers overlapping is taken in consideration for annotation.
First, I put an "overlapping" tag to my data with other "speaker" tag. But it seems pyannote.audio is speaker-tag only, even if the end of a sample is overlapped with the beginning of another sample.
So what is the best practice to have ?
Thank you a lot for your help.

**Comment by hbredin** [comment]
You should only use *speaker* tags.  Overlap regions are inferred automatically if/when needed.

**Comment by Raska** [comment]
Ok ! Thank you !
