### ISSUE TITLE
Mistake in diarization pipelines notebook

### ISSUE THREAD

**Issue by kareemamrr** [pyannote/pyannote-audio#334]
In the [Colab notebook](https://colab.research.google.com/github/pyannote/pyannote-audio/blob/develop/notebooks/introduction_to_pyannote_audio_speaker_diarization_toolkit.ipynb) the author initializes the DEMO_FILE dict which is to be fed to the diarization pipeline as ```DEMO_FILE = {'uri': 'ES2004a.Mix-Headset', 'audio': 'ES2004a.Mix-Headset.wav'}```, just like in the tutorial [here](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/pretrained/pipeline). However in a the "Upload audio file" section he initialized it without the ```uri``` key which then throws an error when fed to the pipeline. This error is also in "pyannote-audio-hub" 's [README](https://github.com/pyannote/pyannote-audio-hub)

**Comment by hbredin** [comment]
Thanks for reporting this issue.
I have pushed a fix in pyannote.audio.
