### ISSUE TITLE
F-measure replaces Detection Error Rate for Tensorboard for SAD?

### ISSUE THREAD

**Issue by picheny-nyu** [pyannote/pyannote-audio#336]
I was rerunning an SAD experiment from February with some new parameters. I noticed that the Tensorboard display now shows F-Measure rather than detection error rate for the validation phase. Just checking that I have not done anything wrong, and just curious about the switch? (It also makes comparisons a little harder with work done a few months ago...)

**Comment by hbredin** [comment]
The detection error rate tends to quickly saturate and makes it nearly impossible to compare different version of SAD. The F-score is a much better metric for that purpose, hence the switch.

Note that I did the same for speaker change detection, overlapped speech detection and speaker embedding.

**Comment by picheny-nyu** [comment]
The reports for test data still seem to produce detection error rate - is that correct?

**Comment by hbredin** [comment]
It does return detection error rate, indeed (though the threshold is optimized on validation set for detection f-score).

You can use pyannote.metrics to compute other metrics if needed.

**Comment by hbredin** [comment]
Closing stalled issue. Please re-open if needed.
