### ISSUE TITLE
"pyannote.database" relies on a YAML configuration file but could not find any

### ISSUE THREAD

**Issue by mt19146** [pyannote/pyannote-audio#337]
I am trying to load a pre-trained model for embedding, but I am getting this error:

FileNotFoundError: "pyannote.database" relies on a YAML configuration file but could not find any. Here are the locations that were looked for: /content/database.yml, /root/.pyannote/database.yml.

Here is my code,

import torch
model = torch.hub.load('pyannote/pyannote-audio', 'emb')

till yesterday it was working fine but now it has stopped working, I saw you have made some changes in database directory, I am not a developer, i am researcher and i am using pyannote for a project

**Comment by hbredin** [comment]
Thanks for reporting this issue.

I just pushed a fix to `pyannote.audio` (develop branch).
Can you please confirm this solve your issue?

**Comment by hbredin** [comment]
Also, out of curiosity, can you please let me know the type of project you are working on (either by [email](mailto:bredin@limsi.fr) or directly in this issue) and how `pyannote.audio` is used in your research? That's always nice to know :-)

**Comment by mt19146** [comment]
I am trying to develop a diarization model. Using a pre-trained model from pyannote I am trying to extract embedding for clustering. For voice activity and segmentation I am using different techniques. Before using pyaanote, i was trying to perform diarization using unsupervised techniques, using Deep auto encoders, but the embedding extracted were extremely poor in clustering. so decided to go for supervised techniques. Do you have idea about unsupervised diarization?

**Comment by mayank10j** [comment]
Facing same issue with latest commit of develop branch : 
FileNotFoundError: "pyannote.database" relies on a YAML configuration file but could not find any. Here are the locations that were looked for: /***/database.yml, /root/.pyannote/database.yml

**Comment by vadimkantorov** [comment]
Just tried to install from pip. Same error

**Comment by yhlim19** [comment]
Hi, I had the same error
FileNotFoundError: "pyannote.database" relies on a YAML configuration file but could not find any. Here are the locations that were looked for: D:\Programming\PythonTest\pyannote_Audio\database.yml, C:\Users\yhlim\.pyannote\database.yml.
How do you solve it actually?

**Comment by yhlim19** [comment]
Hi, I have the same kind of issue from the latest branch..FileNotFoundError: "pyannote.database" relies on a YAML configuration file but could not find any. Here are the locations that were looked for: D:\Programming\PythonTest\pyannote_Audio\database.yml, C:\Users\yhlim\.pyannote\database.yml.
Could you provide some guidance?

> Thanks for reporting this issue.
> 
> I just pushed a fix to `pyannote.audio` (develop branch).
> Can you please confirm this solves your issue?

**Comment by alex-smith-ai** [comment]
Why is this a closed issue? I'm having the same issue and I don't see anything indicating people have found a solution. 

Thanks.

**Comment by hbredin** [comment]
Feel free to contribute a link to a Google Colab notebook reproducing the issue and I'll have a look.

**Comment by EklavyaFCB** [comment]
Same issue

**Comment by Yagna24** [comment]
Hi @hbredin , I am trying to run this on colab : 

`!pyannote-audio sad train --subset=train --to=200 --parallel=4 /content/pyannote-audio/tutorials/models/speech_activity_detection AMI.SpeakerDiarization.MixHeadset` 

I get the same error : 

```
  File "/usr/local/lib/python3.7/dist-packages/pyannote/database/config.py", line 99, in get_database_yml
    raise FileNotFoundError(msg)
FileNotFoundError: "pyannote.database" relies on a YAML configuration file but could not find any. Here are the locations that were looked for: /content/pyannote-audio/tutorials/models/speaker_change_detection/database.yml, /root/.pyannote/database.yml.
```

Please let me know if you have come up with the solution.

**Comment by Yagna24** [comment]
> I am trying to develop a diarization model. Using a pre-trained model from pyannote I am trying to extract embedding for clustering. For voice activity and segmentation I am using different techniques. Before using pyaanote, i was trying to perform diarization using unsupervised techniques, using Deep auto encoders, but the embedding extracted were extremely poor in clustering. so decided to go for supervised techniques. Do you have idea about unsupervised diarization?

Hi @mt19146, I am working on a similar project, can you share your findings?

**Comment by mt19146** [comment]
Hi See this,

https://github.com/muskang48/Speaker-Diarization

**Comment by chengyineng38** [comment]
I encountered this issue just now too. The odd thing is it wasn't a problem when I diarized 25 files, but the error appeared when I scaled it to 25k files.
