### ISSUE TITLE
ValueError: Segments must not be empty.

### ISSUE THREAD

**Issue by dannima** [pyannote/pyannote-audio#338]
Got this error when I was trying to define my own protocol for AMI and train a speech activity detector from scratch.

What I've done:
1) Write a `database.yml` file. The content is as follows:
```
Databases:
   AMI:
     - /data/corpora/amicorpus/E*/audio/{uri}.wav
     - /data/corpora/amicorpus/I*/audio/{uri}.wav
     - /data/corpora/amicorpus/T*/audio/{uri}.wav

Protocols:
   AMI:
      SpeakerDiarization:
         Array1-01:
           train:
              annotation: ../../../data/ami/lists/train.rttm
              annotated: ../../../data/ami/lists/train.uem
           development:
              annotation: ../../../data/ami/lists/dev.rttm
              annotated: ../../../data/ami/lists/dev.uem              
           test:
              annotation: ../../../data/ami/lists/test.rttm
              annotated: ../../../data/ami/lists/test.uem
```

2) run `$ export PYANNOTE_DATABASE_CONFIG='./database.yml'`

3) Open `python` in the same directory and run the following, as instructed [here](https://github.com/pyannote/pyannote-database#preprocessors):
```
>>> from pyannote.database import FileFinder, get_protocol
>>> preprocessors = {'audio': FileFinder(database_yml='database.yml')}
>>> protocol = get_protocol('AMI.SpeakerDiarization.Array1-01', preprocessors=preprocessors)
```
So far so good.
But then when I run:
```
>>> for item in protocol.train():
...     wav = item['audio']
```
The error occurs. More specifically:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sad/lib/python3.8/site-packages/pyannote/database/protocol/speaker_diarization.py", line 90, in train
    for item in generator:
  File "/sad/lib/python3.8/site-packages/pyannote/database/custom.py", line 137, in subset_iter
    annotateds = load_uem(file_uem)
  File "/sad/lib/python3.8/site-packages/pyannote/database/util.py", line 416, in load_uem
    timelines[uri] = Timeline(segments=segments, uri=uri)
  File "/sad/lib/python3.8/site-packages/pyannote/core/timeline.py", line 151, in __init__
    raise ValueError('Segments must not be empty.')
ValueError: Segments must not be empty.
```
Any idea what might be wrong? Thank you!

**Comment by hbredin** [comment]
The most likely error is that there is an empty (or extremely short) segment in `train.uem`.
Look for lines in `train.uem` where end time is smaller than (or equal to) start time.

**Comment by dannima** [comment]
Do you mean `train.rttm`? The shortest segment in `train.rttm` is less than 0.03s. Is it considered too short?

**Comment by hbredin** [comment]
No. I *really* meant `train.uem`. And too short means [shorter than one micro-second](https://github.com/pyannote/pyannote-core/blob/bc1506515c4245bdf898aec29dd3e84f1dd56181/pyannote/core/segment.py#L76-L77).

**Comment by dannima** [comment]
Thanks! I've found where the problem is — My `train.uem` file only contains three fields; It misses the second channel id column...
