### ISSUE TITLE
Trouble with pre-trained model (while giving a sample audio file other than from the AMI Corpus):

### ISSUE THREAD

**Issue by serene9199** [pyannote/pyannote-audio#346]
Hi,

I used the pre-trained model for diarization of an input audio file containing the voices of 2 speakers, which is not part of the AMI corpus. But the output yielded showing a single speaker instead of two. Can you please suggest any way to get the correct result?

I followed the instructions from [this notebook](https://github.com/pyannote/pyannote-audio/blob/develop/notebooks/introduction_to_pyannote_audio_speaker_diarization_toolkit.ipynb).

I tried running it after replacing the `ES2004a.Mix-Headset.wav` to my own audio sample in .wav format.
`DEMO_FILE = {'uri': 'ES2004a.Mix-Headset', 'audio': 'ES2004a.Mix-Headset.wav'}`

Thank you.

**Comment by hbredin** [comment]
Thanks for your interest in pyannote.audio, @serene9199.

As any machine learning approach, domain mismatch (i.e. difference between the type of data used for training and that used for testing) also applies for speaker diarization. Therefore, you may have to fine-tune the models and speaker diarization pipeline with your own (manually annotated data). See the tutorial section to learn how to do that.

That being said, there are two versions of the pretrained diarization pipeline: `dia` trained on DIHARD, and `dia_ami` trained on AMI. One might perform better than the other on your data.

**Comment by serene9199** [comment]
Thanks for the response.

I'll try as suggested above.
