### ISSUE TITLE
Re-train SAD model with music augmentation

### ISSUE THREAD

**Issue by ChenJiaDong9219** [pyannote/pyannote-audio#352]
I just tried the pre-trained SAD model. It works in silent environment. It didn't work when I put background music. So I guess this pre-trained model can only work in a silent environment?

**Comment by hbredin** [comment]
Would you mind sharing the exact code you used and a sample audio file?

**Comment by ChenJiaDong9219** [comment]
code:
`
import torch
speech_activity_detection = pipeline({'audio': 'music1.wav'})
for speech_region in speech_activity_detection.get_timeline():
    print(f'There is speech between t={speech_region.start:.1f}s and t={speech_region.end:.1f}s.')
`
output:
`
There is speech between t=0.5s and t=0.7s.
There is speech between t=1.0s and t=1.1s.
There is speech between t=1.4s and t=6.5s.
There is speech between t=6.6s and t=8.3s.
There is speech between t=8.5s and t=10.1s.
There is speech between t=10.3s and t=14.0s.
There is speech between t=14.3s and t=21.8s.
There is speech between t=22.0s and t=29.5s.
There is speech between t=29.7s and t=30.9s.
There is speech between t=31.4s and t=44.8s.
There is speech between t=45.0s and t=48.8s.
`
[music1.wav.zip](https://github.com/pyannote/pyannote-audio/files/4460485/music1.wav.zip)

**Comment by hbredin** [comment]
I just checked and indeed the model performs badly on this music-only file. 

One solution would be to retrain the `sad` model with music augmentation, e.g. by replacing this configuration line:
https://github.com/pyannote/pyannote-audio/blob/2fc38fb8c347bafb937ffee26dd2d37e96770297/tutorials/models/speech_activity_detection/config.yml#L21

by

```yaml
      collection: MUSAN.Collection.BackgroundNoise
         - MUSAN.Collection.BackgroundNoise
         - MUSAN.Collection.Music
```

This should make the model much more robust to music.

I might try to do that but cannot promise anything regarding when this new model will be released.

**Comment by ChenJiaDong9219** [comment]
Thank you! I'll retrain the model if needed.

**Comment by hbredin** [comment]
I have retrained a model on DIHARD with music from MUSAN: [2cb3a90f1b.zip](https://github.com/pyannote/pyannote-audio/files/4509668/2cb3a90f1b.zip)

Unfortunately, as depicted in [this notebook](https://gist.github.com/hbredin/be491c2ece7364f60aa23269218cb00f), it does not help with your music file.

You probably should re-train a model using your own set of music augmentation for it work.

Closing.
