### ISSUE TITLE
Bug in the shell script 'sh ${TUTORIAL_DIR}/download_ami.sh ${DOWNLOAD_TO}' in the data preparation tutorial

### ISSUE THREAD

**Issue by kan-cloud** [pyannote/pyannote-audio#362]
I was following the pyannote-audio data preparation tutorial (link below):
https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/data_preparation

I had no problem cloning the pyannote.audio repository,
but when I proceeded to download the Headset mix subset of AMI using the given script:

$ sh ${TUTORIAL_DIR}/download_ami.sh ${DOWNLOAD_TO}

I received the following error:

Syntax error: "(" unexpected

**Comment by hbredin** [comment]
I think this is due to an incompatible bash shell. 
Any idea @hadware?

**Comment by sangeetaghangam** [comment]
instead of sh download_ami.sh use bash download_ami.sh

**Comment by kan-cloud** [comment]
> I think this is due to an incompatible bash shell.
> Any idea @hadware?
> 
> PS: please refrain from using screenshots as those are really not helpful, not searchable and difficult to read.

Understood and inconvenient regretted. I apologise, I am new to github, and software development etiquette in general.

**Comment by hbredin** [comment]
No harm done.

> > I think this is due to an incompatible bash shell.
> > Any idea @hadware?
> > PS: please refrain from using screenshots as those are really not helpful, not searchable, and difficult to read.
> 
> Understood and inconvenience regretted. I apologize, I am new to GitHub, and software development etiquette in general.

Sorry if my remark felt a bit harsh... No harm done. 

Does switching to `bash` as @sangeetaghangam suggested (thanks, by the way) solve your issue?

**Comment by kan-cloud** [comment]
> No harm done.
> 
> > > I think this is due to an incompatible bash shell.
> > > Any idea @hadware?
> > > PS: please refrain from using screenshots as those are really not helpful, not searchable, and difficult to read.
> > 
> > 
> > Understood and inconvenience regretted. I apologize, I am new to GitHub, and software development etiquette in general.
> 
> Sorry if my remark felt a bit harsh... No harm done.
> 
> Does switching to `bash` as @sangeetaghangam suggested (thanks, by the way) solve your issue?

I have the run the script and will post an update as soon as I have an answer. Thank you for your prompt involvement!

**Comment by kan-cloud** [comment]
> instead of sh download_ami.sh use bash download_ami.sh

Thank you so much! It worked!

**Comment by hadware** [comment]
Ah, well, coming to the rescue a bit too late. Thanks to @sangeetaghangam for suggesting that fix.
