### ISSUE TITLE
bug? getting negative percentage in running validation on overlap detection

### ISSUE THREAD

**Issue by alonshoa** [pyannote/pyannote-audio#363]
Hi,
I'm running the validation step on overlap detection, using my dataset, I've also tested it with AMI and got the same behavior.  I ran train for 100 epocs, and then started the validation step with the output model, and I'm getting negative percentage in as results of epoch 
![image](https://user-images.githubusercontent.com/5207429/80276818-bdefb680-86f3-11ea-9660-58ad6ac22147.png)

**Comment by hbredin** [comment]
Looks like you are using an old version of `pyannote-audio` that validates models using detection recall at a target precision. The latest version (from `develop` branch) reports f-score instead.

That being said, these negative values simply meant that the model does not even reach 80% precision: [this is unfortunately not documented](https://github.com/pyannote/pyannote-audio/blob/1e93d0746fac2289a486c0f8ba6c7896cdf616ea/pyannote/audio/pipeline/overlap_detection.py#L202-L204).

Also, overlap detection is a difficult task and 100 epochs is far from enough to even start getting a useful model. Keep training! 

PS: please refrain from posting screenshots as those are not searchable, difficult to read, and not indexed by Github. Raw text is much better!

**Comment by alonshoa** [comment]
thanks :)
