### ISSUE TITLE
Data preparation for SAD/VAD 

### ISSUE THREAD

**Issue by bluemonk482** [pyannote/pyannote-audio#365]
Hi, thanks for the lib!

I have a bunch of wav files that I want to detect the pauses and how long the pauses are. I find large part if nor all of what is described [here](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/data_preparation), nonrelevant if I may say so. I cannot afford any training or fine-tuning your pretrained model, I simply want to apply your pretrained sad model to my wav files. However I am struggling to figure out how to make my wav files the correct format for your lib. Thanks again. Any suggestions would be helpful!!

**Comment by hbredin** [comment]
You do not need to go through the whole data preparation process if you just want to apply a model. [This](https://github.com/pyannote/pyannote-audio-hub#usage-1) should help.

**Comment by bluemonk482** [comment]
Thank you very much for your response! I will close the issue now.
