### ISSUE TITLE
Python entry-point for Model Training

### ISSUE THREAD

**Issue by rohitpaturi** [pyannote/pyannote-audio#369]
Hi, I was wondering if there is a python entry-point for the model training (interested in overlap detection https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/models/overlap_detection). This would help step into each of the blocks used for training, like feature extraction, model architecture blocks etc.

**Comment by hbredin** [comment]
The API is unfortunately not documented, only the pyannote-audio command line tool is, through the tutorials.

However, you might want to have a look at [this](https://github.com/pyannote/pyannote-audio/issues/220#issuecomment-575213143) conversation where I tried to list the most important parts of the API.  

If you want to help with writing the documentation, do not hesitate 👍

**Comment by rohitpaturi** [comment]
Thanks, this is helpful.
