### ISSUE TITLE
Custom features for training a model

### ISSUE THREAD

**Issue by rohitpaturi** [pyannote/pyannote-audio#370]
Is there a way to specify any custom features like MFCC, LFBE (with frame rate etc) in the config.yml (interested in overlap detection: https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/models/overlap_detection) or changing the frame rate among other parameters of the SincNet for feature extraction

**Comment by hbredin** [comment]
The `feature_extraction` section of the `config.yml` configuration file can be used for that purpose. [This tutorial](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/feature_extraction) provides an example with MFCC features.

The list of available handcrafted features (based on [librosa](https://librosa.github.io/librosa/)) is available in[`pyannote.audio.features`](https://github.com/pyannote/pyannote-audio/blob/develop/pyannote/audio/features/with_librosa.py).

If you decide to use your own feature extractor, you should write a subclass of [`pyannote.audio.features.base.FeatureExtraction`](https://github.com/pyannote/pyannote-audio/blob/develop/pyannote/audio/features/base.py#L44).
