### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes while finding scd score on test file

### ISSUE THREAD

**Issue by alamnasim** [pyannote/pyannote-audio#371]
Hi,

I am running speaker change detection for ami dataset.
I am getting this error:
scd_scores = scd(test_file)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/na/.local/lib/python3.8/site-packages/pyannote/audio/features/base.py", line 152, in __call__
    features = self.get_features(y.data, sample_rate)
  File "/home/na/.local/lib/python3.8/site-packages/pyannote/audio/features/pretrained.py", line 201, in get_features
    return self.model_.slide(
  File "/home/na/.local/lib/python3.8/site-packages/pyannote/audio/train/model.py", line 500, in slide
    data[indices] += fX_
ValueError: operands could not be broadcast together with shapes (1174,2) (581,2) (1174,2) 

I also tried this: 
test_file = {'uri': 'EN2002b.Mix-Headset', 'audio': '/home/na/amicorpus/EN2002b/audio/EN2002b.Mix-Headset.wav'}
scd_scores = scd(test_file)

I am getting the same error in both the cases.

I don't understand why numpy size has changed.

My whole script is:
import torch
from pyannote.database import get_protocol
from pyannote.database import FileFinder
from pyannote.audio.utils.signal import Peak
sad = torch.hub.load('pyannote/pyannote-audio:develop', 'sad_ami')
preprocessors = {'audio': FileFinder()}
protocol = get_protocol('AMI.SpeakerDiarization.MixHeadset',
                        preprocessors=preprocessors)
#test_file = next(protocol.test())
test_file = {'uri': 'EN2002b.Mix-Headset', 'audio': '/home/na/amicorpus/EN2002b/audio/EN2002b.Mix-Headset.wav'}
scd_scores = scd(test_file)

Any Help appreciate.

Thanks.

**Comment by alamnasim** [comment]
Issue resolved after freshly installed in some other system.

still not understand why faced issue on that particular desktop.

**Comment by hbredin** [comment]
Thanks for letting me know.
