### ISSUE TITLE
Diarization timpstamp error 

### ISSUE THREAD

**Issue by nayanhalder** [pyannote/pyannote-audio#373]
I am running diarization pipeline with the following code and got the following output.

import torch
pipeline = torch.hub.load('pyannote/pyannote-audio', 'dia_dihard')

diarization = pipeline({'audio': '/home/nayan/Desktop/pynote/pyannote-audio/code/cio.wav'})

with open('/home/nayan/Desktop/pynote/pyannote-audio-hub/audio.rttm', 'w') as f:
    diarization.write_rttm(f)
  
for turn, _, speaker in diarization.itertracks(yield_label=True):
    print(f'Speaker "{speaker}" speaks between t={turn.start:.1f}s and t={turn.end:.1f}s.')

output :

Speaker "A" speaks between t=0.0s and t=1.5s.
Speaker "A" speaks between t=2.2s and t=2.4s.
Speaker "A" speaks between t=3.1s and t=11.8s.
Speaker "A" speaks between t=12.2s and t=14.8s.
Speaker "A" speaks between t=15.4s and t=16.2s.
Speaker "A" speaks between t=16.5s and t=16.9s.
Speaker "A" speaks between t=17.4s and t=19.6s.
Speaker "A" speaks between t=21.0s and t=29.0s.
Speaker "A" speaks between t=29.6s and t=30.7s.
Speaker "A" speaks between t=31.2s and t=33.5s.
Speaker "A" speaks between t=33.7s and t=33.8s.
Speaker "A" speaks between t=34.4s and t=36.7s.
Speaker "A" speaks between t=37.4s and t=48.1s.
Speaker "A" speaks between t=48.7s and t=50.4s.
Speaker "A" speaks between t=51.1s and t=53.2s.
Speaker "A" speaks between t=54.1s and t=57.8s.
Speaker "A" speaks between t=58.9s and t=61.3s.
Speaker "A" speaks between t=61.8s and t=63.4s.
Speaker "A" speaks between t=63.9s and t=66.1s.
Speaker "A" speaks between t=66.3s and t=67.6s.
Speaker "A" speaks between t=67.8s and t=68.2s.
Speaker "A" speaks between t=68.5s and t=68.8s.
Speaker "A" speaks between t=69.5s and t=70.0s.

i noticed though there is no change in speaker between 0 to 14.8 sec, there are 4 output coming because of intermediate silence.  what i need to do so that with only speaker change the output entry will come, not with every silence. like i am expecting 
Speaker "A" speaks between t=0.0s and t=14.8s.
Speaker "B" speaks between t=15.4s and t=19.6s.

How i can merge the first 4 rows into a single row. 
how i can  merge 5th, 6th and 7th row into a single row. 

also i have 2 speakers, but it is showing only Speaker A.

How i can achieve that, can you please advise on this.

**Comment by hbredin** [comment]
See #346.
