### ISSUE TITLE
Frame rate of segmentation models (SAD, SCD, OVL)

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#374]
One observation I had while testing the Pretrained model on a test file in the AMI test set (uri 'EN2002a.Mix-Headset') is that the the shape of ovl_scores is (1269754, 2), whereas the uem file has a duration of 2142.709375 seconds. Applying the default settings of a 2 second window with a step of 0.5 seconds to feed the model, we would expect the scores to have (4282,2). Looks like the frame rate of feature extraction is different from the frame rate of the model window. Can you please point to what the frame rate is for the default Sincnet feature extraction and how to control this from the config(or code). Thanks!

_Originally posted by @rohitpaturi in https://github.com/pyannote/pyannote-audio/issues/368#issuecomment-625493698_

**Comment by hbredin** [comment]
Though segmentation models are applied on 2s chunks, they do provide scores at the frame level. 

You can get an idea of the actual frame rate by looking at the `sliding_window` attribute of the returned `SlidingWindowFeature` instance

```python
model = torch.hub.load('pyannote/pyannote-audio', 'ovl')
ovl_scores = model({'audio': '/path/to/audio.wav'})
frame = ovl_scores.sliding_window
print(frame.step)  # in seconds
print(frame.duration)  # in seconds
```

**Comment by rohitpaturi** [comment]
Got it, thanks!

**Comment by hbredin** [comment]
Closing as I believe the original question has been answered.
