### ISSUE TITLE
Example with OS database?

### ISSUE THREAD

**Issue by AdolfVonKleist** [pyannote/pyannote-audio#38]
This looks really nice. I was wondering if you have or plan to make available a quickstart example using an open source database?

**Comment by hbredin** [comment]
Definitely. 

Yet, I still have to find such an open-source database. It needs to have the following features:
- 10+ hours of speech (the longer the better)
- 100+ different speakers (the higher the better)
- fine "who speaks when" manual temporal annotations
Any suggestions?

Then, it would just be a matter of creating a `pyannote.database` plugin for this database: https://github.com/pyannote/pyannote-db-template

**Comment by ironiksk** [comment]
Hello,
I've done the db plugin for LibriSpeech corpus. Please try to use it:

https://github.com/ironiksk/pyannote-db-librispeech

**Comment by hbredin** [comment]
That's awesome. Thanks @ironiksk. Will definitely have a a try!

**Comment by hbredin** [comment]
Same here, except this will probably have to wait until september...

**Comment by hbredin** [comment]
Latest release of pyannote.audio (v1.0) has tutorials relying on the AMI database.
Closing as I believe this solves the original issue.

I still have to find some time trying the Librispeech plugin, though :(
