### ISSUE TITLE
Update optimal params.yml

### ISSUE THREAD

**Issue by lizolson1** [pyannote/pyannote-audio#381]
When using the command line interface: 

```sh
$ pyannote-pipeline train --subset=development --forever ${EXP_DIR} AMI.SpeakerDiarization.MixHeadset
```

The generated params.yml has parameters for clustering:

```
    clustering:
      threshold: 0.34116643801470203
```

However the sample optimal params.yml in the README has the parameters:

```
    clustering:
      damping: 0.5
      preference: -1.571915891387201
```

Trying to run use the provided params.yml gives the error
```sh
ValueError: parameter 'damping' does not exist
```
Do you know what the necessary threshold parameter is for reproducing the best results? Or should the parameters be damping and preference, in which case I might have a version issue? Thanks!

**Comment by hbredin** [comment]
Thanks for reporting this issue. I believe [this](https://github.com/pyannote/pyannote-audio/commit/f886996cc28c850d15da0c9b1736f7189e80f6ab) commit fixes the issue.
The `config.yml` file was missing a `method: affinity_propagation` parameter.

**Comment by hbredin** [comment]
Closing this stalled issue. Please reopen if needed.
