### ISSUE TITLE
Is the unique speaker identifier really necessary?

### ISSUE THREAD

**Issue by alfonsozunigaj** [pyannote/pyannote-audio#388]
I'm using this awesome library you've build for my bachelor's degree thesis, where I intent to use the speaker diarization tools to separate the channels in mono records that contact centers have accumulated for years to then train further models with the intention of automatizing the quality management tasks. My problem is that each record I have available **has a unique identifier for the contact center agent that took/made the call, but I don't have an identifier for the person on the other side of the call.** I do have an identifier that can be interpreted as the "phone number" of the other side of the call, but that doesn't assure me that the person in that call will always be the same.

My question is, if in the data preparation process I choose to just put a uid in the identifier of the non-agent side of the call, will my training/tunning results be awful? Is there another work around that maybe comes to mind?

**Comment by hbredin** [comment]
It depends on what you are trying to achieve. 

For training segmentation models (speech activity or speaker change detection) _local_ identifiers are fine. For training speaker embeddings, you should make sure that identifiers are _global_.

**Comment by LearnedVector** [comment]
@hbredin trying to warp my head around this. can you explain the theory of why you would need global identifiers for the speaker embeddings?

**Comment by hbredin** [comment]
Most supervised approaches to training speaker embedding internally rely on a multi-class classifier (one class per speaker).

If two different speakers share the same identifier, or if the same speaker has two different identifiers in two different files, then the classifier will have a hard time doing its job.

**Comment by hbredin** [comment]
Closing this stalled issue as I believe the original issue has been solved.
Please reopen if needed.
