### ISSUE TITLE
Feasability of the implementation of a Speaker Enrollment pipeline.

### ISSUE THREAD

**Issue by hadware** [pyannote/pyannote-audio#391]
**Is your feature request related to a problem? Please describe.**
The title is pretty self-explanatory. I'd just like to know how much work would be needed to implement a pipeline for a speaker unrolling task: are all the required building blocks already here in your opinion? If there isn't too much digging involved, i'd probably be willing to do it myself :)

**Comment by hbredin** [comment]
Can you please define "speaker unrolling"? I am not familiar with this wording.

Did you mean "speaker enrollment"? 
If so, what do you have in mind exactly? Speaker identification?

**Comment by Rachine** [comment]
Hello,

Yes, it would be speaker enrollment. 
Based on variable amount of target speakers find all the segments in the audio from this speaker
We were thinking to a pipeline that look like this https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/41939.pdf

**Comment by hbredin** [comment]
I didn't go through the paper but I think the [SpeechTurnClosestAssignment](https://github.com/pyannote/pyannote-audio/blob/06f76a2c5a37c79cf42710167c7b7404658879d3/pyannote/audio/pipeline/speech_turn_assignment.py#L43) might get you started.

**Enrollment**

_Basic idea:_ gather all speaker embedding for each target and take the average.

https://github.com/pyannote/pyannote-audio/blob/06f76a2c5a37c79cf42710167c7b7404658879d3/pyannote/audio/pipeline/speech_turn_assignment.py#L94-L113

**Recognition**

_Basic idea:_ for each test speech turn (or, here, speaker cluster), find closest target speaker (by comparing their average embedding. You might also want to consider the _reject_ option if even the closest target speaker is too far. 

https://github.com/pyannote/pyannote-audio/blob/06f76a2c5a37c79cf42710167c7b7404658879d3/pyannote/audio/pipeline/speech_turn_assignment.py#L115-L144

**Comment by hbredin** [comment]
Closing this issue as I believe the original question has been answered.
I'd still be interested in knowing how it went 👀

**Comment by Rachine** [comment]
Hey! This is still ongoing. We have the pipeline up and running but we are having a hard time to finetune correctly a spk emb model on our smallish dataset 😿
