### ISSUE TITLE
Please correct the README file

### ISSUE THREAD

**Issue by aidosRepoint** [pyannote/pyannote-audio#392]
The command below

`cp ${TUTORIAL}/database.yml ${DOWNLOAD_TO}`

produces: 
`cp: cannot stat '/database.yml': No such file or directory`

You were referring to the tutorial directory as `TUTORIAL_DIR` previously. Please correct the relevant README part.
**

**Comment by hbredin** [comment]
Thanks for reporting this.

For this kind of minor edits, feel free to edit it yourself by clicking on the "pencil" icon: this will create a pull request for you (without all the hassle of forking, cloning, editing, pushing, ...)

**Comment by aidosRepoint** [comment]
> Thanks for reporting this.
> 
> For this kind of minor edits, feel free to edit it yourself by clicking on the "pencil" icon: this will create a pull request for you (without all the hassle of forking, cloning, editing, pushing, ...)

thanks a lot!

I have completely forgotten about this way of editing.
