### ISSUE TITLE
Stuck with validation stage

### ISSUE THREAD

**Issue by aidosRepoint** [pyannote/pyannote-audio#398]
Hi everyone!

When running the validation step from [this](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/models/speech_activity_detection#validation) tutorial I get the following message:

`user@user-desktop:~/VAD/pyannote-audio$ pyannote-audio sad validate --cpu --subset=development --from=1 --to=10 --every=1 ${TRN_DIR} AMI.SpeakerDiarization.MixHeadset
/home/user/.local/lib/python3.7/site-packages/pyannote/database/database.py:51: UserWarning: Ignoring deprecated 'preprocessors' argument in MUSAN.__init__. Pass it to 'get_protocol' instead.
  warnings.warn(msg)
/home/user/.local/lib/python3.7/site-packages/pyannote/database/protocol/protocol.py:128: UserWarning: Existing key "annotation" may have been modified.
  warnings.warn(msg.format(key=key))
0iteration [00:00, ?iteration/s]`

Nothing happens after it. I did it in parallel with training, as well as separately. Every time it's being stuck the same.

**Comment by hbredin** [comment]
Validation on the `AMI` development set on `--cpu` might take a while indeed.
It probably is doing something, just slowly... 

Can you please 
- check the CPU load? 
- try with a smaller development set (e.g. by using a smaller `uri` list)?

**Comment by aidosRepoint** [comment]
> Validation on the `AMI` development set on `--cpu` might take a while indeed.
> It probably is doing something, just slowly...
> 
> Can you please
> 
> * check the CPU load?
> * try with a smaller development set (e.g. by using a smaller `uri` list)?

indeed it was because of the cpu training. I decreased the epochs number in training process, decreased validation trials (--every), and run training on cpu, while running validation on gpu. It helped.
