### ISSUE TITLE
How to use finetuned model? 

### ISSUE THREAD

**Issue by marlon-br** [pyannote/pyannote-audio#400]
Is it possible to use finetuned model through hub API?

I have taken pretrained model and finetuned it with one more speaker. I used pyannote-audio to train for 100 more epochs on my audio.
Now I wonder if it is possible to use finetuned model / load it with torch.hub.load()?

I use sample Colab to make my experiments, so not sure if it is possible to update config.yml with paths to finetuned models.

**Comment by hbredin** [comment]
Hi @marlon-br and welcome to `pyannote.audio`!

Only pretrained models available in [`pyannote-audio-hub`](https://github.com/pyannote/pyannote-audio-hub) are served by `torch.hub`:

```python
import torch.hub
pretrained_model = torch.hub.load(...)
```

To load your fine-tuned model, you'd have to use the (magic) `Wrapper` class:

```python
from pyannote.audio.features import Wrapper
finetuned_model = Wrapper("/path/to/train/{YOUR_PROTOCOL}.train/weights/0100.pt")
```
`finetuned_model` can then be used in the same way you would use `pretrained_model`.
Use `help(Wrapper)` for more details on things `Wrapper` can do.

If you happen to have run the validation step (recommended), use

```python
from pyannote.audio.features import Pretrained
finetuned_model = Pretrained("/path/to/train/{YOUR_PROTOCOL}.train/validate/{YOUR_PROTOCOL}.development")
```
This will automatically load the best epoch for you.

I'd happily merge a pull request updating the [fine-tuning tutorial](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/finetune) with this answer.

**Comment by marlon-br** [comment]
Hi Hervé,
Thanks for the detailed answer.

Actually I try to enable "dia_dihard" pipeline, no just single model. Could you please advise how to enable pipeline with finetuned model?

I tried something like:

```
from pyannote.audio.pipeline import SpeakerDiarization

pipeline = SpeakerDiarization(embedding = "/content/fine/emb/train/IK.SpeakerDiarization.kirilov.train/weights/0100.pt", 
                              sad_scores = "/content/fine/sad/train/IK.SpeakerDiarization.kirilov.train/weights/0100.pt",
                              scd_scores = "/content/fine/scd/train/IK.SpeakerDiarization.kirilov.train/weights/0100.pt")

FILE = {'audio': "/content/groundtruth/groundtruth.wav"}
diarization = pipeline(FILE)
diarization
```

But it looks like I am doing something wrong, since I am getting an error:

```
/usr/local/lib/python3.6/dist-packages/pyannote/pipeline/pipeline.py in __getattr__(self, name)
     87         msg = "'{}' object has no attribute '{}'".format(
     88             type(self).__name__, name)
---> 89         raise AttributeError(msg)
     90 
     91     def __setattr__(self, name, value):

AttributeError: 'SpeechActivityDetection' object has no attribute '_binarize'
```

**Comment by marlon-br** [comment]
thanks, that helped!
