### ISSUE TITLE
Please update the validation directory definition in the SAD tutorial

### ISSUE THREAD

**Issue by kan-cloud** [pyannote/pyannote-audio#401]
the current step is
export VAL_DIR=${TRN_DIR}/validate/AMI.SpeakerDiarization.MixHeadset.development

it should be:
export VAL_DIR=${TRN_DIR}/validate_detection_fscore/AMI.SpeakerDiarization.MixHeadset.development

**Comment by hbredin** [comment]
Thanks for reporting the issue!

Feel free to [edit it](https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-another-users-repository) yourself -- you will then appear as a contributor to the repo.
