### ISSUE TITLE
Apply UEM file to raw model output

### ISSUE THREAD

**Issue by EL-Col** [pyannote/pyannote-audio#410]
Hi, I'm following the guidelines for applying a pretrained SAD model on my own audio data. I've managed to get everything to work and have obtained DER scores for the sections that have been transcribed using a .uem file and the metrics package. 

I was wondering, however, if there was any way to apply the .uem file earlier than at the scoring step? My audio files can sometimes be quite long compared to the sections outlined in my uem. 

My code follows the same rough path as outlined here https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/pretrained/model. So, something like this:

```
sad = torch.hub.load('pyannote/pyannote-audio:develop', 'sad_ami')
raw_scores = sad(test_file)
binarize = Binarize(offset=value, onset=value, log_scale=True,
                            min_duration_off=0.0, min_duration_on=0.0)
speech = binarize.apply(raw_scores, dimension=1)
```
Is there anyway to apply the uem here? I've read through the documentation, sorry if I missed this anywhere.

Many thanks.

**Comment by hbredin** [comment]
You can use the `crop` method of `sad` pretrained model to only process an excerpt of your file:

```python
from pyannote.core import Segment
segment = Segment(10., 30.)
data = sad.crop(test_file, segment)
```

However, `data` is now a `np.ndarray` and not a `SlidingWindowFeature` as `raw_scores`.
You'd have to create a new `raw_scores` out of `data`:

```python
from pyannote.core import SlidingWindow, SlidingWindowFeature
frames = sad.sliding_window
shifted_frames = SlidingWindow(start=segment.start, step=frames.step, duration=frames.duration)
raw_scores = SlidingWindowFeatures(data, shifted_frames)
```

By the way, I'd gladly consider a pull request adding an option to `pyannote.audio.features.base.FeatureExtraction.crop` to output a `SlidingWindowFeature` instead of a `np.ndarray`.

**Comment by EL-Col** [comment]
I see! That's very helpful, thank you.

I'll test this and consider adding an option to `pyannote.audio.features.base.FeatureExtraction.crop` to output a `SlidingWindowFeature`. I'll submit a PR if I manage to do this. 

Thanks again.
