### ISSUE TITLE
Hi, I am trying to understand what does speaker embedding model do.

### ISSUE THREAD

**Issue by abbasshujah** [pyannote/pyannote-audio#411]
Hi,

I am sorry for creating a feature request to get my question through to you. I want to understand what the speaker embedding model actually does. I am trying to do a project that does conversation summarization for which I need to diarize audio files. I have no other way to reach out if I have further questions. Again apologies for asking about the speaker embedding model using this route but any help would be greatly appreciated.

**Comment by hbredin** [comment]
A speaker embedding model takes a speech utterrance as input and output a fixed dimension vector (i.e. a point in a high-dimensional space). The model is trained to output similar vectors (i.e. close to each other) for any two utterrances of the same speaker, and distant vectors for utterrances from two different speakers. It can then be used for clustering, for instance.  

See the introduction of this paper for details: https://arxiv.org/pdf/2003.14021.pdf
