### ISSUE TITLE
use pretrained model locally

### ISSUE THREAD

**Issue by RawadMelhem** [pyannote/pyannote-audio#413]
Hi,
Is it allowed to download 'dia' pre-trained model to my PC and use it without torch hub load.
I have downloaded the project "pyannote-audio-master" but I could't find .pt file which it is supposed to be the pre-trained model.
I appreciate your help.
Thank you

**Comment by hbredin** [comment]
Pretrained models are available in [pyannote/pyannote-audio-hub](https://github.com/pyannote/pyannote-audio-hub) repository.

**Comment by RawadMelhem** [comment]
Thanks, but when I load the model and test it I got the following error:

model = torch.load('0023.pt')
test= model({"audio":'filename.wav'})

TypeError: 'collections.OrderedDict' object is not callable

**Comment by hbredin** [comment]
Something like what follows should do the trick:

```python
from pyannote.audio.features.wrapper import Wrapper
model = Wrapper('/absolute/path/to/0023.pt')
```

**Comment by RawadMelhem** [comment]
I've got the error:

"0023.pt" directory does not seem to be the path to a pre-trained model checkpoint.
