### ISSUE TITLE
Question about choosing hyper params for inference with pretrained SAD

### ISSUE THREAD

**Issue by tumbleintoyourheart** [pyannote/pyannote-audio#417]
Hi,

I'm new and trying to use sad pretrained model like this, following [official tutorial](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/pretrained/model)

```
import torch
sad = torch.hub.load('pyannote/pyannote-audio', 'sad_ami')
test_file = {'uri': 'filename', 'audio': '/path/to/your/filename.wav'}

# obtain raw SAD scores (as `pyannote.core.SlidingWindowFeature` instance)
sad_scores = sad(test_file)

# binarize raw SAD scores
# NOTE: both onset/offset values were tuned on AMI dataset.
# you might need to use different values for better results.
from pyannote.audio.utils.signal import Binarize
binarize = Binarize(offset=0.52, onset=0.52, log_scale=True, 
                    min_duration_off=0.1, min_duration_on=0.1)

# speech regions (as `pyannote.core.Timeline` instance)
speech = binarize.apply(sad_scores, dimension=1)
```

Is this using cpu or gpu? If it's not utilizing gpu, how can I do it? I tried `sad.device = torch.device('cuda')` but no differences were found in inference time (of course `torch.cuda.is_available()` is `True`)

**Comment by hbredin** [comment]
`sad_scores = sad(test_file)` defaults to using GPU when available.

You should be able to speed things up a bit by increasing batch size until it no longer fits in memory:
```python
sad = torch.hub.load('pyannote/pyannote-audio', 'sad_ami', batch_size=128)
```


`torch.hub.load` also supports a `device=...` option if you want more control: 

```python
sad = torch.hub.load('pyannote/pyannote-audio', 'sad_ami', device="cpu")
```

The rest of the script runs on CPU only (but is fast, anyway).

PS: I would looooove a pull request adding these bits of information in the tutorial!

**Comment by tumbleintoyourheart** [comment]
Hi, thanks for the quick response,

One more question, even if we retrain a new model from scratch, we still need a `Binarize` object to finally classify each frame as 'speech' or 'non-speech', don't we? Can we get rid of that so it's truly end-to-end?

**Comment by tumbleintoyourheart** [comment]
Since post processing with `Binarize` object in Speech Activity Detection seems to be unavoidable, I'm so curious about how to choose proper values for `onset, offset, ...`. In case of using pretrained models it the best choice to follow the `params.yml` files that come along with?

And when we do inference with just 1 audio file and suppose we also have its ground truth, how do we compute the metrics then?

**Comment by hbredin** [comment]
See [this tutorial](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/pipelines/speech_activity_detection) for answers.

**Comment by ajay960singh** [comment]
@hbredin The tutorial is no longer available. Can you redirect me to another resource explaining how to choose the proper values of `onset, offset, ....` for my data?

**Comment by hbredin** [comment]
I updated the above link.
