### ISSUE TITLE
Incorrect metric transfer

### ISSUE THREAD

**Issue by Ruslanmlnkv** [pyannote/pyannote-audio#42]
Hello, If I understand right, you don't use "metric" in module triplet_loss.py and it don't transfer SequenceEmbeddingAutograd after kwargs. In this way always use "cosine" as default.
Model traininig very slow due to distance computing. I have dataset with 1000+ speakers around 10 minutes for each and GPU. The first epoch's metrics were not computed within 3 hours. May be you have some idea how I can speed up it? 
My approach settings is:
```
     metric: cosine
     margin: 0.1
     clamp: positive
     per_batch: 1
     per_label: 40
     per_fold: 40
     gradient_factor: 10000
     batch_size: 512
```

**Comment by hbredin** [comment]
You are right about ˋmetric` parameter not being passed to the parent class. I will fix this in the next release. Thanks for catching this... this might actually explain weird behaviors I noticed in the past!

To speed up training, I suggest you reduce the number of speakers ˋper_fold` to something smaller like ˋper_fold=20`. All possible triplets are tested so it means that the number of tested triplets is proportional ˋper_fold^3ˋ. 

You may also want to reduce ˋper_label` to only a few samples per speaker: ˋper_label=3`. It needs to be greater than 2 to be able to build positive pairs.

**Comment by Ruslanmlnkv** [comment]
Thanks so much, I'll try this.

**Comment by hbredin** [comment]
This has just been fixed in `develop` branch. 
Thanks again for catching this critical bug!
