### ISSUE TITLE
Incompatibility with pyannote-metrics

### ISSUE THREAD

**Issue by lizolson1** [pyannote/pyannote-audio#420]
Thank you for building upon these tools. There are currently some incompatibilities with the updated pyannote-pipeline I wanted to bring to your attention, apologies if you are already planning on addressing them. 

The recent pyannote-metrics update does not have a scripts/pyannote-metrics.py, as the tutorials/pipelines/speaker-darization/README.md suggests to use for evaluation. 

I am currently using an older commit of pyannote-metrics (v. 2.3) to keep this functionality, but the scripts/pyannote-metrics.py does not work with the update to pyannote-pipeline (v. 2.0a0). Now the pyannote-metrics.py call to get_protocol() has an issue with the 'progress' flag.

**Comment by hbredin** [comment]
Thanks @lizolson1 for reporting this -- that's really helpful.

I just updated the faulty tutorial to use `pyannote-metrics` in place of `pyannote-metrics.py`.
Please re-open if that does not fix your issue.
