### ISSUE TITLE
Using librosa==0.8.0, cause librosa.util.exceptions.ParameterError

### ISSUE THREAD

**Issue by mukangt** [pyannote/pyannote-audio#422]
I am tring to use the pipeline by 'dia', but I got this error:
`librosa.util.exceptions.ParameterError: Mono data must have shape (samples,).`
Then I check the version of librosa, I found librosa==0.7.2 is ok, but librosa==0.8.0 could cause the above error.

**Comment by xunyuc2** [comment]
got the same error, solved when roll back librosa to 0.7.2

**Comment by aidosRepoint** [comment]
this issue has also been addressed [here](https://stackoverflow.com/questions/63128049/parametererror-mono-data-must-have-shape-samples-received-shape-1-8748872)

**Comment by hbredin** [comment]
I confirm this is due to breaking changes in librosa 0.8: 
https://github.com/librosa/librosa/commit/f2079c1300c63d515f7fbad1f65208aa57dc5265

Anyone willing to help update pyannote.audio code to support librosa 0.8 ?
