### ISSUE TITLE
does order matter in the rttm file? or can i shuffle it?

### ISSUE THREAD

**Issue by LearnedVector** [pyannote/pyannote-audio#423]
I have an rttm file that I want to sample from. I see that the example rttm file for AMI is in order. Does the order matter or can i just randomly sample from the file?

**Comment by hbredin** [comment]
When loading a RTTM file, `pyannote` will create a [`pyannote.core.Annotation`](http://pyannote.github.io/pyannote-core/structure.html#annotation) instance that is sorted by time internally. Therefore, lines in a RTTM files can be safely shuffled.

What do you mean by _sample from_? You should not have to worry about _sampling_ as `pyannote.audio` will do the sampling for you when training models. Can you please clarify what you are trying to achieve?
