### ISSUE TITLE
Existing key 'annotation' may have been modified. warnings.warn(msg.format(key=key))

### ISSUE THREAD

**Issue by aidosRepoint** [pyannote/pyannote-audio#426]
**Describe the bug**
Whenever I run training on my own dataset, I see further logs:

**Logs**
```bash

/home/user/.local/lib/python3.7/site-packages/pyannote/database/database.py:51: UserWarning: Ignoring deprecated &apos;preprocessors&apos; argument in MUSAN.__init__. Pass it to &apos;get_protocol&apos; instead.
  warnings.warn(msg)
Loading labels: 0file [00:00, ?file/s]/home/user/.local/lib/python3.7/site-packages/pyannote/database/protocol/protocol.py:128: UserWarning: Existing key &quot;annotation&quot; may have been modified.
  warnings.warn(msg.format(key=key))


```
**What does the annotation key error signify?**

I don't use MUSAN or any other noise augmentation since my raw audio is already noisy.

**Content of database.yml file** 
Databases:
   REPOINT: ./repoint_corpus/*/audio/{uri}.wav

Protocols:
   REPOINT:
      SpeakerDiarization:
         Repoint:
           train:
              uri: ./REPOINT/Repoint.train.lst
              annotation: ./REPOINT/Repoint.train.rttm
              annotated: ./REPOINT/Repoint.train.uem
           development:
              uri: ./REPOINT/Repoint.development.lst
              annotation: ./REPOINT/Repoint.development.rttm
              annotated: ./REPOINT/Repoint.development.uem
           test:
              uri: ./REPOINT/Repoint.test.lst
              annotation: ./REPOINT/Repoint.test.rttm
              annotated: ./REPOINT/Repoint.test.uem

**Comment by hbredin** [comment]
This is a [warning printed by `pyannote.database`](https://github.com/pyannote/pyannote-database/issues/56), not an error.

The latest version of `pyannote.database` (that is used to load your `database.yml`) checks that `annotation` time span is strictly contained within `annotated` time span. 

In case it is not, it will automatically crop the `annotation` key with `annotated` time span and print this warning.
You should probably double-check your RTTM and UEM files looking for annotations outside of the annotated span.

**Comment by aidosRepoint** [comment]
> This is a [warning printed by `pyannote.database`](https://github.com/pyannote/pyannote-database/issues/56), not an error.
> 
> The latest version of `pyannote.database` (that is used to load your `database.yml`) checks that `annotation` time span is strictly contained within `annotated` time span.
> 
> In case it is not, it will automatically crop the `annotation` key with `annotated` time span and print this warning.
> You should probably double-check your RTTM and UEM files looking for annotations outside of the annotated span.

thank you! Closing the issuee
