### ISSUE TITLE
Call for collaboration on DIHARD III

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#432]
Sending out an SOS...

Is there anyone here who would you like to join forces (with me, pyannote.audio lead developer) and prepare a submission to [Third DIHARD Speech Diarization Challenge](https://dihardchallenge.github.io/dihard3/index)?

**Comment by sangeetaghangam** [comment]
Hello hbredin - I am interested, esp in the measurement and calibration of system performance. Let me know your thoughts. BTW I also wanted to understand if there is an optimal way to train the neural networks without using the pre-trained models from pyannote?

**Comment by hbredin** [comment]
> Hello hbredin - I am interested, esp in the measurement and calibration of system performance. 

I have been looking at [diarization evaluation metrics](https://github.com/pyannote/pyannote-metrics/blob/develop/docs/pyannote-metrics.pdf) in the past and I agree that there is more to say about this question. Please send me an email if you would like to discuss this in more details.

However, [DIHARD evaluation plan](https://dihardchallenge.github.io/dihard3/docs/third_dihard_eval_plan_v1.1.pdf) clearly defines the evaluation metrics that will be used and unfortunately does not leave a lot of room for studying this (otherwise interesting) question.

Instead, I am rather looking for people that would like to help design and train and test speaker diarization model using the challenge data.

> BTW I also wanted to understand if there is an optimal way to train the neural networks without using the pre-trained models from pyannote?

Can you please open a dedicated issue to discuss this as this seems unrelated to the original issue?

**Comment by sangeetaghangam** [comment]
@hbredin I'll send you a separate not about the metrics and will open another issue for the question included above.

For the DIHARD III challenge, my understanding is that core emphasis is on segmentation and overlap speech. There is no training data to be provided, but evaluation data will be provided which includes DIHARD II dataset so this cannot be used for training. I am already investigating overlap speech (2+ speakers) and would be interested in collaborating on this for the competition assuming it meets the goals you have in mind. I'll send you another email about this to discuss in detail
