### ISSUE TITLE
Memory optimization for deploying to IoT

### ISSUE THREAD

**Issue by aidosRepoint** [pyannote/pyannote-audio#437]
Hi!

This is not a bug at all, but I couldn't find another possible type of question that will fit my situation.

The situation is: I need to deploy the SAD model onto Jetson device where RAM is restricted.

Is there any possibility to unlink some libraries so that they will not be installed, or not be loaded into memory?

For instance, I have noticed that there's tensorboard installed as a requirement, which I don't really need for my purposes. What is the better way to exclude it?

**Comment by hbredin** [comment]
Ooooh! Would be nice to deploy models on IoT devices.

I guess this somehow relates to [this issue](./425 ) where @danFromTelAviv  is asking for a simple (and minimalist) inference API. Unfortunately, I don't know much (nor have resources to dedicate to) this kind of things right now.

Are you sure external libraries really is the issue? Maybe you could simply try to decrease the batch size used for inference?
See https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/pretrained/model#applying-pretrained-models-on-your-own-data for how to do that.

**Comment by aidosRepoint** [comment]
> Ooooh! Would be nice to deploy models on IoT devices.
> 
> I guess this somehow relates to [this issue](./425) where @danFromTelAviv is asking for a simple (and minimalist) inference API. Unfortunately, I don't know much (nor have resources to dedicate to) this kind of things right now.
> 
> Are you sure external libraries really is the issue? Maybe you could simply try to decrease the batch size used for inference?
> See https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/pretrained/model#applying-pretrained-models-on-your-own-data for how to do that.

thank you for answering ;-)

**Comment by aidosRepoint** [comment]
Dear @hbredin , I have found that `Pretrained` class has this line of code:
`self.model_ = model.eval().to(self.device)`
it seems like it builds the model both, on CPU and GPU.
Is there any way to use only CPU or GPU in order to save resources?
