### ISSUE TITLE
Optimal mechanism to train neural network pipeline without using pretrained models

### ISSUE THREAD

**Issue by sangeetaghangam** [pyannote/pyannote-audio#439]
Hello - the use of pretrained model for the pyannote pipeline is fairly easy for training with target/custom data set, however I wanted to train the pipeline from the neural network code directly. Is there a way to use command line pyannote tools without the pretrained models?

**Comment by hbredin** [comment]
I think this is related [to the last bits of the discussion](https://github.com/pyannote/pyannote-audio/issues/430#issuecomment-688765211) I had with @danFromTelAviv.

You can first train (or fine-tune) [SAD](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/models/speech_activity_detection), [SCD](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/models/speaker_change_detection) and [EMB](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/models/speaker_embedding) neural networks separately following their respective tutorials.

Then, you can follow the [diarization tutorial](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/pipelines/speaker_diarization) and update the configuration file to link to the scores obtained with your own models: https://github.com/pyannote/pyannote-audio/issues/430#issuecomment-688765211
