### ISSUE TITLE
Applying pretrained models gets killed

### ISSUE THREAD

**Issue by Persoli** [pyannote/pyannote-audio#443]
First of all, thanks for creating this library!
I'm facing some problems, let's see if you can help.

following the tutorial [Applying pretrained models on your own data](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/pretrained/model) gets my process killed when applying the model. RAM is not used fully, but cores go up to 100% and then go back to 0 in a few seconds. 

**To Reproduce**
I run this on a 2min cropped audio that I took from the AMI database:
```bash
import torch
import multiprocessing 

torch.set_num_threads(multiprocessing.cpu_count())

print('downloading model')
sad = torch.hub.load('pyannote/pyannote-audio', 'sad_ami', device='cpu', batch_size=32)
print('finished')

test_file = {'uri': 'audio_real.wav', 'audio': './audio.wav'}

print('applying sad')
sad_scores = sad(test_file)
print('finished')

print('binarizing')
from pyannote.audio.utils.signal import Binarize
binarize = Binarize(offset=0.52, onset=0.52, log_scale=True, 
                    min_duration_off=0.1, min_duration_on=0.1)
print('finished')

print('applying')
speech = binarize.apply(sad_scores, dimension=1)
print('finished')

print(speech)
```

**pyannote environment**

```bash
$ pip freeze | grep pyannote
pyannote.audio==2.0a1+63.g4d7687d
pyannote.core==4.1
pyannote.database==4.0.1
pyannote.metrics==3.0.1
pyannote.pipeline==1.5.2
```

**Additional context**
I've ran this same program on 5 sec audios and it succeeded. I've also ran that on a GCP machine with 64 cores and 64 GB of RAM, and I still got the process killed, with the last message being 'applying sad', and then "Killed".

**Comment by hbredin** [comment]
Thanks for your interest in pyannote and welcome to the community.

Since it works with 5sec audio and gets killed with 2min audio, it looks like this might be a memory issue.
Does this work as expected on GPU?

**Comment by MarvinLvn** [comment]
@hbredin 

One of the voice type classifier's user met the same problem recently.
I've tried to profile the memory usage of the **apply_pretrained** function. I'll only show the lines consuming some memory as well as some context. Note that this has been done on my old version of pyannote, so there might exist some differences with the current version : 

Standard behavior (without any changes) :
```
   406    351.5 MiB      0.0 MiB               pretrained = Pretrained(validate_dir=validate_dir,
   407    351.5 MiB      0.0 MiB                                       duration=duration,
   408    351.5 MiB      0.0 MiB                                       step=step,
   409    351.5 MiB      0.0 MiB                                       batch_size=batch_size,
   410    362.2 MiB     10.7 MiB                                       device=device)
   411    362.2 MiB      0.0 MiB               output_dir = validate_dir / 'apply' / f'{pretrained.epoch_:04d}

   452   3280.0 MiB      1.2 MiB           for current_file in getattr(protocol, subset)():
   453   3280.0 MiB   2916.6 MiB               fX = pretrained(current_file)
   454   3280.0 MiB      0.0 MiB               precomputed.dump(current_file, fX)
```

Line 410 loads the model : we won't be able to optimize this part (thus, I won't show it in the logs below)
Line 453 which does apply the model on the audio consumes 3000 MiB of memory, which seems quite big (my batch size is 32, and the audio file lasts only a few minutes)

With call to **with torch.no_grad()** in the apply_pretrained function : 

```
   453    587.7 MiB      1.2 MiB               for current_file in getattr(protocol, subset)():
   454    587.5 MiB    224.2 MiB                   fX = pretrained(current_file)
   455    587.5 MiB      0.0 MiB                   precomputed.dump(current_file, fX)
```

With call to  **with torch.no_grad()** in the apply_pretrained function + batch size of 8 : 

```
   453    457.9 MiB      1.3 MiB               for current_file in getattr(protocol, subset)():
   454    457.7 MiB     91.3 MiB                   fX = pretrained(current_file)
   455    457.7 MiB      0.0 MiB                   precomputed.dump(current_file, fX)
```

**torch.no_grad()** is supposed to deactivate the autograd engine (without it, we can't backprop, but this is not something we want during the inference time)

**Comment by hbredin** [comment]
Thanks a lot for narrowing this down! That was a misunderstanding on my side: I thought calling `model.eval()` would do just that: 
https://github.com/pyannote/pyannote-audio/blob/c3791bc02ce5bc839a559427628592fad62fdf79/pyannote/audio/features/pretrained.py#L139

Wrapping this line (and maybe the next one) with `torch.no_grad` should probably be enough:
https://github.com/pyannote/pyannote-audio/blob/c3791bc02ce5bc839a559427628592fad62fdf79/pyannote/audio/train/model.py#L468-L468

I'd gladly merge a PR!

**Comment by MarvinLvn** [comment]
@Persoli 

PR https://github.com/pyannote/pyannote-audio/pull/444 should likely solve your issue.

**Comment by Persoli** [comment]
Thank you guys for your help! I actually solved it by reinstalling it using conda and changing my python version (I was trying it with python 3.8.5 and then I changed to 3.8.2).
