### ISSUE TITLE
Using oracle SAD and SCD

### ISSUE THREAD

**Issue by swm1718** [pyannote/pyannote-audio#445]
Hello - I am trying to use a pre-trained pipeline with oracle SAD and SCD based on one of the tutorials, but cannot get it to work.  I think it must be possible as it was mentioned in previous issues #256 and #318.  The relevant part of the code I have tried is shown below, but it gave the same results as not specifying 'oracle'.  I suspect it is missing the file location of the oracle RTTM file, but cannot see where it should go.  Please could you show me where I've gone wrong?  Many thanks.  Simon

import torch
pipeline = torch.hub.load('pyannote/pyannote-audio', 'dia')
pipeline.sad_scores = 'oracle'
pipeline.scd_scores = 'oracle'

for meeting in meetings:
    fname = 'audio/' + meeting + '.wav'
    diarization = pipeline({'audio': fname})
    ....

**Comment by hbredin** [comment]
This is untested code but it should work:

```python
import torch
from pyannote.audio.pipeline import OracleSpeechTurnSegmentation

# load and instantiate pretrained pipeline (with automatic SAD and SCD)
pipeline = torch.hub.load('pyannote/pyannote-audio', 'dia')

# override speech turn segmentation sub-pipeline
pipeline.speech_turn_segmentation = OracleSpeechTurnSegmentation()

# load / create the reference segmentation as a pyannote.core.Annotation instance
# - from RTTM file with pyannote.database.util.load_rttm
# - or manually with http://pyannote.github.io/pyannote-core/structure.html#annotation
reference = ...

diarization = pipeline({'audio': 'file.wav', 'annotation': reference})
```

Note, however, that the clustering thresholds were optimized for automatic (SAD + SCD) segmentation, not for oracle segmentation. This may lead to over- or under-clustering results.

**Comment by swm1718** [comment]
Thank you very much for that.  I have tried the code using your first option for loading the reference segmentation (i.e. using `from pyannote.database.util import load_rttm` and then `reference = load_rttm(meeting + ".rttm")`.  I get the error message below about a missing 'dict' object 'relabel_tracks' that I cannot explain, do you know what the issue is here?

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-26ed5b09cf70> in <module>
     34 
     35     fname = 'audio_hsum_WPE/' + meeting + '.wav'
---> 36     diarization = pipeline({'audio': fname, 'annotation': reference})
     37 
     38     # dump result to disk using RTTM format

~/anaconda3/lib/python3.7/site-packages/pyannote/audio/pipeline/speaker_diarization.py in __call__(self, current_file)
    152 
    153         # segmentation into speech turns
--> 154         speech_turns = self.speech_turn_segmentation(current_file)
    155 
    156         # some files are only partially annotated and therefore one cannot

~/anaconda3/lib/python3.7/site-packages/pyannote/audio/pipeline/speech_turn_segmentation.py in __call__(self, current_file)
     59         """
     60 
---> 61         return current_file["annotation"].relabel_tracks(generator="string")
     62 
     63 

AttributeError: 'dict' object has no attribute 'relabel_tracks'
```

**Comment by hbredin** [comment]
`load_rttm` returns a dictionary of `Annotation` instances, not an `Annotation` instance.
This is because one RTTM file can contain annotations for multiple audio files:

```python
rttms = load_rttm(...)  # returns a dict
reference = rttms[your_file_identifier]  
```
