### ISSUE TITLE
pyannote-audio commands fail when pyannote-audio is installed through pip

### ISSUE THREAD

**Issue by raphaelreme** [pyannote/pyannote-audio#446]
Hi!

**Describe the bug**

I'm trying to use pyannote-audio commands on an environment where pyannote is installed through pip. But it seems that the last deployed package of pyannote-audio is from April (v2.0a1). Whereas pyannote-database has been upgraded and deployed to the version v4.0.1 since. (As pyannote pipeline and probably some others.)

Therefore the pyannote-audio command relies on a former version of pyannote database (v3.0.1 probably) which is incompatible with the one downloaded by pip (v4.0.1).

I think I know how to resolve this. (-> Manually pin all the versions of pyannote packages of April.) But as I followed the tutorial on github recently, I don't know if it's gonna work all the same with the April version. (I shall find out soon enough though)

Nevertheless I post this issue in case you weren't aware of it and hoping that it could help some other people struggling with the same problem :)

**Step to reproduce**
```bash
$ # On a new environment do:
$ pip install pyannote-audio
$ mkdir exp_dir
$ pyannote-audio sad train --pretrained=sad --subset=train --parallel=8 exp_dir AMI.SpeakerDiarization.MixHeadset
```

Do you know when a new version of pyannote-audio will be deployed on PyPi ?

**Comment by raphaelreme** [comment]
(A little more detail about the error I get if it can help)

```bash
$ pyannote-audio sad train --subset=train --pretrain=sad --parallel=8 exp_dir AMI.SpeakerDiarization.MixHeadset
Using cache found in /home/raph/.cache/torch/hub/pyannote_pyannote-audio_develop
Traceback (most recent call last):
  File "/home/raph/.virtualenvs/audio-ml/bin/pyannote-audio", line 8, in <module>
    sys.exit(main())
  File "/home/raph/.virtualenvs/audio-ml/lib/python3.8/site-packages/pyannote/audio/applications/pyannote_audio.py", line 363, in main
    app.train(protocol, **params)
  File "/home/raph/.virtualenvs/audio-ml/lib/python3.8/site-packages/pyannote/audio/applications/base.py", line 184, in train
    protocol = get_protocol(protocol_name, progress=True,
TypeError: get_protocol() got an unexpected keyword argument 'progress'
```

And indeed https://github.com/pyannote/pyannote-database/commit/03b211daeca209de901576dfe9e0b35f48afc0a2 this commit from june (which is deployed on PyPi) has deleted the progress kwarg.

**Comment by raphaelreme** [comment]
Version of April deployment:
```
$ pip install
    pyannote-audio==2.0a1 \
    pyannote-pipeline==1.5 \
    pyannote-metrics==2.3 \
    pyannote-database==3.0.1 \
    pyannote-core==3.7.1
```

Note: It will not support the Musan Collection used for data augmentation as described it the tutorial ;)

**Comment by hbredin** [comment]
Thanks for reporting this issue and for offering a solution.

> Do you know when a new version of pyannote-audio will be deployed on PyPi ?

`pyannote.audio` is being refactored to rely on `pytorch-lightning` in [this PR](https://github.com/pyannote/pyannote-audio/pull/407).  
I will make a new release when this is done and will make sure to pin `pyannote-*` version correctly to avoid any future similar issues.

Until then, the recommended way to install `pyannote.audio` is to do it from source, as described in the [Installation](https://github.com/pyannote/pyannote-audio#installation) section. 

Closing this issue but feel free to ask me to re-open it if needed.
