### ISSUE TITLE
Update tutorials

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#448]
cc @mogwai

Contrary to what I said earlier, tutorials in pytorch-lighning PR have not been updated with the new pyannote.audio CLI.

The main changes are that the actual task no longer has to be provided in the command line tool: it is read directly from the configuration file.

In short: `pyannote-audio sad train` becomes `pyannote-audio train`.

That being said, CLI unit tests have been updated:
https://github.com/pyannote/pyannote-audio/blob/pytorch-lightning/tests/cli

Your first task will probably be to update tutorials, using bash scripts in https://github.com/pyannote/pyannote-audio/blob/pytorch-lightning/tests/cli as examples.

**Comment by mogwai** [comment]
- [ ] Convert to Jupyter Notebook
- [ ] Move Citations
- [ ] Order tutorials

**Comment by hbredin** [comment]
Ideally, I'd like to have both CLI and API tutorials. 
The CLI might have its own audience.

**Comment by mogwai** [comment]
This is being parked until the refactor?

**Comment by hbredin** [comment]
Yes. Let's put this on hold for a while.
