### ISSUE TITLE
In silence speech segment found

### ISSUE THREAD

**Issue by Vintic** [pyannote/pyannote-audio#450]
[silence_2.wav.zip](https://github.com/pyannote/pyannote-audio/files/5260194/silence_2.wav.zip)

**Describe the bug**
Pretrained model found in silence some speech

**To Reproduce**
Steps to reproduce the behaviour:
```
from pyannote.audio.utils.signal import Binarize
import torch
sad = torch.hub.load('pyannote/pyannote-audio', 'sad_ami', device='cpu', batch_size=128)
binarize = Binarize(offset=0.52, onset=0.52, log_scale=True, 
                    min_duration_off=0.1, min_duration_on=0.5)
sad_scores2 = sad({'audio': 'silence_2.wav'})
# speech regions (as `pyannote.core.Timeline` instance)
speech2 = binarize.apply(sad_scores2, dimension=1)
```

**pyannote environment**

```bash
$ pip freeze | grep pyannote
pyannote.audio @ https://github.com/pyannote/pyannote-audio/tarball/develop
pyannote.core==4.1
pyannote.database==4.0.1
pyannote.metrics==3.0.1
pyannote.pipeline==1.5.2
```

**Comment by hbredin** [comment]
Thanks for trying out pyannote.audio.

Quote from [this tutorial](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/pretrained/model):
> Note that, in case of domain mismatch between your data and the AMI corpus, you might be better off training your own models or fine-tuning a pretrained one.

You may want to try with a model trained on the DIHARD dataset (replace `sad_ami` with `sad`) or increase the `offset` and `onset` thresholds.

But ideally, you should try to [fine-tune a model to your own data](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/finetune).
