### ISSUE TITLE
Working with fine-tuned models and optimised pipeline locally isn't so clear

### ISSUE THREAD

**Issue by ooza** [pyannote/pyannote-audio#457]
Hi,
Unfortunately, I didn't get the same result.
I'm looking to use the check points along with the optimized diarization pipeline and apply them locally on a single wav file.
I have tested the following:
```
sad_scores = cwd+"/experiments/sad/train/./weights/0023.pt"
scd_scores = cwd+"/experiments/scd/train/./weights/0023.pt"
emb_scores = cwd+"/experiments/emb/train/./weights/0023.pt"
method = "affinity_propagation"

pipeline = SpeakerDiarization(sad_scores = sad_scores,
                                                  scd_scores = scd_scores,
                                                   embedding = emb_scores,
                                                   method=method)

pipeline.load_params(params_file)
diarization = pipeline(test_file)
```
and compared it to the result that I got on icolab using the command ```pyannote-pipeline apply``` (with a custom protocol that I've defined following the tutorial of pyannote-database).
The two obtained results on the same input file were different by 2,6% (of DER)!
Should I provide the npy files (of the input file) in addition to the params.yml file and the check points ?
Am I missing something ?
Working with fine-tuned models and optimised pipeline locally isn't so clear!

**Comment by hbredin** [comment]
Getting a different output is expected since you replaced pretrained models by your own locally fine-tuned models and also fine-tuned your pipeline hyperparameters. 

The whole point of fine-tuning is to get a system better suited to your data and get better (hence different) results.

**Comment by ooza** [comment]
Thanks for your reply. 
Actually, both results were generated using my fine-tuned models (not pretrained vs fine-tuned).
The main difference is: the first result was obtained using ```pyannote-pipeline apply```(after creating a custom protocol..),
while the second was obtained without defining any protocol. I've picked up the **same checkpoints** of the first experiment and used them along with the **params.yml file**, in the python API, to define a diarization pipeline and apply it on the same input wav file but without any annotation data, as mentioned in my first comment (

```
test_file = {'uri': 'comp_010025', 'audio': cwd+'/experiments/test_files/comp_010025.wav'}

sad_scores = cwd+"/experiments/sad/train/./weights/0023.pt"
scd_scores = cwd+"/experiments/scd/train/./weights/0023.pt"
emb_scores = cwd+"/experiments/emb/train/./weights/0023.pt"
method = "affinity_propagation"

pipeline = SpeakerDiarization(sad_scores = sad_scores,
                                                  scd_scores = scd_scores,
                                                   embedding = emb_scores,
                                                   method=method)

pipeline.load_params(params_file)
diarization = pipeline(test_file)

```
The idea is to apply the diarization pipeline on an input wav file without providing any annotation data. But I didn't get the same result.
Am I missing something? apart from the checkpoints and the params.yml of the optimised pipeline.
**PS: the difference in terms of DER is 0.83% (not 2.6%)**

**Comment by hbredin** [comment]
There might be a small difference in the way embeddings (and scores) are computed.
[This tutorial](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/pipelines/speaker_diarization) uses the `--step=0.1` option (i.e. uses a 90% overlap between consecutive windows used for extracting embeddings) while the above syntax [defaults to using `step=0.25`](https://github.com/pyannote/pyannote-audio/blob/b8d623596e1c01a1049a0ba2eb5be2f6bf8ba1a0/pyannote/audio/features/pretrained.py#L63-L65).

Try with [the following syntax](https://github.com/pyannote/pyannote-audio/blob/b8d623596e1c01a1049a0ba2eb5be2f6bf8ba1a0/pyannote/audio/features/wrapper.py#L97-L100):

```python
pipeline = SpeakerDiarization(
    sad_scores = {sad_scores: {'step': 0.1}},
    scd_scores = {scd_scores: {'step': 0.1}},
    embedding = {emb_scores: {'step': 0.1}},
    method=method)
```

**Comment by ooza** [comment]
Yes indeed, the difference is due to the fact that I've used  ```--step=0.1```, while the default value is 0.25.
The problem was fixed using the syntax that you suggested.
Thank you. Closing the issue.

**Comment by ooza** [comment]
@hbredin 
I have one more question regarding the performance of the diarization pipeline.
Actually, it looks 4.18 minutes to test an input file of 3 minutes using my fine-tuned models locally (CPU) as described above.
Do you have any suggestions to speed up the pipeline's inference ? Like using batched solution or something else. 
Knowing that I got the same performance on GPU our server.

**Comment by hbredin** [comment]
Would be nice to have a detailed breakdown of the duration taken by each part of the pipeline.
To speed up inference, two easy options that come to mind:
1. increase `step`  to something like 0.25 (2.5x speed up) or 0.5 (5x speed up) for SAD and SCD (don't do that for EMB).  you might get a slight decrease in performance, though.
2. increase `batch_size` (default is 32) to a larger value, using the same syntax as the one you used for `step`.

**Comment by ooza** [comment]
Thanks for your reply.
 How can I do this? 
"Would be nice to have a detailed breakdown of the duration taken by each part of the pipeline."

Yes, increasing the step to 0.5 for SAD and SCD makes the running time much faster. I've passed from 4:18min to 1:51min on CPU. However the DER has increased by 0.6%.
I surprisingly haven't see any improvement in the perfromance when I've increased the batch_size to 128, e.g.:
```embedding={emb_scores: {'step': 0.1,'batch_size': 128}},```
One last question:
Do inference support GPU ?

**Comment by hbredin** [comment]
> Thanks for your reply.
> How can I do this?
> "Would be nice to have a detailed breakdown of the duration taken by each part of the pipeline."
Dive in the speaker diarization pipeline code and add timing logs in there.

> Yes, increasing the step to 0.5 for SAD and SCD makes the running time much faster. I've passed from 4:18min to 1:51min on CPU. However the DER has increased by 0.6%.

> One last question:
> Do inference support GPU ?
It does. You can pass a `device`  option in the same way you did for `step` and `batch_size`.

**Comment by Akshat4112** [comment]
How to run speaker diarization pipeline with GPU? it looks like lot of people use --gpu but how can we pass it from training?
