### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV) when running sad in loop

### ISSUE THREAD

**Issue by kkawabat** [pyannote/pyannote-audio#459]
I have a list of short audio files (~ 1500 files, 5 ~ 30 seconds long) that I am trying to calculate the start and end times.   Below is my simplified script following the sample code in [pyannote-audio/tutorials/pretrained/model/README.md](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/pretrained/model/README.md).

```python
    sad = torch.hub.load('pyannote/pyannote-audio', 'sad_ami')

    binarize = Binarize(offset=0.52, onset=0.52, log_scale=True,
                        min_duration_off=0.1, min_duration_on=0.1)

    df = pd.read_csv(/path/to/input.csv)
    speech_list = []
    for i, row in df.iterrows():
        print(i)
        sad_scores = sad({'uri': 'filename', 'audio': row['filePath']})
        speech = binarize.apply(sad_scores, dimension=1)

        if len(speech) == 0:
            start, end = float('nan'), float('nan')
        else:
            start, end = speech[0].start, speech[0].end

        speech_list.append([row['file_id'], start, end, len(speech)])
    pd.DataFrame(speech_list, columns=col).to_csv(/path/to/output.csv)
```
I ran the script 3 times the first time I got  `Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)` after 500 files. The second time the computer got noticably slower until it completely froze and I had to restart, the third time I got the same SIGSEGV crash after 1100 files. 

I am wondering if this is a known memory leak issue. Or if I am processing it incorrectly.

**Comment by hbredin** [comment]
A (possibly related) memory leak has been fixed [recently](https://github.com/pyannote/pyannote-audio/commit/a1d2f4512413d106cec3c9b304e35c50be1e111b). Are you using the latest version of `develop` branch?

**Comment by kkawabat** [comment]
hmm I am not encountering this issue anymore so I believe so.
