### ISSUE TITLE
Breaking change in Keras optimizer

### ISSUE THREAD

**Issue by yinruiqing** [pyannote/pyannote-audio#46]
There is a breaking change in Keras optimizer in version 2.0.7. So when I use a _SMORMS3_ (an optimizer defined in pyannote-audio and used in pyannote-speech-detection and pyannote-change-detection), it raise an error: 
`get_updates() missing 1 required positional argument: 'constraints'`

**Comment by hbredin** [comment]
We should probably contribute SMORMS3 directly into Keras. 
This would avoid any other future problem...

@GregGovit, would you be interested in doing this? 
If you don't have time, would you allow us to do that on your behalf?

For such a contribution to be accepted in Keras, I think we should also contribute a simple optimizer benchmark on MNIST. See https://github.com/fchollet/keras/blob/master/examples/mnist_mlp.py

**Comment by hbredin** [comment]
In the meantime, 
* either we update https://github.com/pyannote/pyannote-audio/blob/master/setup.py#L47 to make sure we use Keras <= 2.0.6 
* or we update https://github.com/pyannote/pyannote-audio/blob/master/pyannote/audio/applications/speech_detection.py#L308 (and its equivalent in change detection script) to RMSProp

**Comment by hbredin** [comment]
I went for the easiest solution: fix our own SMORMS3 implementations to match the new Keras API.
The fix is available in `develop` branch. Closing.
