### ISSUE TITLE
How many hours of training are needed for speaker diarization model?    

### ISSUE THREAD

**Issue by preniqivjosa** [pyannote/pyannote-audio#461]
Hello, I am interested to train my own model for speaker diarization in my native language.
I am interested to know what is the good amount of training hours and is there any limitation on the number of speakers?

**Comment by alamnasim** [comment]
It depends on your use case, application and domain.

For your native language you may need to train it from scratch and based on your domain keywords and application where you have to use, you need to annotate target audio files in rttm and uef format.

Yes It also depends on the number of speakers, if you have more speakers it would be better for your model to adapt.
