### ISSUE TITLE
Couldnt find YAML file

### ISSUE THREAD

**Issue by yhlim19** [pyannote/pyannote-audio#464]
Hi, I have the same kind of issue from the latest branch..FileNotFoundError: "pyannote.database" relies on a YAML configuration file but could not find any. Here are the locations that were looked for: D:\Programming\PythonTest\pyannote_Audio\database.yml, C:\Users\yhlim.pyannote\database.yml.
Could you provide some guidance?

**Comment by bbrookie** [comment]
This problem occurs because you did not use the command line in the correct directory. When you use the command line, make sure that there is a database.yml file in this directory.

**Comment by yhlim19** [comment]
> This problem occurs because you did not use the command line in the correct directory. When you use the command line, make sure that there is a database.yml file in this directory.
> 
> > Hi, I have the same kind of issue from the latest branch..FileNotFoundError: "pyannote.database" relies on a YAML configuration file but could not find any. Here are the locations that were looked for: D:\Programming\PythonTest\pyannote_Audio\database.yml, C:\Users\yhlim.pyannote\database.yml.
> > Could you provide some guidance?

Hi,
I had cloned the whole file first.
I tried to find the location of the database.yml file elsewhere but couldnt find any.
Wish I could use your help.

**Comment by bbrookie** [comment]
> > This problem occurs because you did not use the command line in the correct directory. When you use the command line, make sure that there is a database.yml file in this directory.
> > > Hi, I have the same kind of issue from the latest branch..FileNotFoundError: "pyannote.database" relies on a YAML configuration file but could not find any. Here are the locations that were looked for: D:\Programming\PythonTest\pyannote_Audio\database.yml, C:\Users\yhlim.pyannote\database.yml.
> > > Could you provide some guidance?
> 
> Hi,
> I had cloned the whole file first.
> I tried to find the location of the database.yml file elsewhere but couldnt find any.
> Wish I could use your help.

So i think you should first read the [guide](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/data_preparation)
