### ISSUE TITLE
Make pyannote consume less memory

### ISSUE THREAD

**Issue by vinperdom** [pyannote/pyannote-audio#467]
First of all, thank you for creating pyannote!

I process audio from telemarketing companies in Brazil, using ML to rate how was the customer service, and I'd like to use pyannote to calculate a few more KPIs. I'm running it on the Google "Cloud Run" service, which basically allows you to create a docker image and deploy it to a VM, communicating through HTTP requests. It works perfectly, but since the memory limit is 1024 MB, I can only do so much with it. When I apply it on audios with more than a few minutes, it breaks due to lack of memory. 

Locally it works fine, as you can see below.

![Screenshot from 2020-10-29 23-18-43](https://user-images.githubusercontent.com/29169767/97653221-055a5500-1a3f-11eb-8306-f3c71d5f7f5e.png)
  

Maybe we could fragment the audio into smaller chunks and apply the model iteratively.

**Comment by hbredin** [comment]
You could do that indeed.

**Comment by vinperdom** [comment]
I did it and worked fine. If this may help people in the future, I used pydub to divide the audio into chunks and got to apply the model in under 1024 MB.

**Comment by TaridaGeorge** [comment]
@vinperdom  how about the timestamps? You divide the audio into chunks of how many seconds?

**Comment by vinperdom** [comment]
3~4 seconds made the code run on less than 700 MB. More than that and it went to approximately 1060. Every time I iterated and generated a chunk, I added the result with the time it happened in the actual audio. So if it was the third chunk and the intervals were 3 seconds each, I'd add 9 seconds to the timestamp received. Worked perfectly.

**Comment by mogwai** [comment]
The new inference class in version 2 will help with this problem @hbredin ?

**Comment by hbredin** [comment]
No, not in its current shape. Would have to be updated to support streaming.
