### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by mogwai** [pyannote/pyannote-audio#473]
<a href="https://github.com/mogwai"><img src="https://avatars1.githubusercontent.com/u/5440566?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mogwai](https://github.com/mogwai)**
_Wednesday Oct 14, 2020 at 09:23 GMT_
_Originally opened as https://github.com/hbredin/pyannote-audio-v2/issues/16_

----

When the repository is public, add code coverage.

**Comment by hbredin** [comment]
The repo is now public, can we add code coverage?

**Comment by mogwai** [comment]
Yes we certainly can.

**Comment by mogwai** [comment]
```
[![codecov](https://codecov.io/gh/pyannote/pyannote-audio/branch/develop/graph/badge.svg)](https://codecov.io/gh/pyannote/pyannote-audio)
```
[![codecov](https://codecov.io/gh/pyannote/pyannote-audio/branch/develop/graph/badge.svg)](https://codecov.io/gh/pyannote/pyannote-audio)
