### ISSUE TITLE
pyannote-audio CLI

### ISSUE THREAD

**Issue by mogwai** [pyannote/pyannote-audio#476]
<a href="https://github.com/hbredin"><img src="https://avatars2.githubusercontent.com/u/1080837?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hbredin](https://github.com/hbredin)**
_Sunday Oct 18, 2020 at 12:54 GMT_
_Originally opened as https://github.com/hbredin/pyannote-audio-v2/issues/30_

----

- [x] ditch `docopt` in favor of `typer`
- [x] consider ditching `validate` mode (we need to rethink what we mean by "validation")

**Comment by mogwai** [comment]
<a href="https://github.com/mogwai"><img src="https://avatars1.githubusercontent.com/u/5440566?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mogwai](https://github.com/mogwai)**
_Tuesday Oct 20, 2020 at 14:24 GMT_

----

Typer looks really good

**Comment by mogwai** [comment]
<a href="https://github.com/hbredin"><img src="https://avatars2.githubusercontent.com/u/1080837?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hbredin](https://github.com/hbredin)**
_Wednesday Oct 21, 2020 at 11:10 GMT_

----

Also consider `thinc`  configuration system: https://thinc.ai/docs/api-config

**Comment by mogwai** [comment]
<a href="https://github.com/hbredin"><img src="https://avatars2.githubusercontent.com/u/1080837?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hbredin](https://github.com/hbredin)**
_Wednesday Oct 21, 2020 at 11:27 GMT_

----

https://pypi.org/project/catalogue/ might be a simpler alternative.

**Comment by mogwai** [comment]
<a href="https://github.com/mogwai"><img src="https://avatars1.githubusercontent.com/u/5440566?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mogwai](https://github.com/mogwai)**
_Wednesday Oct 21, 2020 at 11:37 GMT_

----

https://hydra.cc is a configuration by composition that you might have already seen?

**Comment by hbredin** [comment]
Ended up using Hydra and dropping validation mode. 

See [this PR](512) and [this related issue](515).

**Comment by hbredin** [comment]
Here is what remains to be done regarding `pyannote-audio-train` CLI:

- [ ] prevent DDP/hydra combo to create multiple output dirs (see https://forums.pytorchlightning.ai/t/using-hydra-ddp/567 for a possible solution)
- [ ] add support for fine-tuning from an exiting checkpoint (should inherit checkpoint's hydra config)
- [ ] add support for Hydra structured config (this might help: https://github.com/pytorch/hydra-torch, https://github.com/romesco/hydra-lightning)
