### ISSUE TITLE
Pipelines

### ISSUE THREAD

**Issue by mogwai** [pyannote/pyannote-audio#477]
<a href="https://github.com/hbredin"><img src="https://avatars2.githubusercontent.com/u/1080837?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hbredin](https://github.com/hbredin)**
_Sunday Oct 18, 2020 at 12:55 GMT_
_Originally opened as https://github.com/hbredin/pyannote-audio-v2/issues/31_

----

**Comment by mogwai** [comment]
<a href="https://github.com/mogwai"><img src="https://avatars1.githubusercontent.com/u/5440566?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mogwai](https://github.com/mogwai)**
_Thursday Oct 22, 2020 at 18:37 GMT_

----

Are these going to be the different models combined into a pipeline to perform the entire speaker diarization problem?

**Comment by mogwai** [comment]
<a href="https://github.com/hbredin"><img src="https://avatars2.githubusercontent.com/u/1080837?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hbredin](https://github.com/hbredin)**
_Friday Oct 23, 2020 at 07:54 GMT_

----

Yes. I am happy with the old API so we can probably just bring back the old `pyannote.audio.pipeline` module.

**Comment by hbredin** [comment]
Closed by #505
