### ISSUE TITLE
Investigate a CI with GPU Access

### ISSUE THREAD

**Issue by mogwai** [pyannote/pyannote-audio#478]
<a href="https://github.com/mogwai"><img src="https://avatars1.githubusercontent.com/u/5440566?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mogwai](https://github.com/mogwai)**
_Thursday Oct 22, 2020 at 18:16 GMT_
_Originally opened as https://github.com/hbredin/pyannote-audio-v2/issues/39_

----

For testing inference and training it would be nice to check that they are on the correct device. Luckily lightning takes care of this mostly but it would be good to verify for out custom inference code.

This would also mean that we could train a few models and verify results are as expected.

**Comment by mogwai** [comment]
<a href="https://github.com/hbredin"><img src="https://avatars2.githubusercontent.com/u/1080837?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hbredin](https://github.com/hbredin)**
_Friday Oct 23, 2020 at 09:06 GMT_

----

Would be nice to to fully re-train all models after each commit.
Something like https://cml.dev/

**Comment by mogwai** [comment]
<a href="https://github.com/mogwai"><img src="https://avatars1.githubusercontent.com/u/5440566?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mogwai](https://github.com/mogwai)**
_Friday Oct 23, 2020 at 16:33 GMT_

----

Maybe something like https://dvc.org/ would be useful here too

**Comment by aktech** [comment]
Hi @mogwai I am the creator of Cirun.io, "GPU" and "CI" caught my eye.

FWIW I'll share my two cents. I created a service for problems like these, which is basically running custom machines (including GPUs) in GitHub Actions: https://cirun.io/

It is used in multiple open source projects needing GPU support like the following:

https://github.com/pystatgen/sgkit/
https://github.com/qutip/qutip-cupy

It is fairly simple to setup, all you need is a cloud account (AWS or GCP) and a simple yaml file describing what kind of machines you need and Cirun will spin up ephemeral machines on your cloud for GitHub Actions to run. It's native to GitHub ecosystem, which mean you can see logs/trigger in the Github's interface itself, just like any Github Action run.

Also, note that Cirun is free for Open source projects. (You only pay to your cloud provider for machine usage)
