### ISSUE TITLE
numpy.ndarray vs. torch.Tensor

### ISSUE THREAD

**Issue by mogwai** [pyannote/pyannote-audio#482]
<a href="https://github.com/hbredin"><img src="https://avatars2.githubusercontent.com/u/1080837?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hbredin](https://github.com/hbredin)**
_Friday Oct 30, 2020 at 17:10 GMT_
_Originally opened as https://github.com/hbredin/pyannote-audio-v2/issues/55_

----

> I have noticed over the last few pr's that you often use numpy instead of torch tensors? Is this because of some performance improvement or are you just more familiar with the API? If we want to boost performance at some stage, it might be a good idea to convert everything to tensors including the random number operations as they are much slower than the torch ones.

Can you please clarify your thoughts on this in a dedicated issue?

_Originally posted by @hbredin in https://github.com/hbredin/pyannote-audio-v2/pull/37#issuecomment-719658266_

**Comment by mogwai** [comment]
<a href="https://github.com/mogwai"><img src="https://avatars1.githubusercontent.com/u/5440566?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mogwai](https://github.com/mogwai)**
_Saturday Oct 31, 2020 at 15:02 GMT_

----

At some point, the library will benefit massively from torchscripting as many areas as possible. I'm going to double check this now, but I don't think we can JIT a lot of the code if it has numpy calls: 

```py
import torch

@torch.jit.script
def test_method():
    t = torch.rand(1,3,40)
    t = t.numpy() 
    t += 1
    return t
```

```
Traceback (most recent call last):
  File "play.py", line 10, in <module>
    def test_method():
  File "/home/harry/miniconda3/envs/v2/lib/python3.8/site-packages/torch/jit/_script.py", line 939, in script
    fn = torch._C._jit_script_compile(
RuntimeError: 
Tried to access nonexistent attribute or method 'numpy' of type 'Tensor'.:
  File "play.py", line 12
def test_method():
    t = torch.rand(1,3,40)
    t = t.numpy()
        ~~~~~~~ <--- HERE
    t += 1
    return t
```

Another reason is  that the torch.Tensor API is almost identical to the numpy one so considering that we have to use torch.Tensors for training, we may as well stick with them the whole time?

**Comment by mogwai** [comment]
<a href="https://github.com/hbredin"><img src="https://avatars2.githubusercontent.com/u/1080837?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hbredin](https://github.com/hbredin)**
_Saturday Oct 31, 2020 at 16:38 GMT_

----


I just searched for `.numpy()` in current code base and it is only used in `Inference` for now.
I agree that this is a good idea to get rid of this whenever possible.

What about calls to `.cpu()` in `Inference`? I think we should keep them, shouldn't we?

**Comment by mogwai** [comment]
<a href="https://github.com/mogwai"><img src="https://avatars1.githubusercontent.com/u/5440566?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mogwai](https://github.com/mogwai)**
_Saturday Oct 31, 2020 at 16:59 GMT_

----

Definitely, you don't want the GPU memory getting clogged up. It would also be good to have the option to write the results to file if you're processing large amounts of data so that RAM doesn't run out either?

**Comment by mogwai** [comment]
<a href="https://github.com/hbredin"><img src="https://avatars2.githubusercontent.com/u/1080837?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hbredin](https://github.com/hbredin)**
_Saturday Oct 31, 2020 at 17:00 GMT_

----

Or even better: support audio streams

**Comment by mogwai** [comment]
<a href="https://github.com/mogwai"><img src="https://avatars1.githubusercontent.com/u/5440566?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mogwai](https://github.com/mogwai)**
_Tuesday Nov 03, 2020 at 16:10 GMT_

----

I wasn't clear about this actually, what I mean is the use of numpy all over. 

`np.sum`
`np.exp`
`np.vstack`
`np.mean` 

These can all be replaced at some point by the torch equivalent

**Comment by Z-demo** [comment]
> [<img alt="" width="48" height="48" src="https://avatars1.githubusercontent.com/u/5440566?v=4">](https://github.com/mogwai) **[mogwai的](https://github.com/mogwai)****评论**
> _2020年10月31日星期六格林尼治标准时间15:02_
> 
> 在某个时候，图书馆将通过尽可能多地编写火炬手脚本而受益匪浅。我现在要再次检查这一点，但是如果它有numpy调用，我认为我们不能将很多代码JIT：
> 
> ```python
> 进口 火炬
> 
> @火炬。准时。脚本
> def  test_method（）：
>      t  = 火炬。兰特（1，3，40）
>     吨 = 吨。numpy（） 
>      t  + =  1
>     返回 t
> ```
> 
> ```
> Traceback (most recent call last):
>   File "play.py", line 10, in <module>
>     def test_method():
>   File "/home/harry/miniconda3/envs/v2/lib/python3.8/site-packages/torch/jit/_script.py", line 939, in script
>     fn = torch._C._jit_script_compile(
> RuntimeError: 
> Tried to access nonexistent attribute or method 'numpy' of type 'Tensor'.:
>   File "play.py", line 12
> def test_method():
>     t = torch.rand(1,3,40)
>     t = t.numpy()
>         ~~~~~~~ <--- HERE
>     t += 1
>     return t
> ```
> 
> 另一个原因是torch.Tensor API与numpy几乎相同，因此考虑到我们必须使用torch.Tensor进行培训，我们还是可以一直坚持下去吗？

how to resolve this error  "RuntimeError: 
> Tried to access nonexistent attribute or method 'numpy' of type 'Tensor'.:
>"?      thank you!!
