### ISSUE TITLE
Consider Optuna for optimizing model architecture and training

### ISSUE THREAD

**Issue by mogwai** [pyannote/pyannote-audio#485]
<a href="https://github.com/hbredin"><img src="https://avatars2.githubusercontent.com/u/1080837?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hbredin](https://github.com/hbredin)**
_Wednesday Nov 04, 2020 at 06:38 GMT_
_Originally opened as https://github.com/hbredin/pyannote-audio-v2/issues/62_

----

https://github.com/optuna/optuna/blob/master/examples/pytorch_lightning_simple.py

**Comment by mogwai** [comment]
<a href="https://github.com/mogwai"><img src="https://avatars1.githubusercontent.com/u/5440566?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mogwai](https://github.com/mogwai)**
_Wednesday Nov 04, 2020 at 13:15 GMT_

----

https://docs.ray.io/en/master/tune/tutorials/tune-pytorch-lightning.html

**Comment by hbredin** [comment]
Closed by #512
