### ISSUE TITLE
chore: Remove large binary files from the git history

### ISSUE THREAD

**Issue by mogwai** [pyannote/pyannote-audio#487]
Currently there are several large binary files in the repository that cause it to take a fair time to clone. This can been seen by running the following command which lists all tracked files in the entire repository:

```
git rev-list --objects --all \
| git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
| awk '/^blob/ {print substr($0,6)}' \
| sort --numeric-sort --key=2 \
| cut --complement --characters=13-40 \
| numfmt --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
```

It would be good to clean them out and host models trained with the new version somewhere else.

**Comment by mogwai** [comment]
This will need a force push to the repository and will re-write the tags as well. 

This script takes some time to run. 

We should create a test repository for this first to see the results ?

```
#!/bin/bash

set -e 
readarray -t res <<< $(git rev-list --objects --all | git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' | awk '/^blob/ {print substr($0,6)}' | sort --numeric-sort --key=2 | cut --complement --characters=13-40 | numfmt --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest | tac | awk '{print $3}' | egrep '*.(wav|pt)$') 

remove_file() {
    git filter-branch --force --index-filter \
      'git rm --cached --ignore-unmatch '$1 \
      --prune-empty --tag-name-filter cat -- --all
}
for i in "${res[@]}"; do
    echo Removing $i
    remove_file $i
done
```

**Comment by hbredin** [comment]
This should be on hold until PR #491 is merged and tests are updated to use the new Debug DownloadableProtocol.
