### ISSUE TITLE
torch.hub.load('pyannote/pyannote-audio', 'dia') failed

### ISSUE THREAD

**Issue by bitcarousel** [pyannote/pyannote-audio#495]
**The bug**
Went through the tutorial introduction_to_pyannote_audio_speaker_diarization_toolkit juypter notebook. 
Worked like charm until the diarization command:
pipeline = torch.hub.load('pyannote/pyannote-audio', 'dia') failed with: 

ImportError: cannot import name 'Pretrained' from 'pyannote.audio.features' (/usr/local/Caskroom/miniconda/base/envs/Pyannote/lib/python3.8/site-packages/pyannote/audio/features/__init__.py)

It tries to use:
Using cache found in /Users/abc/.cache/torch/hub/pyannote_pyannote-audio_master

Any idea?

**To Reproduce**
```bash
import torch
pipeline = torch.hub.load('pyannote/pyannote-audio', 'dia')
diarization = pipeline(DEMO_FILE)
```

**pyannote environment**

```bash
$ pip freeze | grep pyannote
pyannote.audio==1.1
pyannote.core==4.1
pyannote.database==4.0.2
pyannote.metrics==3.0.1
pyannote.pipeline==1.5.2
```

**Comment by hbredin** [comment]
Can you start fresh 
* using the notebook on the master branch 
* using pyannote.audio 1.1 (released yesterday)
* with an empty ~/.cache/torch/hub directory

Because of yesterday's release, it might have broken things.

**Comment by bitcarousel** [comment]
Thanks it works now
