### ISSUE TITLE
Store pretrained models

### ISSUE THREAD

**Issue by mogwai** [pyannote/pyannote-audio#513]
Look into something similar to what asteroid are doing: 

https://github.com/mpariente/asteroid/blob/master/docs/source/readmes/pretrained_models.md

https://zenodo.org/communities/asteroid-models?page=1&size=20

**Comment by hbredin** [comment]
https://zenodo.org/communities/pyannote-audio

**Comment by hbredin** [comment]
Pretrained models can now be stored on hugginface model hub in v2.
Example: https://huggingface.co/hbredin/VoiceActivityDetection-PyanNet-DIHARD
