### ISSUE TITLE
Add support for autor_lr_find

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#514]
https://pytorch-lightning.readthedocs.io/en/latest/lr_finder.html

**Comment by hbredin** [comment]
Possibly found a bug in pytorch-lightning: https://pytorch-lightning.slack.com/archives/CQXV8BRH9/p1605557610495400

**Comment by hbredin** [comment]
https://colab.research.google.com/gist/hbredin/7a2defe2a2b8760fb903429113092951/the-boringmodel.ipynb

**Comment by hbredin** [comment]
A working version is available in `feature/cli` branch.

**Comment by mogwai** [comment]
This is merged into develop now?

**Comment by hbredin** [comment]
Yes but let's keep this open because the PL bug has not been fixed yet and I had to hack it to make it work.
