### ISSUE TITLE
"create_rng_for_worker" should depend on the "global_rank"

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#526]
`create_rng_for_worker` only depends on the worker id (and a global seed).

https://github.com/pyannote/pyannote-audio/blob/1eb9ac52cf871db151e0a00dd936f0c8fb1f964c/pyannote/audio/utils/random.py#L45-L48

However, the way distributed training with `ddp` accelerator is implemented in pytorch-lightning is that each GPU across each node gets its own process [(source)](https://pytorch-lightning.readthedocs.io/en/stable/multi_gpu.html#distributed-data-parallel).

It means that though workers 1 and 2 on GPU1 will generate different training samples, worker 1 on GPU1 will generate identical training samples to worker 1 on GPU2 -- hence removing all benefits from distributed multi-GPU training.

Solution: use [`global_rank`](https://pytorch-lightning.readthedocs.io/en/stable/lightning_module.html#global-rank) in combination with worker id to generate the seed.

**Comment by hbredin** [comment]
To backup my concerns, here is the training logs of two runs: one using two GPUs (the orange one), one use just one GPU (the blue one):

<img width="925" alt="image" src="https://user-images.githubusercontent.com/1080837/100238360-6a1aa980-2f30-11eb-8589-aa94a4466cd0.png">

The good thing is that I think we nailed reproducibility :-)

**Comment by hbredin** [comment]
Fixing this bug will not be enough as I just realized that `Task.train__iter__` is called at the beginning of each epoch. 

It means that the model sees the very same data at each epoch. 
This needs to be solved.

**Comment by mogwai** [comment]
That certainly isn't what we want!
