### ISSUE TITLE
what's the "architecture.yml" file of Pretrained ETAPE model?

### ISSUE THREAD

**Issue by NemoCpp** [pyannote/pyannote-audio#53]
Hi  Hervé BREDIN,
what's the "architecture.yml" file of Pretrained ETAPE model?
"A TristouNet model (trained and validated on ETAPE database) is available for you to test directly in tutorials/speaker-embedding/2+0.5/TristouNet."

in TristouNet folder, I only find "0986.h5", maybe that's the weight_h5, but where is the  architecture.yml?

**Comment by hbredin** [comment]
This `architecture.yml` no longer exists in `pyannote.audio`.

The network architecture is now described in the `config.yml` file:
https://github.com/pyannote/pyannote-audio/blob/e3d683b65a6ace52d9de1f5d027ec71d7e9a08e2/tutorials/speaker-embedding/2%2B0.5/TristouNet/config.yml#L1-L7

**Comment by NemoCpp** [comment]
i try to assign:
architecture_yml = '2+0.5/TristouNet/config.yml'
weight_h5 = '2+0.5/TristouNet/train/Etape.SpeakerDiarization.TV.train/weights/0986.h5'
embedding = SequenceEmbedding.from_disk(architecture_yml, weights_h5)

if give me:
ValueError: Improper config format: {'approach': {'name': 'TripletLoss', 'params': {'clamp': 'positive', 'metric': 'euclidean', 'margin': 0.1, 'per_batch': 1, 'per_label': 10, 'batch_size': 128, 'gradient_factor': 10000, 'per_fold': 20}}, 'architecture': {'name': 'TristouNet', 'params': {'mlp': [16, 16], 'rnn': 'LSTM', 'recurrent': [16], 'bidirectional': 'concat'}}}

did I use the wrong file or wrong method?

**Comment by hbredin** [comment]
Until the API is fully documented, I suggest you use the `pyannote-speaker-embedding apply` command line tool as described in the tutorial to extract the embeddings:
 https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/speaker-embedding#extraction

Obvisouly, this means that you first created the `pyannote.database` plugin for your own database.
Did you manage to do that?

**Comment by NemoCpp** [comment]
Yes, I will make my plugin later.
but now, I want to quickly do a test on a single wav file(not part of ETAPE),  just to get a knowledge of the module.

**Comment by NemoCpp** [comment]
thanks, I will try
