### ISSUE TITLE
Cannot change the size of training data in SAD

### ISSUE THREAD

**Issue by yining4869** [pyannote/pyannote-audio#544]
Hi, thanks for your amazing work on pyannote!
I found whatever the size of dataset I chose when I train a SAD model, the number of batches in one epoch pyannote used always be 675 when chunk_size=2s. And when I change the chunk_size, the number of batches in one epoch also changed accordingly. But the size of dataset didn't change the number of batches in one epoch. 
I searched the issues here but did not find any clues on how to fix this. Do you know how to solve this problem? 
Thanks!

**Comment by hbredin** [comment]
`per_epoch` hyper-parameter controls the duration of an epoch (in days of audio).
https://github.com/pyannote/pyannote-audio/blob/03ddaeea69d56527e7a69aa3b14d9b0584bab168/pyannote/audio/labeling/tasks/speech_activity_detection.py#L75-L77

Removing this hyper-parameter will result in an epoch equal to the total duration of your dataset.

**Comment by yining4869** [comment]
Oh, I see! Thanks so much!
