### ISSUE TITLE
Pretrained french models

### ISSUE THREAD

**Issue by Asanoci** [pyannote/pyannote-audio#552]
Hello,

First of all, thank you for your amazing library :)

I was wondering why pretrained models on french data are not avalaible ? I tried to use the models currently available on french data, but it did not work very well (if not at all), Is there a way to achieve Speaker diarization on french audios, with models currently uploaded ?

Thank you :)

**Comment by hbredin** [comment]
> First of all, thank you for your amazing library :)
Thanks for the kind words.
 
> I was wondering why pretrained models on french data are not avalaible ? 
Simply because nobody trained any. Feel free to contribute one!

**Comment by hbredin** [comment]
None that I am aware of, unfortunately.
