### ISSUE TITLE
ValueError: all input arrays must have the same shape

### ISSUE THREAD

**Issue by NemoCpp** [pyannote/pyannote-audio#56]
Hello,
I try to run pyannote on my dataset, and I got error in pack_ndarray function of "pyannote/generators/batch.py"

    def pack_ndarray(self, ndarrays):
        return np.stack(ndarrays)

I print shape of my ndarrays
(201, 35)
(201, 35)
(201, 35)
(201, 35)
(108, 35)
(201, 35)
(175, 35)
(157, 35)
(34, 35)
(51, 35)
...
the first dim is not the same, so what's my mistake?

**Comment by hbredin** [comment]
Can you please provide me with a standalone and minimalist script that I could run to reproduce the error?

**Comment by NemoCpp** [comment]
below is my code, ref from your script 

# for reproducibility
import numpy as np
np.random.seed(1337)


duration = 1
step = 2
min_duration = 0.1
nb_epoch = 1000
subset = 'train'
from pyannote.audio.optimizers import SSMORMS3
optimizer = SSMORMS3()
batch_size = 8192
parallel = 0


# environment
WAV_TEMPLATE = '/home/pyannote-test/tbdata/{uri}.wav'
LOG_DIR = '/home/log'


preprocessors = {'wav': WAV_TEMPLATE}
from pyannote.database import PPD
database = PPD(preprocessors=preprocessors)



# experimental protocol (ETAPE TV subset)
protocol = database.get_protocol('SpeakerDiarization', 'TalkBankPart')



# -- FEATURE EXTRACTION --
from pyannote.audio.features import YaafeMFCC
feature_extraction = YaafeMFCC(e=False, De=True, DDe=True, coefs=11, D=True, DD=True)

# -- ARCHITECTURE --
from pyannote.audio.embedding.models import TristouNet
architecture = TristouNet(
    rnn ='LSTM',
    recurrent= [16],
    mlp = [16, 16],
    bidirectional = 'concat',
    )

from pyannote.audio.embedding import LegacyTripletLoss
glue = LegacyTripletLoss(
    feature_extractor = feature_extraction,
    duration = duration,
    min_duration=min_duration,
    distance = 'sqeuclidean',
    margin = 0.2,
    per_label = 40,
    )


from pyannote.audio.embedding.base import SequenceEmbedding
embedding = SequenceEmbedding(glue=glue)

embedding.fit(
    design_embedding = architecture,
    protocol=protocol,
    epochs=nb_epoch,
    train=subset,
    optimizer=optimizer,
    batch_size=batch_size,
    log_dir=LOG_DIR,
    max_q_size=1 if parallel else 0
    )

**Comment by NemoCpp** [comment]
I found my mistake, it's about min_duration
