### ISSUE TITLE
Explicit display of validation process

### ISSUE THREAD

**Issue by aidosRepoint** [pyannote/pyannote-audio#563]
As far as I understand, the validation process has no explicit display (like a progress bar, tqdm).
When validating on a fairly big development set, the process takes quite a lot of time. It would be comfortable to see the progress.

PS: I mainly train speech activity detection models.

**Comment by hbredin** [comment]
This will be taken care of in upcoming`v2` -- (much faster) validation will happen during training (no separate call for validation).

**Comment by aidosRepoint** [comment]
> This will be taken care of in upcoming `v2` -- (much faster) validation will happen during training (no separate call for validation).

thanks a lot @hbredin ! Closing the issue
