### ISSUE TITLE
Accent / Language identification

### ISSUE THREAD

**Issue by madkote** [pyannote/pyannote-audio#565]
**Is your feature request related to a problem? Please describe.**
Determine / classify audio by accent, eg. en-US vs en-GB.

**Describe the solution you'd like**
* train model on data sets
  * en-US
  * en-GB
  * en-XX
* load model
* pass audio (wav) and receive label with confidence

**Describe alternatives you've considered**
By using MFCC and CNN

**Additional context**
The problem is similar to language identification

**Comment by hbredin** [comment]
This should be quite straightforward to implement in pyannote.audio (currently available in `develop` branch).

This is also a good candidate for writing a tutorial on how to come up with your own task.
Would you be interested in collaborating on this? I could definitely help you along the way...

**Comment by madkote** [comment]
Hi @hbredin , thank you for reply.

yes, the task should be straightforward within the project (I saw that pytorch is in use). I would not say, I am expert in that field, but with your supervision and support, I could do it.

I will check the difference between `master` and `develop` branch, to make a better picture for my self.

I think as a start, I will look up for some basic dataset and comeback to you with my questions in this thread.
