### ISSUE TITLE
Include breathing sounds in speech activity detection?

### ISSUE THREAD

**Issue by youssefavx** [pyannote/pyannote-audio#571]
Hey guys, this is an incredible library! Thank you so much for making it. 

I'm currently trying to extract the noise from audio files. I already have working code that uses the example you linked for speech activity detection. The way I do it is take the timestamps between speeches, and then take those no-speech audio segments and stitch them together. 

However, I end up with lots of successive breaths. Is it possible to include breathing sounds in the speech activity detection model or set some parameter to include those as I'd prefer noise without those breaths?

No worries if not, either way this library will save me a ton of time, so thank you again for your amazing work.

**Comment by hbredin** [comment]
There is no such thing as a breathing sounds detector in pyannote.audio for now.
You'd need to annotate those sounds manually on a bunch of files and train a dedicated model yourself.

One simple solution would be to only keep non-speech regions longer than a particular duration.
You'd probably miss some real noise but would probably get rid of most breathing sounds.

**Comment by youssefavx** [comment]
This was a brilliant idea, I implemented and it worked. What I did was sort by the longest segments between speech sounds, and then crossfade those bits together. This gives me only noise for the most part at the start.

A fun byproduct is it sounds like a bouncing ball but instead of the sound of impact, its breaths - near the very end.

**Comment by hbredin** [comment]
Would you mind sharing (i.e. uploading an audio sample) of this *fun byproduct*?
