### ISSUE TITLE
combining diarization with wav2lip demo and questions

### ISSUE THREAD

**Issue by eyaler** [pyannote/pyannote-audio#573]
Thanks for you work. I have integrated your speaker diarization models with wav2lip for automatic audio to animated skit creation, in this colab: [j.mp/wav2lip](j.mp/wav2lip). here are some funny results: [https://twitter.com/eyaler/status/1348769977663451136](https://twitter.com/eyaler/status/1348769977663451136). also i wanted to ask:
1. is it worth while to consider instead for the case of two speakers case - the speaker change model for better results or finer control?
2. should i expect better results with the upcoming 2.0?
3. is there a way to constrain the number of speakers when it is known?
4. is there a way to get confidences from the model?
5. where can i find more info on how the models resolves overlapping detections?
thanks!

**Comment by hbredin** [comment]
> Thanks for you work. I have integrated your speaker diarization models with wav2lip for automatic audio to animated skit creation, in this colab: [j.mp/wav2lip](j.mp/wav2lip). here are some funny results: https://twitter.com/eyaler/status/1348769977663451136. also i wanted to ask:

That is an interesting use case for speaker diarization, indeed. Thanks for sharing! 

>     1. is it worth while to consider instead for the case of two speakers case - the speaker change model for better results or finer control?

The speaker change model will probably not be very useful.
Knowing the number of speakers (especially when there are only two) can really help clustering. 
I'd recommend you try replacing the speaker embedding clustering part  of the diarization pipeline by something that can take the number of clusters as input (e.g. spectral clustering with K-means)

>     2. should i expect better results with the upcoming 2.0?

I can't tell for sure but I am currently working on new models (that will end up in 2.0) that should improve the segmentation part (e.g. in the linked twitter example above, it looks like speaker change precision could be improved by this new model).

>     3. is there a way to constrain the number of speakers when it is known?

Unfortunately, no. But, as stated in (1), if you try and replace the clustering part of the pipeline by spectral clustering with K-means, this could be done. 

>     4. is there a way to get confidences from the model?

You'd have to be more specific as to what you mean by "confidence" exactly.
One confidence number for the whole diarization? One that evolves over time? How would you use it?
 
>     5. where can i find more info on how the models resolves overlapping detections?

Here: https://arxiv.org/abs/1910.11646

(will convert this Github issue into a Github discussion [as soon as the feature is enabled again](https://github.com/github/feedback/discussions/2924#discussioncomment-254592)).

**Comment by eyaler** [comment]
thanks!

> You'd have to be more specific as to what you mean by "confidence" exactly.
> One confidence number for the whole diarization? One that evolves over time? How would you use it?
I would like to know per speaker segment or per switch event or per short time frame, so that i can play with some threshold if i see the results are switching too often or too seldom

**Comment by hbredin** [comment]
We might have something like that in 2.0. Cannot promise any ETA, though.
