### ISSUE TITLE
Missing hubconf.py in pyannote-audio_develop

### ISSUE THREAD

**Issue by bitcarousel** [pyannote/pyannote-audio#599]
Tried to fine-tune the sad_ami model with my own protocol.
Any idea why it failes with:
[Errno 2] No such file or directory: '/home/ec2-user/.cache/torch/hub/pyannote_pyannote-audio_develop/hubconf.py

________
[ec2-user@ip-10-255-255-134 pyannote-audio]$ pyannote-audio sad train --pretrained=sad_ami --subset=train --to=5 --parallel=4 ${EXP_DIR} ARM.SpeakerDiarization.ArchiMob

/usr/local/lib64/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Using cache found in /home/ec2-user/.cache/torch/hub/pyannote_pyannote-audio_develop
Could not load "0" model from torch.hub.The following exception was raised:

[Errno 2] No such file or directory: '/home/ec2-user/.cache/torch/hub/pyannote_pyannote-audio_develop/hubconf.py'
_________

There is really no hubconf.py file in this directory:

_________
[ec2-user@ip-10-255-255-134 pyannote_pyannote-audio_develop]$ ls -la
total 56
drwxrwxr-x. 8 ec2-user ec2-user 4096 Jan 27 21:53 .
drwxrwxr-x. 4 ec2-user ec2-user   83 Jan 27 21:53 ..
-rw-rw-r--. 1 ec2-user ec2-user  142 Jan 27 21:53 .gitattributes
drwxrwxr-x. 4 ec2-user ec2-user   64 Jan 27 21:53 .github
-rw-rw-r--. 1 ec2-user ec2-user  985 Jan 27 21:53 .gitignore
-rw-rw-r--. 1 ec2-user ec2-user  954 Jan 27 21:53 .pre-commit-config.yaml
-rw-rw-r--. 1 ec2-user ec2-user 1061 Jan 27 21:53 LICENSE
-rw-rw-r--. 1 ec2-user ec2-user  114 Jan 27 21:53 MANIFEST.in
-rw-rw-r--. 1 ec2-user ec2-user 4237 Jan 27 21:53 README.md
-rw-rw-r--. 1 ec2-user ec2-user   34 Jan 27 21:53 codecov.yml
drwxrwxr-x. 3 ec2-user ec2-user   63 Jan 27 21:53 doc
-rw-rw-r--. 1 ec2-user ec2-user  172 Jan 27 21:53 environment.yaml
drwxrwxr-x. 2 ec2-user ec2-user  117 Jan 27 21:53 notebook
drwxrwxr-x. 3 ec2-user ec2-user   38 Jan 27 21:53 pyannote
-rw-rw-r--. 1 ec2-user ec2-user  383 Jan 27 21:53 requirements.txt
-rw-rw-r--. 1 ec2-user ec2-user 3156 Jan 27 21:53 setup.cfg
-rw-rw-r--. 1 ec2-user ec2-user 1751 Jan 27 21:53 setup.py
drwxrwxr-x. 5 ec2-user ec2-user  172 Jan 27 21:53 tests
drwxrwxr-x. 2 ec2-user ec2-user   85 Jan 27 21:53 tutorials
-rw-rw-r--. 1 ec2-user ec2-user    6 Jan 27 21:53 version.txt_
____________
However the pyannote_pyannote-audio_master has a hubconf.py file. 
Can I somehow force pyannote-audio command to use the master?

**Comment by hbredin** [comment]
pyannote-audio CLI was incorrectly referring to `develop` branch. Fixed it in 36ddfe7.
Will make a new release soon -- in the meantime, you can re-install `pyannote.audio` from `master` branch.

**Comment by hbredin** [comment]
1.1.2 has been released: `pip install pyannote.audio==1.1.2`

**Comment by eyaler** [comment]
solution:
```
!pip install pyannote.core==4.1 pyannote.pipeline==1.5.2 pyannote.audio==1.1.1
!wget -nc https://raw.githubusercontent.com/pyannote/pyannote-audio/1.1.1/hubconf.py -P /root/.cache/torch/hub/pyannote_pyannote-audio_main
!wget -nc https://raw.githubusercontent.com/pyannote/pyannote-audio/1.1.1/hubconf.py -P /root/.cache/torch/hub/pyannote_pyannote-audio-hub_master
import torch
import pyannote.core #https://github.com/pyannote/pyannote-audio/issues/561
pipeline = torch.hub.load('pyannote/pyannote-audio', 'dia', trust_repo=True)
```
