### ISSUE TITLE
Parameter choosing and uem 

### ISSUE THREAD

**Issue by talal-sen** [pyannote/pyannote-audio#600]
I have a few key questions 

1. When preparing the uem and rttm files, does speaker A in recording 1 is considered the same as speaker A in recording 2?
2. For training the EMB models, the config files specifies: per_fold, per_label,per_epoch. How do i define these parameters for my own training data?

# we use additive angular margin loss
task:
   name: AdditiveAngularMarginLoss
   params:
      margin: 0.05
      s: 10
      duration: 2.0   # train on 2s audio chunks
      per_fold: 256   # number of speakers per batch
      per_label: 1    # number of sample per speaker
      per_epoch: 5    # one epoch = 5 days worth of audio

**Comment by hbredin** [comment]
> I have a few key questions
> 
>     1. When preparing the uem and rttm files, does speaker A in recording 1 is considered the same as speaker A in recording 2?

For training speaker embedding, yes: speaker labels must be global to the corpus.
For training segmentation tasks (e.g. voice activity detection or overlapped speech detection), no: speaker labes can be local to each file.

>     2. For training the EMB models, the config files specifies: per_fold, per_label,per_epoch. How do i define these parameters for my own training data?

See documentation here:
https://github.com/pyannote/pyannote-audio/blob/aa692f587c92962f70a2c4ef0764820102e2057e/pyannote/audio/embedding/approaches/arcface_loss.py#L120-L126

**Comment by talal-sen** [comment]
Thanks @hbredin for your kind response. 

Just elaborating more on point 2, how do I know Number of sequences per speaker in each batch as each batch would be sampling the training dat randomly I believe. In my case I have long wav files with speakers taking turns, thus one wav file will contain many utterances by multiple speakers. Similarly for number of different speakers per batch?

**Comment by hbredin** [comment]
Just set `per_label` to 1 and increase `per_fold` until batches no longer fit in memory..
