### ISSUE TITLE
I can't visualize diarization output on my linux server

### ISSUE THREAD

**Issue by wenyuqing** [pyannote/pyannote-audio#601]
Hello,I am using the follow code to test the installation of pyannote.
I run them on my remote linux server.

`DEMO_FILE = {'uri': 'ES2004a.Mix-Headset', 'audio': 'ES2004a.Mix-Headset.wav'}
from pyannote.database.util import load_rttm
groundtruth = load_rttm('test_pyannote/MixHeadset.test.rttm')[DEMO_FILE['uri']]
groundtruth
from pyannote.core import Segment, notebook
EXCERPT = Segment(600, 660)
notebook.crop = EXCERPT
groundtruth`

But there is no visualization resulst or errors coming out .

**Comment by hbredin** [comment]
Are you running this code in a notebook? Visualization only works in notebooks.
