### ISSUE TITLE
Consider using nemo speaker embeddings

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#608]
https://ngc.nvidia.com/catalog/models/nvidia:nemospeechmodels

**Comment by Shellcat-Zero** [comment]
@hbredin Do you happen to know what the best embeddings are for diarization currently? Strictly based on the tutorials, I've found Speechbrain to be more accurate than Nemo, even though Speechbrain takes much longer than Nemo to compute, but I have not seen any comparative analysis for this. I was just wondering if the lower accuracy was the reason that [Nemo embeddings](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/asr/speaker_diarization/results.html#models-for-speaker-diarization) were never adopted here. I cannot find the model specifications (details of training datasets, model size, etc) for the Speechbrain embedding(s) used here by pyannote.audio for comparison to those Nemo embeddings.

**Comment by hbredin** [comment]
I am not aware of any study/benchmark that focuses on this particular aspect.
