### ISSUE TITLE
Speaker Embedding Clustering for Single File

### ISSUE THREAD

**Issue by bitcarousel** [pyannote/pyannote-audio#614]
I am trying to cluster the speaker embeddings for a single file.  
Is it also possible not to create a new experimental protocol every time for testing a new single file? tSNE visualization requires "annotation" from the the protocol. 

X, Y = [], []
for segment in long_turns:
    # "strict" only keeps embedding strictly included in segment
    x = embeddings.crop(segment, mode='strict')
    # average speech turn embedding
    X.append(np.mean(x, axis=0))

    # keep track of speaker label (for later scatter plot)
    **y = test_file['annotation'].argmax(segment)**
    Y.append(y)

X = np.vstack(X)
_, y_true = np.unique(Y, return_inverse=True)

My finetuned model fails also by the tSNE visualisation step with error: 
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

**Comment by bitcarousel** [comment]
Command:

# apply tSNE on embeddings
from sklearn.manifold import TSNE
tsne = TSNE(n_components=2, metric="cosine")
X_2d = tsne.fit_transform(X)

# plot 
fig, ax = plt.subplots()
fig.set_figheight(5)
fig.set_figwidth(5)
plt.scatter(*X_2d.T, c=y_true)

Fails with:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-9de3370346fa> in <module>()
      2 from sklearn.manifold import TSNE
      3 tsne = TSNE(n_components=2, metric="cosine")
----> 4 X_2d = tsne.fit_transform(X)
      5 
      6 # plot

/usr/local/lib64/python3.6/site-packages/sklearn/manifold/_t_sne.py in fit_transform(self, X, y)
    930             Embedding of the training data in low-dimensional space.
    931         """
--> 932         embedding = self._fit(X)
    933         self.embedding_ = embedding
    934         return self.embedding_

/usr/local/lib64/python3.6/site-packages/sklearn/manifold/_t_sne.py in _fit(self, X, skip_num_points)
    702             X = self._validate_data(X, accept_sparse=['csr'],
    703                                     ensure_min_samples=2,
--> 704                                     dtype=[np.float32, np.float64])
    705         else:
    706             X = self._validate_data(X, accept_sparse=['csr', 'csc', 'coo'],

/usr/local/lib64/python3.6/site-packages/sklearn/base.py in _validate_data(self, X, y, reset, validate_separately, **check_params)
    419             out = X
    420         elif isinstance(y, str) and y == 'no_validation':
--> 421             X = check_array(X, **check_params)
    422             out = X
    423         else:

/usr/local/lib64/python3.6/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     61             extra_args = len(args) - len(all_args)
     62             if extra_args <= 0:
---> 63                 return f(*args, **kwargs)
     64 
     65             # extra_args > 0

/usr/local/lib64/python3.6/site-packages/sklearn/utils/validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    662         if force_all_finite:
    663             _assert_all_finite(array,
--> 664                                allow_nan=force_all_finite == 'allow-nan')
    665 
    666     if ensure_min_samples > 0:

/usr/local/lib64/python3.6/site-packages/sklearn/utils/validation.py in _assert_all_finite(X, allow_nan, msg_dtype)
    104                     msg_err.format
    105                     (type_err,
--> 106                      msg_dtype if msg_dtype is not None else X.dtype)
    107             )
    108     # for object dtype data, we only check for NaNs (GH-13254)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

Any Idea why?

**Comment by jnaranjo-sciling** [comment]
Can you provide the full pipeline from reading the audio file?

**Comment by Vitthal98** [comment]
I'm encountering the same error when following the documentation for extracting speaker embeddings and plotting t-SNE given by pyannote-audio [here](https://github.com/pyannote/pyannote-audio/tree/master/tutorials/pretrained/model) .
Has anybody managed to figure out how to solve the warnings and error message?

**Comment by QuchenFu** [comment]
Same here

**Comment by sanbaideng** [comment]
I got an error:

Exception has occurred: KeyError
'annotation'
  File "E:\pyannote-audio-demo\demo\embidding.py", line 61, in <module>
    y = test_file['annotation'].argmax(segment)

in line :

 y = test_file['annotation'].argmax(segment),

--------
test_file = {'uri': 'muyu.wav', 'audio': 'E:\\pyannote-audio-demo\\demo\\rmdmy.wav'}

test_file has no key 'annotation' i think,
is this a bug?
