### ISSUE TITLE
Overlapping speech detection

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#62]
- [ ] https://github.com/idnavid/pyknograms
- [ ] https://github.com/idnavid/dissertation/blob/master/SHOKOUHI-DISSERTATION-2017-rev3.pdf
- [ ] [LEVERAGING LSTM MODELS FOR OVERLAP DETECTION IN MULTI-PARTY MEETINGS](http://www.leap.ee.iisc.ac.in/sriram/publications/papers/leveraging-lstm-models.pdf)

**Comment by hbredin** [comment]
In latest version of pyannote.audio (v1.0), `pyannote.audio.labeling.tasks.SpeechActivityDetection` has a `overlap` boolean parameter that can be used to train SAD with 3 classes (non-speech vs. one speaker vs. 2+ speakers) instead of 2 (non-speech vs. speech).

**Comment by claudiv** [comment]
Hi there! Thank you for opensourcing this project 👍 . 

I want to detect overlapping speech regions using pyAnnote.Audio version 1.0.1.
I trained a model with speech activity detection and enabled overlap detection (as you proposed in the previous comment). Then I applied the model to AMI corpus. 
Now it's unclear to me how/where I can see the detected overlapping speech regions. 
When I load my precomputed SAD-scores, I would normally binarize these SAD-scores to obtain speech regions, but where can I see regions with amount of detected speakers > 1 ?

Best wishes

**Comment by hbredin** [comment]
With `overlap=True`, SAD scores are now 3-dimensional:
* 1st dimension is for non-speech
* 2nd dimension is for exactly one speaker
* 3rd dimension is for 2 or more speakers

Therefore, you should binarize the 3rd dimension, ie use `dimension=2` in 
https://github.com/pyannote/pyannote-audio/blob/b678920057ace936c8900c62d2975e958903fae2/pyannote/audio/signal.py#L161

FYI, I never really used this overlap detection so I'd be curious to receive some feedback on how well it performs...

**Comment by chitwansaharia** [comment]
Hi,

I am also working on the problem of overlap detection for AMI. For training, I followed your tutorial, just adding overlap: True parameter to `config.yml`, and I got a training loss curve like this (comparison b/w overlap and non-overlap)
<img width="438" alt="screenshot 2019-01-23 at 1 09 01 pm" src="https://user-images.githubusercontent.com/16670698/51590485-1728d300-1f10-11e9-9efe-536ebb922114.png">
However, I am not sure how to evaluate this model using `pyannote-metrics` after binarizing the 3rd dimension.

**Comment by hbredin** [comment]
You can take inspiration for `pyannote-overlap-detection` [validation code](https://github.com/pyannote/pyannote-audio/blob/master/pyannote/audio/applications/overlap_detection.py#L98-L188) or use the script directly
```bash
$ pyannote-overlap-detection --help
```

It will compute recall at fixed precision.

**Comment by chitwansaharia** [comment]
Thanks a lot!

**Comment by hbredin** [comment]
Closing this stalled issue. Please re-open if needed.

See https://arxiv.org/abs/1910.11646 for more up-to-date overlapped speech detection results (obtained with pyannote.audio).
