### ISSUE TITLE
hi, if wav file name is like '1505728826.11848331.wav', it will throw "ValueError: Could not find file "1505728826.1184833""

### ISSUE THREAD

**Issue by NemoCpp** [pyannote/pyannote-audio#63]
may be it's because pandas 
 pyannote/parser/timeline/base.py, line 54-67
          df = pandas.read_table(path,
                               delim_whitespace=True,
                               header=None, names=self.fields(),
                               comment=self.comment(),
                               converters=self.converters(),
                               keep_default_na=False, na_values=[],
                               )
           could be fix if add dtype={'uri': object}

**Comment by hbredin** [comment]
Seems to be a [`pyannote.parser`](https://github.com/pyannote/pyannote-parser) bug, not `pyannote.audio`.

Would you mind opening an issue there?
I'd also happily merge a pull request fixing this issue...

**Comment by hbredin** [comment]
Fixed: https://github.com/pyannote/pyannote-parser/issues/2
