### ISSUE TITLE
use GPU for process the audio instead of CPU

### ISSUE THREAD

**Issue by RG7279805** [pyannote/pyannote-audio#649]
hii i want to diarize audios but I am not able do that with GPU. someone suggested to use --gpu flag but how do I do that in python i am using this script 

def diarize(self):
        pipeline = torch.hub.load(' /pyannote-audio', 'dia')

        # apply diarization pipeline on your audio file
        diarization = pipeline({'audio': self.audioPath })

        # dump result to disk using RTTM format
        with open('audio.rttm', 'w') as f:
            diarization.write_rttm(f)
        
        # iterate over speech turns
        jsonFile = open('dia.json','w+')
        for turn, _, speaker in diarization.itertracks(yield_label=True):
            print(f'Speaker "{speaker}" speaks between t={turn.start:.1f}s and t={turn.end:.1f}s.')

thanks in advance

**Comment by hadware** [comment]
Hey,

if i'm not mistaken, the diarization pipeline should load itself on the GPU by default (if it is available).

**Comment by RG7279805** [comment]
Does it work on and cards too?

**Comment by hbredin** [comment]
`pyannote.audio` is based on `PyTorch`. If `PyTorch` supports AMD (does it?), then `pyannote.audio` supports AMD.

**Comment by Akshat4112** [comment]
Any help on how to use --gpu would be appreciated?
