### ISSUE TITLE
The output of the pretrained model

### ISSUE THREAD

**Issue by wenyuqing** [pyannote/pyannote-audio#650]
Thanks for your code.
I use your pretrained diarization model on my own .wav file and the output looks like this.
![image](https://user-images.githubusercontent.com/48059861/111962856-d186e580-8b2d-11eb-80c0-7bd9f4386d5a.png)
Could you tell me the meaning of the numbers such as 2049,2073 and the letters such as GY,NL..

**Comment by hbredin** [comment]
The pretrained pipeline returns a pyannote.core.Annotation instance.
See https://pyannote.github.io/pyannote-core/structure.html#annotation for more details.
