### ISSUE TITLE
Performing Speaker Verification

### ISSUE THREAD

**Issue by ajay960singh** [pyannote/pyannote-audio#651]
How can I perform Speaker Verification with Pyannote?

I've an audio segment of the user and I want to compare new instances to this segment to verify the user.

**Comment by hadware** [comment]
If i'm not mistaken, there isn't any Speaker Verification pipeline in pyannote. 

However, it's pretty easy to build one yourself using the speaker embedding pre-trained pipelines. Here's an older issues that might be relevant for your problem: #391

**Comment by hbredin** [comment]
Also relevant: https://huggingface.co/hbredin/SpeakerEmbedding-XVectorMFCC-VoxCeleb

**Comment by ajay960singh** [comment]
@hbredin This is giving us reasonable accuracy. Seems like pyannote.audio 2.0 is still in development. When do you expect it to go into production?

**Comment by hbredin** [comment]
`pyannote.audio` is a research project, developed by academic researchers like me. 
Therefore, it will most likely never be production-ready.

Feel free to drop me an email to discuss potential collaborations with your company (e.g. through sponsoring of a software engineer working on making `pyannote.audio` closer to what you call _production_).

Closing as the original question has been answered.
