### ISSUE TITLE
cache_dir for pretrained huggingface model

### ISSUE THREAD

**Issue by loretoparisi** [pyannote/pyannote-audio#658]
Hello, I was trying to new pretrained model from Huggingface hub,  installing the `develop` branch
```
pip install https://github.com/pyannote/pyannote-audio/archive/develop.zip
```

and the example [here](https://huggingface.co/pyannote/segmentation) 

```python
from pyannote.audio import Inference
inference = Inference("pyannote/segmentation")
segmentation = inference("audio.wav")
# `segmentation` is a pyannote.core.SlidingWindowFeature
# instance containing raw segmentation scores like the 
# one pictured above (output)

from pyannote.audio.pipelines import Segmentation
pipeline = Segmentation(segmentation="pyannote/segmentation")
HYPER_PARAMETERS = {
  # onset/offset activation thresholds
  "onset": 0.5, "offset": 0.5,
  # remove speaker turn shorter than that many seconds.
  "min_duration_on": 0.0,
  # fill within speaker pauses shorter than that many seconds.
  "min_duration_off": 0.0
}

pipeline.instantiate(HYPER_PARAMETERS)
segmentation = pipeline("audio.wav")
```

I would like to have a way to specify pretrained model `cache_dir` as it works for all huggingface models like:

```python
tokenizer = Wav2Vec2Tokenizer.from_pretrained(
    "facebook/wav2vec2-base-960h", cache_dir=os.getenv("cache_dir", "../../models"))
model = Wav2Vec2ForCTC.from_pretrained(
    "facebook/wav2vec2-base-960h", cache_dir=os.getenv("cache_dir", "../../models"))
```

in order to have control where files are downloaded. Is this possibile for this develop branch release?

**Comment by hbredin** [comment]
`PYANNOTE_CACHE` environment variable can be used to control where models are cached:
https://github.com/pyannote/pyannote-audio/blob/3c4d0a68a39893ba5a0a4fc3c40e74aaeb92f7de/pyannote/audio/core/model.py#L46-L49

That being said, I'd happily merge a PR that adds a `cache_dir` option to `pyannote.audio.core.model.Model.from_pretrained` and `pyannote.audio.core.pipeline.Pipeline.from_pretrained`:

https://github.com/pyannote/pyannote-audio/blob/3c4d0a68a39893ba5a0a4fc3c40e74aaeb92f7de/pyannote/audio/core/model.py#L799-L804

**Comment by loretoparisi** [comment]
@hbredin testing and then opening the PR thanks!

**Comment by loretoparisi** [comment]
@hbredin so I did those changes, nothing breaks. But I have a clue when calling a `Pipeline` or `Inference` like:

```python
inference = Inference("pyannote/segmentation")
pipeline = Segmentation(segmentation="pyannote/segmentation")
pipeline.instantiate(HYPER_PARAMETERS)
pipeline = VoiceActivityDetection(segmentation="pyannote/segmentation")
pipeline.instantiate(HYPER_PARAMETERS)
vad = pipeline(audio_ds[0])
```

etc. how to pass the cache_dir, I assume I should change the class `Inference` as well to add a `cache_dir` param to pass to the `from_pretrained`? If so I will do, thanks.

**Comment by hbredin** [comment]
I'd rather not add another parameter to pipelines and `Inference`.
Both can be passed `Model` instances directly, so you could do something like that instead:

```python
model = Model.from_pretrained("pyannote/segmentation", cache_dir=...)
inference = Inference(model)
pipeline = Segmentation(segmentation=model)
```

**Comment by loretoparisi** [comment]
Thank you I have tested it [here](https://github.com/loretoparisi/hf-experiments/blob/master/src/audioseg/run.py) 
and it works perfectly. PR sent!
