### ISSUE TITLE
speaker embedding with KeyError: 'duration'

### ISSUE THREAD

**Issue by oucxlw** [pyannote/pyannote-audio#661]
import torch
model = torch.hub.load('pyannote/pyannote-audio', 'emb')
import numpy as np
from pyannote.core import Segment
excerpt1 = Segment(start=11.5, end=13)
emb1 = model.crop({'audio': './wbh_share/xlw_wyx_qc_0415_L_jie58s.wav'},expert1)
assert isinstance(emb1, np.ndarray)

 File "/home/.cache/torch/hub/pyannote_pyannote-audio_master/pyannote/audio/features/base.py", line 202, in crop
    min(current_file["duration"], segment.end + context),
# KeyError: 'duration'

**Comment by Shridharpawar77** [comment]
hi @oucxlw, did you find Any solution?
