### ISSUE TITLE
Diarization Error Rate

### ISSUE THREAD

**Issue by MariaMegalli** [pyannote/pyannote-audio#664]
I understand how the DER is calculated, but I want to know the percentage DER of the whole model? and is there is a way to improve the DER ?
According the pretrained model on the colab the result is DER of the demo file is 42.9% (which is high)
and when i tried my own file, it give me DER = 103.2% , why the rate is so high even i tracked the file by myself and found out it was correct through the speaker diarization detection 
Thanks

**Comment by hbredin** [comment]
For questions regarding the computation of DER metric, please open an issue on [pyannote.metrics](https://github.com/pyannote/pyannote-metrics) repository.

For questions regarding pyannote.audio, please make it clear what you are trying to achieve.
What do you mean by *"percentage DER of the whole model"*?

**Comment by Wulin824** [comment]
+1

**Comment by hbredin** [comment]
1. You can read about the evaluation of speaker diarization papers in [my paper](https://www.isca-speech.org/archive/Interspeech_2017/pdfs/0411.PDF) introducing [pyannote.metrics](http://pyannote.github.io/pyannote-metrics/).
2. You would have to share more details (i.e. the piece of code that you are actually running).  How can you compute a performance metric if you do not have a manual reference (a.k.a groundtruth) to compare to?

**Comment by MariaMegalli** [comment]
@hbredin 
I found what I need in the paper.
Thank you so much for your help.
