### ISSUE TITLE
Universal Unique Id

### ISSUE THREAD

**Issue by karimfayed** [pyannote/pyannote-audio#669]
I would like ask if is it possible give a person a universal unique id that would be used by the model to identify him in different audio files. for ex:
There are 3 people that are talking in 2 different files.
_Person1 speaks first in the first file but speaks last in the second file._
**_Can I have him be person1 in both files or is it not possible?_**

**Comment by hbredin** [comment]
What you are looking for is speaker verification or speaker tracking: this is feasible in pyannote.audio but does not come out of the box. See #651 and #391 for related issues.
