### ISSUE TITLE
Live Stream audio

### ISSUE THREAD

**Issue by MartinEmilEshack** [pyannote/pyannote-audio#670]
My input audio will be recorded and might reach an hour or two of length. I'm also planning to host the model on a remote host. Uploading and processing an audio file that big will take so much time.

Is it possible to give the model a live stream audio? or maybe keep the same person-id for different small files?

If not I have a question
What is the largest length of audio file with maximum number of persons that the model can process without loosing accuracy?

**Comment by hbredin** [comment]
> Is it possible to give the model a live stream audio? or maybe keep the same person-id for different small files?

Online speaker diarization is something that is not currently supported in pyannote.audio.
Regarding speaker tracking, it is feasible with pyannote.audio but not available out of the box. 
See related issues #391 and #651.
