### ISSUE TITLE
SAD for validate

### ISSUE THREAD

**Issue by Wulin824** [pyannote/pyannote-audio#677]
I can train SAD normally, but when I want to validate, the code stops running，as shown in the following figure, stay in the load dev dataset. Is it because batchsize(64) is too big, or is there insufficient running memory?
![1](https://user-images.githubusercontent.com/56509789/120962678-c76e9d80-c792-11eb-8a2e-786b87899d61.png)

**Comment by Gabrielk99** [comment]
Hello, what is the solution? i have the same problem, i have just wait?
