### ISSUE TITLE
the time of train, validate and test

### ISSUE THREAD

**Issue by Wulin824** [pyannote/pyannote-audio#678]
When training models separately, both training and testing can be performed quickly, but validate is really slow. Why? Is it the reason for not adding parallel operation? Please explain the difference between them, thank you!
![微信图片_20210607190520](https://user-images.githubusercontent.com/56509789/121006326-5c898a80-c7c3-11eb-9888-0211e99f3711.png)

**Comment by Grolaf** [comment]
Hello, 

It is not an answer, but an issue on training duration.

When I perform training on AMI dataset (prepared with the tutorial), I can see that the duration will take YEARS to achieve :
As you can see below, the first epoch taken about two hours.
```
$ pyannote-audio scd train --subset=train --to=1000 --parallel=4 ${EXP_DIR} AMI.SpeakerDiarization.MixHeadset

Loading labels: 0file [00:00, ?file/s]/home/antoine/.local/lib/python3.7/site-packages/pyannote/database/protocol/protocol.py:128: UserWarning: Existing precomputed key "annotated" has been modified by a preprocessor.
  warnings.warn(msg.format(key=key))
Loading labels: 118file [00:05, 23.20file/s]

Training:   0%|                     | 2/1000 [1:24:23<701:49:26, 2531.63s/epoch]
Epoch #2:   6%|▉              | 40/675 [04:44<1:14:52,  7.08s/batch, loss=0.148]

```

What did I do wrong here ?
If some information are missing, please feel free to tell me what.

Thanks !
