### ISSUE TITLE
Missing `hbredin/VoiceActivityDetection-PyanNet-DIHARD` in Huggingface model hub

### ISSUE THREAD

**Issue by jonaskratochvil** [pyannote/pyannote-audio#679]
Hello, I have been successfully using the VAD checkpoint `hbredin/VoiceActivityDetection-PyanNet-DIHARD` from Huggingface model hub, but it has been removed from there recently. Is there any chance of uploading this checkpoint again?

Thank you,

Jonas

**Comment by hbredin** [comment]
It's back up.

Would you mind sharing what you used that model for?

**Comment by jonaskratochvil** [comment]
Thank you, that was fast. 
I am using the model as a preprocessing step for wav2vec asr. In my use-case I deal with long audios so splitting it into small VAD pieces makes it easier to process in parallel. Moreover, when I do audio normalization per VAD chunk rather than for the whole audio I get quite substantial wer decrease. The `hbredin/VoiceActivityDetection-PyanNet-DIHARD` works very well for my use-case thank you for making available.

**Comment by hbredin** [comment]
Closing.

A better model is now available in upcoming pyannote.audio 2.0: [`pyannote/segmentation`](https://hf.co/pyannote/segmentation)

`hbredin/VoiceActivityDetection-PyanNet-DIHARD` will no longer be supported and I might remove it later without notice.

**Comment by manish-kumar-iisc** [comment]
@jonaskratochvil  
how are you doing "audio normalization per VAD chunk"
@hbredin do you have idea, what he is pointing to?
