### ISSUE TITLE
Loading labels takes a long time

### ISSUE THREAD

**Issue by lfgogogo** [pyannote/pyannote-audio#690]
I'm training the speech_activity_detection model,at first ,loading labels works well,but it become slow later,so i stop the command line: pyannote-audio sad train --subset=train --to=80 --parallel=2 ${EXP_DIR} AMI.SpeakerDiarization.MixHeadset.
Then i restart it,loading labels still takes a long time,about 500s a file!The data i use to train model consists of 5000 audios,so i can't wait that long.
I don't konw this happens due to memory bottleneck or something else,anyone knows please help,thank you a lot.

**Comment by lfgogogo** [comment]
And here are the versions：
![image](https://user-images.githubusercontent.com/42054022/123922884-0de2a100-d9bb-11eb-911d-a0a4a23f6412.png)

**Comment by Gabrielk99** [comment]
I have a problem like that, but in my case is in the process of validation after finetuning.
![image](https://user-images.githubusercontent.com/34044829/123957278-f89d5080-d981-11eb-889e-9fea0ffaacbc.png)

**Comment by Gabrielk99** [comment]
yet in the same problem.
