### ISSUE TITLE
Comparing Speaker Embeddings

### ISSUE THREAD

**Issue by MartinEmilEshack** [pyannote/pyannote-audio#697]
Hello,
I have asked before if pyannote-audio could perform live audio diarization or have consistent speaker IDs on multiple audio files,
#670 , and you responded that speaker tracking between multiple audio files is not available out of the box.

As a workaround,
First, we saved speakers embedding as a reference from a single speaker audio file.
Then, after performing diarization on small audio files and getting their segments of speakers, we extracted their embedding.
We used the [emb_ami](https://github.com/pyannote/pyannote-audio-hub#speaker-embedding) embedding model

We would like to compare the reference embedding with the segments embedding to later correct the IDs of the diarization output of the small audio files.
Then it would have consistent speaker IDs over multiple audio files.

How would we compare two embeddings and determine if they should be considered two different speakers or the same speaker?
We have used cdist but how would we judge the resulting distance?

**Comment by hbredin** [comment]
> How would we compare two embeddings and determine if they should be considered two different speakers or the same speaker?
> We have used cdist but how would we judge the resulting distance?

`cdist(..., metric="cosine")` is the way to go, indeed. 
Then, you'd have to annotate a few of your files to tune the actual threshold to apply -- no magic value will always work, it really depends on the data.

Please note that a [much better speaker embedding model](https://huggingface.co/pyannote/embedding) is available in upcoming pyannote.audio 2.0.
