### ISSUE TITLE
Speaker Diarization Timelines Difference on Windows and Linux

### ISSUE THREAD

**Issue by qasimali000** [pyannote/pyannote-audio#701]
Hi

I was working on Speaker Diarization using the Pre built Pipeline on custom audio files, initially I tested the Pyannote Speaker Diarization on my Windows machine and then I installed it on my Linux Ubuntu Machine where I'm getting some variation in the results, when I noticed the difference, I tested two audio files as a test case and figured that the timelines which were being generated were different on both machines for the same audio files. 

I wanted to ask, if there are some configuration parameters which are needed to be tuned in order to get it right in Pyannote, please let me know if that is the case. 

Also, I'm attaching the RTTM Files generated from Windows and Linux executions so you can have better clarity on the issue. To the extent of my analysis which I did, the results which are being generated from windows are much better and accurate as compared to those of Linux. As, it is clearly stated by the contributors of Pyannote that there is no support or guarantee for Windows platform, it is a bit odd for it to perform better on Windows and not on linux.

Looking forward to your response.

Thanks

[pyannote_test.zip](https://github.com/pyannote/pyannote-audio/files/6777032/pyannote_test.zip)

**Comment by hbredin** [comment]
I did a quick comparison of your two files

```python
from pyannote.database.util import load_rttm
_, windows = load_rttm('windows_results.rttm').popitem()
_, linux = load_rttm('linux_results.rttm').popitem()

from pyannote.metrics.diarization import DiarizationErrorRate
metric = DiarizationErrorRate()
metric(windows, linux, detailed=True)
# {'false alarm': 29.014999999999823,
#  'total': 305.23800000000017,
#  'correct': 298.36600000000044,
#  'confusion': 3.8459999999998864,
#  'missed detection': 3.025999999999833,
#  'diarization error rate': 0.11757055150407066}
```

They differ mostly in terms of false alarm: `linux` says speech, `windows` says non speech.

Probably a difference in the way audio is decoded between Linux and Windows.
This is most likely where the difference comes from.

But as you rightfully noted, pyannote is not meant to be used on Windows so I won't be able to provide more help regarding this issue. I'd be happy to receive any feedback once you found where the issue came from...

**Comment by qasimali000** [comment]
Thank You for your response. I'm still looking into the issue, will let you if I make any progress.

Thank You

**Comment by ShanuD11** [comment]
how did you perform inference on windows ? can you share the input? im facing the issue of runtime error and multi processing error? @qasimali000
