### ISSUE TITLE
Please check the issue, thanks for help.

### ISSUE THREAD

**Issue by Gabrielk99** [pyannote/pyannote-audio#703]
Hello, can you help?

1 - The process to validate a finetuned model is exactly equal the validate of training in the tutorial of train the model with my own dataset?
 
If the answer is yes, so ignore the second question.

2- Do you can introduce in the tutorial of finetuned how validate the model after finetuned process? Please, if possible, this would already help to clear certain doubts.

**Comment by hbredin** [comment]
1. Yes.
