### ISSUE TITLE
Data preparation for Pyannote.audio

### ISSUE THREAD

**Issue by AnishaKarthyedath** [pyannote/pyannote-audio#704]
I am started using pyannote.audio for speaker diarization. I have an issue with the dataset. I have my audio files in the .wav extension, also I have all the transcripts in the .cha extension. I would appreciate anyone could help me out to make .uae and .rttm file out of these audio files to proceed with my speaker diarization.

**Comment by Gabrielk99** [comment]
Hello, this is a simple task, all you need is creat a script that read your annotation for the files .wav, this mean, the labels for the dataset, and generate a file .rttm and .uem and .lst.

well, the file .rttm, is explained in tutorials in : https://github.com/pyannote/pyannote-audio/blob/master/tutorials/data_preparation
the .uem is like "name without extension" 1 start end, this mean the interval of annotation of your files.
and the .lst is the all file name. 

Read the .rttm, .uem, and .lst, that the owner left available for the better understanding

**Comment by AnishaKarthyedath** [comment]
Thank you for the quick response. I am able to create all the required file
