### ISSUE TITLE
Online Demo not work

### ISSUE THREAD

**Issue by yanhuibin315** [pyannote/pyannote-audio#709]
**Describe the bug**
I tried to connect streamlit to play pyannote-audio [demo](https://share.streamlit.io/pyannote/pyannote-audio-demo/main/app.py). But it showed me that  "This page does not exist or you do not have access."

**To Reproduce**
Just connect [demo](https://share.streamlit.io/pyannote/pyannote-audio-demo/main/app.py) in Chrome.

**Additional context**
Can somebody update that path or create a new page to test?

**Comment by hbredin** [comment]
Link is now fixed.

**Comment by hevinyu** [comment]
> Link is now fixed.

The demo link can't be opened again.

**Comment by hevinyu** [comment]
@hbredin 
The demo link can't be opened again.
