### ISSUE TITLE
Unsupervised segmentation

### ISSUE THREAD

**Issue by mibrahim210** [pyannote/pyannote-audio#71]
I have a one conversation with several people and it is unsupervised. I would only like to segment all the speakers in the conversation. In your speaker change detection code, i have given that that url(Local filepath) of the dataset. But after one interation I was getting an error which I believe due to the length of the dataset. Which part of the code I can use from this project.?

My final goal is to only segment unique speakers from the conversation. Any idea would be appreciated or any basic algorithmic steps which i can borrow from your code.

**Comment by hbredin** [comment]
Can you please provide me with the complete sequence of steps (alongside with the data you used) that leads to the error you mentioned?

**Comment by coder210** [comment]
I used the code from the change_detection folder. I am attaching the screenshots and I am adding the input file also. I changed the path of ETAPE databse.
<img width="645" alt="screen shot 2017-12-12 at 23 08 46" src="https://user-images.githubusercontent.com/2685377/33911329-4e55c752-df92-11e7-83e4-92fb588a344b.png">
<img width="633" alt="screen shot 2017-12-12 at 23 09 18" src="https://user-images.githubusercontent.com/2685377/33911330-4e81ad22-df92-11e7-8eff-5abaf2ca7d50.png">
<img width="835" alt="screen shot 2017-12-12 at 23 12 14" src="https://user-images.githubusercontent.com/2685377/33911332-4eade6a8-df92-11e7-9765-9dae8f570528.png">

**Comment by hbredin** [comment]
Sorry. Screenshots do not help.

What I need is a (as short as possible) documented Python script that leads to the error.
You can use gist.github.com to share this script, if it is easier.
