### ISSUE TITLE
Fine-tuning a pretrained model gives an [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by AnishaKarthyedath** [pyannote/pyannote-audio#711]
Fine-tuning the pre-trained model: speaker activity detection using my own data throws an error. 

I have used the following command to tune the model:

" pyannote-audio sad train --pretrained=sad_dihard --subset=train --to=5 --parallel=4 ${EXP_DIR} Seedlings.SpeakerDiarization.MixHeadset"

**Error:**.

Could not load "0" model from torch.hub. The following exception was raised:

[Errno 2] No such file or directory: '/Users/karthyedath.1/.cache/torch/hub/pyannote_pyannote-audio_develop/hubconf.py'. 

I tried to remove the cache using the command   " rm -r /Users/karthyedath.1/.cache/torch/hub"  However, which couldn't resolve the issue. Could anyone help me to resolve the issue?

**Comment by Gabrielk99** [comment]
Maybe if you download the file and put on directory can resolves.

**Comment by AnishaKarthyedath** [comment]
Sorry . I forgot to update the issue.  Copying the hubconf.py file into the directory solved the issue. Thank you Gabrielk99  for the response :)
