### ISSUE TITLE
What feature is used to trained models

### ISSUE THREAD

**Issue by Gabrielk99** [pyannote/pyannote-audio#716]
Hi, you can answer one question about the input of models?

I was see in paper that can be used the features provides for librosa or the method of extraction features from a SincModel, and i would like know, what method is used for standart.

**Comment by hbredin** [comment]
All pyannote.audio models work from the waveform directly.
Some of them compute MFCC internally, others rely on SincNet.

I recommend you have a look at the definition of each model directly in the code base.
For instance, PyanNet relies on SincNet: https://github.com/pyannote/pyannote-audio/blob/12c1574754165b0de447be6edcec90a70431da6d/pyannote/audio/models/segmentation/PyanNet.py#L166
