### ISSUE TITLE
How to remove hold music from a recorded .mp3/.wav file?

### ISSUE THREAD

**Issue by StanSilas** [pyannote/pyannote-audio#72]
Is it possible to use this library for detecting and removing "hold music" from a given audio file, so that all that remains is the actual conversation between the people.

**Comment by hbredin** [comment]
The short answer is "yes": this tool can be used to train (and then apply) a speech activity detector to detect only speech regions in an audio file.

The long answer is that it needs a bit of work. You have to:
- gather training data (i.e. audio files in which speech regions are manually annotated)
- format this training data into a [pyannote.database plugin](https://github.com/pyannote/pyannote-db-template)
- follow the [`pyannote-speech-detection` tutorial](https://github.com/pyannote/pyannote-audio/tree/master/tutorials/speech-activity-detection) to train you speech activity detector
- enjoy!

**Comment by SHREYAS290601** [comment]
If I want to detect this on a live call lets say there is an automated process to transcribe the speech that a speaker or voicemail says...and remove the part where the hold-on music is or any ring('phone ring') is it feasible?

**Comment by SHREYAS290601** [comment]
Also can you provide with an example of how the annotations should look like?
