### ISSUE TITLE
Speaker Change Detection

### ISSUE THREAD

**Issue by aiparikh** [pyannote/pyannote-audio#73]
Hi,

We are trying to use pyannote for Speaker Change Detection in supervised way.

We have created our own database. We are trying to follow tutorial instructions. But getting following error. We haven't modified the code.

We have attached the screenshot of the error and our newly created database.
![screenshot from 2017-12-21 13-24-13](https://user-images.githubusercontent.com/27027832/34245934-60890634-e652-11e7-9000-792dbb3b0c4b.png)

Could you please guide us in this?

Regards
Ankur
[pyannote-db-template-master.tar.gz](https://github.com/pyannote/pyannote-audio/files/1578353/pyannote-db-template-master.tar.gz)
![screenshot from 2017-12-21 13-24-13](https://user-images.githubusercontent.com/27027832/34245950-6feabfdc-e652-11e7-9625-c8eb5f69eb49.png)

**Comment by hbredin** [comment]
It might actually come from a wrong format in your `mdtm` file.
However, without the file `cd5ff082-855e-4451-b9f3-fed0dd390544`, it is difficult to judge.

`mdtm` files are supposed to store timestamps in seconds (not frame index).

```
cd5ff082-855e-4451-b9f3-fed0dd390544 1 20 1031 M S U S0
```
In `protocol1.train.mdtm`, the above line means that speaker `S0` speaks between time t=20s and t=1051s, is that what you had in mind?

**Comment by aiparikh** [comment]
You are absolutely correct. It was a mistake. We corrected it. Please find attached new database. 

Now, we are getting one more error. PFA screenshot here.

We can send the audio file on email as it's a private data. Can you please share your email id at ankur.parikh85@gmail.com? We will send you the file.

Thank you very much.

Regards
Ankur
[pyannote-db-template-master.tar.gz](https://github.com/pyannote/pyannote-audio/files/1579041/pyannote-db-template-master.tar.gz)
![screenshot from 2017-12-21 17-18-05](https://user-images.githubusercontent.com/27027832/34254636-f3ce7634-e672-11e7-8498-60c7f17165c2.png)

**Comment by hbredin** [comment]
Which version of pyannote.audio and pyannote.generators are you using?

```python
import pyannote.audio
print(pyannote.audio.__version__)
import pyannote.generators
print(pyannote.generators.__version__)
```

Try updating/downgrading `pyannote.generators`.

**Comment by aiparikh** [comment]
Thank you very much for the suggestion. It worked with 0.10 version of Pyannote.Generators and 0.2.1 version of Pyannote.Audio
