### ISSUE TITLE
Input to training SCD shoud be like output from VAD?

### ISSUE THREAD

**Issue by Gabrielk99** [pyannote/pyannote-audio#730]
Hello Everything is fine?

1 - A curious thing caught my attention, in my experiments, I noticed that for an audio where at a certain moment a speaker finished his speech and another one entered right after, without a silence step, the SCD model reached 100% accuracy.

2- This made me realize that the training I do disregards the output of the previous VAD model. After all I apply my raw entries. From what I've seen in the pipeline the SCD expects the output from the VAD, so training my data with raw input doesn't work very well, the input should it be like  the output from the VAD correct? However, I noticed that I haven't seen in the tutorials how this is done, or if it is done. What I did was label the audios again considering the silences as a new class, and the result of the SCD was infinitely better, of a straight line without any peaks, it was something full of peaks in the places it should have, with a certain error as they were trained up to 100 times.

3-Thus, I would like to know: The output of the VAD would be the audio without silence? Also, do you train the models in isolation without considering the previous outputs? as in the case of SCD and VAD, or is there a way to train the SCD using the output of the VAD?

**Comment by hbredin** [comment]
By default, SCD models are only trained to detect `speech from one speaker --> speech from another speaker` changes.
`non speech --> speech from one speaker` and `speech from one speaker --> non speech` are not marked as changes.

If you want to train the model to also detect thoses changes, you should use `non_speech = True`: 

https://github.com/pyannote/pyannote-audio/blob/a448164b4abe56a2c0da11e143648d4fed5967f8/pyannote/audio/labeling/tasks/speaker_change_detection.py#L87-L89

That being said, and as I alread told you in #706, I don't recommend using SCD model.
