### ISSUE TITLE
Speaker Change Detection

### ISSUE THREAD

**Issue by aiparikh** [pyannote/pyannote-audio#74]
Hi,

I have two doubts :
1. Is 'speech activity detection' prerequisite to 'speaker change detection'?

2. Another question is current approach in pyannote is speaker and content invariant?

3. In striking balance between purity and coverage, what should be the value of coverage that should be good enough practically?

Regards
Ankur

**Comment by hbredin** [comment]
1. No, both can be done independently from each other.
2. Yes, as long as your training data contains lots of different speakers.  
3. It depends on what you plan to do with the resulting speech turns. If you plan to apply hierarchical agglomerative clustering, you should prefer high purity (>90%).
