### ISSUE TITLE
Caching model output when optimizing pipelines

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#743]
It is not implemented yet but I agree that this is needed to speed up optimization. Anyway, the tutorial needs to be updated.

Instead of using the precomputed `scores` key, I think we should go with a caching mechanism implemented directly within the pipeline
* either by adding a key to `file` the first time the pipeline is applied to it (and read from it the next time) 
* or (better, I think) by defining a new method (e.g. `VoiceActivityDetection.get_raw_scores(file)` decorated by a caching decorator like [this one](https://docs.python.org/3/library/functools.html#functools.cache). 

Would you be willing to contribute this new feature?

_Originally posted by @hbredin in https://github.com/pyannote/pyannote-audio/discussions/736#discussioncomment-1295697_

**Comment by hbredin** [comment]
One way of doing it is the following:
* update [`pyannote.pipeline.optimizer.Optimizer.{tune | tune_iter}`](https://github.com/pyannote/pyannote-pipeline/blob/79636068cce0533aaf9682e3deecab30fb8564a1/pyannote/pipeline/optimizer.py#L239-L323) to set a new `self.pipeline.is_training` boolean flag to `True`
* update `pyannote.audio` pipelines to use this new flag and only cache raw scores when `is_training` exists and is `True`.

**Comment by matakanobu** [comment]
I agree with your idea.

I think that a pseudo code is like this.

```python

def __init__(
    self,
    segmentation: PipelineModel = "pyannote/segmentation",
    fscore: bool = False,
    **inference_kwargs,
):
    ...
    self.is_training = False


def apply(self, file: AudioFile) -> Annotation:

    if self.is_training: return self.get_raw_scores(file)

    activation = self.segmentation_inference_(file)
    file["@voice_activity_detection/activation"] = activation

    speech = self._binarize(activation)
    speech.uri = file["uri"]
    return speech


@cache
def get_raw_scores(
    self, file: AudioFile
) ->  Union[SlidingWindowFeature, np.ndarray]:

    scores = self.segmentation_inference_(file)
    return scores

```

[functools.cache](https://docs.python.org/3/library/functools.html#functools.lru_cache) arguments to the function must be a hashable(i.e. get_raw_scores arg must be a hashnable). But, it seems that type of "AudioFile" is Mapping or "ProtocolFile". So I think that we may need to update ProtocolFile into hashnable.

**Comment by hbredin** [comment]
After thinking about this a bit more, I think we should instead rely on the fact that `file` is a dict-like.
We already store `activation` inside `file` for debugging purposes so let's do this instead:

```python
CACHED_ACTIVATIONS = "@voice_activity_detection/activations"

def apply(self, file: AudioFile) -> Annotation:

    if self.is_training and CACHED_ACTIVATIONS not in file:
        file[CACHED_ACTIVATIONS] = self.segmentation_inference_(file)

    else:
        file[CACHED_ACTIVATIONS] = self.segmentation_inference_(file)

    activations = file[CACHED_ACTIVATIONS]

    speech = self._binarize(activations)
    speech.uri = file["uri"]
    return speech
```

We could somehow factorize the `if else` thing but I'd rather make it clear that one thing thing is happening during training and the other one is not. Also, when testing (i.e. `is_training == False`), we don't want to rely on the cached activations even if they are available in `file`: we want to recompute them.

**Comment by hbredin** [comment]
WIP in #752 and https://github.com/pyannote/pyannote-pipeline/pull/33

**Comment by hbredin** [comment]
Just-released pyannote.pipeline 2.1 now sets `pipeline.training` to False in `Optimizer.{tune | tune_iter}`.

Several pyannote.audio pipelines now use this feature to cache model outputs:
* VoiceActivityDetection
* OverlappedSpeechDetection
* Segmentation
* Resegmentation

Consequently, hyper-parameter optimization is much faster (20x for the VAD pipeline I just optimized...)

@matakanobu, I would loooove to hear your feedback!
