### ISSUE TITLE
feature-extraction tutorial 'db.yml' file not found

### ISSUE THREAD

**Issue by EngineerReversed** [pyannote/pyannote-audio#75]
Hi Bredin!
I was trying to replicate [feature-extraction](https://github.com/pyannote/pyannote-audio/tree/master/tutorials/feature-extraction) tutorial. I followed the installation instructions as given in master branch.
But when I tried to execute command ```cat ~/.pyannote/db.yml```, I got the error as follows:
> cat: /home/abhishek/.pyannote/db.yml: No such file or directory

So, after skipping this, when I tried to extract the features from audio files ```pyannote-speech-feature ${EXPERIMENT_DIR} GameOfThrones``` I got the following error:
>/home/abhishek/anaconda3/envs/pyannote-audio/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/abhishek/anaconda3/envs/pyannote-audio/bin/pyannote-speech-feature", line 11, in <module>
    sys.exit(main())
  File "/home/abhishek/anaconda3/envs/pyannote-audio/lib/python3.5/site-packages/pyannote/audio/applications/feature_extraction.py", line 188, in main
    preprocessors = {'wav': FileFinder(db_yml)}
  File "/home/abhishek/anaconda3/envs/pyannote-audio/lib/python3.5/site-packages/pyannote/database/util.py", line 85, in __init__
    with open(config_yml, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/abhishek/.pyannote/db.yml'

So, I have the following doubts:
1. What is db.yml file?
2. How is this file created? I created the pyannote.database plugin for GameOfThrones but this file was not created in the process.
3. Do we have to create a symbolic link to the database (audio .wav files) for ```~/.pyannote/db.yml``` which redirects to ```/path/to/GameOfThrones/corpus/{uri}.wav```
    * Is this {uri} variable need to be defined externally in bash terminal or is directly incorporated from files?

**Comment by hbredin** [comment]
This might help: https://github.com/pyannote/pyannote-database#preprocessors

**Comment by EngineerReversed** [comment]
Thanks for guiding me to the link. I earlier read the whole but could not make sense of it. Now, I created a ```db.yml``` file which contains the link to my audio database as follows:
> GameOfThrones: /home/abhishek/AthenasOwl/Voice_Recognition/Speaker_diarization/Datasets/pyannote_database/pyannote-db-gameofthrones/GameOfThrones/audio_files/{uri}.wav

I further created a ```.pyannote``` folder in home directory and placed ```db.yml``` file inside the folder. Now, I was able to go forward. However, I encountered another error while executing ```pyannote-speech-feature ${EXPERIMENT_DIR} GameOfThrones.SpeakerDiarization.Season1``` the command in ubuntu terminal
>Traceback (most recent call last):
  File "/usr/local/bin/pyannote-speech-feature", line 7, in <module>
    from pyannote.audio.applications.feature_extraction import main
  File "/usr/local/lib/python3.5/dist-packages/pyannote/audio/applications/feature_extraction.py", line 87, in <module>
    from pyannote.audio.features.utils import Precomputed
  File "/usr/local/lib/python3.5/dist-packages/pyannote/audio/features/__init__.py", line 29, in <module>
    from .with_yaafe import YaafeCompound, YaafeZCR, YaafeMFCC
  File "/usr/local/lib/python3.5/dist-packages/pyannote/audio/features/with_yaafe.py", line 33, in <module>
    import yaafelib
ImportError: No module named 'yaafelib'

I installed the ```yaafe``` module using conda but when I looked at the error, I found that it is looking for ```yaafe``` in local python3.5 packages not in conda environment setup earlier. 
1. Do I have to install ```yaafelib``` in local python3.5"?
2. How can I use the ```yaafe``` installed in conda environment?

**Comment by hbredin** [comment]
I guess this is a problem in your setup. Not sure how to help. 
Can you start fresh with an empty `conda` environment, activate it, `conda install` yaafe, then `pip install` pyannote?

**Comment by EngineerReversed** [comment]
For the above problem, I took the code out of the `conda` environment and was successfully able to run code by installing [yaafe](https://github.com/Yaafe/Yaafe) from the source. 

PS: You may close the issue as the issue was about `db.yml` file.
