### ISSUE TITLE
Training failure with several Keras versions

### ISSUE THREAD

**Issue by Yanivs24** [pyannote/pyannote-audio#77]
Hi,
I have the latest version of Keras (2.1.3) and when I tried to train a model for speaker embedding I received the following error: 
> TypeError: get_updates() missing 1 required positional argument: 'constraints'.

I looked at keras' sources and this error is due to an API change in keras.optimizer.get_updates() that was not changed in the file pyannote/audio/optimizers.py. When I tried to downgrade to keras 2.0.0 I got another error related to inconsistency in keras.models.save_model signature. 

Please fix this inconsistency or provide a suitable version of Keras.
Thanks!

**Comment by hbredin** [comment]
Can you try with Keras 2.0.5 ?

https://github.com/pyannote/pyannote-audio/blob/e3d683b65a6ace52d9de1f5d027ec71d7e9a08e2/setup.py#L47

**Comment by Yanivs24** [comment]
Yes it worked. 
Thanks!
