### ISSUE TITLE
Explanation of Warning Message about Bad Cluster Centers

### ISSUE THREAD

**Issue by picheny-nyu** [pyannote/pyannote-audio#770]
**Describe the bug**
"UserWarning: All samples have mutually equal similarities. Returning arbitrary cluster center(s)."

I am running the pretrained dia_ami pipeline and get the above message. The data is fairly noisy, so I am not expecting great results, but would like to better understand this error message - I am worried I messed up the database file or the rttm file in some fashion......

**Comment by hbredin** [comment]
See https://scikit-learn.org/stable/modules/generated/sklearn.cluster.AffinityPropagation.html#sklearn.cluster.AffinityPropagation
