### ISSUE TITLE
Segmentation visualization

### ISSUE THREAD

**Issue by Jamiroquai88** [pyannote/pyannote-audio#773]
Hi,

firstly, thank you for your amazing work, I really appreciate it and I have been using pyannote for a couple of years now. I have a question about how to visualize segmentation in the way it is shown in https://huggingface.co/pyannote/segmentation - figure on top labeled as output.

I am running simple ipython notebook and when running this
```python
from pyannote.audio import Inference

inference = Inference("pyannote/segmentation")

seg = inference("1_trimmed_short.wav")

seg
```
I am getting error
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/anaconda3/envs/pyannote2.0/lib/python3.8/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~/anaconda3/envs/pyannote2.0/lib/python3.8/site-packages/pyannote/core/feature.py in _repr_png_(self)
    242 
    243         from .notebook import repr_feature
--> 244         return repr_feature(self)
    245 
    246     _HANDLED_TYPES = (np.ndarray, numbers.Number)

~/anaconda3/envs/pyannote2.0/lib/python3.8/site-packages/pyannote/core/notebook.py in repr_feature(feature)
    395     plt.rcParams['figure.figsize'] = (notebook.width, 2)
    396     fig, ax = plt.subplots()
--> 397     notebook.plot_feature(feature, ax=ax)
    398     data = print_figure(fig, 'png')
    399     plt.close(fig)

~/anaconda3/envs/pyannote2.0/lib/python3.8/site-packages/pyannote/core/notebook.py in plot_feature(self, feature, ax, time, ylim)
    327 
    328         window = feature.sliding_window
--> 329         n, dimension = feature.data.shape
    330         (start, stop), = window.crop(self.crop, mode='loose',
    331                                      return_ranges=True)

ValueError: too many values to unpack (expected 2)
```
The `seg.data` has obviously 3 dimensions. Do I understand it correctly, that the first dimension refers to sliding window with size of 5s (and shift is 0.5s) and in every window there is 293 x `Kmax=4` where 293 refers to 16ms (as written in the paper) temporal resolution?

My goal is to try this for speaker switch detection.

Many thanks

**Comment by hbredin** [comment]
Thanks for your kind words about pyannote. I really appreciate receiving this (rare) kind of feedback!

> The `seg.data` has obviously 3 dimensions. Do I understand it correctly, that the first dimension refers to sliding window with size of 5s (and shift is 0.5s) and in every window there is 293 x `Kmax=4` where 293 refers to 16ms (as written in the paper) temporal resolution?

Yes. That is correct. 

You found out the hard way that `pyannote.core` visualization does not support 3-dimensional features like this one for now. 
But I'd be happy to merge a PR that adds this feature. The output could look like that: 

![image](https://user-images.githubusercontent.com/1080837/135812552-8ce06715-01cb-4e18-9bb9-92ccdad26db1.png)

> My goal is to try this for speaker switch detection.

I have been meaning to use this model for speaker change (switch?) detection as well but did not have time to work on that yet. So, I'd love to learn a bit more about your findings! I'd even be willing to collaborate on this if you are interested...

**Comment by Jamiroquai88** [comment]
@hbredin thanks a lot
I am a little bit unsure about the picture above.
I was able to implement something like this:
![image](https://user-images.githubusercontent.com/9023716/136251966-b25b02fd-d061-45a0-9f27-7a8306135280.png)
For now I just update `data` attribute and let it plot the figure itself. For every timeframe, I update the last 5 seconds (window size), so in 5.5s I update 0.5-5.0 s. Is this okay or it should be done differently?
Don't worry about the time axis, I'll check it once I get to implementing it.

**Comment by hbredin** [comment]
My proposition was to actually draw every 5s chunk and make sure we visualize the whole matrix (hence creating additional rows to avoid overlap between adjacent chunks).

Since the segmentation model is permutation-invariant, the output might shuffle speakers from one chunk to another -- so what you suggest will look weird when that happens. 

But there are two different problems here:
1. visualizing the data (my proposition)
2. making use of the data (your task)

For 2., you may want to have a look at this paper (and code) where we propose a way to deal with the shuffling issue:
https://github.com/juanmc2005/StreamingSpeakerDiarization/

**Comment by Jamiroquai88** [comment]
@hbredin thanks, it makes sense to me now
mainly I wanted to visualize the online speaker change detection (thanks for providing the link to streaming diarization, I already read it)
