### ISSUE TITLE
Train models for gender and age recognition

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#774]
VoxCeleb has recently been enriched with age and gender metadata

https://github.com/hechmik/voxceleb_enrichment_age_gender
https://arxiv.org/abs/2109.13510

Would be nice to train a model for those two tasks...

**Comment by Mlallena** [comment]
This expansion looks very good - it would certainly allow for many different options.

Will this be merged with basic pyannote-audio soon? Or is there a way to use it already?

**Comment by hadware** [comment]
I've got a bit of time to try and finish my PR (sorry to both of you for the delay). I'll keep you posted and tell you when it's ready. I've already started making a notebook tutorial modeled on the ones already written by @hbredin .

**Comment by Mlallena** [comment]
Thank you for your answer, @hadware. Can't wait to see the finished PR and the tutorial!

**Comment by Mlallena** [comment]
@hadware How's it going?

**Comment by hadware** [comment]
Good! The results are promising, i'll be doing what needs to be done next week to make it merge-worthy.

**Comment by skanda1005** [comment]
Any update in the PR?

**Comment by hbredin** [comment]
The PR has been merged. It is now possible to train multi-label segmentation models using  `pyannote.audio.tasks.MultiLabelSegmentation`? 

No tutorial exists yet but you could use [this notebook](https://github.com/pyannote/pyannote-audio/blob/551b2c4170bd3f10a30d6a052eb9d4b6e8ddce27/tutorials/multilabel_detection.ipynb) as a starting point to train male/female classifier, for instance.
