### ISSUE TITLE
Is it possible to Enable GPU for triplet loss embedding extraction? (problem of Zero GPU-Util while High GPU memory usage)

### ISSUE THREAD

**Issue by glynpu** [pyannote/pyannote-audio#80]
Hi, I am trying to accelerate the training process with my GPU, only to find a high GPU memory usage while a ZERO GPU-Util, as shown in the following picture.

Is there any appropriate way to adopt GPU during training of triplet models? 

Ps. Both of these two threads are for triplet loss training. No other application are adopting GPU. 

![aqhvoky_8 _ b h_3a zhc](https://user-images.githubusercontent.com/14951566/35864207-10816cee-0b8c-11e8-9d18-508c0b773207.png)

**Comment by hbredin** [comment]
A future version will make better use of GPUs.
However, I cannot provide with you with any ETA. Sorry.
