### ISSUE TITLE
Typo in raw scores extraction command

### ISSUE THREAD

**Issue by SahilAtWingman** [pyannote/pyannote-audio#806]
`$ export EXP_DIR=tutorials/pipelines/speaker_diarization

$ for SUBSET in developement test
 > do
 > for TASK in sad scd emb
 >  do
 >    pyannote-audio ${TASK} apply --step=0.1 --pretrained=${TASK}_ami --subset=${SUBSET} ${EXP_DIR} AMI.SpeakerDiarization.MixHeadset    
 >  done
 > done`

developement needs to replaced with development

**Comment by hbredin** [comment]
Thanks. Feel free to edit the file / open a PR fixing this issue. I will then merge it.
