### ISSUE TITLE
ModuleNotFoundError: No module named 'pyannote.audio.core'

### ISSUE THREAD

**Issue by ORainn** [pyannote/pyannote-audio#809]
Hi👋I'm recently learning a repo that uses pyannote and when I try to run the script I receive this error. Could you please tell me how to fix it so that I can use pyannote successfully?
The original code as follows:
`from pyannote.audio.core.io import Audio, AudioFile`

Best wishes!

**Comment by ORainn** [comment]
By the way, the version of pyannote.audio in my local env is 1.1.2.

**Comment by hbredin** [comment]
Looks like you need to install from [develop branch](https://github.com/pyannote/pyannote-audio/tree/develop#neural-speaker-diarization).

**Comment by ORainn** [comment]
> Looks like you need to install from [develop branch](https://github.com/pyannote/pyannote-audio/tree/develop#neural-speaker-diarization).

I've followed your guidance and solved this problem. thx!
