### ISSUE TITLE
anyway to *just apply*

### ISSUE THREAD

**Issue by koyo922** [pyannote/pyannote-audio#81]
I just want to experiment with the "Speaker Change Detection" as a **SOLUTION OUT OF BOX** ; for the first step, I need to test it on my own unlabeled data using a *pretrained model* and see if it generalizes well; and then decide whether to train my own model.

Something that *looks like a pretrained model* was find here:
https://github.com/yinruiqing/change_detection/tree/master/model

But I do not have access to the ETAPE database, nor do I understand the complicated structure or concepts (e.g. terms like "protocol" in "<database.task.protocol>") of the database;
So, how can I replicate your amazing work on my own data ?

Thanks !

**Comment by koyo922** [comment]
I have found the document for database here
https://github.com/pyannote/pyannote-database#table-of-contents

So, the only problem left is how to ensure the effectiveness by evaluating a pretrained model on my own data, before training one?

**Comment by hbredin** [comment]
No pre-trained model is available for now. Sorry.
You'll have to go through this [tutorial](https://github.com/pyannote/pyannote-audio/tree/master/tutorials/change-detection) using your own [pyannote.database](https://github.com/pyannote/pyannote-database) plugin.
