### ISSUE TITLE
How to Run a job on multiple GPUs

### ISSUE THREAD

**Issue by mujhenahiata** [pyannote/pyannote-audio#820]
solutions tried:
1. CUDA_VISIBLE_DEVICES=0,1  pyannote-audio ovl train --subset=train --to=200 --gpu=2 ${EXP_DIR} AMI.SpeakerDiarization.MixHeadset 
2. CUDA_VISIBLE_DEVICES=0,1 
 {enter}
pyannote-audio ovl train --subset=train --to=200 --gpu=2 ${EXP_DIR} AMI.SpeakerDiarization.MixHeadset 

Even after this the training is running on one GPU only.
what alternative remedy can solve the above mentioned issue
![image](https://user-images.githubusercontent.com/94825377/144179898-e7eaec7b-f99c-4977-ae07-0b6d4b98033f.png)

**Comment by hbredin** [comment]
pyannote 1.x does not support multi-gpu training. 
This will be supported in upcoming pyannote 2.0 that you can already try from `develop` branch.

**Comment by fabiocat93** [comment]
is multi-GPUs training supported with the most updated version of pyannote 2?

**Comment by hbredin** [comment]
Yes. Via pytorch-lightning trainer.
