### ISSUE TITLE
Prodigy recipe to dump annotations into RTTM and UEM files

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#821]
```bash
prodigy pyannote.database dataset dataset.rttm dataset.uem
```

Inspired by the built-in [db-out recipe](https://prodi.gy/docs/recipes#db-out), this recipe dumps the annotation into RTTM and UEM files (as expected by pyannote.audio and pyannote.database).

By default, this should only dump annotations where `answer` is `accept`. An option called `--filter={accept | ignore | reject | flag}` could be used to dump ignored/rejected/flags annotations.

**Comment by hbredin** [comment]
@J-Petiot would be nice to have this recipe :)
Let's call it `pyannote.database`.

**Comment by J-Petiot** [comment]
Good idea, I can work on it
