### ISSUE TITLE
Training a Speaker Change Detection model on your own data

### ISSUE THREAD

**Issue by ckobus** [pyannote/pyannote-audio#823]
Hi,

I would like to train a SCD model on my own data; I came across this page https://github.com/pyannote/pyannote-audio/tree/master/tutorials/models/speaker_change_detection

But I also noticed there was a develop branch https://github.com/pyannote/pyannote-audio/tree/develop with new features, etc

Would you advise following what is documented on the develop branch?

Thank you for your answer!

Catherine Kobus

**Comment by hbredin** [comment]
I would indeed advise _against_ using speaker change detection from pyannote.audio 1.x.

Training a [segmentation model](https://huggingface.co/pyannote/segmentation) using upcoming pyannote.audio 2.0 (develop) branch will most likely give you much better results.

PS: if I am not mistaken, it looks like we are both based in Toulouse -- feel free to [drop me an email](https://herve.niderb.fr/fastpages/about/) if you are interested in collaborating on this!

**Comment by hbredin** [comment]
Closing stalled issue.
