### ISSUE TITLE
Does voice activity and other model work on audio data created from pydub module

### ISSUE THREAD

**Issue by kafan1986** [pyannote/pyannote-audio#834]
Does voice activity and other model work on audio data from pydub module without the need to write it to a file first

**Comment by hbredin** [comment]
Branch `develop` of pyannote.audio supports calling pipelines
* from a path: `pipeline("audio.wav")`
* from a dict: `pipeline({"waveform": np.ndarray, "sample_rate": int})`
* a few other options documented here: https://github.com/pyannote/pyannote-audio/blob/78df4890f855bcde94735a7bb8fe31a7234b8ac6/pyannote/audio/core/io.py#L51-L59

**Comment by kafan1986** [comment]
> 

Thanks for replying. I have one more query. I have already performed VAD step using a different model. I can create a Pynote.Audio.Annotation object from my VAD data. Now question is how can I feed this object to embedding and clustering step for performing diarization?

**Comment by hbredin** [comment]
Closing as the original issue is now solved.
Please open a new one so that each issue is self-contained.
