### ISSUE TITLE
Huggingface Inference API and widget

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#835]
[pyannote.audio 2.0](https://github.com/pyannote/pyannote-audio/tree/develop) will bring a unified pipeline API:

```python
from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization")
output = pipeline("audio.wav")   # or pipeline({"waveform": np.ndarray, "sample_rate": int})
```

where `output` is a [`pyannote.core.Annotation`](http://pyannote.github.io/pyannote-core/structure.html#annotation) instance.

I just [created a space](https://huggingface.co/spaces/pyannote/pretrained-pipelines) that allows to test a bunch of pipelines shared on Hugginface Hub but it would be nice if those were testable directly in their own model card.

My understanding is that two things needs to happen 
* pyannote pipeline support must be added to [Hugginface Inference API](https://github.com/huggingface/huggingface_hub/tree/main/api-inference-community)
* a new widget (based on [wavesurfer.js](https://wavesurfer-js.org/) ?) must be added to the list of [Huggingface widgets](https://huggingface.co/docs/hub/main#what-are-all-the-possible-taskwidget-types)

**Comment by jonaskratochvil** [comment]
Hello, thank you for your effort. There is currently missing model checkpoint in Huggingface would it be possible to add it?

**Comment by hbredin** [comment]
@julien-c: `stale bot` keeps closing this issue... I wonder whether it is trying to tell us something about the infamous audio segmentation widget ;-p

**Comment by julien-c** [comment]
well someone is assigned on the issue so let's see :)

(also ccing @mishig25 on our side for visibility)

**Comment by hbredin** [comment]
Or is [this](https://github.com/huggingface/hub-docs/tree/main/js/src/lib/components/InferenceWidget/widgets) it?

**Comment by julien-c** [comment]
to the second question: yes! sorry if this was not clear before, they're all open source

**Comment by julien-c** [comment]
(and @mishig25 is maintaining them)
