### ISSUE TITLE
Getting syntax error using develop branch

### ISSUE THREAD

**Issue by deayalar** [pyannote/pyannote-audio#836]
Hello!
I was taking a look at the new features in develop branch.
So I was following the example about the speaker diarization pipeline https://github.com/pyannote/pyannote-audio/tree/develop#speaker-diarization
But I got a syntax error:

(min_speakers=)
                 ^
SyntaxError: invalid syntax
It shows the error just by importing 
from pyannote.audio.pipelines import SpeakerDiarization

So I guess the error comes from here

https://github.com/pyannote/pyannote-audio/blob/78df4890f855bcde94735a7bb8fe31a7234b8ac6/pyannote/audio/pipelines/utils.py#L235

**Comment by acidcoma** [comment]
I got same error!

**Comment by hbredin** [comment]
This syntax has been added in Python 3.8: https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging

Looks like you both use Python 3.7 or earlier.

**Comment by hbredin** [comment]
Support for Python 3.7 is back in current develop branch. Closing.
