### ISSUE TITLE
speaker change detection

### ISSUE THREAD

**Issue by l-guo** [pyannote/pyannote-audio#84]
hi

I am trying to use speaker change detection
but when I using pyannote-change-detection -h
there is an error as below

pyannote-change-detection -h
Using Theano backend.
Traceback (most recent call last):
  File "/homes/user1/anaconda3/envs/py35-pyannote-audio/bin/pyannote-change-detection", line 7, in <module>
    from pyannote.audio.applications.change_detection import main
  File "/homes/user1/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/audio/applications/change_detection.py", line 144, in <module>
    from pyannote.audio.generators.change import ChangeDetectionBatchGenerator
  File "/homes/user1/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/audio/generators/change.py", line 31, in <module>
    from pyannote.audio.generators.periodic import PeriodicFeaturesMixin
  File "/homes/user1/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/audio/generators/periodic.py", line 33, in <module>
    from pyannote.audio.features.utils import PyannoteFeatureExtractionError
  File "/homes/user1/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/audio/features/__init__.py", line 29, in <module>
    from .with_yaafe import YaafeCompound, YaafeZCR, YaafeMFCC
  File "/homes/user1/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/audio/features/with_yaafe.py", line 42, in <module>
    from pyannote.audio.features.utils import PyannoteFeatureExtractionError
  File "/homes/user1/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/audio/features/utils.py", line 42, in <module>
    from pyannote.database.util import get_unique_identifier
  File "/homes/user1/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/database/__init__.py", line 37, in <module>
    from .database import Database
  File "/homes/user1/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/database/database.py", line 30, in <module>
    from .util import PyannoteDatabaseException
  File "/homes/user1/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/database/util.py", line 148
    methods.append(f'{subset}{suffix}')
                                                         ^
SyntaxError: invalid syntax

do you know what is the problem?
could you help me to solve it?

**Comment by hbredin** [comment]
This is due to `pyannote.database` now relying on a very convenient [feature introduced in Python 3.6](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498).

Two options:
- either upgrade to Python 3.6 (recommended, as I no longer support older versions)
- or downgrade to pyannote.database 1.1 (`pip install pyannote.database==1.1`)

**Comment by l-guo** [comment]
it worked!
thank you for your answering!

**Comment by l-guo** [comment]
sorry for interrupt you again...
last time I downgrade pyannote.database and the system is worked
as you recommended upgrade to Python 3.6, this time I upgrade Python from 3.5 to 3.6
but install stopped with the error below...

Building wheels for collected packages: pysndfile
  Running setup.py bdist_wheel for pysndfile ... error
  Complete output from command /homes/user1/anaconda3/envs/py36-pyannote-audio/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-gb49dep7/pysndfile/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpbgmww8uipip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/pysndfile
  copying pysndfile/Faiff.py -> build/lib.linux-x86_64-3.6/pysndfile
  copying pysndfile/sndio.py -> build/lib.linux-x86_64-3.6/pysndfile
  copying pysndfile/__init__.py -> build/lib.linux-x86_64-3.6/pysndfile
  running build_ext
  check for clang compiler ... no
  building '_pysndfile' extension
  creating build/temp.linux-x86_64-3.6
  gcc -pthread -B /homes/user1/anaconda3/envs/py36-pyannote-audio/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/homes/user1/anaconda3/envs/py36-pyannote-audio/lib/python3.6/site-packages/numpy/core/include -I/homes/user1/anaconda3/envs/py36-pyannote-audio/include/python3.6m -c _pysndfile.cpp -o build/temp.linux-x86_64-3.6/_pysndfile.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  In file included from /homes/user1/anaconda3/envs/py36-pyannote-audio/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                   from /homes/user1/anaconda3/envs/py36-pyannote-audio/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                   from /homes/user1/anaconda3/envs/py36-pyannote-audio/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from _pysndfile.cpp:469:
  /homes/user1/anaconda3/envs/py36-pyannote-audio/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^
  g++ -pthread -shared -B /homes/user1/anaconda3/envs/py36-pyannote-audio/compiler_compat -L/homes/user1/anaconda3/envs/py36-pyannote-audio/lib -Wl,-rpath=/homes/user1/anaconda3/envs/py36-pyannote-audio/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/_pysndfile.o -lsndfile -o build/lib.linux-x86_64-3.6/pysndfile/_pysndfile.cpython-36m-x86_64-linux-gnu.so
  /homes/user1/anaconda3/envs/py36-pyannote-audio/compiler_compat/ld: cannot find -lm
  /homes/user1/anaconda3/envs/py36-pyannote-audio/compiler_compat/ld: cannot find -lpthread
  /homes/user1/anaconda3/envs/py36-pyannote-audio/compiler_compat/ld: cannot find -lc
  collect2: error: ld returned 1 exit status
  error: command 'g++' failed with exit status 1

  ----------------------------------------
  Failed building wheel for pysndfile

**Comment by hbredin** [comment]
This issue is related to `pysndfile` not compiling properly -- not pyannote.audio.
Sorry, I won't be able to help you...
