### ISSUE TITLE
How can I prepare training data for speaker embedding?

### ISSUE THREAD

**Issue by sablea** [pyannote/pyannote-audio#845]
I want to train speaker embedding model with other language by pyannote-audio2.0.
I'm not sure if training speaker embedding should be needed .rttm file(i.e. label indicating the speaker and speaking time) and .uem file. 
I have read all tutorials about pyannote-audio, and I found that the protocol used to train speaker embedding in the tutorials is called "voxceleb. Speakervarification. Voxceleb2". 
Could you tell me the format of training data and database.yml for speaker embedding?

**Comment by hbredin** [comment]
You can use any "SpeakerDiarization" protocol to train speaker embedding, as long as each speaker is given a unique identifier. 

That being said, I would not recommend using pyannote to train speaker embeddings.
For now (January 2022) speechbrain speaker embeddings are much better than pyannote's
