### ISSUE TITLE
Using pyannote/segmentation Model offline

### ISSUE THREAD

**Issue by TobiasTe** [pyannote/pyannote-audio#847]
Hi,

Thank you for the very nice library! 

I have a probably dumb question. I would like to use the pretrained Segmentation Model offline and wonder how to do that if it is possible? What exactly do I have to download and how do I call it in my code?

So, speaking code, I would just like to replace the line
Model.from_pretrained("pyannote/segmentation") 
by something that also works offline.

Best regards and thanks again
Tobias

**Comment by hbredin** [comment]
1. Download the [checkpoint](https://huggingface.co/pyannote/segmentation/tree/main) from Huggingface Hub
```bash
wget https://huggingface.co/pyannote/segmentation/resolve/main/pytorch_model.bin
```

2. Load it with `Model.from_pretrained`
```python
from pyannote.audio import Model
model = Model.from_pretrained("/path/to/pytorch_model.bin")
```

**Comment by TobiasTe** [comment]
Thanks for the quick answer and sorry for one more question:

To use the speaker diarization pipeline offline (I actually can't just use it online with Pipeline.from_pretrained("pyannote/speaker-diarization") because I get some symlink error on windows), I figured out that I can run
`pipeline = Pipeline.from_pretrained('/path/to/config.yaml')`
where I took the config.yaml file from hugging face and changed the segmentation parameter to '/path/to/pyannote_seg_model.bin' and the embedding parameter to '/path/to/pyannote_emb_model.bin'. This worked.

However, in the original config.yaml, you use as embedding model speechbrain/spkrec-ecapa-voxceleb (why? Is it better than using the pyannote embedding model?). I tried to reproduce this offline by just download the 'embedding_model.ckpt' from speechbrain/spkrec-ecapa-voxceleb and setting the embedding parameter in the config.yaml to the path to that file, but this doesn't work (error message see below). Could you give me a hint how this should be done?

Thanks a lot!

Error message when setting embedding parameter to the path to the 'embedding_model.ckpt' file from speechbrain:
```The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Users\user\miniconda3\envs\pyannote2\lib\site-packages\pyannote\audio\core\pipeline.py", line 98, in from_pretrained
    pipeline = Klass(**config["pipeline"].get("params", {}))
  File "C:\Users\user\miniconda3\envs\pyannote2\lib\site-packages\pyannote\audio\pipelines\speaker_diarization.py", line 119, in __init__
    self._embedding = PretrainedSpeakerEmbedding(self.embedding, device=emb_device)
  File "C:\Users\user\miniconda3\envs\pyannote2\lib\site-packages\pyannote\audio\pipelines\speaker_verification.py", line 267, in PretrainedSpeakerEmbedding
    return PyannoteAudioPretrainedSpeakerEmbedding(embedding, device=device)
  File "C:\Users\user\miniconda3\envs\pyannote2\lib\site-packages\pyannote\audio\pipelines\speaker_verification.py", line 202, in __init__
    self.model_: Model = get_model(self.embedding)
  File "C:\Users\user\miniconda3\envs\pyannote2\lib\site-packages\pyannote\audio\pipelines\utils.py", line 73, in get_model
    model = Model.from_pretrained(model, strict=False)
  File "C:\Users\user\miniconda3\envs\pyannote2\lib\site-packages\pyannote\audio\core\model.py", line 821, in from_pretrained
    module_name: str = loaded_checkpoint["pyannote.audio"]["architecture"]["module"]
KeyError: 'pyannote.audio'
