### ISSUE TITLE
Pretrained models w/ 0.5s, 1s and 5s windows

### ISSUE THREAD

**Issue by rafellerc** [pyannote/pyannote-audio#86]
Is there a pretrained model on ETAPE-TV with 0.5s, 1s and 5s windows, as mentioned in the paper? Because the one TristouNet included, seems to be a 2s only. Or am I wrong?

**Comment by rafellerc** [comment]
Is there a pretrained model on ETAPE-TV with 0.5s, 1s and 5s windows, as mentioned in the paper? #86

**Comment by hbredin** [comment]
You are right. Only one model is available.

**Comment by hbredin** [comment]
Drop be an email. We'll try to find a solution...
