### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by Sungbinyouk** [pyannote/pyannote-audio#861]
**Describe the bug**
When trying to run speech-diarization, CUDA error: no kernel image is available or execution on the device. 

**To Reproduce**
```bash
$ conda create -n pyannote python=3.8.5
$ conda activate pyannote
$ conda install pytorch torchaudio -c pytorch
$ conda install numpy cffi
$ conda install libsndfile=1.0.28 -c conda-forge
$ pip install pytz
$ pip install speechbrain
$ conda install -c conda-forge jupyter notebook
$ conda install ipykernel
$ ipython kernel install --user --name=pyannote
$ jupyter notebook
```

```notebook
!pip install https://github.com/pyannote/pyannote-audio/archive/develop.zip
from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization")
```

Error:

CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by hbredin** [comment]
Closing as this is not specific to pyannote. This is a PyTorch/CUDA incompatibility issue. 
Googling the error message should help you find the solution.
