### ISSUE TITLE
speaker diarization & poor effect,Why？

### ISSUE THREAD

**Issue by luhuijun666** [pyannote/pyannote-audio#865]
two tests:
first sample : dev00.wav:
result:
start=2.1s stop=12.8s speaker_SPEAKER_00
start=13.2s stop=16.7s speaker_SPEAKER_00
start=18.4s stop=21.4s speaker_SPEAKER_00
start=21.9s stop=26.1s speaker_SPEAKER_00
start=26.3s stop=28.2s speaker_SPEAKER_00
start=28.5s stop=30.0s speaker_SPEAKER_00
analysis: wrong!because there are two man speaking in the scene.

second sample: tst00.wav
[ 00:00:00.257 --> 00:00:07.784] A SPEAKER_00
[ 00:00:03.615 --> 00:00:06.720] H SPEAKER_01
[ 00:00:07.784 --> 00:00:11.715] I SPEAKER_01
[ 00:00:11.834 --> 00:00:26.076] J SPEAKER_01
[ 00:00:13.150 --> 00:00:14.382] B SPEAKER_00
[ 00:00:15.074 --> 00:00:15.495] C SPEAKER_00
[ 00:00:19.090 --> 00:00:19.917] D SPEAKER_00
[ 00:00:22.515 --> 00:00:23.292] E SPEAKER_00
[ 00:00:26.397 --> 00:00:29.957] G SPEAKER_00
analysis: wrong! there are more than 4 speakers in the scene.
I wonder why the "pyannote/speaker-diarization"  is so poor. Could someone explain it for me?
Or is there something wrong?

**Comment by luhuijun666** [comment]
The test code：
# instantiate pretrained speaker diarization pipeline
from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization")

# apply pretrained pipeline
diarization = pipeline("tests/data/dev00.wav")
#diarization = pipeline("dev00.wav")

# print the result
for turn, _, speaker in diarization.itertracks(yield_label=True):
    print(f"start={turn.start:.1f}s stop={turn.end:.1f}s speaker_{speaker}")

**Comment by luhuijun666** [comment]
I used "tests/data/dev00.wav”  in  your code.
Could you offer a  test result of ""tests/data/dev00.wav” ?
I  could not understand  why my test result is so poor.

**Comment by luhuijun666** [comment]
> You did not do anything wrong: these are the expected outputs of the pipeline.

But the result is very poor, why?

**Comment by hbredin** [comment]
Let me know if you find out!

**Comment by Yagna24** [comment]
Hi @luhuijun666 , I don't understand how you have used from_pretrained() here : 

```
from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization")
```

Me using the same snippet throws me an error, also when I try to search for `from_pretrained() ` in the `pyannote.audio ` I don't find it  except in the hugging face transformers.

**Comment by hbredin** [comment]
Closing as this is more a research question than a bug.
