### ISSUE TITLE
pyannote-audio2 is slower than pyannmte-audio1

### ISSUE THREAD

**Issue by pengyuan101** [pyannote/pyannote-audio#879]
Thank you for your efforts! But I found that the pyannote-audio2 is twice as slow as the pyannote-audio1 by GPU.I would like to know what is causing this problem.

**Comment by hbredin** [comment]
Closing as duplicates of https://github.com/pyannote/pyannote-audio/discussions/852

**Comment by pengyuan101** [comment]
OK，I found that the most time is used in embeding.thanks!
