### ISSUE TITLE
small typo in readme of pyannote-change-detection tutorial

### ISSUE THREAD

**Issue by royaljain** [pyannote/pyannote-audio#88]
$ pyannote-speech-detection apply \
          --epoch=49 \
          --threshold=0.1 \
          ${TRAIN_DIR} \               #<train_dir>
          Etape.SpeakerDiarization.TV

==>

$ pyannote-change-detection apply \
          --epoch=49 \
          --threshold=0.1 \
          ${TRAIN_DIR} \               #<train_dir>
          Etape.SpeakerDiarization.TV

**Comment by hbredin** [comment]
Thanks. It's already fixed in `develop` branch and will be solved in next release.
