### ISSUE TITLE
Diarization result looks empty when using own audio file

### ISSUE THREAD

**Issue by kormoczi** [pyannote/pyannote-audio#886]
Hi,

**Describe the bug**
I am not sure if this is a bug or not, but I cannot find out the reason for this problem:
I am trying to run a simple diarization based on the example on the main github page of pyannote-audio.
If the input file is from the test database (dev00.wav), than the method works.
But if I change to my own file (similar wav, sample rate 16000), the diarization result is just empty.
(I have installed the develop branch, with pip3 install https://github.com/pyannote/pyannote-audio/archive/develop.zip)
What are the requirements for the wav file?
Thanks!

**To Reproduce**
Here is the code I am trying to use:
```
import torchaudio
from pyannote.audio import Pipeline
waveform, sample_rate = torchaudio.load("dev00.wav")
audio_in_memory = {"waveform": waveform, "sample_rate": sample_rate}
# instantiate pretrained speaker diarization pipeline
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization")
# apply pretrained pipeline
diarization = pipeline(audio_in_memory)
# print the result
for turn, _, speaker in diarization.itertracks(yield_label=True):
    print(f"start={turn.start:.1f}s stop={turn.end:.1f}s speaker_{speaker}")
```

**pyannote environment**
```
$ pip3 freeze | grep pyannote
pyannote.audio==0.0.1
pyannote.core==4.3
pyannote.database==4.1.1
pyannote.metrics==2.3
pyannote.pipeline==2.2
```

**Comment by kormoczi** [comment]
I have tried to you this colab as well:
https://colab.research.google.com/github/pyannote/pyannote-audio/blob/develop/tutorials/intro.ipynb

And with my own audio files the diarization result is the following:
Annotation: diarization
Annotation with 0 items

So as I could understand, it cannot detect any speaker... But why?

**Comment by kormoczi** [comment]
I have played with the original demo audio in the colab a little bit more.
If I cut a smaller part of dev00.wav (like half of the original size), it is still working.
But if I cut a very small part (like 5 seconds), then the problem is there.
(Or maybe because there are no multiple sound / silence segments...)
Is it normal behaviour?

**Comment by kormoczi** [comment]
Sure! For the code I am using this colab:
https://colab.research.google.com/github/pyannote/pyannote-audio/blob/develop/tutorials/intro.ipynb
Start with the "Installation" step (just modified a little bit - folium should be installed):
```
!pip install folium==0.2.1
!pip install -q https://github.com/pyannote/pyannote-audio/archive/develop.zip
!pip install -q speechbrain
```
Then continue with the "Upload audio file" step (just added some imports, because I have skipped some steps):
```
from pyannote.core import notebook
from pyannote.audio import Audio 
from IPython.display import Audio as IPythonAudio
import google.colab
own_file, _ = google.colab.files.upload().popitem()
OWN_FILE = {'audio': own_file}
notebook.reset()
# load audio waveform and play it
waveform, sample_rate = Audio()(OWN_FILE)
IPythonAudio(data=waveform.squeeze(), rate=sample_rate, autoplay=True)
```
Then continue with the "Speaker diarization with pyannote.pipeline" step (just replace DEMO_FILE to OWN_FILE):
```
from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained('pyannote/speaker-diarization')
diarization = pipeline(OWN_FILE)
```
The final step is the visualization of the results:
```
diarization
```
If I upload the "test_data_3.wav" audio file (length is 10 seconds), then it works, I get some results, but if I upload the "test_data_4.wav" audio file (only 4 seconds, first part of the "test_data_3.wav" audio file), it just gives an error during the visualization step:
```
ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/IPython/core/formatters.py](https://localhost:8080/#) in __call__(self, obj)
    336             method = get_real_method(obj, self.print_method)
    337             if method is not None:
--> 338                 return method()
    339             return None
    340         else:

4 frames
[/usr/local/lib/python3.7/dist-packages/pyannote/core/timeline.py](https://localhost:8080/#) in __init__(self, segments, uri)
    151 
    152         if any(not segment for segment in segments_set):
--> 153             raise ValueError('Segments must not be empty.')
    154 
    155         self.segments_set_ = segments_set

ValueError: Segments must not be empty.
```
I have attached the wav file in a zip compressed way.

[tests_data_3.zip](https://github.com/pyannote/pyannote-audio/files/8063820/tests_data_3.zip)
[tests_data_4.zip](https://github.com/pyannote/pyannote-audio/files/8063823/tests_data_4.zip)

**Comment by hbredin** [comment]
I just [pushed](https://github.com/pyannote/pyannote-audio/commit/767b350f43dadf4c65f0c5d203aeaef3bb6362a9) a potential fix for short files.

Can you try with a fresh install from `develop` branch and let me know if this fixes your issue?

**Comment by kormoczi** [comment]
I have tried, and right now it runs without errors, but the diarization results looks strange.
I have an example (right now this is a little bit longer sample, 14 seconds), where there are 3 different speakers (one female and two male speakers), and the result shows just one speaker.
I haven't tested this sample previously, so I do not know if it should be ok with the previous version(s) or not...

[test_mix_05.zip](https://github.com/pyannote/pyannote-audio/files/8068396/test_mix_05.zip)

**Comment by hbredin** [comment]
Try reducing `min_activity` hyper-parameter as suggested in https://github.com/pyannote/pyannote-audio/issues/837

**Comment by pengyuan101** [comment]
> I have tried, and right now it runs without errors, but the diarization results looks strange. I have an example (right now this is a little bit longer sample, 14 seconds), where there are 3 different speakers (one female and two male speakers), and the result shows just one speaker. I haven't tested this sample previously, so I do not know if it should be ok with the previous version(s) or not...
> 
> [test_mix_05.zip](https://github.com/pyannote/pyannote-audio/files/8068396/test_mix_05.zip)
Have you solved this problem? I had the same problem.
