### ISSUE TITLE
Error return of Speaker Diarization On my own datasets

### ISSUE THREAD

**Issue by pengyuan101** [pyannote/pyannote-audio#899]
Thanks for your work.It's doing really well on the public stats.But when I income an audio with multiple speakers from phone, it always returns only one speaker.Below are the parameters I used and the audios.

CONFIG = {
    "segmentation": "pyannote/segmentation",
    "embedding": "speechbrain/spkrec-ecapa-voxceleb",
    "clustering": "AgglomerativeClustering"
}
PARAMS = {
    "onset": 0.5, "offset": 0.5,
    "stitch_threshold": 0.04, "min_activity": 6.0,
    "clustering": {"method": "average", "threshold": 0.595}
}
[https://drive.google.com/file/d/1mKLQXXzbspvI81A8oznRChjnGeDLiX_D/view?usp=sharing](url)
[https://drive.google.com/file/d/1czl_TSpvMePMH1JPX9eoglxGzxpY61fO/view?usp=sharing](url)
return：
![image](https://user-images.githubusercontent.com/51777276/154635928-1f706df1-28cf-4ed3-973f-035acede69aa.png)
![image](https://user-images.githubusercontent.com/51777276/154636061-c54d9cd8-0db3-40a4-9388-9ab30bcbf979.png)

**Comment by hbredin** [comment]
[See related FAQ question](https://github.com/pyannote/pyannote-audio#pretrained-pipelines-do-not-produce-good-results-on-my-data-what-can-i-do)
