### ISSUE TITLE
Save pipeline locally for offline usage

### ISSUE THREAD

**Issue by jellypyu** [pyannote/pyannote-audio#910]
I was wondering if there is a possibility to save the new pretrained pipeline (v2.0) from Huggingface locally so it can be used offline. The old pipeline/model (v1.1) could be stored with `torch.save()`, but the new one seems to work differently.

It seems like multiple files are downloaded to `~/.cache/huggingface/hub`. Can those somehow be combined and used to load the "full" pipeline?

**Comment by hbredin** [comment]
All `Pipeline.from_pretrained` does is download and read [this](https://huggingface.co/pyannote/speaker-diarization/blob/main/config.yaml) configuration file. 

Similarly, all `Model.from_pretrained` does is download and read [checkpoints](https://huggingface.co/pyannote/segmentation/blob/main/pytorch_model.bin).

You can use `Pipeline.from_pretrained("/path/to/local/config.yml")` and `Model.from_pretrained("/path/to/local/model.ckpt")` to load local versions.

`pyannote/speaker-diarization` pipeline also relies on `speechbrain` [speaker embedding](https://huggingface.co/speechbrain/spkrec-ecapa-voxceleb) so you'll probably have to ask `speechbrain` maintainers on how to do that for this part of pyannote.
