### ISSUE TITLE
Integrating the Speaker diarization pipeline and speech overlap pipeline

### ISSUE THREAD

**Issue by dingyic1** [pyannote/pyannote-audio#928]
**Is your feature request related to a problem? Please describe.**

Hi, I am trying to find the a way to Integrat the Speaker diarization pipeline and speech overlap pipeline, so that they can detect overlap speech and do diarization at same time. I have set up the diarization pipeline like this:

pipeline = pipelines.SpeakerDiarization(segmentation= "seg_000.pt",
                                        embedding="emb_000.pt",
                                        embedding_batch_size=32)

and the overlap pipeline like this:

pipeline = pipelines.OverlappedSpeechDetection(segmentation= "seg_000.pt")

The seg_000 is the fine tuned segementation model.
However, I have no idea how to combine them together. Does the "pipelines.SpeakerDiarization" has the function or parameter that can be used to detect overlap stuff?

**Comment by hbredin** [comment]
`SpeakerDiarization` pipeline already accounts for overlapped speech, thanks to the segmentation model. As such, it should already detect (and assign) overlapping speakers.

**Comment by dingyic1** [comment]
Thank you so much!
