### ISSUE TITLE
Shortening speech segments from speaker diarization

### ISSUE THREAD

**Issue by ibleaman** [pyannote/pyannote-audio#929]
Using the pretrained speaker diarization pipeline,
```
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization")
diarization = pipeline("audio.wav", num_speakers=2)
```
is there a way to specify the maximum duration of a silent segment to be tolerated in the middle of a speech segment?

I use the output of diarization as the input for manual transcription, and my transcribers prefer to work with shorter speech segments (<10 seconds; current pipeline sometimes produces 20-sec segments). Specifying that silent intervals longer than X seconds should not be included in a speech segment would be one approach to breaking up longer speech segments. Is there an existing way to include this as a parameter, similar to `num_speakers` above? Thanks!

**Comment by hbredin** [comment]
At some point, I will try to document the internals of the speaker diarization pipeline but you may want to play with those hyper-parameters:

* To be stricter on voice activity detection, increase `onset` detection threshold (between 0.0 and 1.0)

* To postprocess resulting speech turns and remove those shorter than 200ms :
```python
min_duration_on = 0.2
```

* To postprocess resulting speech turns and fill gaps between speech turns of one speaker shorter than 200ms:
```python
min_duration_off = 0.2
```


They can be set like this:

```python
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization")
parameters = pipeline.default_parameters()
parameters["min_duration_off"] = 0.2
pipeline.instantiate(parameters)
```

**Comment by ibleaman** [comment]
@hbredin Thanks for the quick response! I was able to tweak the hyper-parameters as you've indicated.

If my goal is to break up long contiguous speech segments (at the short silences which occur in the middle of them), am I understanding correctly that I should decrease `min_duration_off` (so that short silences are *not* included in speech segments) and maybe also increase `onset`? I tried some very extreme values (`parameters["min_duration_off"] = 0.01` and `parameters["onset"] = 0.99`), but I am still seeing roughly the same number of speech segments of roughly the same length.

Another trick I just tried is resampling the wav from 44.1kHz to 16kHz, and diarizing that file instead. For some reason this is shortening the speech segments very nicely, at the pauses.

**Comment by hbredin** [comment]
> Another trick I just tried is resampling the wav from 44.1kHz to 16kHz, and diarizing that file instead. For some reason this is shortening the speech segments very nicely, at the pauses.

That is weird -- this downsampling is done by pyannote.audio automatically anyway.

**Comment by ibleaman** [comment]
For those who find this question after the release of version 2.x, here is how the relevant parameter can be modified:

    from pyannote.audio import Pipeline
    pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization", use_auth_token=token)
    pipeline.segmentation.min_duration_off = 0.3

(As of today, 7 December 2022, the default `min_duration_off` is approx. 0.58. Decreasing this value means that shorter silences are recognized as boundaries between speech segments.)

**Comment by hbredin** [comment]
Thanks @ibleaman. This parameter is now also documented in [this tutorial](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/adapting_pretrained_pipeline.ipynb).
