### ISSUE TITLE
Sizes of tensors must match except in dimension 0

### ISSUE THREAD

**Issue by tunga99937** [pyannote/pyannote-audio#937]
I have trained segmentation with my own data, anh then use it together with pretrained embedding speechbrain/spkrec-ecapa-voxceleb to produce speaker diarization pipeline. The segmentation training and testing is successful and can be applied to segment audio. However, the diarization pipeline get error: "Sizes of tensors must match except in dimension 0. Expected size 73600 but got size 73601 for tensor number 5 in the list." when applied to diarizate audio as well as when optimizing pipeline hyper-parameters. How can I fix it?

Here is my detail implementation:
- Training segmentation:
```
seg_task = Segmentation(cskh, duration=2.0, max_num_speakers=2, batch_size=128)
seg_model = PyanNet(task=seg_task , sincnet={'stride': 10})
trainer = pl.Trainer(gpus=1, max_epochs=500)
trainer.fit(seg_model)
```
- Declare Diarization pipeline:
```
from pyannote.audio.pipelines import SpeakerDiarization as SpeakerDiarizationPipeline
pipeline = SpeakerDiarizationPipeline(segmentation="lightning_logs/version_1/checkpoints/epoch=499-step=93999.ckpt", embedding="speechbrain/spkrec-ecapa-voxceleb", segmentation_batch_size = 128)
initial_params = {
                "onset": 0.810,
                "offset": 0.481,
                "min_duration_on": 0.055,
                "min_duration_off": 0.098,
                "min_activity": 6.073,
                "stitch_threshold": 0.040,
                "clustering": {"method": "average", "threshold": 0.595}
            }
pipeline.instantiate(initial_params)
``` 
- Darizating audio:
![image](https://user-images.githubusercontent.com/57978809/159867431-5e2a4b63-7313-4f2a-bbac-eecdc79f4c9d.png)

**Comment by bouacheya** [comment]
Hi, did you manage to solve your problem ? I have the same issue

**Comment by tunga99937** [comment]
> 



> Hi, did you manage to solve your problem ? I have the same issue

**Comment by tunga99937** [comment]
> 



> Hi, did you manage to solve your problem ? I have the same issue

**Comment by tunga99937** [comment]
> Hi, did you manage to solve your problem ? I have the same issue

I have not solved this, so I decide to use pyannote v1 to deal with our speaker diarization task. However, I still want to use pyannote v2

**Comment by olvb** [comment]
I ran into the same issue. Here is a google colab reproducing it: https://colab.research.google.com/drive/1IPtoE9YBi6H_dhxYWkyzea-Derid5a6F?usp=sharing

**Comment by hbredin** [comment]
Thanks a lot for taking the time to create this Google Colab. That's really helpful. 

PR #1002 should fix the issue. Can you please confirm?

**Comment by olvb** [comment]
Thanks for the quick PR! This fixes it for me

**Comment by hbredin** [comment]
The PR was quick simply because you prepared a nice Google Colab to reproduce the error.
Thanks for that! 

Out of curiosity, what are you using pyannote.audio for?

**Comment by hbredin** [comment]
Also, the fix has been merged in `develop` branch.

**Comment by olvb** [comment]
> Out of curiosity, what are you using pyannote.audio for?

My team will be working with emergency services phone recordings (SAMU) and we will probably be using pyannote to separate between caller and operator speech turns.
