### ISSUE TITLE
Add expected runtimes and hardware to notebooks

### ISSUE THREAD

**Issue by CompRhys** [pyannote/pyannote-audio#943]
Would it be possible to add comments to each of the notebooks giving total expected runtimes and on what hardware the models were run?

**Comment by hbredin** [comment]
It is definitely possible but also not at the top of my priority list.

Would you like to contribute these numbers? 
The process would look like:

1. Update the notebooks to run on Google Colab
2. Add [%%time](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-time) magic command at the top of each cell of interest
3. Actually run the notebooks on Google Colab GPUs
4. Make a PR to this repo with the updated notebooks
