### ISSUE TITLE
How to perform scratch training for speaker diarization?

### ISSUE THREAD

**Issue by saumyaborwankar** [pyannote/pyannote-audio#953]
I was able to find the pipeline for speaker diarization but I was unable to train it using the voice activity pipeline training tutorial. Also, the speaker diarization pipeline needs 2 models segmentation and embedding so how does that work. Do we train the segmentation model along with training the speaker diarization model?
Please help and provide steps if you can.

**Comment by kaleaniket** [comment]
> I was able to find the pipeline for speaker diarization but I was unable to train it using the voice activity pipeline training tutorial. Also, the speaker diarization pipeline needs 2 models segmentation and embedding so how does that work. Do we train the segmentation model along with training the speaker diarization model? Please help and provide steps if you can.

Hello,
Did you find anything for this?
