### ISSUE TITLE
ValueError: 'waveform' must be provided as a (channel, time) torch Tensor

### ISSUE THREAD

**Issue by bitnom** [pyannote/pyannote-audio#956]
**Describe the bug**
I'm trying to continuously stream from the microphone using sounddevice (Returns ndarray) and recognize/diarize but I get the error:

```
File "stt_pipeline.py", line 69, in main
    diarized, full_text = segmentation({"waveform": mic_data[None], "sampling_rate": samplerate})
  File "stt_pipeline.py", line 46, in segmentation
    speaker_output = SPEAKER_SEGMENTATION(audio)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\project-JXAd3k8e-py3.8\lib\site-packages\pyannote\audio\core\pipeline.py", line 205, in __call__
    file = Audio.validate_file(file)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\project-JXAd3k8e-py3.8\lib\site-packages\pyannote\audio\core\io.py", line 153, in validate_file
    raise ValueError(
ValueError: 'waveform' must be provided as a (channel, time) torch Tensor.
```

**To Reproduce**

I posted a runnable example code here: https://stackoverflow.com/questions/71947410/valueerror-waveform-must-be-provided-as-a-channel-time-torch-tensor

**Content of `config.yml`**

Idk what this yaml is all about. I don't have one in my project.

**pyannote environment**

Win11 using the current `develop` branch of this git repo for pyannote.audio.

```powershell
>pip freeze | grep pyannote
pyannote.audio==0.0.1
pyannote.core==4.4
pyannote.database==4.1.3
pyannote.metrics==3.2
pyannote.pipeline==2.2
```

**Comment by hbredin** [comment]
Did you check the shape of `waveform` as the error message tells you?

My guess is that you need to transpose `waveform` so that it has shape `(channels, frames)` -- instead of the default `(frames, channels)` returned by `sounddevice.InputStream`.

**Comment by bitnom** [comment]
> Did you check the shape of `waveform` as the error message tells you?
> 
> My guess is that you need to transpose `waveform` so that it has shape `(channels, frames)` -- instead of the default `(frames, channels)` returned by `sounddevice.InputStream`.

Thanks. That fixed that error but now I get a new exception:

```
File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\project-JXAd3k8e-py3.8\lib\site-packages\torchaudio\functional\functional.py", line 1461, in resample
    waveform.device,
AttributeError: 'numpy.ndarray' object has no attribute 'device'
```

**Comment by bitnom** [comment]
Thanks. That fixed it. I ran into a new issue but will post a new issue for it.
