### ISSUE TITLE
Getting different embeddings on different machines

### ISSUE THREAD

**Issue by rohansharma777** [pyannote/pyannote-audio#959]
On using the pretrained model hosted [here](https://huggingface.co/pyannote/embedding), I am getting embeddings that differ at 10^-4 th position. Any reason why this is happening?

**Comment by hbredin** [comment]
Please provide a (two, I guess) minimum reproducible example as I cannot reproduce this myself.

That being said, this is most likely a float precision issue.
See PyTorch forum for instance: https://discuss.pytorch.org/t/get-different-scores-in-different-machine-with-the-same-torch-version/120907
