### ISSUE TITLE
Speaker diarization high RAM usage for large audios

### ISSUE THREAD

**Issue by Bodawen** [pyannote/pyannote-audio#962]
Hello pyannote team,

First, thanks for the great work. 

I am working on the pyannote speaker diarization,  sometimes need to process large audios like greater than 3 hours. I found that pyannote requires a lot of RAM for large audios. (For 3 hours audio, contains 23 speakers needs more than 18 GB RAM) To explore the details of the RAM usage, I recorded the RAM of the different phases for speaker diarization. The result is very interesting:
For the segmentation phase( Including Feature Extraction, VAD, Embedding Generation), the RAM requirement is not so high. I guess the main RAM usage is for video feature and Embedding.

For the clustering phase, the RAM requirement increased. This is as expected. The space complexity of clustering is O(n^2).

I am confused about the resegmentation phase. From the result of experiment, for the most audio, the RAM usage of resegmentation is more than clustering. It seems to depend on the detected number of speaker. The more speakers, the more RAM require.  Can you explain why the resegmentation needs so much RAM? Is that possible to reduce it?

**Comment by hbredin** [comment]
Would you mind sharing a link to a Google Colab containing a minimum reproducible example that I can quickly (understand: in less than 5 minutes) run to reproduce this behavior?

**Comment by Bodawen** [comment]
The Google Colab code is following:
https://colab.research.google.com/drive/18b1eunWBmtMD0gxRqOXyYdxw2nRO_JoV?usp=sharing
And the Result:
[output.txt](https://github.com/pyannote/pyannote-audio/files/8700812/output.txt)

I checked the experimental result again and found that the reason might be that python garbage collection cannot free memory in time? After segmentation and clustering, the allocated memory will not be freed.

**Comment by hbredin** [comment]
Can you please provide a link with read access?

**Comment by Bodawen** [comment]
Are you unable to read the code in the link?
https://colab.research.google.com/drive/18b1eunWBmtMD0gxRqOXyYdxw2nRO_JoV
