### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by thangld201** [pyannote/pyannote-audio#964]
Does the library support training a speaker diarization model from scratch for other languages ? (such as Vietnamese).<br/> If so, how can I do that ?

**Comment by thangld201** [comment]
@hbredin Could you help me ?

**Comment by hbredin** [comment]
Yes, training for other languages is supported. 
I recommend you start by going through the [documentation](https://github.com/pyannote/pyannote-audio#documentation) to get to know the library.
