### ISSUE TITLE
Question about load model

### ISSUE THREAD

**Issue by Shoawen0213** [pyannote/pyannote-audio#965]
Hi! thanks for your awesome projec!
sorry for bothering you. I have several stupid questions.
Before I want to fine-tune the model with my own dataset, i try to train with AMI again.
I've seen [pyannote-audio](https://github.com/pyannote/pyannote-audio/tree/develop) for reference.
(1). If I want to re-train a Segmentation model with AMI. My problem is which step I should follow on this website?
Seems that I should follow "Training a voice activity detection model from scratch", but it is only for "VAD". Your model already takes care of VAD and OSD, so seems that not this part.
Or i should follow "Fine-tuning a pretrained speaker segmentation model", i choose this because
from pyannote.audio import Model pretrained = Model.from_pretrained("pyannote/segmentation")
call the whole speaker segmentation model.
Sorry for my misunderstanding... I confuse about this part for several weeks...

(2). As mentioned above, i choose "Fine-tuning a pre-trained speaker segmentation model" for trying, then I store the model in "ckpt"
But when i want to load the "ckpt" for inference, it has some error that I have no idea what's happened...
Code below is what i use to load model
`model_old = Model.from_pretrained('/home/shaowen/PYANNOTE_Train/logs/test/version_2/checkpoints/epoch=49-step=90749.ckpt') der_old = test(model=model_old, protocol=ami, subset="test") 
print(f"Local DER (model_finetuned) = {der_old * 100:.1f}%")`
the error message↓

![image](https://user-images.githubusercontent.com/63163334/167573945-19df4897-0c1f-4e5b-8362-22ab4a043094.png)

did i do something wrong....?

**Comment by hbredin** [comment]
> Hi! thanks for your awesome projec! sorry for bothering you. I have several stupid questions. 

There is no stupid questions -- only questions I (sometimes) don't have time to answer :)

Regarding (1), you should indeed go with "fine-tuning a pretrained segmentation model".

Regarding (2), would you mind sharing a link to a Google Colab containing a minimum reproducible example that I can quickly (understand: in less than 5 minutes) run to reproduce the error?

**Comment by Shoawen0213** [comment]
Hi @hbredin  thanks for your reply!
Regarding (1), Please forgive my stupidity... I was confused about why using the "Fine-tune..." part. 
The tutorial, "Training a voice activity detection model from scratch" is for teaching how to train "VAD" task by using PyanNet, and the dataset is "ami". after using the code provided in tutorail：
`from pyannote.audio.tasks import VoiceActivityDetection`
`vad_task = VoiceActivityDetection(ami, duration=2.0, batch_size=128)`
`from pyannote.audio.models.segmentation import PyanNet`
`vad_model = PyanNet(task=vad_task, sincnet={'stride': 10})`
`import pytorch_lightning as pl`
`trainer = pl.Trainer(gpus=1, max_epochs=1)`
`trainer.fit(vad_model)`
I will get a model for the VAD task, am I right?
If the answer is yes, then i can also train other tasks which i saw in [here](https://github.com/pyannote/pyannote-audio/blob/develop/pyannote/audio/tasks/__init__.py#L24), like i can train osd task, segmentation task...etc?
If the answer is yes, then if I use this way to train a segmentation model by using ami dataset. 
like
`from pyannote.audio.tasks import Segmentation`
`seg_task = Segmentation(ami, duration=2.0, batch_size=128)`
does this one will be the same as the model _(not the same weight of course)_
`from pyannote.audio import Model`
`pretrained = Model.from_pretrained("pyannote/segmentation")`
sorry for this odd question...
I was just confused what the meaning of the "training" and "fine-tune" part in this tutorial.
because of in my shallow knowledge, I should train a whole model(system) first, then according to different domains to fine-tune the model. The training tutorial seems that need to train different task, but pyannote/segmentation contains both vad and osd. So i confused...
If i didn't say my question clearly, please let me know!!
Thanks

Regarding (2), my question is that i will get a "ckpt" file after fine-tune(just same with the tutorial). If i want to use 
`Model.from_pretrained('xxx/logs/test/version_2/checkpoints/epoch=49-step=90749.ckpt') `
to load this "ckpt" to inference the test data by using this model.
It will have the error.
But i fix this problem!!
just need to add `strict=False `, then it could load succesfully
like
`ckpt_path = 'xxx/logs/test/version_2/checkpoints/epoch=49-step=90749.ckpt'`
``Model.from_pretrained(ckpt_path, **strict=False**) ``
sorry for bothering...
