### ISSUE TITLE
Add `inference_kwargs` to `SpeakerSegmentation` class like the one in `VoiceActivityDetection`

### ISSUE THREAD

**Issue by pooya-mohammadi** [pyannote/pyannote-audio#966]
**Is your feature request related to a problem? Please describe.**
`SpeakerSegmentation` class does not take in any arguments for determining the model's device. It uses the default device which is available on the machine. 

**Describe the solution you'd like**
It would be convenient if you could provide a variable like `inference_kwargs` which is available for `VoiceActivityDetection` that accepts arbitrary device values as well.

**Describe alternatives you've considered**
I accessed the private model from the outer class and changed the device manually
```
self.diarize_model = SpeakerSegmentation("pyannote/segmentation")
diarize_model._segmentation.model.to(device)
diarize_model._segmentation.device = device
```

**Comment by hbredin** [comment]
Feel free to submit a PR adding this feature. Thanks!
