### ISSUE TITLE
Deactivate shortcuts when help is displayed

### ISSUE THREAD

**Issue by J-Petiot** [pyannote/pyannote-audio#968]
[H] displays the help. [H] hides the help.
[H] displays the help. [ESC] also hides the help but skips the current chunk and goes to the next one.
You should disable the keyboard shortcuts when the help is displayed (I don't know if you have control over this)

https://github.com/pyannote/pyannote-audio/pull/950#issuecomment-1123733153

**Comment by J-Petiot** [comment]
I think I can't really control that, but I can change the ESC shortcut with another key if it seem confusing with the help window.

**Comment by hbredin** [comment]
OK then I suggest we revert to the original Prodigy shortcuts.
https://prodi.gy/docs/api-web-app#actions

**Comment by J-Petiot** [comment]
In the original Prodigy shortcuts "ignore" is bind to "space" which seems to correspond much more to "play/pause audio".
They suggest "X" for reject, we can use this one as we do not use reject ?

**Comment by hbredin** [comment]
What should we do about this issue?
