### ISSUE TITLE
Jouer l'audio à la création d'un segment

### ISSUE THREAD

**Issue by J-Petiot** [pyannote/pyannote-audio#972]
Quand on crée un segment (que ce soit au clavier ou à la souris), il serait judicieux de recommencer à jouer l'audio à partir du début du segment créé, comme celà se produit déjà quand on active un segment existant en cliquant dessus.
Même chose quand on active un segment grâce aux raccourcis clavier haut ou bas.

https://github.com/pyannote/pyannote-audio/pull/950#issuecomment-1123733153

**Comment by J-Petiot** [comment]
When we switch from a region to another it doesn't pause the audio, so the user can play and switch region, if we play the audio every time the region switch we don't add a feature, we remove one, the possibility of changing regions without listening to all the beginnings of the others.

**Comment by hbredin** [comment]
> the possibility of changing regions without listening to all the beginnings of the others.
Can you explain? I did not get it.

**Comment by J-Petiot** [comment]
Je voulais dire, je trouverais ça plus agréable à utiliser si on pouvait passer d'une région à l'autre sans que ça les joue, c'est moins fatiguant à l'oreille, je trouve que de laisser l'utilisateur le choix de jouer ou non l'audio est plus intéressant que de mettre play sur la fonction de switch. En sachant que si l'audio est entrain de se jouer, appuyer sur les flèches haut et bas ne le met pas en pause et ça switch directement. 
Je peux faire un commit avec pour te laisser tester si tu veux.

**Comment by hbredin** [comment]
Mon "issue" a deux parties. Je pense que tu parles de la seconde. 

Dans la première, je propose de jouer l'audio quand on créé un nouveau segment.
Pour l'instant ce n'est pas le cas (à moins d'une erreur de ma part)

**Comment by J-Petiot** [comment]
Oui oui je parle de la seconde partie, pour la première c'est une bonne idée, je l'ai mis dans le commit là normalement.
