### ISSUE TITLE
Changer la description des champ de texte

### ISSUE THREAD

**Issue by J-Petiot** [pyannote/pyannote-audio#973]
Peut-on remplacer le titre des zones de texte par quelque chose qui clarifie ce qui est attendu?
Ex. Assign a global tag to local SPEAKER_00 au lieu de SPEAKER_00
https://github.com/pyannote/pyannote-audio/pull/950#issuecomment-1123733153

**Comment by hbredin** [comment]
I am not that happy with the current phrasing `Assign a global tag`.
I'd like to make it clear that this name will be re-used in future chunks.

Would `Choose a name for the rest of the recording` be better?

**Comment by J-Petiot** [comment]
A shorter sentence may be better, but we can go that for now
