### ISSUE TITLE
Rajouter du feedback à la création d'un tag global

### ISSUE THREAD

**Issue by J-Petiot** [pyannote/pyannote-audio#974]
Quand on donne un nom à un SPEAKER_XX et qu'on appui sur "ENTER", l'absence de feedback utilisateur donne l'impression que le nom n'est pas pris en compte. Il faudrait au moins sortir le curseur de la zone de texte -- et éventuellement trouver un meilleur feedback (ex. passer au nom suivant s'il y en a plusieurs à nommer)
https://github.com/pyannote/pyannote-audio/pull/950#issuecomment-1123733153

**Comment by J-Petiot** [comment]
"ENTER" cannot move to the next name because it "accept" the chunk and moves to the next chunk already.
It seems clear enough as it is to me, with placeholder disappearing, in fact this is what Prodigy uses, but one can think of something else.

**Comment by hbredin** [comment]
Ce que je voulais dire, c'est que le curseur reste dans la zone de texte quand on appuie sur ENTER.
Ca donne l'impression que le nouveau nom n'est pas pris en compte (ce qui est faux) et que la touche ENTER n'a aucun effet (ce qui est vrai). C'est vraiment du UX (User Experience) ici. Tout fonctionne bien, le nom est bien pris en compte -- c'est juste le sentiment que j'ai eu en appuyant sur ENTER après avoir tapé le nom "sheldon" suivi de ENTER (par réflexe).
