### ISSUE TITLE
Configuration de l'autoplay

### ISSUE THREAD

**Issue by J-Petiot** [pyannote/pyannote-audio#975]
Serait-il judicieux de lancer le player dès qu'un nouveau chunk est chargé ?
Y a-t-il des inconvénients à ça ?
https://github.com/pyannote/pyannote-audio/pull/950#issuecomment-1123733153

**Comment by J-Petiot** [comment]
The autoplay is already set to True. 
I didn't quite understand whether you want it or not... But we can set it to False if you want.

**Comment by hbredin** [comment]
For some reason, it did not autoplay on my machine.
I confirm that this should be set to True.

**Comment by hbredin** [comment]
Will re-open if I notice this error again.
