### ISSUE TITLE
Extrait audio de l'audio snippet

### ISSUE THREAD

**Issue by J-Petiot** [pyannote/pyannote-audio#977]
Il semble que l'audio snippet (qui est joué quand on passe la souris sur les étiquettes en haut) contient des extraits audio qui ne sont pas dans l'ordre chronologique d'apparition dans le fichier.
https://github.com/pyannote/pyannote-audio/pull/950#issuecomment-1123804237

**Comment by J-Petiot** [comment]
Le niveau sonore de l'audio snippet est plus bas que celui du player principal.

**Comment by hbredin** [comment]
Is this fixed?
