### ISSUE TITLE
Changer l'écoute de l'audio snippet

### ISSUE THREAD

**Issue by J-Petiot** [pyannote/pyannote-audio#980]
Quand on commence à bien connaitre les locuteurs, on n'a plus vraiment besoin d'écouter l'audio snippet.
Ça devient même perturbant parce qu'il s'overlappe par dessus le player principal. Je propose de changer un peu le comportement l'audio snippet ne commence à jouer que lorsqu'on clique sur l'étiquette du speaker nommé.
Ou alors on ajoute une petite icône 🗣 sur laquelle il faut passer la souris pour jouer l'audio snippet.
https://github.com/pyannote/pyannote-audio/pull/950#issuecomment-1123804237

**Comment by hbredin** [comment]
I have just tested this new feature.
Seems to work fine but sometimes the audio snippet stops playing even though I keep my mouse on the speaker. Could it because of the blinking that may artificially lead to a `mouse out` event?
Anyway, you probably don't have make it blink.
