### ISSUE TITLE
Too many SPEAKER_XX labels?

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#986]
<img width="702" alt="image" src="https://user-images.githubusercontent.com/1080837/169487290-3ed24935-14f4-4379-be18-306a147ec6b3.png">

The screenshot shows the UI before I edit anything.

The model identified one speaker (leonard) and left another one unidentified?
Why is there so many SPEAKER_XX? (speaker_00 to speaker_06)?

**Comment by J-Petiot** [comment]
It's probably because he recognised more speakers in the "context" parts of the audio (which are removed afterwards), it's true that with examples like this, it doesn't look very clean...
I should be able to remove them afterwards.

**Comment by hbredin** [comment]
Did you do something to solve this issue?

**Comment by J-Petiot** [comment]
Not yet
