### ISSUE TITLE
Use A, B, C instead of GSPEAKER_XX

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#987]
![image](https://user-images.githubusercontent.com/1080837/169488947-8b9710fb-c9ac-49d7-82cf-b1de5e48f01f.png)

When the annotator does not assign a name, it should be automatically assigned one in alphabetical order (instead of current behavior to use GSPEAKER_XX).

**Comment by J-Petiot** [comment]
Are you sure you have the last update ? 
There is no longer supposed to be a "GSPEAKER_XX"...
And the labels should be coloured
