### ISSUE TITLE
Why does "database" recipe create multiple databases?

### ISSUE THREAD

**Issue by hbredin** [pyannote/pyannote-audio#990]
I have annotated a bunch of files, coming from two different directories, but saved all these annotations in the same Prodigy `dataset`.

When running `prodigy pyannote.database dataset MyDatabase /output/directory`, it creates two databases (`MyDatabase` and `MyDatabase1`) while I expected only one.

**Comment by J-Petiot** [comment]
I did that on purpose, I thought we should separate if it came from a different directory... But it's true that it's not useful, I'll remove this part.
