### ISSUE TITLE
How to visualize the outputs of speaker diarization results on my own videos? 

### ISSUE THREAD

**Issue by JiangXiaobai00** [pyannote/pyannote-audio#996]
Hi, thank you very much for your excellent work. I have tested the speaker diarization model on my own audio directly with the pretrained model and found it to work well. 

Now I want to visualize the speaker diarization results as shown in the picture below which is captured from [https://huggingface.co/pyannote/segmentation]. What should I do？Can you give me some suggestions？

Best wishes.
![捕获](https://user-images.githubusercontent.com/44131397/170866198-d2204443-0a86-4392-b9a2-199318378d6a.JPG)

**Comment by hbredin** [comment]
`pyannote.audio` pipelines return `pyannote.core.Annotation` instances that can be visualized directly in Jupyter Notebook. See http://pyannote.github.io/pyannote-core/visualization.html

**Comment by JiangXiaobai00** [comment]
Words cannot express how thankful I am. Your suggestion is really helpful. 

Thanks for your suggestions, I already know how to visualize the results. I changed your code slightly so that it can save the visualization directly without going through the jupyter notebook, although I know it's trivial for you

`import pyannote.core.notebook as notebook
import matplotlib as mpl
import matplotlib.pyplot as plt
from pyannote.core import Annotation
from pyannote.core import Segment

mpl.use('Agg')
notebook.width = 10
plt.rcParams['figure.figsize'] = (width, 2)

# only display [0, 20] timerange
notebook.crop = Segment(0, 20)

# plot annotation
annotation = Annotation()
annotation[Segment(1, 5)] = 'Carol'	
annotation[Segment(6, 8)] = 'Carol'
annotation[Segment(6, 8)] = 'Bob'
annotation[Segment(12, 18)] = 'Carol'
annotation[Segment(7, 20)] = 'Alice'
notebook.plot_annotation(annotation, legend=True, time=True)

plt.show()

plt.savefig('visualization.png')`
