### ISSUE TITLE
Question about training model with own dataset and ask some hint for doing augmentation

### ISSUE THREAD

**Issue by Shoawen0213** [pyannote/pyannote-audio#998]
Hi! I'm interested in online speaker diarization by using pyannote-audio. I ask about some training issues in [StreamingSpeakerDiarization](https://github.com/juanmc2005/StreamingSpeakerDiarization), J pro asks me to ask here for some suggestions.
Please forgive my stupidity. Sorry to trouble you!
I have two questions. 
1. I have generated my own dataset following the tutorial from pyannote-database and it works on fine-tuning with good performance. I would like to know if I want to train **the segmentation model** with my own dataset. If i code like ↓
`from pyannote.audio.models.segmentation import PyanNet`
`from pyannote.audio.tasks import Segmentation`
`import pytorch_lightning as pl`
`seg_task = Segmentation(dataset, duration=5, max_num_speakers=4)`
`model = PyanNet(task=seg_task, sincnet={'stride': 10})`
`trainer = pl.Trainer(max_epochs=1)`
`trainer.fit(model) ` 
does it the correct way to train a segmentation model?
I have seen the [Training, fine-tuning, and transfer learning](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/training_a_model.ipynb) before, but i'm not sure is this the right way

2. pyannote/segmentation is trained with additive background noise and impulse responses. J pro says that I should do this while training and recommend me to take a look at [torch-audiomentations](https://github.com/asteroid-team/torch-audiomentations). I have seen this before and I also try 
`from torch_audiomentations import AddBackgroundNoise`
`augmentation = AddBackgroundNoise("/path/to/background/noise/directory")`
`vad_task = VoiceActivityDetection(ami, augmentation=augmentation)` 
which is mentioned in [Training, fine-tuning, and transfer learning](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/training_a_model.ipynb) before. I also read [augmentation.ipynb](https://github.com/pyannote/pyannote-audio/blob/develop/notebook/augmentation.ipynb) for trying how to do augmentation. I'm not sure where and how to add augmentation like additive background noise and impulse responses when training. Could you give me some template or some hints for me...? 

3. I'm interested that if i want to add some data pre-processing before doing trained or inference. Where and how i should add it to the pipeline or pipeline? Seems that the data is called from the protocol, even training or inference, but I'm curious in which step I can add some pre-processing. Could you give me some hints?
If i have something not described clearly, please let me know!

thank you very much for your excellent work and kind reply!
Looking forward to your reply!

**Comment by hbredin** [comment]
>     1. I have generated my own dataset following the tutorial from pyannote-database and it works on fine-tuning with good performance. I would like to know if I want to train **the segmentation model** with my own dataset. If i code like ↓
>        `from pyannote.audio.models.segmentation import PyanNet`
>        `from pyannote.audio.tasks import Segmentation`
>        `import pytorch_lightning as pl`
>        `seg_task = Segmentation(dataset, duration=5, max_num_speakers=4)`
>        `model = PyanNet(task=seg_task, sincnet={'stride': 10})`
>        `trainer = pl.Trainer(max_epochs=1)`
>        `trainer.fit(model) `
>        does it the correct way to train a segmentation model?
>        I have seen the [Training, fine-tuning, and transfer learning](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/training_a_model.ipynb) before, but i'm not sure is this the right way

Yes. It is the correct way. You can also play a bit with the [number of LSTM layers](https://github.com/pyannote/pyannote-audio/blob/aede20e9c80458e57030d3c5a46473b712ebd089/pyannote/audio/models/segmentation/PyanNet.py#L67). The pretrained `pyannote/segmentation` model used [this configuration](https://huggingface.co/pyannote/segmentation/blob/main/config.yaml#L18-L27) 

>     2. pyannote/segmentation is trained with additive background noise and impulse responses. J pro says that I should do this while training and recommend me to take a look at [torch-audiomentations](https://github.com/asteroid-team/torch-audiomentations). I have seen this before and I also try
>        `from torch_audiomentations import AddBackgroundNoise`
>        `augmentation = AddBackgroundNoise("/path/to/background/noise/directory")`
>        `vad_task = VoiceActivityDetection(ami, augmentation=augmentation)`
>        which is mentioned in [Training, fine-tuning, and transfer learning](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/training_a_model.ipynb) before. 

That is indeed the way to do it. Pass this extra `augmentation` parameter to the `Segmentation` task:

```python
seg_task = Segmentation(dataset, duration=5, max_num_speakers=4, augmentation=augmentation)
```

>     3. I'm interested that if i want to add some data pre-processing before doing trained or inference. Where and how i should add it to the pipeline or pipeline? Seems that the data is called from the protocol, even training or inference, but I'm curious in which step I can add some pre-processing. Could you give me some hints?

Not sure what you mean by preprocessing here. What do you have in mind exactly?

**Comment by Shoawen0213** [comment]
Hi! @hbredin Thanks for your reply!!!!
For question 1, where does [this configuration](https://huggingface.co/pyannote/segmentation/blob/main/config.yaml#L18-L27) store? I can't find this file in pyannote.audio. 

For question 2, I understand that I can add an augmentation parameter in the task, but I would like to know how to add impulse responses or something else? Maybe I didn't describe the question well, I know that I can add noise like Musan with AddBackgroundNoise. what about impulse responses? 
BTW, I find that the Musan folder contains "music", "noise", and "speech", which is the correct folder? An does the impulse responses  data use from [here ](http://www.openslr.org/26) _([sim_rir_16k.zip](https://www.openslr.org/resources/26/sim_rir_16k.zip))_?

For the question3, well, I thought that it was my bad description. I thought that sometimes we might do some processing when obtaining a speech utterance, like pre-emphasis, STFT, etc. I am just curious about does those procedures need to add or where to add them? 

Please forgive my stupidity. I know that some questions I asked it's quite ridiculous.
Sorry to trouble you! Looking forward to your reply!
I really appreciate your excellent work and the kind reply!

**Comment by Shoawen0213** [comment]
Hi! @hbredin  thanks for your quick reply!!
I will dive into it more!!
Thanks for your help!!
