### ISSUE TITLE
Error when import Pipeline

### ISSUE THREAD

**Issue by hungnmai** [pyannote/pyannote-audio#999]
I'm using python 3.9 (I also tried python 3.8) and installed pyannote.audio==2.0a1, but I get error when import 
`from pyannote.audio import Pipeline
`

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Pipeline' from 'pyannote.audio' (/path/lib/python3.9/site-packages/pyannote/audio/__init__.py)
`

**Comment by maxsanwal** [comment]
yes i have used 
https://github.com/pyannote/pyannote-audio#installation

**Comment by dgoryeo** [comment]
I just got the error as well --Python 3.8 and I have followed the installation steps completely. Any idea how to resolve this?

**Comment by ladrua** [comment]
They changed a bit how the Pipeline works. The documentation on huggingface seems correct for the latest 2.1.1 version.
https://huggingface.co/pyannote/segmentation

**Comment by remic33** [comment]
> They changed a bit how the Pipeline works. The documentation on huggingface seems correct for the latest 2.1.1 version.
> https://huggingface.co/pyannote/segmentation

There is an error in the first two lines, it import model (without maj) and use the Model with a man. It seems that the import of Pipeline do not work for me neither. Wtf?
